analogdevicesinc/linux

- drivers/hwmon/ltc2945.c
The sense resistor is a parameter of the board. It should be configured in
the driver via a device-tree / ACPI property, so that the proper current
measurements can be done in the driver.
It shouldn't be necessary that userspace need to know about the value of
the resistor. It makes things a bit harder to make the application code
portable from one board to another.
> hwmon: (ltc2945): add support for sense resistor

- .travis.yml
We do this anyway in the script.
So, tell Travis-CI to do it.
Saves a few minutes from the build run, because the docker won't start.
> .travis.yml: limit BUILD_TYPE=sync_branches_with_master build on master

- arch/arm/boot/dts/overlays/rpi-cn0504-overlay.dts
The value of the sense resistor is 0.02 ohms. Add value in micro-ohms in
the device tree.
> arch: arm: rpi-cn0504: add sense resistor value

- arch/arm/boot/dts/adi-fmcomms8.dtsi
- arch/arm/boot/dts/socfpga_arria10_socdk_fmcomms8.dts
adi-fmcomms8.dtsi is a copy of arch/arm64/boot/dts/xilinx/adi-fmcomms8.dtsi .
More information: https://wiki.analog.com/resources/eval/user-guides/ad-fmcomms8-ebz
> arm: dts: Add AD-FMCOMMS8-EBZ + Arria 10 SoC Development Kit support

- drivers/iio/adc/ad9361.c
ad9361_gt() is returning the index from ad9361_adi_gt_info[]. Since this
gain_table_info containts full table information too, the returned value
will not be valid as an index for lna_table[][] and mixer_table[][].
> iio: adc: ad9361: Fix ad9361_get_rx_gain() in split table mode

- drivers/net/ethernet/cadence/macb.h
- drivers/net/ethernet/cadence/macb_main.c
- drivers/net/ethernet/freescale/fec_main.c
- drivers/net/phy/phy-core.c
The ADIN1100 is in pre-release state on the company website:
https://www.analog.com/en/products/adin1100.html
This change adds some required bits to have support for this in the current master.
When updating to kernel 5.4 these will be unrequired, but it's good to have support for this in 4.19.
> net: phy,macb,fec: backports to support Clause 45 before adding ADIN1100

- Kconfig.adi
- drivers/net/phy/Kconfig
- drivers/net/phy/Makefile
- drivers/net/phy/adin-compat.h
- drivers/net/phy/adin-t1l.c
The ADIN1100 is a low power single port 10BASE-T1L transceiver designed for
industrial Ethernet applications and is compliant with the IEEE 802.3cg
Ethernet standard for long reach 10 Mb/s Single Pair Ethernet.
https://www.analog.com/en/products/adin1100.html
This change adds support for this kernel version.
The upstream version will differ, but it will also have newer/different PHYlib pieces that are not compatible with this version.
This also requires PR #1235 in order to work with the Xilinx carriers.
> net: phy: adin-t1l: add initial support for ADIN1100 industrial PHY 

- arch/arm/boot/dts/overlays/rpi-adar1000-overlay.dts
Each individual ADAR1000 will appear with it's device name so this patch
updates the name.
> arch: arm: boot: dts: Update ADAR1000 device names

- ci/travis/run-build-docker.sh
- ci/travis/run-build.sh
- drivers/firmware/xilinx/zynqmp.c
Since Ubuntu 20.10, GCC 10 is used.
This one seems to find all kinds of new warnings, as it seems to do more static analysis by default.
The things it finds are pertinent, but they are in kernel core-code which we don't want to patch as it is hard to maintain afterwards when upgrading.
One thing that is a bit dubious is the warning in `drivers/firmware/xilinx/zynqmp.c`.
This one really looks valid. An index in a static array is accessed at index 2562, when the array is only 63 elements long.
This could be valid, since it may map over reserved memory area.
However, it could also be faulty.
A patch was sent to Xilinx to notify them about this.
Also, installing `make`  vs `build-essential` package, since we don't need everything from that package.
This would save some build-time. …
> ci,travis: fix build with GCC 10

- drivers/iio/adc/navassa/adrv9002.c
For operations that need to be in a specific ensm to succeed, we need to
add some delays to make sure that the device actually goes into that
state before proceeding with the operation. This problem was visible
when changing the LO frequency for a port with the enable mode set to
pin.
> iio: adrv9002: Add some delays when changing ensm

- .github/workflows/build.yml
- ci/travis/run-build.sh
This adds the checkpatch script in it's own separate file. It's also a
separate job.
We will make this build-run optional, so that we make it a recommendation,
not an enforcement for PRs.
> .github/actions: add a yaml file for the checkpatch script 

- .github/workflows/sync_branches_with_main.yml
- .travis.yml
- ci/travis/run-build.sh
This migrates the job to sync the main branch with other branches to the
Github actions.
This is a re-adaption of the old build to synchronize legacy branches with
the main branch.
> .github/actions: add yml file to sync branches with main branch

- drivers/iio/adc/ad7768.c
This patch adds an additional parameter to the register read function.
By passing the data pointer to the function, the returned value will used
only for status check.
With this change, the status check won't be confused with a register value
check:
ret = ad7768_spi_reg_read()
if (ret){}
> iio: adc: ad7768: Update spi_reg_read function

- .github/workflows/build.yml
- .github/workflows/build_rpi.yml
Most of the time these branches will build after being auto-sync-ed from
the main branch.
Sometimes, some PRs will be issued. In those cases we will also need to run
the build on a PR context.
So, these branches will need to build on both contexts (push &
pull_request).
The build_rpi.yml file can live in master, since the rules won't allow it
to build on any other branch than these branches. And the patch will get
auto-sync-ed to the rpi-4.19.y branch.
> .github/actions: add build rules for the RPi branches

- .github/workflows/build.yml
- ci/travis/run-build.sh
This migrates the dtb_build_test job to Github Actions to build all
device-trees via CI.
> .github/actions: add dtb_build_test job

- arch/arm/boot/dts/adi-ad9081-fmc-ebz.dtsi
- arch/arm/boot/dts/zynq-zc706-adv7511-ad9081.dts
* VCXO = 122.88 MHz
* M = 8
* L = 4
* Sample Rate = 250 MSPS
> arm: dts: zynq-zc706-adv7511-ad9081: Support for AD9081-FMC-EBZ on ZC706

- .github/workflows/build.yml
- ci/travis/run-build.sh
By default we only build PRs targeting the main branch of release branches.
However if a user wants to build a push-branch, then the user will need to
prefix the branch with 'staging/'.
That way the same build rules will run as for a PR.
> .github/workflows/build.yml: build 'staging/' prefixed pushed branches

- arch/arm64/boot/dts/xilinx/zynqmp-zcu102-rev10-ad9364-fmcomms4.dts
Since AD9364 is installed on FMCOMMS4, dac_core should be configured accordingly.
> arch: arm64: zcu102-fmcomms4: Use proper dac_core compatible string

- drivers/iio/adc/talise/talise.c
- drivers/iio/adc/talise/talise_arm.c
"halError" is not defined in some functions, which leads to compile errors for undeclared variables when compiling with TALISE_VERBOSE=1.
This change defines the variable in the functions where it was previously missing.
Signed-off-by: Isaac True <isaac@is.having.coffee>
> iio: adc: talise: Add missing halError variables for debugging with TALISE_VERBOSE=1

- arch/arm/boot/dts/adi-adin1100-mii.dtsi
- arch/arm/boot/dts/adi-adin1100-rmii.dtsi
- arch/arm/boot/dts/zynq-zc706-adv7511-adin1100-mii.dts
- arch/arm/boot/dts/zynq-zed-adv7511-adin1100-mii.dts
- arch/arm/boot/dts/zynq-zed-adv7511-adin1100-rmii.dts
- arch/arm64/boot/dts/xilinx/zynqmp-zcu102-rev10-adin1100-mii.dts
- arch/arm64/boot/dts/xilinx/zynqmp-zcu102-rev10-adin1100-rmii.dts
We just need to enable GEM1 and set it to MII/RMII.
The ADIN T1 driver will do the rest.
Also, since the eval board has the PHY address configurable via
dip-switches, we won't be setting the PHY address in the DT. That way, we
can probably avoid silly situations where the PHY doesn't probe if a
dip-switch is played-with.
> arch: arm,arm64: adin1100: add support for evall board (MII/RMII modes)

- drivers/nvmem/adi_axi_sysid.c
Sysid memory now contains a git branch field which needs to be taken
into account by the driver.
Signed-off-by: Sergiu Arpadi <sergiu.arpadi@analog.com>
> nvmem: adi_axi_sysid: Add git branch field

- drivers/iio/gyro/adxrs290.c
Sign-extend the rate and temperature data to
fix issue #1274.
Signed-off-by: KJimenez <kister.jimenez@analog.com>
> iio:gyro:adxrs290: fix data signedness

- .github/workflows/build.yml
- ci/travis/run-build.sh
Since are doing the dual licensing thing, we might as well do a CI check
for it, otherwise we keep forgetting to add Dual BSD/GPL and then have to
add patches to update the license.
> ci/travis/run-build.sh: check that new ADI drivers are dual-licensed 

- drivers/iio/beamformer/adar1000.c
Add TX buffer for clock generation. Before this the only the chip select
was visible.
> iio: beamformer : adar1000: Fix clock generation

- drivers/spi/spi-cadence.c
This change was added via 931ac60d1aa503 ("spi: xilinx-ps: Make sure the
SPI peripheral clock is fast enough").
Then this was bumped to the rate of the aper_clk via commit 2cf70479bf673
("spi: xilinx-ps: Set ref_clk rate to 3/2 of the aper clock rate").
It took a while to find this out as this was buried in merge commit
5ea3bc963dcd5 ("Merge remote-tracking branch 'xilinx/master-next' into
xcomm_zynq").
In the meantime the section in Xilinx's user-guide about SPI clocks
(referenced in commit 931ac60d1aa503) has disappeared.
The fix in commit 2cf70479bf673 seems a bit empyrical.
After talking to Lars, the reply was:
-----------------------------------------------------------------------
The SPI controller has two clock domains and the signal that was used to
start the SPI transfer is not …
> spi: cadence: remove Zynq workaround for SPI Clocks

- drivers/spi/spi-cadence.c
That code isn't present in the upstream version, so remove it. The upstream
driver queries the rate from the clock framework via clk_get_rate().
> spi: cadence: remove caching of clk rate

- include/linux/jesd204/jesd204.h
In 204C modes frames per multiframe (JESD K) can be larger than 255.
Increase storage type to avoid overflows.
> include: jesd204.h: JESD204C fix u8 overflow in frames_per_multiframe

- drivers/iio/adc/ad7768.c
- drivers/iio/buffer/industrialio-buffer-dmaengine.c
- include/linux/iio/buffer-dmaengine.h
> iio: adc: ad7768: cleanup the driver's exit & error paths

- drivers/iio/frequency/hmc7044.c
Implement determine_rate to work around 32-bit long (LONG_MAX) limitations
for 32-bit machines when using round_rate. This fixes a bug seen on
microblaze where clk_set_rate() fails with rate = 3GHz.
> iio: frequency: hmc7044: Implement determine_rate (fix)

- drivers/iio/frequency/ad9172.c
> iio: frequency: ad9172: Fix JESD subclass selection from dt

- arch/arm/boot/dts/zynq-zc702-adv7511-ad9364-fmcomms4.dts
- arch/arm/boot/dts/zynq-zc706-adv7511-ad9364-fmcomms4.dts
- arch/arm64/boot/dts/xilinx/zynqmp-zcu102-rev10-ad9364-fmcomms4.dts
Similar to https://github.com/analogdevicesinc/linux/commit/f9afb38dd02fedc7ee6f4dcdcb6f6c06b1f7bec1.
Note: FMCOMMS4 and FMCOMMS2/3 are sharing the same HDL project.
> arch: dts: fmcomms4: Add license and HDL project tag

- drivers/iio/beamformer/adar1000.c
This patch adds a timeout for the ADC conversion operation. Using this the
driver will not stall in a continuous loop.
> iio: beamformer: adar1000: Add ADC timeout

- drivers/iio/adc/ad9081.c
- drivers/jesd204/jesd204-core.c
- include/linux/jesd204/jesd204-of.h
- include/linux/jesd204/jesd204.h
This changeset is a quick stab at implementing a slightly more generic mechanism of loading device-tree parameters from the devicetree.
A more complete mechanism would require some more re-design of device-trees and trying to impose a more generic mechanism.
This is an intermediate mechanism to reduce some boiler-plate code in the meantime.
> jesd204,ad9081: introduce some helpers for loading JESD204 link params from DT

- drivers/dma/dma-axi-dmac.c
The max_length value can be set to UINT_MAX in some cases, resulting in an
integer overflow and a subsequent divide-by-zero. The variables are now cast
to u64 in order to avoid this condition.
This resolves  #1282 
Signed-off-by: Isaac True <isaac@is.having.coffee>
> dmaengine: axi-dmac: fix overflow resulting in divide-by-zero

- drivers/iio/adc/ad9081.c
API Version 1.0.6, disables VIF mode and uses 0Hz IF mode in case the
initial IF shift is zero. This is not desired, add dt attribute to
control the default behavior, and restore after the API setup call.
> iio: adc: ad9081: Restore default variable IF mode (VIF)

- arch/microblaze/boot/dts/kc705_ad9467_fmc.dts
- arch/microblaze/boot/dts/kc705_fmcdaq2.dts
- arch/microblaze/boot/dts/kc705_fmcjesdadc1.dts
- arch/microblaze/boot/dts/kc705_fmcomms1.dts
- arch/microblaze/boot/dts/kc705_fmcomms2-3.dts
- arch/microblaze/boot/dts/kc705_fmcomms4.dts
- arch/microblaze/boot/dts/kcu105_adrv9371x.dts
- arch/microblaze/boot/dts/kcu105_fmcdaq2.dts
- arch/microblaze/boot/dts/kcu105_fmcomms2-3.dts
- arch/microblaze/boot/dts/kcu105_fmcomms4.dts
- arch/microblaze/boot/dts/vc707_ad6676evb.dts
- arch/microblaze/boot/dts/vc707_fmcadc2.dts
- arch/microblaze/boot/dts/vc707_fmcadc5.dts
- arch/microblaze/boot/dts/vc707_fmcjesdadc1.dts
- arch/microblaze/boot/dts/vc707_fmcomms2-3.dts
- arch/microblaze/boot/dts/vc707_fmcomms4.dts
- arch/microblaze/boot/dts/vcu118_ad9081.dts
- arch/microblaze/boot/dts/vcu118_dual_ad9208.dts
- arch/microblaze/boot/dts/vcu118_fmcdaq3.dts
The edge/level sensitivities are synthesis parameter. However Linux
needs to know what kind of handler to install.
Erroneous configuration can cause undesirable behavior, such as
stuck interrupts, etc.
> microblaze: boot: dts: Fix/update intc xlnx,kind-of-intr properties

- azure-pipelines.yml
Azure doesn't support regex matching. It does support wildcard matching,
which isn't too bad. The odds of branches prefixed with '20' being matched
is pretty low.
> ci,azure: use wildcard matching for branches

- ci/travis/run-build.sh
On Azure, the main branch isn't available. We need to pull it manually to
be able to sync/cherry-pick from it.
> ci: fetch the main branch before sync-ing it

- drivers/iio/jesd204/axi_jesd204_rx.c
- drivers/iio/jesd204/axi_jesd204_tx.c
In the link_running cb, we need to allow the link to come up before
we error here.
> iio: jesd204: axi_jesd204_[rx|tx]: Allow the link to come up

- azure-pipelines.yml
When this is defined, the CSE CI user is configured as commiter for
cherry-picking.
Otherwise git complains it needs a user.
> ci,azure-pipelines: define CI=true env var for cherry-pick

- arch/arm/boot/dts/adi-adrv9002.dtsi
- arch/arm64/boot/dts/xilinx/adi-adrv9002.dtsi
- drivers/iio/adc/navassa/adrv9002.c
- drivers/iio/adc/navassa/adrv9002.h
- drivers/iio/adc/navassa/adrv9002_debugfs.c
This adds some general improvements on the driver:
1. iio: adrv9002: Add default AGC settings
2. arch: dts: Remove AGC settings from adrv9002 node
3. iio: adrv9002: Fix AGC default booleans value
4. iio: adrv9002: Remove dedicated debugfs AGC variable
5. iio: adrv9002: Add generic channels handling
6. iio: adrv9002: Improve profile validations
7. iio: adrv9002: Improve internal channel state change
> adrv9002 misc enhancements

- drivers/jesd204/jesd204-fsm.c
When a state N fails, calling the callbacks for the connections during
state N - 1 will not happen because the FSM is in state N - 1.
So, we need to allow that check to function, only if the FSM isn't rolling
back. It could be that the check is redundant. It could be removed during
an FSM rework/overhaul/rewrite.
> [2019_R2] jesd204: fsm: handle connection callbacks when starting rollback

- drivers/iio/adc/adrv9009.c
- drivers/jesd204/jesd204-fsm.c
For ADRV9009, printing state callbacks regardless of reason.
To better debug the FSM.
Fixing connection callback when starting rollback. These would get skipped when a rollback would get started.
Also handling the callback propagation in reverse order during rollback.
This is not super important now. It may be useful later.
> jesd204,adrv9009: misc jesd204 updates & fixes

- arch/arm/boot/dts/zynq-zc706-adv7511-adrv9371.dts
adi-axi-clkgen 43c00000.axi-clkgen: failed to get s_axi_aclk
adi-axi-clkgen: probe of 43c00000.axi-clkgen failed with error -2
adi-axi-clkgen 43c10000.axi-clkgen: failed to get s_axi_aclk
adi-axi-clkgen: probe of 43c10000.axi-clkgen failed with error -2
> arm: dts: zynq-zc706-adv7511-adrv9371.dts: Fix AXI-CLKGEN ENOENT issue

- azure-pipelines-rpi.yml
- azure-pipelines.yml
It reduces some duplication with regard to steps, as they need to be
defined only once.
> ci,azure-pipelines: use matrix strategy for building 

- Documentation/devicetree/bindings/hwmon/adi,ltc2992.yaml
- Documentation/hwmon/ltc2992.rst
- drivers/hwmon/ltc2992.c
Sync adi linux with upstream version of ltc2992.
> hwmon: ltc2992: Sync with upstream

- drivers/iio/adc/adrv9009.c
> iio: adc: adrv9009: Fix negative temperature readings

- drivers/iio/adc/ad7476.c
The LTC2314-14 is a 14-bit, 4.5Msps, serial sampling A/D converter that draws only
6.2mA from a wide range analog supply adjustable from 2.7V to 5.25V.
> iio: adc: ad7476: Add LTC2314-14 support

- drivers/iio/adc/adrv9009.c
Since phy->jdev is still optional, its existence should be verified
before calling jesd204_fsm() functions.
> iio: adc: adrv9009: Fix iio_dev_attr_jesd204_fsm

- drivers/nvmem/adi_axi_sysid.c
The main fix is: `nvmem: axi_sys_id: fix sysid version enum`
The others are polishes to the driver.
> nvmem: axi_sys_id: fix sysid version enum & other cleanups

- ci/travis/run-build-docker.sh
A recent change in the common lib.sh script requires that these be passed
as env-vars.
> ci: define env-vars for docker builds

- azure-pipelines-rpi.yml
- azure-pipelines.yml
- ci/travis/run-build.sh
This was not omitted by accident during migration to Azure, and wasn't
working because the TRAVIS_PULL_REQUEST check was still around.
> ci: (actually) re-enable checkpatch job

- Documentation/devicetree/bindings/clock/clk-ad9545.yaml
- Kconfig.adi
- drivers/clk/Kconfig
- drivers/clk/Kconfig.adi
- drivers/clk/Makefile
- drivers/clk/adi/Kconfig
- drivers/clk/adi/Makefile
- drivers/clk/adi/clk-ad9545-i2c.c
- drivers/clk/adi/clk-ad9545-spi.c
- drivers/clk/adi/clk-ad9545.c
- drivers/clk/adi/clk-ad9545.h
- include/dt-bindings/clock/ad9545.h
Add support for AD9545 Quad Input, 10-Output, Dual DPLL/IEEE 1588,
1 pps Synchronizer and Jitter Cleaner.
Driver currently implements:
- reference validation
- phase build-out mode only
- set_rate/get_rate/set_phase/get_phase on all 10 clock outputs
> clk: ad9545: Add support

- arch/arm/boot/dts/socfpga_cyclone5_de10_nano_cn0540.dts
Update HDL project tag in socfpga_cyclone5_de10_nano_cn0540.dts, from 'cn0540/de10' to 'cn0540/de10nano'.
> socfpga_cyclone5_de10_nano_cn0540.dts: Fix a typo

- Documentation/devicetree/bindings/clock/clk-ad9545.yaml
- drivers/clk/adi/clk-ad9545.c
"adi,init-freq-hz" is no longer used to set the aux NCO frequency.
This is done using the assigned-clock-rates.
> clk: ad9545: Fix auxiliary NCO DT parsing

- drivers/clk/adi/clk-ad9545.c
This patch sets clk_init_data structs fields to 0. Before
this patch .flag member was receiving random stack values.
> clk: ad9545: Fix clk_init_data flags

- arch/arm/boot/dts/overlays/Makefile
- arch/arm/boot/dts/overlays/adis16480-overlay.dts
Added overlay for the adis devices supported by the adis16480 driver.
> arm: dts: overlays: Add overlay for adis16480

- drivers/iio/imu/adis16480.c
The maximum SPI speed of the adis19495/97 families is 15MHz. However, in
burst mode, we cannot go higher than 6.5MHz.
> iio: adis16480: Limit spi max speed in burst mode

- drivers/iio/adc/navassa/adrv9002.c
This was raised as a warning, that turned out to be a bug.
> [2019_R2] navassa: add missing break statements

- drivers/usb/chipidea/Kconfig
- drivers/usb/chipidea/core.c
This is a reboot of commit f91cd514718ce ("usb: chipidea: Hook up ULPI
support"). The code for this got lost during the merge, but this is
required, since we have a GPIO that we need to make this work.
This is required for M2k and Pluto, so that the flash-drive gets mounted
and the USB ethernet is probed.
> usb: chipidea: Hook up ULPI support

- drivers/clk/clk-fixed-factor.c
- drivers/clk/clk.c
One is a revert. A fix was tried, but that didn't do anything.
In the meantime, the proper fix was introduced in the Xilinx tree via `clk: walk orphan list on clock provider registration `
On the M2k this fixes a division-by-zero caused by this issue.
The M2k DAC clock is a fixed-factor-clock that is orphaned, and so the parent rate is zero.
> clk: backport fixes from Xilinx master tree

- drivers/mtd/spi-nor/spi-nor.c
Make sure we read the entire EDID, or->bouncebuf is big enough.
> mtd: spi-nor: spi-nor: Fix SPI-NOR-UniqueID printing

- drivers/iio/frequency/adf4371.c
Those ports will be enabled by the CCF or can be optionally
enabled from the dt. Keep them default disabled to save power.
> iio: frequency: adf4371: Keep RF8 ports disabled

- arch/arm/boot/dts/zynq-zc702.dtsi
> arm: dts: zynq-zc702.dtsi: Add missing spi-max-frequency property

- arch/arm/boot/dts/zynq-m2k.dtsi
- arch/arm/boot/dts/zynq-pluto-sdr.dtsi
- drivers/mtd/spi-nor/spi-nor.c
According to commit 87fb64ac8af8 ("mtd: spi-nor: Add 4byte support for Zynq
QSPI controller"), "Zynq QSPI controller do not support 4byte addressing
mode.".
However, SFDP will detect it and try to use 4 byte addressing, which will
not work with Zynq QSPI.
Previously the 0x6B opcode was used with the M25P80 driver and SPI-NOR.
Now with SFDP, 0x6C is being attempted, but is failing.
With this change, 0x6B is being used again.
It's likely that there may be a better fix than this, but the way the
spi-nor driver has been patched, it's a bit difficult to identify it.
Commit 87fb64ac8af8 should have fixed it, but it did not take into account
the fact that SFDP run and can set some SPI NOR parameters.
So, the current solution is to skip SFDP if Zynq QSPI is configured.
Signed-off-by: Alexandru …
> mtd: spi-nor: don't run SFDP for Zynq QSPI

- arch/arm/boot/dts/adi-ad9081-fmc-ebz.dtsi
- arch/arm64/boot/dts/xilinx/adi-ad9081-fmc-ebz.dtsi
- arch/arm64/boot/dts/xilinx/zynqmp-zcu102-rev10-ad9081-m8-l4-vcxo122p88.dts
- arch/arm64/boot/dts/xilinx/zynqmp-zcu102-rev10-ad9081-m8-l4.dts
- arch/microblaze/boot/dts/adi-ad9081-fmc-ebz.dtsi
There are different variants of the AD9081-FMCA-EBZ & AD9082-FMCA-EBZ
They differ in the VCXO frequency. Let's make the 100MHz the default.
> dts: AD9081-FMCA-EBZ: Consider the VCXO=100.00 MHz the default

- arch/arm64/boot/dts/xilinx/zynqmp-zcu102-rev10-ad9082-m4-l8.dts
Add device tree for the AD9082-FMCA-EBZ.
FADC=6GHz,  DECIM=4,  IQrate=1.5GSPS, JESD204B Mode=18
FDAC=12GHz, INTERP=8, IQrate=1.5GSPS, JESD204B Mode=17
The corresponding HDL project was build using following parameters.
make RX_JESD_L=8 RX_JESD_M=4 RX_JESD_S=1 TX_JESD_L=8 TX_JESD_M=4 TX_JESD_S=1
> arm64: dts: zynqmp-zcu102-rev10-ad9082-m4-l8.dts: Add AD9082-FMCA-EBZ dt

- drivers/hwmon/ltc2945.c
When commit 91e4717fc9268 ("hwmon: (ltc2945): wrap regmap into an
ltc2945_state struct") it should have also contained this fix, to store the
new state struct, and not the regmap pointer.
This causes a crash when trying to read data from the device.
Fixes: 91e4717fc9268 ("hwmon: (ltc2945): wrap regmap into an ltc2945_state struct")
> hwmon: ltc2945: fix private data reference

- drivers/hwmon/ltc2945.c
When commit 91e4717fc9268 ("hwmon: (ltc2945): wrap regmap into an
ltc2945_state struct") it should have also contained this fix, to store the
new state struct, and not the regmap pointer.
This causes a crash when trying to read data from the device.
Fixes: 91e4717fc9268 ("hwmon: (ltc2945): wrap regmap into an ltc2945_state struct")
Reported-by: Pierre-Yves Lauzier Trépanier <Pierre-Yves.Lauzier.Trepanier@USherbrooke.ca>
> [2019_R2] hwmon: ltc2945: fix private data reference

- arch/arm/boot/dts/zynq-zed-adrv9002-rx2tx2.dts
Update the hdl project tag in zynq-zed-adrv9002-rx2tx2.dts from 'adrv9001/zcu102' to 'adrv9001/zed'.
> zynq-zed-adrv9002-rx2tx2.dts: Fix hdl project tag

- drivers/iio/adc/adrv9009_conv.c
This avoids a potential memory access failure.
> iio: adc: adrv9009_conv: In RX only operation skip configure DAC TPL

- drivers/iio/adc/navassa/adrv9002.c
- drivers/iio/adc/navassa/adrv9002.h
There is some information that might be useful to know about the current
profile which is not exported trough common IIO infrastructure. Hence, we
use the bin attribute used to load the profile to fetch this info. We
need to make the size of the attr 0 otherwise `cat profile_config` would
try to read the compete size and we don't have that much info to share.
For now this is an example of data exported:
```
root@analog:/sys/bus/iio/devices/iio:device1# cat profile_config
Device clk(Hz): 38400000
Clk PLL VCO(Hz): 8847360000
ARM Power Saving Clk Divider: 1
RX1 LO: L02
RX2 LO: L02
TX1 LO: L01
TX2 LO: L01
RX Channel Mask: 0xf3
TX Channel Mask: 0xc
Duplex Mode: FDD
FH enable: 0
MCS mode: Disabled
SSI interface: LVDS
```
Since I'm touching the bin attr, I took the opportunity to declare it
as …
> iio: adrv9002: support reading profile_config

- arch/arm/boot/dts/zynq-zed-adrv9002-rx2tx2.dts
- arch/arm/boot/dts/zynq-zed-adrv9002.dts
Include AD7511 and related nodes so user can connect a monitor to the
HDMI interface.
Remove SYSID since it is already included in the zynq-zed-adv7511.dtsi
> arch: dts: zynq-zed-adrv9002: Enable HDMI output

- drivers/iio/adc/navassa/adrv9002.c
- drivers/iio/adc/navassa/adrv9002.h
- drivers/iio/adc/navassa/adrv9002_conv.c
- drivers/iio/adc/navassa/adrv9002_debugfs.c
iio: adrv9002: fix irq handling
iio: adrv9002: Fix debugfs AGC parameter
iio: adrv9002: disable axi core before device setup
iio: adrv9002: validate ssi interface before device setup
iio: adrv9002: call adrv9002_init() on debugfs
iio: adrv9002: remove adrv9002_intf_tuning_unlocked()
iio: adrv9002: centralize device initialization
The first 2 patches are just "helper" patches to the real bugfixes..
> adrv9002 bugfixes backport

- ci/travis/run-build.sh
- drivers/spi/spi.c
- include/linux/spi/spi.h
The SPi interface in 4.19 is broken for GPIO chip selects. Once a device starts all the GPIO CS go low and recover to HIGH only after the first SPI transfer. This behavior has been fixed in rpi-5.4.y so this is just a backport of 3 patches to fix this bug.
> Fix rpi spi

- drivers/clk/adi/clk-ad9545.c
Wrong operator was used to write data byte by byte in
r-divider registers.
Fixes: e649163a47aef ("clk: ad9545: Add support")
> clk: ad9545: Fix r-div write

- drivers/iio/adc/adrv9009.c
In ADC stitching mode we need to ensure that only one ORX is enabled.
However we also need to allow this to be ORX2. Therefore only clobber
obsRxChannelsEnable in case both are enabled. In this case pick one.
> iio: adc: adrv9009: Fix obsRxChannelsEnable clobbering in stitching mode

- drivers/iio/adc/Kconfig
- drivers/iio/adc/navassa/Makefile
Instead of just enabling verbosity on errors and parameters validation on
the API, make this configurable through Kconfig. This makes things neater
and we still keep the same default behavior. But now we can disable things
without having to directly tweak the Makefile.
> iio: adrv9002: add new kconfig options

- drivers/clk/clk-axi-clkgen.c
Displaying an error message when s_axi_aclk is not yet ready
might be confusing for the users.
An example for which this happens before axi-clkgens get
registered, is the zcu102-adrv9009 project:
adi-axi-clkgen 83c00000.axi-clkgen: failed to get s_axi_aclk
adi-axi-clkgen 83c10000.axi-clkgen: failed to get s_axi_aclk
adi-axi-clkgen 83c20000.axi-clkgen: failed to get s_axi_aclk
> clk: axi-clkgen: Don't display error when -EPROBE_DEFER

- ci/travis/run-build.sh
Checkpatch was failing for Azure. This is the error and the fix:
Package python-git is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
python-git-doc
E: Package 'python-git' has no installation candidate
Error: Process completed with exit code 100.
> ci: checkpatch: Replace python-git to python-git-doc

- arch/arm/boot/dts/zynq-zed-adrv9002-rx2tx2.dts
Update hdl project tag from 'adrv9001/zcu102' to 'adrv9001/zed'.
> dts: zynq-zed-adrv9002-rx2tx2.dts: Fix hdl project tag

- drivers/iio/adc/adrv9009.c
Since TALISE_setTxAttenCtrlPin() is not called anywhere outside adrv9009.c,
the initial settings related to tx1/2_atten_ctrl_pin where not applied (e.g.,
attenuation pin control was kept disabled independent of
"adi,tx1-atten-ctrl-pin-enable"/"adi,tx2-atten-ctrl-pin-enable" properties).
> iio: adc: adrv9009: Apply initial tx1/2_atten_ctrl_pin settings

- drivers/clocksource/timer-cadence-ttc.c
This reverts commit f5ac896b6a23eb46681cdbef440c1d991b04e519.
Because of this change we sometimes get on some systems:
clocksource: ttc_clocksource: mask: 0xffff max_cycles: 0xffff, max_idle_ns: 716713566 ns
clocksource: Switched to clocksource ttc_clocksource
------------[ cut here ]------------
WARNING: CPU: 0 PID: 1 at kernel/time/sched_clock.c:179 sched_clock_register+0x50/0x260
Modules linked in:
CPU: 0 PID: 1 Comm: swapper/0 Not tainted 5.4.0-13598-g99be0914fc99-dirty #19
Hardware name: Xilinx Zynq Platform
[<c010db18>] (unwind_backtrace) from [<c010a218>] (show_stack+0x10/0x14)
[<c010a218>] (show_stack) from [<c05eaba8>] (dump_stack+0xb0/0xcc)
[<c05eaba8>] (dump_stack) from [<c011b144>] (__warn+0xb8/0xd0)
[<c011b144>] (__warn) from [<c011b1d4>] (warn_slowpath_fmt+0x78/0xac) …
> [RFC] Revert "clocksource/drivers/cadence-ttc: Use ttc driver as platform driver"

- drivers/iio/adc/adrv9009.c
This fixes a typo in the Fast Frequency Hopping calibration attribute.
> iio: adc: adrv9009: Fix typo in calibrate_fhm_en attribute

- Documentation/devicetree/bindings/clock/clk-ad9545.yaml
- drivers/clk/adi/clk-ad9545.c
Allow the user to specify the DPLL loop filter bandwidth in uHz instead of Hz. Less than 1 Hz loop bandwidth is required for locking on very low freq references like GPS.
> Ad9545 allow uhz loop bw

- drivers/iio/adc/ad9361.c
Since the attribute has a _store function defined, S_IWUSR
should be also set.
The issue was pointed by: https://github.com/analogdevicesinc/linux/issues/1461
> iio: adc: ad9361: Fix rssi_gain_step_error DEVICE_ATTR mode

- drivers/iio/frequency/cf_axi_dds.c
On the DMA/Buffer side we always use common data types 8/16/32.
So in case we have NP=12 mode, we need to set storagebits to 16.
This commit also enables the optional shift format.
> iio: frequency: cf_axi_dds: Roundup JESD204 NP always to the next pow2

- Documentation/devicetree/bindings/clock/clk-ad9545.yaml
- drivers/clk/adi/clk-ad9545.c
Add support for TDC sources priorities.
TDC sources can be RefA, RefB and auxiliary NCOs. AD9545 will use as input for the DPLLs a valid TDC source with the highest priority specified in the DT. If an error occurs on a used TDC source AD9545 will automatically revert to a valid one with a lower priority.
Even if only one source can be used at a time by a DPLL, when setting the rate of the DPLL, the driver will
compute N div, FRAC, MOD for all possible TDC sources. Those parameters are stored on chip in Translation Profiles. See:
ad9545_pll_set_rate
This is needed in order to maintain the same PLL output frequency, even after reference switching.
> Ad9545 add ref priorities

- arch/arm64/boot/dts/xilinx/zynqmp-adrv9009-zu11eg-reva-adrv2crr-fmc-reva.dts
The SW_LID code was causing powering issues on adrv9009-zu11eg. Since we do
not require a SW_LID code to be sent it makes more sense to change it to
something else that would not impact functionality.
Related to https://github.com/analogdevicesinc/linux/issues/1464
> arch: arm64: dts: Change SW0 linux code to  SW_LINEIN_INSERT

- drivers/iio/adc/navassa/adrv9002.c
- drivers/iio/adc/navassa/adrv9002_conv.c
Some low rate profiles don't play well with prbs15. The reason is still unclear. We suspect that the chip error checker might have
some time constrains and cannot reliable validate prbs15 full sequences in the test time. Using a shorter sequence as prbs7 fixes the problem...
> [ADRV9002 - 2019_R2] Fix low rate profiles

- drivers/iio/adc/navassa/adrv9002.c
- drivers/iio/adc/navassa/adrv9002_conv.c
Some low rate profiles don't play well with prbs15. The reason is still unclear. We suspect that the chip error checker might have
some time constrains and cannot reliable validate prbs15 full sequences in the test time. Using a shorter sequence as prbs7 fixes the problem...
The last patch is just a small improvement on the tx tuning logic...
> [ADRV9002] Fix low rate profiles

- Documentation/devicetree/bindings/clock/clk-ad9545.yaml
- drivers/clk/adi/clk-ad9545.c
In fast acquisition the DPLL automatically reduces
the loop bandwidth by successive factors of 2 while the loop is
acquiring.
This mechanism drastically reduces DPLL locking time
for low loop bandwidth applications like 1 pps signals.
> Ad9545 add fast acquisition

- drivers/clk/adi/clk-ad9545.c
Wrong macro used to translate source index.
Fixes: 86eb803984c3 ("clock: ad9545: Add reference priorities")
> clk: ad9545: Fix source selection

- drivers/iio/adc/navassa/adrv9002.c
- drivers/iio/adc/navassa/adrv9002_debugfs.c
We need to synchronize all IIO accesses on the device channels with
updating the device profile. This means, that all checks like:
```
if (!chan->enabled)
return -ENODEV;
```
__must__ be done inside the device lock. Otherwise something like the
following could happen:
1. CPU1 tries to do some configuration on TX1 (passes `the tx->enabled`);
2. CPU2 starts a profile update and grabs the lock;
3. CPU1 will wait on the lock before doing the configuration;
4. CPU2 releases the lock (new profile disables TX1);
5. CPU1 will try to do something on a disabled channel.
Best case scenario we just get an error from the device. Worst case, we
"lock" the device firmware...
While applying this change to debugfs interfaces, we just unify checking if
the channel is enabled or not (as this is simple …
> [2019_R2] iio: adrv9002: fix possible data races

- drivers/iio/adc/navassa/adrv9002.h
- drivers/iio/adc/navassa/adrv9002_conv.c
- drivers/iio/adc/navassa/adrv9002_debugfs.c
This adds support for near end loopback in debugfs. This enables internal
fpga loppback which means that the hdl ADCs will take data from the
internal hdl DACs.
> iio: adrv9002: support near end loopback

- drivers/iio/adc/navassa/adrv9002.c
- drivers/iio/adc/navassa/adrv9002_debugfs.c
We need to synchronize all IIO accesses on the device channels with
updating the device profile. This means, that all checks like:
```
if (!chan->enabled)
return -ENODEV;
```
__must__ be done inside the device lock. Otherwise something like the
following could happen:
1. CPU1 tries to do some configuration on TX1 (passes `the tx->enabled`);
2. CPU2 starts a profile update and grabs the lock;
3. CPU1 will wait on the lock before doing the configuration;
4. CPU2 releases the lock (new profile disables TX1);
5. CPU1 will try to do something on a disabled channel.
Best case scenario we just get an error from the device. Worst case, we
"lock" the device firmware...
While applying this change to debugfs interfaces, we just unify checking if
the channel is enabled or not (as this is simple …
> iio: adrv9002: fix possible data races

- drivers/iio/adc/ad7124.c
Currently AD7124-8 driver could not use more than 8 IIO channels
because it was assigning the channel configurations bijectively
to channels specified in the device-tree. This is not possible
to do when using more than 8 channels as AD7124-8 has only 8
configuration registers.
This patch implements LRU and packing of configurations
in order to allow the user to specify more than 8 channels
in device-tree.
> iio: adc: ad7124: allow more than 8 channels

- arch/arm64/boot/dts/xilinx/adi-ad9081-fmc-ebz.dtsi
- arch/arm64/boot/dts/xilinx/zynqmp-zcu102-rev10-ad9081-m8-l4.dts
- arch/arm64/boot/dts/xilinx/zynqmp-zcu102-rev10-ad9081.dts
Don't violate max rate of 1500MHz between CDDC/FDDC.
Use QPLL for RX otherwise we violate max lane rate.
> arm64: dts: adi-ad9081-fmc-ebz.dtsi: Fix JESD204 use case

- drivers/iio/jesd204/axi_adxcvr.c
- drivers/iio/jesd204/axi_adxcvr.h
- drivers/iio/jesd204/xilinx_transceiver.c
- drivers/iio/jesd204/xilinx_transceiver.h
This commit adds support for physical layer PRBS Generation and Checking.
The new feature is supported starting with HDL core version 17.02.a
Depending on the direction AXI-ADXCVR-RX or AXI-ADXCVR-TX different new
sysfs files are supported which are explained below.
axi-adxcvr-rx:
prbs_select
Writing selects the PRBS type. (accepted values depend on the GT
architecture) Reading returns the selected type.
0: PRBS_DISABLE
7: PRBS7
9: PRBS9
15: PRBS15
23: PRBS23
31: PRBS31
prbs_status:
Reading returns a status string. Values are:
unlocked: The PRBS is unlocked
valid: The PRBS is locked and no errors are detected
error: The PRBS has locked but errors were detected
These conditions are sticky and can be cleared by writing 1 to
prbs_counter_reset
prbs_error_counters:
Reading returns a string …
> iio: jesd204: axi_adxcvr: Support for physical layer PRBS

- drivers/iio/adc/navassa/adrv9002.c
We were returning the function without unlocking the device mutex in case
orx is not enabled.
Fixes: e13f42041ff9 ("iio: adrv9002: fix possible data races")
> iio: adrv9002: fix possible deadlock

- Documentation/devicetree/bindings/clock/clk-ad9545.yaml
- drivers/clk/adi/clk-ad9545.c
Remove the default value from driver and add the FACQ trigger option in the device tree.
> Ad9545 add fast acq trigger

- drivers/iio/adc/navassa/adrv9002.c
This PR adds some improvements to the device cleanup in case of errors in the initialization phase. We also need to reset the ORx state in `adrv9002_cleanup()`...
> adrv9002 improve dev cleanup

- drivers/iio/adc/navassa/adrv9002.c
- drivers/iio/adc/navassa/adrv9002.h
- drivers/iio/adc/navassa/adrv9002_conv.c
The assumption until now was that TX ports could only be enabled if the RX port on the same channel (some differences in rx2tx2) was also enabled. The reason for this is that the TX clock is derived from RX SSI interface. While this will still be true for LVDS interfaces, it won't apply anymore for CMOS. In that case, we will be able to have TX ports enabled without the corresponding RX. Hence, the profile validations have to be done in a different way. These are the restrictions being applied on systems supporting tx only profiles:
1. Split mode can have all 4 ports with different rates;
2. Split mode can have any combination for enabling/disabling ports;
3. rx2tx2 mode cannot have RX2 enabled while RX1 is off (same for TX);
4. rx2tx2 mode cannot have RX2 rate != RX1 rate (same for TX). …
> adrv9002 tx only profiles

- arch/arm/boot/dts/overlays/Makefile
- arch/arm/boot/dts/overlays/rpi-adxrs290-overlay.dts
Added support for adxrs290 via SPI0 of RPI.
Signed-off-by: kimpaller <kimchesed.paller@analog.com>
> arch: arm: overlays: rpi-adxrs290 support

- drivers/iio/adc/Kconfig
These select statements allow AD7768 and AD7768-1 to be compiled as part of the kernel
> update kconfig with missing select statements

- arch/arm64/boot/dts/xilinx/zynqmp-zcu102-rev10-ad9081-m8-l4.dts
- drivers/iio/frequency/cf_axi_dds.c
This commit adds support for a new single-shot mode of util_dacfifo.
Note: This feature requires HDL support and is only enabled if the
single-shot-output-gpios attribute is provided in the device tree!
Signed-off-by: David Winter <david.winter@analog.com>
> drivers: frequency: cf_axi_dds: Add dacfifo singleshot output support

- drivers/iio/adc/ad9083.c
This patch will generate "jesd_m" number of channels, parameter parsed from
the device tree at run time.
Also check if channels are complex or not.
> iio: adc: ad9083: Generate "jesd_m" channels and check they are complex.

- Documentation/devicetree/bindings/iio/amplifiers/adi,ada4250.yaml
- drivers/iio/Kconfig.adi
- drivers/iio/amplifiers/Kconfig
- drivers/iio/amplifiers/Makefile
- drivers/iio/amplifiers/ada4250.c
ADA4250 is an instrumentation amplifier with SPI programmable gains that
is optimized for ultra-low power systems.
> drivers:iio:amplifiers: ADA4250 support

- drivers/iio/adc/navassa/adrv9002.c
The driver was returning TDM instead of TDD for TDD profiles...
Fixes: 13c38fb977a6e ("iio: adrv9002: support reading profile_config")
> iio: adrv9002: set the correct string for duplex mode

- drivers/iio/adc/navassa/adrv9002.c
Fixes ORx not being enabled if the RX on the same channel is not... ORx actually depends on TX. The second patch is a minor change on a return value that (at this moment) should not have "side" effects
> Fix adrv9002 ORx

- drivers/iio/amplifiers/ada4250.c
Fix warnings related to `range` and `vlsb` variables that may be used
uninitialized in the `set_offset` function.
> drivers:iio:amplifier:ada4250: fix warnings

- Documentation/devicetree/bindings/iio/frequency/ad916x.yaml
- drivers/iio/frequency/ad9162.c
The ad9162 driver should also be capable of handling the following devices:
* AD9161;
* AD9163;
* AD9164.
We just had to be careful about nco only mode as it's not supported on all devices.
> new ad9162 compatible devices

- Documentation/devicetree/bindings/clock/clk-ad9545.yaml
- drivers/clk/adi/clk-ad9545.c
- include/dt-bindings/clock/ad9545.h
Aux. DPLL can be used as closed loop compensation for the system clock.
A stable reference can be used as a source for the Aux. DPLL. This source
can be received at one of the Mx pins and routed through an aux. TDC
or can be an input Ref. X.
> Ad9545 sys clock compensation

- drivers/iio/frequency/ad9162.c
- drivers/iio/frequency/cf_axi_dds.c
Some time ago the HDL design was updated to use M=2, so the complex mode
workaround using HDL TPL core register 0x428 is no longer necessary.
In addition the DDS channel defines are missing two channels.
This patch fixes this. However this caused the
out_altvoltage2_frequency_nco channel attribute to collide with the added
out_altvoltage2_TX1_Q_F1_raw attribute and libiio wasn't able to resolve
the extended_name anymore. This fixes this issue by changing the
requency_nco attribute to channel4.
> iio: frequency: ad9162: Fix complex NCO mode

- drivers/iio/frequency/ad9162.c
- drivers/iio/frequency/cf_axi_dds.c
iio: frequency: ad9162: Fix complex NCO mode
Some time ago the HDL design was updated to use M=2, so the complex mode
workaround using HDL TPL core register 0x428 is no longer necessary.
In addition the DDS channel defines are missing two channels.
This patch fixes this. However this caused the
out_altvoltage2_frequency_nco channel attribute to collide with the added
out_altvoltage2_TX1_Q_F1_raw attribute and libiio wasn't able to resolve
the extended_name anymore. This fixes this issue by changing the
requency_nco attribute to channel4.
> Fix ad9162

- drivers/iio/adc/navassa/adrv9002.c
- drivers/iio/adc/navassa/adrv9002.h
- drivers/iio/adc/navassa/adrv9002_conv.c
This backports two fixes for 2019_R2:
* Allow TX only profiles to be loaded. Without this, we would return error in case tx is enabled and rx not. However, in some cases (as explained in the patch log) that is actually possible...
* With the new SDK release, we can select between long/short SSI strobes. However, we only support short strobe so we cannot allow profiles with long strobe configured.
> adrv9002 2019 r2 backports

- arch/arm64/boot/dts/xilinx/zynqmp-zcu102-rev10-ad9081-m8-l4-do.dts
- arch/arm64/boot/dts/xilinx/zynqmp-zcu102-rev10-ad9081.dts
To prevent current designs from breaking, the data offload engine should
only be enabled when explicitly requested.
This commit removes the device tree entry from the generic AD9081 / ZCU102
reference design and moves it into its own file.
> arch: arm64: dts: Move data_offload enabled design to separate dts

- arch/arm64/boot/dts/xilinx/zynqmp-zcu102-rev10-ad9081-204b-txmode9-rxmode4.dts
This patch correctly sets the JRX TPL phase adjust.
> arm64: dts: ad9081-204b-txmode9-rxmode4: Revise JRX TPL phase adjust

- drivers/misc/adi-axi-data-offload.c
This commit adjusts use of the transfer length register to match the
latest hardware revision.
In short, the transfer_length % 64 == 0 constraint was moved into
hardware, by just storing REGMAP[TRANSFER_LENGTH] = length >> 6.
This is an improvement in two ways:
* The user can no longer request invalid transfer lengths which may result
in an additional data beat.
* Transfer lengths larger than 4 GiB can now be represented in a single
32-bit register. The hardware is expected to support storage sizes of
up to 16 GiB, which would have been an issue with the previous setup.
> misc: adi-axi-data-offload: Update transfer_length register use

- drivers/net/phy/adin1100.c
net: phy: adin1100: Add get_features hook:
- move features selection in the get_features callback
net: phy: adin1100: Add reset ops:
- chip supports software reset
net: phy: adin1100: Fix aneg status read:
- Auto negotiation status is now read from 0x0201 C45 register
- Before this patch current speed and full/half duplex could not be printed by ethtool
> Adin1100 ethtool supp

- drivers/iio/adc/navassa/adrv9002.c
- drivers/iio/frequency/cf_axi_dds.c
This patchset fixes some minor races that could happen. The first patch would already be enough for not having issues in the dds_driver. Nevertheless, it's a good thing that we make sure we do not have receive rate=0 and the second patch is about that...
> Misc improvements

- arch/arm/boot/dts/socfpga_cyclone5_de10_nano.dtsi
Similar to Cyclone 5 SoCKit platform, enable watchdog0 for DE10-Nano
too. This is required when U-Boot also enables it - in the latest
versions this happens by default.
socfpga_cyclone5.dtsi (included by socfpga_cyclone5_de10_nano.dtsi)
enables watchdog0.
Signed-off-by: Liviu Adace <liviu.adace@analog.com>
> arch: arm: boot: dts: Enable watchdog0 for DE10-Nano

- drivers/iio/gyro/adis16136.c
- drivers/iio/gyro/adis16260.c
- drivers/iio/imu/adis16400.c
- drivers/iio/imu/adis16475.c
- drivers/iio/imu/adis16480.c
- drivers/iio/imu/adis_buffer.c
- include/linux/iio/imu/adis.h
This patch just syncs the adis lib and drivers wih upstream. Naturally,
there are some minor things that can't still be synced but we this, we are
very close to the upstream version.
> iio: adis: sync with upstream

- drivers/iio/adc/cf_axi_tdd.c
The clock rate variable can be written and read at the same time from two
different cpus/threads. Hence, the readers can potentially read a mixture
of the old and new value. As we don't really care if the value we read is
the old or the new one, we can do a relaxed read/write of the shared
resource. We just want to make sure we have a valid value and not some
weird mixture.
Fixes: f799193a1f2d0 ("iio: cf_axi_tdd: Replace profile_config")
> iio: axi_tdd: fix possible data race

- drivers/base/regmap/regmap.c
This patch adds support for 7 bits register, 17 bits value type register
formating. This is used, for example, by the Analog Devices
ADMV1013/ADMV1014.
> regmap: add support for 7/17 register formating

- Documentation/devicetree/bindings/clock/clk-ad9545.yaml
- drivers/clk/adi/clk-ad9545.c
Allow user to change ,using the DT, the fill/drain rate parameters
of the PLL phase/lock detector. These must be customized
for low PLL bandwidth applications like 1 pps. Also affects
behavior of the fast acquisition process, which uses the lock status
in order to change the PLL loop bandwidth.
> Ad9545 add tub properties

- arch/arm64/boot/dts/xilinx/zynqmp-zcu102-rev10-stingray.dts
There is only one device left on the new revision C xud board.
> arch: arm64: dts: stingray: Remove adf4371 device.

- drivers/iio/jesd204/xilinx_transceiver.c
There is a typo, which causes VCO0_min to be clobbered when VCO1_min
provided in the devicetree.
> iio: jesd204: xilinx_transceiver: Fix QPLL VCO1 min overwrite bug

- arch/arm64/boot/dts/xilinx/zynqmp-adrv9009-zu11eg-reva.dtsi
ZU11EG uses MIO16, MIO17 for UART1 these two pins belong to uart1_4_grp
group: uart1_4_grp
pin 16 (MIO16)
pin 17 (MIO17)
> dts: zynqmp-adrv9009-zu11eg-reva.dtsi: Fix UART1 pinctrl assignments

- drivers/iio/adc/navassa/adrv9002_conv.c
When ADI_ADRV9001_SSI_TYPE_LVDS, data type is always DDR.
Fixes: https://github.com/analogdevicesinc/linux/commit/4e87369884e44a8a91df76f190f252d6229216e4
> iio: adc: adrv9002_conv: Fix the DDS rate calculation

- Documentation/devicetree/bindings/trivial-devices.yaml
- MAINTAINERS
- arch/arm/boot/dts/overlays/Makefile
- arch/arm/boot/dts/overlays/rpi-adxl313-overlay.dts
- drivers/iio/accel/Kconfig
- drivers/iio/accel/Makefile
- drivers/iio/accel/adxl313.h
- drivers/iio/accel/adxl313_core.c
- drivers/iio/accel/adxl313_i2c.c
- drivers/iio/accel/adxl313_spi.c
This PR adds a minimal skeleton driver for the ADXL313 3-axis digital acceleromter and adds it to the device-tree's list of trivial devices.
Done as part of the GSoC 2021, under The Linux Foundation.
> Skeleton driver for ADXL313

- drivers/iio/frequency/adf4371.c
The .num_channels from adf4371_chip_info is incorrectly set for ADF4371 from
the IIO point of view (however, correctly set from the clock framework point
of view) to 4, because IIO_TEMP is not taken into consideration. This makes
the last IIO channel (corresponding to ADF4371_CH_RF32 in this case)
unavailable.
> iio: frequency: adf4371: Expose ADF4371_CH_RF32's IIO attributes

- drivers/iio/frequency/adf4371.c
The .num_channels from adf4371_chip_info is incorrectly set for from
the IIO point of view (however, correctly set from the clock
framework point of view) to 4 (ADF4371) and 3 (ADF4372), because
IIO_TEMP is not taken into consideration. This makes the last
IIO channel (corresponding to ADF4371_CH_RF32 - ADF4371 and
ADF4371_CH_RF16 - ADF4372) unavailable.
> iio: frequency: adf4371: Export all IIO channels

- drivers/iio/adc/cf_axi_tdd.c
DMA gating is controlled by bit [5:4] of the TDD control word 0, where bit 5 represents TX and bit 4 RX. Going through the four possible values gives us:
* `0b00` : `0`: Gating disabled
* `0b01` : `1`: RX gated
* `0b10` : `2`: TX gated
* `0b11` : `3`: RX and TX gated
This commit simply swaps `rx_tx` and `none`.
References:
* [Regmap](https://wiki.analog.com/resources/fpga/docs/hdl/regmap)
Note: This is technically a change to the public api, i'm not sure about the policy here ...
> iio: cf_axi_tdd: Fix swapped values in DMA gating enum

- drivers/iio/industrialio-buffer.c
- drivers/iio/inkern.c
Make sure that the complete buffer scan mask gets cleared before
computing a new one. For that we need to multiply the number of elements
by the element size.
Fixes: 81d00795b1537 ("iio: Track enabled channels on a per channel basis")
The issue was brought up in the iio mailing list in this [thread](https://marc.info/?l=linux-iio&m=162205504405949&w=2).
> iio: buffer: fix channel {en|dis}ablement

- drivers/iio/adc/navassa/adrv9002_conv.c
There was a precedence issue in the rate calculation. The issue was on the
expression using the ternary operator making it a bit harder than usual to
spot. With this patch, we make things more explicit by removing the ternary
operator. We add some more lines of code but we make the code (and the
expression) more readable.
Fixes: 6fe83818f07f5 ("iio: adc: adrv9002_conv: Fix the DDS rate calculation")
> iio: adrv9002: fix the DDS rate calculation

- Documentation/devicetree/bindings/trivial-devices.yaml
- MAINTAINERS
- arch/arm/boot/dts/overlays/Makefile
- arch/arm/boot/dts/overlays/rpi-ad5110-overlay.dts
- drivers/iio/potentiometer/Kconfig
- drivers/iio/potentiometer/Makefile
- drivers/iio/potentiometer/ad5110.c
This PR adds a bare-minimal skeleton driver for ADI's AD5110, a Nonvolatile Digital Potentiometer. Along with the driver, this PR includes a device-tree overlay for AD5110 to use with Raspberry Pi and adds it to the device-tree's list of trivial devices.
Done as part of GSoC 2021, under The Linux Foundation.
> Skeleton driver for AD5110 Digital potentiometer

- arch/arm/boot/dts/adi-fmcomms8.dtsi
- arch/arm64/boot/dts/xilinx/adi-fmcomms8.dtsi
- arch/arm64/boot/dts/xilinx/zynqmp-adrv9009-zu11eg-reva.dtsi
- arch/arm64/boot/dts/xilinx/zynqmp-adrv9009-zu11eg-revb-adrv2crr-fmc-revb-sync-fmcomms8.dts
- drivers/iio/frequency/hmc7044.c
Draws extra current and doesn't improve much.
> iio: frequency: hmc7044: Remove option for High performance PLLs/VCO

- Documentation/devicetree/bindings/iio/frequency/adi,admv1014.yaml
- drivers/iio/Kconfig.adi
- drivers/iio/frequency/Kconfig
- drivers/iio/frequency/Makefile
- drivers/iio/frequency/admv1014.c
Add support for ADMV1014 Microwave Downconverter.
More info:
https://www.analog.com/en/products/admv1014.html
> drivers:iio: add ADMV1014 support

- Documentation/devicetree/bindings/iio/frequency/adi,admv1013.yaml
- drivers/iio/Kconfig.adi
- drivers/iio/frequency/Kconfig
- drivers/iio/frequency/Makefile
- drivers/iio/frequency/admv1013.c
Add support for ADMV1013 Microwave Upconverter.
More info:
https://www.analog.com/en/products/admv1013.html
Signed-off-by: Antoniu Miclaus antoniu.miclaus@analog.com
> drivers:iio: add ADMV1013 support

- drivers/iio/frequency/admv1013.c
- drivers/iio/frequency/admv1014.c
Remove `sysfs.h` includes after removal of the custom IIO device
attributes.
> drivers:iio:frequency: remove unused header

- drivers/iio/adc/ad9083.c
This commit simply adds the missing mutex_init to the AD9083 driver.
Fixes #1535
> iio: adc: ad9083: Add missing mutex_init

- drivers/iio/frequency/admv1013.c
Return invalid argument if vcm value is outside of the supported bounds.
Fixes: 0538776 (iio:frequency:admv1013:add support for ADMV1013)
> drivers:iio:admv1013: add default case

- Documentation/devicetree/bindings/iio/frequency/adi,adrf6780.yaml
- drivers/iio/Kconfig.adi
- drivers/iio/frequency/Kconfig
- drivers/iio/frequency/Makefile
- drivers/iio/frequency/adrf6780.c
Add support for the ADRF6780 microwave upconverter.
More info:
https://www.analog.com/en/products/adrf6780.html
> iio:frequency:adrf6780: add support for ADRF6780

- arch/arm64/boot/dts/xilinx/zynqmp-adrv9009-zu11eg-reva.dtsi
With commit cb7956a28117 ("hwmon: axi-fan-contro: Sync with upstream"),
the devicetree binding for "adi,pulses-per-revolution" changed to
"pulses-per-revolution" as this a generic property of a FAN. Hence, the
talise devicetree needs to be properly updated otherwise the driver
won't probe.
> arm64: dts: fix axi-fan-control probing

- arch/arm64/boot/dts/xilinx/zynqmp-adrv9009-zu11eg-reva.dtsi
With commit cb7956a28117 ("hwmon: axi-fan-contro: Sync with upstream"),
the devicetree binding for "adi,pulses-per-revolution" changed to
"pulses-per-revolution" as this a generic property of a FAN. Hence, the
talise devicetree needs to be properly updated otherwise the driver
won't probe.
> [2019_R2]: arm64: dts: fix axi-fan-control probing

- arch/arm/boot/dts/zynq-zed-adv7511-adrv9002-rx2tx2.dts
- arch/arm/boot/dts/zynq-zed-adv7511-adrv9002.dts
- arch/arm64/boot/dts/xilinx/zynqmp-zcu102-rev10-adrv9002-rx2tx2.dts
- arch/arm64/boot/dts/xilinx/zynqmp-zcu102-rev10-adrv9002.dts
This patch adds IIO labels for the axi_tdd_core present on the adrv9002
based projects. This fixes some userland apps that have to identify
multiple instances of this core.
> arch: arm{64}: dts: add iio labels to the adrv9002 TDD core

- drivers/iio/frequency/ad9528.c
- drivers/iio/frequency/hmc7044.c
- include/linux/iio/frequency/ad9528.h
iio: frequency: jesd204-fsm add support for desired SYSREF
The framework allows to specify a max SYSREF frequency. The drivers
then divide by powers of 2 the lmfc rate. This leaves out some possible
rates in between. Add an option to specify the SYSREF frequency.
>  iio: frequency:  jesd204-fsm add support for desired SYSREF

- drivers/clk/adi/clk-ad9545.c
clk: ad9545: Add debugfs status: Add debugfs files for the two PLL blocks, 4 input references, Auxiliary DPLL:
AUX_DPLL:
Lock status: Unlocked
Reference: Faulted
PLL0:
PLL status: Locked
Freerun Mode: Off
Holdover Mode: Off
PLL Profile: On
Profile Number: 0
Temperature: 49 C
Ref-A-Div:
Reference: Faulted: Too Fast Too Slow
clk: ad9545: Fix typo: fixed a typo in the ad9545_pll_clk struct
> Ad9545 add status debugfs

- drivers/iio/adc/adrv9009.c
In case TALISE_waitInitCals() return action/error make sure that
errorFlag gets printed. In addition it may return the action to
rerun the Cals, do it once before error out.
> iio: adc: adrv9009: Improve InitCals error handling and reporting

- arch/arm/boot/dts/zynq-adrv9361-z7035-bob.dts
- arch/arm/boot/dts/zynq-adrv9361-z7035-fmc.dts
- arch/arm/boot/dts/zynq-adrv9364-z7020-bob.dts
- arch/arm/boot/dts/zynq-zc702.dtsi
This will prevent the boards from directly going into sleep/standby mode
during their boot process.
SW_LID event was replaced by SW_LINEIN_INSERT for consistency reasons
(it is used by adrv9009-zu11eg too).
> arch: arm: dts: Remove SW_LID events

- drivers/iio/frequency/admv1013.c
Rename second argument of the `admv1013_freq_change` function to
`action` as in `linux/notifier.h`
Update rate only on the `POST_RATE_CHANGE` callback.
In the other cases, no changes are made.
Fixes: 0538776 (iio:frequency:admv1013: add support for ADMV1013)
Reference: #1598
> drivers:iio:admv1013: update clk_notifier usage

- drivers/iio/frequency/adf4350.c
The 'snprintf' formatting expects a pointer to a device_node (so that it
can gives us it's name) which we were not giving. This obviously leads to
null pointer dereference.
On top of this, it does not make sense to add the device_node name here as
we might not even have OF and we are already checking for the node name
(and set it as default for the 'indio_dev->name') further down in the
probe function. Hence, I'm reverting this to the state it was after
commit 100fe5035cc3 ("iio: frequency: adf4350: remove use of of.h").
Fixes: b6c8aa018518e ("Merge tag 'xilinx-v2020.1' into master-xilinx-v2020.1")
> iio: adf4350: fix a null pointer dereference during probe

- drivers/clk/adi/clk-ad9545.c
Add compensation via Aux. DPLL to the Aux. NCO clocks.
Fixes: 0e9163cefbb2 ("clk: ad9545: Add SYS clock compensation")
> clk: ad9545: Fix compensation

- arch/arm/boot/dts/adi-adrv9002.dtsi
- arch/arm64/boot/dts/xilinx/adi-adrv9002.dtsi
The decrement-pin of the rx0 pintcrl was overlapping with the ORX2 enable
pin.
Fixes: 7e92fd3b0f957 ("arch: dts: adrv9002: add orx support")
> arch: arm{64}: dts: fix adrv9001 overlapping pins

- drivers/iio/frequency/admv1014.c
Rename second argument of the `admv1014_freq_change` function to
`action` as in `linux/notifier.h`
Update rate only on the `POST_RATE_CHANGE` callback.
In the other cases, no changes are made.
Fixes: a0b4049 (iio:frequency:admv1014: add support for ADMV1014)
Reference: #1598 
> drivers:iio:admv1014: update clk_notifier usage

- arch/arm/boot/dts/overlays/rpi-adxl355-overlay.dts
- drivers/iio/accel/adxl355.h
- drivers/iio/accel/adxl355_core.c
- drivers/iio/accel/adxl355_i2c.c
- drivers/iio/accel/adxl355_spi.c
Add the channels, the read_raw(), and write_raw() functions to the
adxl355 driver. The channels include acceleration and temperature data
with thier offsets, calibbiases, scales, sampling frequency, and high
pass filter -3dB frequency.
The driver is tested with both the I2C and SPI interfaces on a raspberry
pi 3B using the IIO Oscilloscope.
Some other minor changes have also been done which include adding regmap ranges, changing i2c address, etc.
> iio: accel: Add channels support to adxl355

- drivers/pwm/pwm-axi-pwmgen.c
In Documentation/devicetree/bindings/pwm/pwm-axi-pwmgen.yaml
is documented as adi,axi-pwmgen and this is the corect naming
> drivers: pwm: pwm-axi-pwmgen.c: Fix name

- drivers/usb/Kconfig.adi
Most of your designed require only DRD support based on ID pin.
We don't need HNP or SRP. In fact OTG_FSM just causes issues on
most FPGA/SoC carriers.
> drivers/usb/Kconfig.adi: Remove CONFIG_USB_OTG_FSM

- drivers/spi/spi-bcm2835.c
The bcm2835_spi_transfer_one function can create a deadlock
if it is called while another thread already has the
CCF lock.
The summary of the stack exception caused by this when trying to print the clk_summary:
Exception stack:
- spi_pump_messages -> spi_transfer_one_message -> clk_get_rate
- spi_pump_messages -> bcm2835_spi_transfer_one -> clk_get_rate
- ksys_ioctl -> do_vfs_ioctl ->v3d_clock_up_get -> clk_set_rate
- clk_summary_show -> clk_summary_show_subtree -> ad9545_out_clk_get_phase
- spi_transfer_one_message -> clk_get_rate
- drm_ioctl_kernel -> v3d_job_init -> v3d_clock_up_get -> clk_set_rate
- ksys_read -> full_proxy_read -> clk_summary_show -> clk_summary_show_subtree -> ad9545_out_clk_get_phase
- do_vfs_ioctl -> v3d_submit_cl_ioctl -> v3d_clock_up_get -> clk_set_rate
- …
> spi: spi-bcm2835: Fix deadlock

- drivers/iio/industrialio-buffer.c
iio_buffer_remove_sample is not exported as a symbol and it
can be used in modules.
Export it to solve the problem
> drivers: iio: industrialio-buffer.c: Export symbol

- drivers/pwm/pwm-axi-pwmgen.c
the line DIV_ROUND_CLOSEST(clk_rate, NSEC_PER_USEC) isn't
really avoiding the overflow, for example for the case where
clk_rate = 100MHz and period = 1ms multiplying won't work
as expected
Use u64 as type for tmp to fix the issue
Fixes: 5d139ed2ac6f2 ("drivers: pwm: pwm-axi-pwmgen: Add support for multiple channels")
> drivers: pwm: pwm-axi-pwmgen.c: Fix overflow

- drivers/iio/adc/navassa/adrv9002_debugfs.c
Export the api version through debugfs. This might be useful to quickly
identify the version of some tools (eg: TES) that are expected to work
with the current api version.
> iio: adrv9002: export api version

- drivers/iio/accel/adxl313.h
- drivers/iio/accel/adxl313_core.c
- drivers/iio/accel/adxl313_i2c.c
- drivers/iio/accel/adxl313_spi.c
Add proper device setup and channels support for basic functionalities of the ADXL313 accelerometer. Channels include raw acceleration, calibbias, scale and sampling frequency.
This PR also has some minor changes such as adding regmap range tables for the readable and writable registers and 3 wire spi support.
> iio: accel: Add channels support to ADXL313

- drivers/spi/spi-bcm2835.c
Remove unused variable clk_hz.
Fixes: 095c8ca0d6f5 ("spi: spi-bcm2835: Fix deadlock")
> spi: spi-bcm2835: Fix warning

- azure-pipelines-rpi.yml
Similar to the azure-pipelines master branch related builds, allow
custom staging branches to trigger the rpi related builds.
> azure-pipelines: allow custom rpi build trigger

- arch/arm64/boot/dts/xilinx/zynqmp-zcu102-rev10-ad9083-fmc-ebz.dts
Update hdl_project tag in zynqmp-zcu102-rev10-ad9083-fmc-ebz.dts
to correspond with hdl project ad9083_evb/zcu102.
> zynqmp-zcu102-rev10-ad9083-fmc-ebz.dts: update hdl_project tag

- drivers/iio/amplifiers/ad8366.c
This fixes and inverted gain read.
> iio: amplifiers: ad8366: Fix ADRF5720/30/31 gain calculation

- azure-pipelines-rpi.yml
A new "PushArtifacts" stage was added in order to save resulted artifacts to SWDownloads and Artifactory.
Artifacts are saved in three separat archives:
-adi_bcm2709_defconfig.tar
-adi_bcm2711_defconfig.tar
-adi_bcmrpi_defconfig.tar
For each build on rpi-5.4.y branch, this archives are overwritten.
> ci: push artifacts to SWDownloads and Artifactory

- drivers/iio/potentiometer/ad5110.c
Add the channel, read_raw(), and write_raw() functions support to the
ad5110 driver with configured offset and scale.
> iio: potentiometer: Add channel support to AD5110

- azure-pipelines-rpi.yml
- ci/travis/artifacts.sh
The first commit fix Azure failures, by adding 'artifactName' variable and fixing a 'tar' warning.
The second commit add a script, artifacts.sh in ci/travis, that contains three functions that will be called in azure-pipelines-rpi.yml files instead of long bash command lines.
> ci: Fix failures and add script for long bash command lines

- arch/arm/boot/dts/zynq-m2k-reva.dts
- arch/arm/boot/dts/zynq-pluto-sdr-revb.dts
- arch/arm/boot/dts/zynq-pluto-sdr.dts
- arch/arm/boot/dts/zynq-zed-adv7511-m2k-revb.dts
- arch/arm/boot/dts/zynq-zed-adv7511-m2k-revc.dts
This will make sure we use the ADM1177 IIO and not the HWMON driver.
> dts: zynq pluto|m2k: Update ADM1177 compatible to adi,adm1177-iio

- arch/arm/boot/dts/zynq-zed-adv7511-ad4020.dts
This commit updates the devicetree for the AD4020 according to the
latest HDL changes.
Signed-off-by: scuciurean <sergiu.cuciurean@analog.com>
> arch: arm: boot: dts: ad4020: Sync with HDL

- drivers/iio/beamformer/adar1000.c
For better visual loock, remove memory allocation also.
> iio: beamformer: adar1000: Reuse local variables

- drivers/iio/adc/navassa/adrv9002_debugfs.c
- drivers/iio/adc/navassa/devices/adrv9001/public/include/adi_adrv9001_gpio.h
- drivers/iio/adc/navassa/devices/adrv9001/public/src/adi_adrv9001_gpio.c
Add support for manually controlling the device gpios through debugfs. The first commit adds a a new API to the device driver API so that we can get the gpio direction. Checkpatch stuff is to be ignored on that commit.
> [dev] add adrv9002 gpio debugfs

- arch/arm/boot/dts/zynq-zed-adv7511.dtsi
This adds the FMC i2c controller that is in the HDL design to the devicetree.
The FMC FRU EEPROM device is also included to allow its contents to be accessed.
Signed-off-by: Michael Bradley <michael.bradley@analog.com>
> arm: dts: zynq-zed-adv7511: Adds FMC I2C  bus and FRU EEPROM

- drivers/iio/frequency/admv1014.c
- The BB output VCM can be changed from 1.05V to 1.85V with an increment
of 0.05V. Although from 1.4V to 1.5V there is a direct shift of 0.1V
in the array of supported values.
- If the vcm input value is valid, return from function after the
registers updates.
> admv1014: vcm settings fixes

- arch/arm64/boot/dts/xilinx/zynqmp-zcu102-rev10-ad9081-m8-l4-do.dts
- arch/arm64/boot/dts/xilinx/zynqmp-zcu102-rev10-ad9081-m8-l4-tdd.dts
This commit adds a new device tree that extends the previously available
zynqmp-zcu102-rev10-ad9081-m8-l4-do.dts by the TDD engine which may
optionally be enabled in the HDL during synthesis.
Additionally, the rx data offload is added to the device tree. This
device isn't new, and has been available in all HDL that contains the tx
data offload - it just didn't have to be exposed before.
> arch: arm64: dts: Add new zcu102/ad9081 dt with tdd engine

- Documentation/hwmon/adt7410.rst
- drivers/hwmon/Kconfig
- drivers/hwmon/adt7410.c
Uses the same register map as the adt7420 chip.
Signed-off-by: Cosmin Tanislav <demonsingur@gmail.com>
> hwmon: adt7410: support adt7422 chip

- drivers/iio/jesd204/axi_jesd204_rx.c
- drivers/iio/jesd204/axi_jesd204_tx.c
OCTETS_PER_MULTIFRAME (K*F) field needs a 10 bits mask.
> iio: jesd204: axi_jesd204_rx/tx: Fix REG_LINK_CONF0 mask

- drivers/mfd/Kconfig
- drivers/power/supply/Kconfig
- drivers/power/supply/max8903_charger.c
- drivers/regulator/Kconfig
- drivers/regulator/max8973-regulator.c
- drivers/rtc/Kconfig
- drivers/rtc/rtc-ds1216.c
- drivers/usb/host/Kconfig
- drivers/w1/masters/Kconfig
- drivers/w1/slaves/w1_ds28e04.c
After adding the maxim projects on wiki we noticed some typos in the Kconfig files and some driver files which failed to specify existing variants of the product. This pull request aims to fix those
> Some typo fixes for maxim drivers and adp5520

- drivers/iio/imu/adis.c
- drivers/iio/imu/adis16460.c
- drivers/iio/imu/adis16475.c
- drivers/iio/imu/adis16480.c
- include/linux/iio/imu/adis.h
This series backports some fixes that got upstreamed for the adis lib and devices... The major difference is that we could still not completely backport the `unmasked_drdy` flag stuff because it depends on something that is still not present in our kernel (being able to request disabled IRQs).
> adis lib sync

- arch/arm/boot/dts/overlays/adis16475-overlay.dts
- arch/arm/boot/dts/overlays/adis16480-overlay.dts
Do some cleanup and refactoring on IMUs overlays. The biggest change is that, now, the compatible property has to be given as an overlay parameter so that we can support more devices without having to recompile the overlay.
> adis overlays

- arch/arm64/boot/dts/xilinx/adi-ad9172-fmc-ebz.dtsi
In this example the DAC REF_CLK is 368640000 Hz.
So we need to set a DAC rate which can be supported by the PLL.
Right now 3.000GHz works due to rounding effects.
> arm64: dts: adi-ad9172-fmc-ebz.dtsi: Use exact DAC rate

- drivers/iio/imu/adis16475.c
With commit 2b764b835b720 ("iio: adis: sync with upstream"), two deadlocks
were introduced:
1) The call to 'adis_write_reg_16()' was not changed to it's unlocked
version.
2) The lock was not being released on the success path of the function.
This change fixes both these issues.
Fixes: 2b764b835b720 ("iio: adis: sync with upstream")
> iio: adis16475: fix deadlock on frequency set

- drivers/iio/filter/admv8818.c
Instead of bypassing the LPF/HPF blocks for out of bounds frequencies,
set the LPF/HPF cutoff frequency to the smallest/highest value available.
Fixes: bd10500885159c88fc7b0fcd97e55154a14dca18 (iio:filter:admv8818: add support for ADMV8818)
> iio: filter: admv8818: update LPF/HPF behavior

- drivers/iio/beamformer/adar1000.c
Test read/write scratchpad register so that we are sure that the device is
present. This will prevent  the driver to probe successfully, with no
device attached to the board.
> iio: beamformer: adar1000: Scratchpad test

- arch/arm64/boot/dts/xilinx/zynqmp-adrv9009-zu11eg-revb-adrv2crr-fmc-revb-sync-jesd204-fsm-multisom-primary.dts
- arch/arm64/boot/dts/xilinx/zynqmp-adrv9009-zu11eg-revb-adrv2crr-fmc-revb-sync-jesd204-fsm-multisom-secondary.dts
Fix hdl project tags in zynqmp-adrv9009-zu11eg-revb-adrv2crr-fmc-revb-sync-jesd204-fsm-multisom-primary.dts
and zynqmp-adrv9009-zu11eg-revb-adrv2crr-fmc-revb-sync-jesd204-fsm-multisom-secondary.dts by removing the
extra '/' from the end.
> adrv9009-zu11eg-revb-adrv2crr-fmc-revb-sync-jesd204-fsm: Fix HDL tags

- Documentation/devicetree/bindings/iio/filter/adi,admv8818.yaml
With 13b575b492b5a311c68cb26398455d729974403d the tolerance property was
replaced with bandwidth.
Adjust the device tree example accordingly.
> dt-bindings: admv8818: fix example

- arch/arm64/boot/dts/xilinx/zynqmp-adrv9009-zu11eg-reva-adrv2crr-fmc-reva.dts
Add AD9545 I2C node for the device present on adrv2crr-fmc.
> dts: zynqmp-adrv9009-zu11eg-reva-adrv2crr-fmc-reva: AD9545 node

- drivers/iio/adc/adrv9009.c
- drivers/iio/adc/adrv9009.h
This patch add support to control the BBDC offset tracking.
> iio: adc: adrv9009: Support for digital baseband DC offset tracking

- arch/arm64/boot/dts/xilinx/zynqmp-adrv9009-zu11eg-reva-adrv2crr-fmc-reva.dts
Add input node for Ref A (10 Mhz). PLL0 will lock on it if available
otherwise will just run based on the Aux. NCO.
OUT 0A will give 30.72 Mhz,
> dts: zynqmp-adrv9009-zu11eg-reva-adrv2crr-fmc-reva: Add input for AD9545

- drivers/iio/adc/Makefile
- drivers/iio/adc/ad9081.c
- drivers/iio/adc/ad9081/adi_ad9081.h
- drivers/iio/adc/ad9081/adi_ad9081_adc.c
- drivers/iio/adc/ad9081/adi_ad9081_config.h
- drivers/iio/adc/ad9081/adi_ad9081_dac.c
- drivers/iio/adc/ad9081/adi_ad9081_device.c
- drivers/iio/adc/ad9081/adi_ad9081_hal.c
- drivers/iio/adc/ad9081/adi_ad9081_hal.h
- drivers/iio/adc/ad9081/adi_ad9081_jesd.c
- drivers/iio/adc/ad9081/adi_ad9081_sync.c
- drivers/iio/adc/ad9081/adi_cms_api_common.h
* Fix DAC Calibration for DAC rates <4GHz to address Noise Floor Issue
* Address ADC with 12 Bit resolution
* Enable Background Cal when calling JESD 204C Calibration
* Allow user to set nyquist Zone per ADC
* Added controls for sysref input receiver configuration
This patch adds support for direct ADC->DAC loopback mode.
Note ADC sample rate must be same as DAC sample rate to get this
loopback mode working.
The default mapping: ADC0->DAC0, ADC1->DAC1, ADC0->DAC2, ADC1->DAC3
can either be modified via the adi,direct-loopback-mode-dac-adc-mapping
device tree attribute or during run-time using the
adi,direct-loopback-mode-dac-adc-mapping debugfs attribute.
After writing the debugfs attribute, the new value needs to be latched
by writing the loopback_mode iio attribute again.
> AD9081 dev

- drivers/iio/adc/ad9081.c
This fixes an invalid pointer deference.
fixes: 7e2c494d1d00  ("iio: adc: ad9081: Update API to Version 1.2.0")
> iio: adc: ad9081: Fix pointer parameter for ad9081_sysref_ctrl()

- Documentation/devicetree/bindings/iio/frequency/adi,admv1014.yaml
Add 0 to the det-prog enum since it is a valid value.
Fix typo in the bb-amp-gain-ctrl property.
Fixes: 77dd8d6b42da2c3be0f1ad6ec9acd0b9c66816c8
(dt:bindings:iio:frequency:add admv1014 doc)
> dt-bindings:admv1014: misc fixes

- drivers/iio/frequency/admv1013.c
Fix comparison when applying quad filters based on the input clock.
Fixes: 0538776f05eeb32902f122013868fdd662d3763c(iio:frequency:admv1013: add support for ADMV1013)
> iio:admv1013: fix comparison for quad filters

- ci/travis/run-build.sh
The `--strict` option is mandatory when sending a patch upstream.
This patch aims to minimize the number of upstream resubmissions due to
styling issues.
> ci: add --strict option for checkpatch

- arch/arm/boot/dts/overlays/Makefile
- arch/arm/boot/dts/overlays/rpi-adxl355-overlay.dts
Add SPI dt overlay for the ADXL355 driver.
> arch:arm:overlays: rpi-adxl355 overlay

- drivers/iio/frequency/admv1013.c
Make sure that the margins for the two common-mode voltage ranges are
included in the checks.
> iio:frequency:admv1013 vcm range fix

- drivers/iio/adc/ad9361.c
In situations where the TX path FIR interpolation is 1 and the
RX path FIR is configured for decimate by 2, the NCO frequencies
need to be adjusted appropriately. This patch adds support for this.
> iio: adc: ad9361: TX QUAD Cal support for clktf=2*clkrf

- arch/arm/boot/dts/overlays/Makefile
- arch/arm/boot/dts/overlays/rpi-ada4250-overlay.dts
- arch/arm/boot/dts/overlays/rpi-admv1013-overlay.dts
- arch/arm/boot/dts/overlays/rpi-admv1014-overlay.dts
- arch/arm/boot/dts/overlays/rpi-admv8818-overlay.dts
- arch/arm/boot/dts/overlays/rpi-adrf6780-overlay.dts
Add dt overlays for several drivers that were merged into the master branch:
- ada4250
- admv1013
- admv1014
- adrf6780
- admv8818
Note: these overlays were used in the driver development, and updated during the review process, therefore tested.
> arch:arm:overlays: add several rpi dt overlays

- Documentation/devicetree/bindings/iio/dac/adi,ad5766.yaml
- drivers/iio/dac/ad5766.c
- https://github.com/torvalds/linux/commit/8fc4f038fa832ec3543907fdcbe1334e1b0a8950#diff-12a23def815fdcc56cbeacb20b51db9bedb16de1ddd71abfc0b8047d47557e0b
- https://github.com/torvalds/linux/commit/d9de0fbdeb0103a204055efb69cb5cc8f5f12a6a#diff-e684de5029dac3b27852954551adcd240d276a92036eb747f4cd05d88a8c42d9
- https://github.com/torvalds/linux/commit/885b9790c25a5fb8b253971c107744b17d8c29e7#diff-e684de5029dac3b27852954551adcd240d276a92036eb747f4cd05d88a8c42d9
Changes to adapt to the ADI linux output buffer have been made
> Sync ad5766 with latest upstream changes

- arch/arm64/boot/dts/xilinx/zynqmp-adrv9009-zu11eg-reva-adrv2crr-fmc-reva.dts
- arch/arm64/boot/dts/xilinx/zynqmp-adrv9009-zu11eg-revb-adrv2crr-fmc-revb-sync-fmcomms8.dts
This adds the FRU eeprom found on the FMCOMMS8
> dts: zynqmp-adrv9009-zu11eg-reva-adrv2crr-fmc-reva: Add FRU at 0x52

- arch/arm64/boot/dts/xilinx/zynqmp-zcu102-rev10-stingray.dts
> arch: arm64: dts: stingray: Update GPIO pinouts

- azure-pipelines-rpi.yml
- ci/travis/prepare_artifacts.sh
- ci/travis/upload_to_artifactory.py
In this pull request:  
- Azure Pipelines builds for rpi-5.10.y branch was updated similar with previous used branch (rpi-5.4.y)
- At the request of the test team the structure of uploaded folder on Artifactory was changed.  The folder follow the 
structure: <build_date>/
-properties.txt - contains git_sha and git_sha_date
-<bcm_type>/ and inside are the next subfolders
-kernel image  file - kernel7.img for bcm2709, kernel7l.img for bcm2711, and kernel.img for bcmrpi
-.dtb files
-overlays - contains .dtbo files
Signed-off-by: Raluca Chis raluca.chis@analog.com
> CI: update rpi branch

- arch/arm64/boot/dts/xilinx/zynqmp-pluto-ng.dts
The ADALM-PLUTO-NG Active Learning Module is an easy to use tool
available from Analog Devices, Inc. (ADI) that can be used to
introduce fundamentals of Software Defined Radio (SDR) or Radio
Frequency (RF) or Communications as advanced topics in electrical
engineering in a self or instructor lead setting.
> arm64: dts: xilinx: Add support for ADALM-PLUTO-NG 

- Documentation/devicetree/bindings/iio/frequency/adi,adrf6780.yaml
- drivers/iio/frequency/adrf6780.c
Sync driver and dt bindings with the upstream version.
Signed-off-by: Antoniu Miclaus antoniu.miclaus@analog.com
> adrf6780: sync with upstream

- arch/arm/boot/dts/overlays/rpi-adrf6780-overlay.dts
Sync with upstream version where the parity-en dt property was removed.
> arch:arm:overlays:adrf6780: sync overlay

- arch/arm64/boot/dts/xilinx/zynqmp-zcu102-rev10-adrv9002-rx2tx2.dts
- arch/arm64/boot/dts/xilinx/zynqmp-zcu102-rev10-adrv9002.dts
In accordance with the HDL the EEPROM is expected to be available on
HPC0 not HPC1.
See: https://github.com/analogdevicesinc/hdl/blob/master/projects/adrv9001/zcu102/system_constr.xdc
> arm64: dts: zcu102-adrv9002: Move EEPROM to HPC0

- arch/arm/boot/dts/overlays/Makefile
- arch/arm/boot/dts/overlays/rpi-ad5593r-overlay.dts
Add i2c overlay for the AD5593r device.
> arch:arm:overlays: add ad5593r rpi overlay

- arch/arm64/boot/dts/xilinx/zynqmp-zcu102-rev10-ad9988-fmcb-m8-l4.dts
This adds an example devicetree for AD9988.
> dts: zynqmp-zcu102-rev10-ad9988-fmcb-m8-l4: Add AD9988 MxFE example dt

- arch/arm/boot/dts/overlays/Makefile
- arch/arm/boot/dts/overlays/rpi-ad5592r-overlay.dts
Add rpi SPI overlay for ad5592r device.
> arch:arm:overlays: add ad5592r overlay

- azure-pipelines-rpi.yml
Knowing that rpi branches are created based on master branch, the azure-pipelines-rpi.yml file was updated based on actual rpi branch in order to have less to modify for future updates of rpi branches.
> CI: update rpi YAML file

- arch/arm/boot/dts/zynq-zc706-adv7511-fmcjesdadc1.dts
- arch/microblaze/boot/dts/kc705_fmcjesdadc1.dts
- arch/microblaze/boot/dts/kc705_fmcomms2-3.dts
- arch/microblaze/boot/dts/kc705_fmcomms4.dts
- arch/microblaze/boot/dts/kcu105_fmcdaq3.dts
- arch/microblaze/boot/dts/kcu105_fmcomms2-3.dts
- arch/microblaze/boot/dts/kcu105_fmcomms4.dts
- arch/microblaze/boot/dts/vc707_fmcadc2.dts
- arch/microblaze/boot/dts/vc707_fmcadc5.dts
- arch/microblaze/boot/dts/vc707_fmcdaq2.dts
- arch/microblaze/boot/dts/vc707_fmcjesdadc1.dts
- arch/microblaze/boot/dts/vc707_fmcomms2-3.dts
- arch/microblaze/boot/dts/vc707_fmcomms4.dts
- arch/microblaze/boot/dts/vcu118_dual_ad9208.dts
- arch/microblaze/boot/dts/vcu118_fmcdaq3.dts
Add missing hdl_project tags in comment section of DTS.
Fix also some typos.
> [No functional changes] Microblaze DTS: add missing hdl_project tags

- drivers/iio/adc/ad7949.c
This driver supports devices with 14-bit and 16-bit sample sizes.
This implies different SPI transfer lengths which are not always handled
properly by some SPI controllers.
To work around this limitation, define a big endian buffer used to split
the buffer into two 8-bit messages in the event that the controller
doesn't support 14-bit or 16-bit transfers.
A separate buffer is introduced here to avoid performing operations on
types of different endianness.
Since all transfers use the same bits_per_word value, move that logic to
the probe function, and let transfers default to the value defined in
the struct spi_device.
Signed-off-by: Liam Beguin <lvb@xiphos.com>
Link: https://lore.kernel.org/r/20210815213309.2847711-3-liambeguin@gmail.com
Signed-off-by: Jonathan Cameron …
> iio: adc: ad7949: enable use with non 14/16-bit controllers

- arch/arm/boot/dts/overlays/Makefile
- arch/arm/boot/dts/overlays/rpi-ad7293-overlay.dts
Add rpi dt overlay example for ad7293.
**NOTE:** PR depends on #1707
> arch:arm:overlays: add ad7293 rpi overlay

- drivers/iio/adc/mykonos/mykonos.c
Correctly use a bitwise operation to check for the desired ARM state
instead of logical operation.
> drivers:iio:adc:mykonos: fix ARM state check routine

- drivers/iio/adc/ad9081.c
This patch adds support for reading the API and silicon version
vi debugfs. Format is “AD%X Rev. %u Grade %u API %u.%u.%u“
Example:
root@analog:~# iio_attr -D axi-ad9081-rx-hpc device_info
AD9082 Rev. 3 Grade 2 API 1.2.0
> iio: adc: ad9081: Support for reading the API and silicon version

- Documentation/devicetree/bindings/iio/dac/adi,ad3552r.yaml
- drivers/iio/Kconfig.adi
- drivers/iio/dac/Kconfig
- drivers/iio/dac/Makefile
- drivers/iio/dac/ad3552r.c
- Upstream link: https://patchwork.kernel.org/project/linux-iio/cover/20211213110825.244347-1-mihail.chindris@analog.com/
- Minor changes made in order to compile with ADI tree
- Add commit to add driver to IIO_ALL_ADI_DRIVERS
> Add driver for AD3552R (Accepted upstream)

- drivers/nvmem/adi_axi_sysid.c
This fixes following kernel panic seen with the sysid on the
ad40xx_fmc project:
Kernel panic - not syncing: stack-protector: Kernel stack is corrupted
in: axi_sysid_probe+0x704/0x71c
Increase custom_info buffer and use snprintf() to truncate in case
the string doesn't fit the reserved buffer space.
Fixes 64ea0d3503ee ("nvmem: adi_axi_sysid: Print System Custom String")
> nvmem: adi_axi_sysid: Fix custom info stack corruption

- arch/arm64/boot/dts/xilinx/zynqmp-adrv9009-zu11eg-revb-adrv2crr-fmc-revb-jesd204-fsm-fmcbridge.dts
Add adrv9009-zu11eg-fmcbridge device tree used for production tests of
the XMicrowave fmcbridge.
> arch:arm64: add dts for fmcbridge xmw

- Documentation/devicetree/bindings/iio/dac/adi,ad7293.yaml
- drivers/iio/Kconfig.adi
- drivers/iio/dac/Kconfig
- drivers/iio/dac/Makefile
- drivers/iio/dac/ad7293.c
Initial driver implementation providing access from userspace to:
- ADC channels (read raw values, set range, set offset)
- DAC channels (set code, set offset)
- Temperature sensing (read raw values, set offset)
- Current sensing (read raw, set offset, set gain)
> ad7293 dev

- drivers/iio/adc/navassa/adrv9002.c
- drivers/iio/adc/navassa/adrv9002.h
This adds support for manipulating RX BBDC loop gain. Note that this is
being supported with raw values because the loop gain is represented as
a fractional value with 31bits representing the fractional part. This
means that the resolution is pretty low and thus making it very hard to
handle in the kernel. Hence, support this as raw and defer the floating
point handling to userspace.
> iio: adrv9002: add support for BBDC loop gain

- README.md
This brings the toplevel README.md up to date with the current supported
Xilinx tag and linux version. It also refactors some other things with
the goal of smoothing the maintenance burden on this file.
@mhennerich, I'm not really sure if the altera section still applies. So, just let me know if something must also be done there....
> docs: update the toplevel readme

- drivers/iio/adc/ad_adc.c
When doing direct register access, bit 31 in the register value is
being used to distinguish between accessing the main register map or the
slave register map. Hence, we need to make sure a slave register map
exists before trying to access it in case the bit 31 is set.
Fixes: ca3d2c2de1b48 ("iio: ad_adc: Merge m2k branch")
@ronagyl can you give this a quick test?
> iio: ad_adc: fix NULL pointer dereference in direct_reg_access

- arch/arm/boot/dts/overlays/Makefile
- arch/arm/boot/dts/overlays/rpi-ad74413r-overlay.dts
The AD74412R and AD74413R are quad-channel, software configurable,
input/output solutions for building and process control applications.
They contain functionality for analog output, analog input, digital input,
resistance temperature detector, and thermocouple measurements integrated
into a single chip solution with an SPI interface.
The devices feature a 16-bit ADC and four configurable 13-bit DACs to
provide four configurable input/output channels and a suite of diagnostic
functions.
The AD74413R differentiates itself from the AD74412R by being
HART-compatible.
> arch: arm: dts: overlays: add rpi-ad74413r

- ci/travis/run-build.sh
With this commit, the following checkpatch warnings are ignored:
* UNDOCUMENTED_DT_STRING: We have a significant amount of "active"
drivers and dts with no bindings. Often this adds noise to CI. Ideally,
we would add all the missing bindings so that we could stop ignoring
this.
* CAMELCASE: All the "external" APIs generate a lot of warnings because
of this. And this is something that we can't really change. I'm also
fairly sure that everyone is mostly used to not do CAMELCASE in the
kernel so ignoring this should not be a big problem.
> ci: add more things to ignore on checkpatch

- arch/arm64/boot/dts/xilinx/zynqmp-pluto-ng.dts
Since drivers/firmware/psci/psci.c registers a pm_power_off, GPIO
poweroff signals should be enabled by the PSCI firmware.
> arm64: dts: xilinx: Move gpio-poweroff from kernel to ATF

- arch/arm64/boot/dts/xilinx/zynqmp-adrv9009-zu11eg-revb-adrv2crr-fmc-revb-jesd204-fsm-fmcbridge.dts
Add eeprom device inside the fmcbridge dts.
> arch:arm64:dts: add fmc eeprom device

- azure-pipelines.yml
- ci/travis/run-build.sh
The main goal of this PR is to fix a false positive checkpatch report... The problem is that whenever a not so old commit is referenced in a new commit (eg: on Fixes tag), checkpatch will report that the commit is not known even though the commit exists. The problem is that a shallow clone with depth=50 (to speed up `git fetch`) is being done in the job and hence checkpatch won't know about the commit because we don't have the whole history.
This all means that we need to fetch the whole git history. To do that while minimizing fetch times, we'll do a partial clone.  What this means is that only the tree and blobs respective to HEAD will be fetched instead of all trees and blobs for all existing commits. This considerably speeds up the fetch time when compared to a full fetch (more than …
> checkpatch fixes and improvements

- drivers/iio/jesd204/altera_adxcvr.c
In case st->link_clk is disabled/unprepared without being
prepared/enabled previously, a warning and the backtrace will
be displayed.
> iio: altera_adxcvr: Prevent clock already disabled/unprepared warnings

- drivers/iio/adc/ad9081.c
- drivers/iio/adc/cf_axi_adc.h
- drivers/iio/adc/cf_axi_adc_core.c
- drivers/iio/addac/one-bit-adc-dac.c
- drivers/iio/beamformer/adar300x.c
- drivers/iio/industrialio-core.c
- include/linux/iio/iio.h
- include/linux/iio/types.h
Update with the upstream version of channel label:
https://git.kernel.org/pub/scm/linux/kernel/git/jic23/iio.git/commit/?id=1d4ef9b39ebecca827642b8897d2d79ea2026682
> Iio channel label

- arch/arm/boot/dts/zynq-zc706-adv7511-ad6676-fmc.dts
- arch/arm/boot/dts/zynq-zc706-adv7511-ad9739a-fmc.dts
- arch/arm/boot/dts/zynq-zc706-adv7511-adrv9009.dts
- arch/arm/boot/dts/zynq-zc706-adv7511-adrv9371.dts
- arch/arm/boot/dts/zynq-zc706-adv7511-fmcomms11.dts
Remove extra eeproms added in the dts associated with the zc706 carrier.
> zc706 dts fixes

- drivers/iio/adc/navassa/adrv9002.c
Replace all 'sprintf()' with 'sysfs_emit()' when reading sysfs attributes.
> iio: adrv9002: make use of sysfs_emit

- arch/arm/boot/dts/zynq-zc706-adv7511-ad9625-fmcadc2.dts
- arch/arm/boot/dts/zynq-zc706-adv7511-ad9625-fmcadc7.dts
- arch/arm/boot/dts/zynq-zc706-adv7511-fmcjesdadc1.dts
According to the schematics, there is only one eeprom device connected to
the fmc i2c, having the slave address 0x50.
https://wiki.analog.com/_media/resources/eval/user-guides/ad-fmcadc2-ebz/02_036007d.pdf
https://wiki.analog.com/_media/resources/eval/user-guides/ad_fmcadcv7b.pdf
https://wiki.analog.com/_media/resources/eval/user-guides/ad-fmcjesdadc1-ebz/ad-fmcjesdadc1_r1.1.pdf
> zc706 dts: remove extra eeprom devices

- arch/arm64/boot/dts/xilinx/zynqmp-zcu102-rev10-stingray.dts
Set default clock priority to CLKIN1 -> CLKIN0 -> CLKIN2 -> CLKIN3. When an
external reference clock is applied on CLKIN1 this will be used as
reference for PLL1 otherwise the onboard CLKIN0 will be used.
> arch: arm64: dts: stingray: Configure CLKIN priority

- drivers/iio/adc/ad9083.c
ad9083_request_clks() will return EPROBE_DEFER if adc_ref_clk is not
yet available. Don't treat this as an error, but ask for a probe defer.
> iio: adc: ad9083: Don't ignore the EPROBE_DEFER requests

- arch/arm/boot/dts/adi-fmcomms1.dtsi
- arch/arm/boot/dts/zynq-zc706-adv7511-ad9136-fmc-ebz.dts
- arch/arm/boot/dts/zynq-zc706-adv7511-adrv9008-1.dts
- arch/arm/boot/dts/zynq-zc706-adv7511-adrv9008-2.dts
- arch/arm/boot/dts/zynq-zc706-adv7511-fmcdaq3.dts
Remove eeproms that are not hardware available on multiple fmc boards.
> arch:arm:boot:dts: emove extra eeprom nodes

- arch/arm/boot/dts/zynq-zc706-adv7511-fmclidar1.dts
- arch/arm/boot/dts/zynq-zc706-adv7511-fmcomms11-RevA.dts
Remove eeproms that are not hardware available on multiple fmc boards:
- fmclidar1
- fmcomms11-revA
> arch:arm:dts: emove extra eeprom nodes

- arch/arm/boot/dts/zynq-zed-adv7511-ad7768-1-evb.dts
Update device tree according to board and HDL updates. Interrupt pin was
changed to an unoccupied one since 55 is used by FMC AXI I2C and a clkgen
IP was added to the spi-engine to generate the serial clock properly.
> arch:arm:boot:dts: update ad7768-1-evb device tree

- drivers/iio/adc/ad9081/adi_ad9081_config.h
- drivers/iio/adc/ad9081/adi_ad9081_dac.c
- drivers/iio/adc/ad9081/adi_ad9081_device.c
- drivers/iio/adc/ad9081/adi_ad9081_sync.c
- Fix Oneshot sync may cause JTX links to fail in certain use cases.
- Fix adi_adxxxx_dac_digital_logic_enable_set needed for all devices,
not just those containing DAC side implementation.
> iio: adc: ad9081: Update API to Version 1.2.2

- drivers/net/ethernet/adi/adin1110.c
It was not possible to set the MAC address of the ADIN1110 via ioctl
SIOCSIFHWADDR (ndo_set_mac_address) and the Linux ip utility.
Setting the MAC address via command 'ip link set addr' would set an unusable
invalid address. Providing a MAC of 'xx:yy:zz:aa:bb:cc' would result in
'1:0:xx:yy:zz:aa' being set, which is rejected when trying to bring the
interface up.
* Use correct address pointer of struct sockaddr in call to ether_addr_copy
> Fix ADIN1110 T1L driver, properly set MAC addr.

- Documentation/devicetree/bindings/clock/clk-ad9545.yaml
- drivers/clk/adi/clk-ad9545.c
- drivers/clk/clk-conf.c
- drivers/iio/frequency/hmc7044.c
e32665df9179 - clk: ad9545: Fix free run rate recalc
Rate recalculation for the free run mode was wrong.
38eb3f601d05 - clk: ad9545: Fix validation timer write
Validation timer would be read from DT but not programmed.
9476bfe5ed52 - clk: ad9545: fix output current selection
Current selection was using the wrong iterator.
60229f6746b6 - iio: hmc7044: add n-shot trigger
Allow user to trigger a sync pulse from a clock mentioned in DT.
19cb9b4bb19d - clk: ad9545: add zero delay support
Mode in which AD9545 aligns the output phase to the input phase.
c7858a6aa38b - blindings: clock: ad9545: document use of slew rate
Allow the user to program the slew rate from DT. Application depended as some ICs are sensible to high output slew-rates.
6994adbf4c02 - clk: clk-conf: allow user to setup an …
> Ad9545 zero delay mode

- drivers/iio/industrialio-core.c
This patch fixes IIO_VAL_FRACTIONAL calculation for negative
values where the exponent is 0.
Signed-off-by: Anand Ashok Dumbre <anand.ashok.dumbre@xilinx.com>
Acked-by: Dragan Cvetic <dragan.cvetic@xilinx.com>
Link: https://lore.kernel.org/r/1597912282-31254-1-git-send-email-anand.ashok.dumbre@xilinx.com
State: waiting
> iio: Fixed IIO_VAL_FRACTIONAL calculation for negative values

- arch/arm/boot/dts/zynq-adrv9002-rx2tx2.dtsi
- arch/arm/boot/dts/zynq-adrv9002.dtsi
Update TX DMA interrupt number to avoid having the same on as the FMC I2C
interrupt. New ID is according to HDL update.
This PR should be passed after [corresponding HDL update](https://github.com/analogdevicesinc/hdl/pull/876) is merged.
> arch:arm:boot:dts:adrv9002 update TX DMA interrupt

- drivers/iio/adc/ad9081.c
Let's turn this case into a warning. We already check if the chip ID
is in the list of supported IDs.
> iio: adc: ad9081: Only WARN in case SPI ID doesn't match chip ID

- arch/arm64/boot/dts/xilinx/zynqmp-zcu102-rev10-stingray.dts
This is useful for EEPROM programming and VADJ enable, using fru-dump tool.
> arch: arm64: dts: stingray: Add ZUD1A-BREAKOUT eval board EEPROM

- arch/arm/boot/dts/overlays/Makefile
- arch/arm/boot/dts/overlays/rpi-ad9545-hmc7044-overlay.dts
A device-tree for RPI 4 to interface using 4-wire GPIO SPI with
AD9545 and HMC7044.
This device-tree enables AD9545 to lock on a 10M MHz input at REFB,
or 1 PPS input at REFBB (PBO mode) generate 10 MHz output that is
fed in HMC7044 CLKIN2 reference input. HMC7044 will be
programmed to generate 10 MHz on all 14 outputs.
> arm: boot: dts: overlays: ad-synchrona-14

- drivers/iio/adc/ad9371.c
- drivers/iio/adc/ad9371.h
This adds additional required calibrations in addition to
RX_QEC and TX_QEC, which are required for large frequency step
procedure as detailed in UG-992.
> iio: adc: ad9371: Additional calibrations for LO change procedure

- drivers/iio/adc/ad9371.c
This fixes loading profiles where clkPllVcoDiv=1.5 or clkPllVcoDiv=1
> iio: adc: ad9371: Fix profile loading for clkPllVcoDiv=1.5

- drivers/uio/uio_dmem_genirq.c
The issue was reported on: https://github.com/analogdevicesinc/linux/issues/1837
> drivers: uio_dmem_genirq: Fix NULL pointer dereference

- ci/travis/run-build.sh
The main purpose of this PR is to improve how these branches are automatically synced. More details are described on the  commit message.
The last patch is for installing checkpatch dependencies so that we stop seeing the annoying `ModuleNotFoundError: No module named 'ply'` warning in the job.
> ci improve sync_branches_with_main handling

- arch/arm/boot/dts/zynq-zc706-adv7511-ad6676-fmc.dts
- arch/arm/boot/dts/zynq-zc706-adv7511-ad9625-fmcadc2.dts
- arch/arm/boot/dts/zynq-zc706-adv7511-fmclidar1.dts
- arch:arm:dts:fmcadc2: remove extra i2c node
- arch:arm:dts:ad6676: remove extra i2c node
- arch:arm:dts:fmclidar1: update slave address
> arch:arm:dts: zc706 related fixes

- arch/arm/boot/dts/overlays/Makefile
- arch/arm/boot/dts/overlays/rpi-adxl367-overlay.dts
The ADXL367 is an ultralow power, 3-axis MEMS accelerometer.
The ADXL367 does not alias input signals to achieve ultralow power
consumption, it samples the full bandwidth of the sensor at all
data rates. Measurement ranges of +-2g, +-4g, and +-8g are available,
with a resolution of 0.25mg/LSB on the +-2 g range.
In addition to its ultralow power consumption, the ADXL367
has many features to enable true system level power reduction.
It includes a deep multimode output FIFO, a built-in micropower
temperature sensor, and an internal ADC for synchronous conversion
of an additional analog input.
> arch: arm: dts: overlays: add rpi-adxl367

- arch/arm/boot/dts/overlays/Makefile
- arch/arm/boot/dts/overlays/rpi-cn0566-overlay.dts
Add overlay for the CN0566 "phaser" board.
Signed-off-by: Mark Thoren <mark.thoren@analog.com>
> arch:arm:overlays add cn0566 rpi overlay

- arch/arm/boot/dts/overlays/Makefile
- arch/arm/boot/dts/overlays/rpi-ad7746-overlay.dts
- arch/arm/boot/dts/overlays/rpi-lm75-overlay.dts
- arch/arm/boot/dts/overlays/rpi-ltc2497-overlay.dts
Add rpi overlays for the following devices:
- ad7746
- lm75
- ltc2497
> rpi overlays: ad7746, lm75, ltc2497

- arch/arm/boot/dts/zynq-zed-adv7511-cn0363.dts
- arch/arm/boot/dts/zynq-zed-adv7511.dts
- arch/arm/boot/dts/zynq-zed-adv7511.dtsi
- arch: arm: dts: zed-adv7511 add eeprom label
- arch: arm: dts: zynq-zed-adv7511: disable EEPROM
- arch: dts: zynq-zed-adv7511-cn0363: disable EEPROM
> arch: arm: dts: eeprom zynq zed 

- arch/arm64/boot/dts/xilinx/zynqmp-zcu102-rev10-stingray.dts
Since zynqmp-zcu102-rev10-stingray-vcxo100.dts was explicitly created
to be used with the VCXO = 100.000 MHz version of AD9081-FMC-EBZ, make
zynqmp-zcu102-rev10-stingray.dts not being dependent on the default
setting from zynqmp-zcu102-rev10-ad9081-m8-l4.dts either.
> arch: arm64: dts: stingray: Make vcxo100/122.88 distinction

- drivers/iio/frequency/ad9528.c
This adds the JESD204_OP_CLK_SYNC_STAGE1 per device callback.
In this state we check the PLL2 lock status and synchronize
the output divider network.
> iio: frequency: ad9528: jesd204-fsm add clock synchronization state

- Documentation/ABI/testing/sysfs-bus-iio-dac-ltc2688
- Documentation/devicetree/bindings/iio/dac/adi,ltc2688.yaml
- MAINTAINERS
- drivers/iio/Kconfig.adi
- drivers/iio/dac/Kconfig
- drivers/iio/dac/Makefile
- drivers/iio/dac/ltc2688.c
The LTC2688 is a 16 channel, 16 bit, +-15V DAC with an integrated precision reference. It is guaranteed monotonic and has built in rail-to-rail output buffers that can source or sink up to 20 mA.
(Just cherry-picked from upstream)...
> support ltc2688

- arch/arm/boot/dts/overlays/Makefile
- arch/arm/boot/dts/overlays/rpi-ltc2688-overlay.dts
Add an example overlay for the ltc2688 DAC.
@mthoren-adi can you run a quick sanity test on this overlay to make sure things are still working?
> arch: arm: dts: add ltc2688 overlay

- drivers/iio/imu/adis16480.c
The trigger handler defined in the driver assumes that burst mode is
being used. Hence, for devices that do not support it, we have to use
the adis library default trigger implementation.
Tested-by: Julia Pineda <julia.pineda@analog.com>
Fixes: 941f130881fa9 ("iio: adis16480: support burst read function")
Link: https://lore.kernel.org/r/20220114132608.241-1-nuno.sa@analog.com
Cc: <Stable@vger.kernel.org>
(cherry picked from commit b0e85f95e30d4d2dc22ea123a30dba36406879a1)
Same as #1878
> iio:imu:adis16480: fix buffering for devices with no burst mode

- arch/arm/boot/dts/overlays/rpi-ad9545-hmc7044-overlay.dts
The first change makes the removal of the overlay clean. So that we don't see any spidev related errors... The second patch is really a fix for being able to actually poweroff the device (using the poweroff gpio defined in the overlay).
PS: Just realized that the fix should actually be the first patch be ehh, since this is not to be backported anywhere, let's leave it as-is.
> synchrona overlay refactor

- arch/arm64/boot/dts/xilinx/zynqmp-zcu102-rev10-ad9695.dts
Add support for subclass 1 for ad9695 with zcu102 carrier.
> arch: arm64: dts: change jesd subclass for zynqmp-zcu102-rev10-ad9695

- ci/travis/run-build.sh
With new git versions, git will stop executing when looking at .git
directories with different ownership from the current user. This is
fixing some vulnerabilities recently found in git. More info in [1].
In our case, this will happen because we are running the build inside a
container which is running as the root user (not sharing UID with the
host) while the repository is being checked out by the host system (azure
VM) with a different UID.
Fix it by adding the docker path to git safe.directory. At some point we
should just stop doing builds inside docker wih azure (it runs it's own
vm per job already).
[1]: https://github.blog/2022-04-12-git-security-vulnerability-announced/
> ci: fix building inside docker

- arch/arm/boot/dts/zynq-coraz7s.dtsi
Add axi sysid node in device tree to enable sysid for
coraz7s based designs
Signed-off-by: Sergiu Arpadi <sergiu.arpadi@analog.com>
> arch: arm: dts: zynq-coraz7s: add sysid support

- Documentation/devicetree/bindings/net/adi,adin1110.yaml
- Kconfig.adi
- drivers/net/ethernet/Kconfig
- drivers/net/ethernet/Makefile
- drivers/net/ethernet/adi/Kconfig
- drivers/net/ethernet/adi/Makefile
- drivers/net/ethernet/adi/adin1110.c
- drivers/net/phy/adin1100.c
The ADIN1110 is a low power single port 10BASE-T1L MAC-PHY
designed for industrial Ethernet applications. It integrates
an Ethernet PHY core with a MAC and all the associated analog
circuitry, input and output clock buffering.
ADIN1110 MAC-PHY encapsulates the ADIN1100 PHY. The PHY registers
can be accessed through the the MDIO MAC registers. We
are registering an MDIO bus with custom read/write in order
to let the PHY to be discovered by the PAL. This will let
the ADIN1100 Linux driver to probe and take control of
the PHY.
b16339a7703a - Kconfig.adi: select ADIN1110 for build
c952e0d8a1ec - dt-bindings: net: adin1110: Add docs
3c3e4537828c - net: adi: adin1110: Add initial support
c581fa48199a - net: phy: adin1100: Add ADIN1110 PHY_ID
While not currently upstreamed, it is needed in …
> Adin1110 add support

- arch/arm/boot/dts/overlays/rpi-ad9545-hmc7044-overlay.dts
Make sure that the default pinctrl state for synchrona is applied. Note
that the pinctrl properties were being directly applied in the pinctrl
controller. While this ok to do in the devietree, it's not in the
overlay because the controller device won't probe again which means no
pinctrl settings will be applied.
As there's no sane way to make sure we unbind and re-bind the controller
in the overlay (unbinding it is also not a very good idea), we attach the
properties in the ad9545 device so that all the pins should be set
before our clocks are up and running.
Fixes: 03153d9eb9f4e ("arm: boot: dts: overlays: ad-synchrona-14")
> arch: arm: overlays: fix pinctrl in rpi-ad9545-hmc7044

- arch/arm64/boot/dts/xilinx/zynqmp-zcu102-rev10-adrv9009-fmcomms8.dts
Device tree was missing sysid node
Signed-off-by: Sergiu Arpadi sergiu.arpadi@analog.com
> arch: arm64: dts: zcu102-fmcomms8: add sysid support

- arch/arm/boot/dts/overlays/rpi-ad9545-hmc7044-overlay.dts
Pins 32 and 36 of RPi 4 are used here for LEDs control.
They are controlled by a user-space application.
Export them from DT instead of having the user to export
them and change direction.
> arch: arm: overlays: rpi-ad9545-hmc7044: add LEDs

- Documentation/devicetree/bindings/clock/clk-ad9545.yaml
- drivers/clk/adi/clk-ad9545.c
0386d3447bcc - bindings: clock: ad9545: fix zero delay property
28711c9c8888 - clk: ad9545: fix zero delay property
Also, pyadi-dt uses the same property name as the one in this fix.
> Ad9545 fix zero delay property

- drivers/iio/beamformer/adar1000.c
Read value of IIO_CHAN_INFO_HARDWAREGAIN was returned as
IIO_VAL_INT_PLUS_MICRO. Change the type to IIO_VAL_INT
to become consistent with the IIO_CHAN_INFO_HARDWAREGAIN
writing.
> iio: beamformer: adar1000: Make gain write/read consistent

- Documentation/devicetree/bindings/net/adi,adin1110.yaml
- drivers/net/ethernet/adi/adin1110.c
- drivers/net/phy/adin1100.c
The ADIN2111 is a low power, low complexity, two-Ethernet ports
switch with integrated 10BASE-T1L PHYs and one serial peripheral
interface (SPI) port.
ADIN2111 contains two ADIN1100 PHYs that are exposed to the user via an
internal MDIO bus. The bus can be accessed via read/write of the MAC's SPI
MDIO control registers.
The driver will register and allocate two struct net_dev structures called "port netdevs".
These are the highest level abstraction of a MAC's physical port.
In this way 
Using standard netdev tools (iproute2, ethtool, etc), the port netdev can also provide to
the user access to the physical properties of the switch port such as PHY link state and I/O statistics.
Ex:
```
adin2111-0-p0: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
inet 192.168.160.160  netmask 255.255.255.0 …
```
> Adin2111 add support

- drivers/net/ethernet/adi/adin1110.c
25a55e7a040d - net: ethernet: adi: adin1110: Fix forwarding
304a700bce83 - net: ethernet: adi: adin1110: Fix MAC address masking
Just found out that ADIN2111 can't mask more than 2 MAC Addresses and that it can perform forwarding offloading in case of multicast and broadcast addresses (no need for the user to start playing with iptables)
> Adin1110 fix forwarding

- arch/arm64/boot/dts/xilinx/zynqmp-zcu102-rev10-cn0506-mii.dts
- arch/arm64/boot/dts/xilinx/zynqmp-zcu102-rev10-cn0506-rgmii.dts
- arch/arm64/boot/dts/xilinx/zynqmp-zcu102-rev10-cn0506-rmii.dts
Device trees for zcu102-cn0506-mii/rmii/rgmii projects
were missing sysid node.
Signed-off-by: Sergiu Arpadi <sergiu.arpadi@analog.com>
> arch: arm64: dts: zcu102-cn0506: add sysid support

- arch/arm/boot/dts/overlays/Makefile
- arch/arm/boot/dts/overlays/rpi-adin1110-overlay.dts
- arch/arm/boot/dts/overlays/rpi-adin2111-overlay.dts
- arch/arm/boot/dts/overlays/rpi-cn0575-overlay.dts
c4d61df2595b - arch: arm: overlays: add eval-adin2111 overlay
fb13e779f923 - arch: arm: overlays: add cn0575 overlay
451e0c33f3f6 - arch: arm: overlays: add adin1110 overlay
A bunch of overlays for every adin1110 eval board out there.
> Rpi adin1110 overlays

- arch/arm/boot/dts/zynq-zed-otg.dts
This change adds an fpga-axi node to the root device tree for
product evaluation. This will allow for multiple small overlays to be
applied to the device tree at run-time.
Signed-off-by: Sean Smith <sean.smith@analog.com>
> arch: arm: dts: zynq-zed-otg.dts Add fpga-axi dt node

- drivers/net/ethernet/adi/adin1110.c
7722b7b79826 - net: adi: adin1110: Set frames as forwarded
c2c38062f6a8 - net: ethernet: adi: adin1110: Add unicast ability flag
Stop duplicate frames from appearing on the network when the two netdev ports are bridged. Duplicate frames were severely limiting bandwidth between hosts that were bridged by ADIN2111.
> Adin1110 forwarding fixes

- arch/arm64/boot/dts/xilinx/zynqmp-adrv9009-zu11eg-revb-adrv2crr-fmc-revb-jesd204-fsm-xmicrowave.dts
- arch: arm64: xmicrowave.dts: enable detector
- arch: arm64: xmicrowave.dts: add labels
> xmicrowave dts updates

- arch/arm/boot/dts/socfpga_arria10_socdk_adrv9002.dts
Add devicetree support for adrv9002 with a10soc carrier.
> arch: arm: dts: add socfpga_arria10_socdk_adrv9002 dts

- ci/travis/prepare_artifacts.sh
Add z option to archives to set the compression method to gzip.
> CI:add z option to tar archive

- drivers/iio/adc/ad9467.c
For AD9649 device, the register 0x18 (VREF) is not available according
to the datasheet, and the VREF can be configured hardware-wise using
either internal 1.0V reference or externally applied 1.0V.
This patch fixes scale handling, by skipping the register operations and
computing VLSB based only on the available `scale_table`.
Fixes: f132a28 ("iio/adc/ad9467.c: Add support for AD9649")
> drivers: iio: ad9467: fix ad9649 scale handling

- ci/travis/prepare_artifacts.sh
This is necessary to avoid uploading the wrong data to SWDownloads.
> CI:set 'exit 1' if timestamp folder is not found

- drivers/iio/adc/ad9467.c
For AD9625 device, the register 0x18 (VREF) is not available according
to the datasheet, and the VREF is 1.0V Vp-p internal reference.
This patch fixes scale handling, by skipping the register operations and
computing VLSB based only on the available ad9625 `scale_table`.
Fixes: 98762a6 ("cf_axi_adc_core: Add support for AD9625 and AD9434")
> drivers: iio: ad9467: fix ad9625 scale handling

- arch/arm64/boot/dts/xilinx/zynqmp-zcu102-rev10-ad9082-204c-txmode22-rxmode23-dual-multi-top.dts
- arch/arm64/boot/dts/xilinx/zynqmp-zcu102-rev10-ad9082-204c-txmode22-rxmode23-dual.dts
- arch/arm64/boot/dts/xilinx/zynqmp-zcu102-rev10-ad9082-204c-txmode22-rxmode23-sc1.dts
- arch/arm64/boot/dts/xilinx/zynqmp-zcu102-rev10-ad9082-204c-txmode22-rxmode23.dts
- arch/arm64/boot/dts/xilinx/zynqmp-zcu102-rev10-ad9082-m4-l8.dts
Fix HDL projects tags for all ad9082+zcu102 device trees.
The tag is used by boot partition scripts to pair DTS with HDL output files.
> zynqmp-zcu102-rev10-ad9082: fix HDL project tag

- ci/travis/run-build-docker.sh
- ci/travis/run-build.sh
This backport fixes CI build for the 2019_R2 branch...
> fix ci build 2019 r2

- arch/arm/boot/dts/zynq-zed-adv7511-ad7768-1-evb.dts
Having the same node name as the HDMI AXI CLKGEN defined in
zynq-zed-adv7511.dtsi caused an error where the clk driver could not be
instantiated because it already existed.
> arch: arm: boot: dts: rename SPI Engine AXI CLKGEN

- drivers/iio/addac/one-bit-adc-dac.c
In one_bit_adc_dac_read_label() the number of input channels
is being read from st->in_num_ch which is not initialized.
Fixes: 88c34541d056 ("drivers: iio: addac: one-bit-adc-dac: Update label storage")
> drivers: iio: adc: one-bit-adc-dac: Fix read_label()

- arch/arm/boot/dts/overlays/rpi-cn0511-overlay.dts
HAT ID EEPROM is connected to I2C0.
Calibration coefficients EEPROM is connected to I2C1.
> arch: arm: overlays: cn0511: Add EEPROMs support

- arch/arm/boot/dts/overlays/Makefile
- arch/arm/boot/dts/overlays/rpi-cn0552-overlay.dts
The EVAL-CN0552-PMDZ is a PMOD form-factor evaluation board for the
AD7746, a high resolution, sigma-delta capacitance-to-digital converter.
More details:
https://wiki.analog.com/resources/eval/user-guides/circuits-from-the-lab/cn0552
Signed-off by: Zuedmar Arceo <zuedmar.arceo@analog.com>
> arch: arm: overlays: Add CN0552 support

- arch/arm/boot/dts/zynq-zc706-adv7511-ad9081-np12.dts
Do not overwrite values of pll1 clkin and vcxo frequencies in
zynq-zc706-adv7511-ad9081-np12.dts, but let them to 100 MHz
as they are set in adi-ad9081-fmc-ebz.dtsi
> arch: arm : boot: dts: set vcxo to 100 MHz

- arch/arm/boot/dts/overlays/rpi-cn0511-overlay.dts
Set the rfout of adf4377 to 6GHz which serves as default DAC_CLK for
ad9166.
> overlays: cn0511: update power-up-frequency

- drivers/iio/jesd204/xilinx_transceiver.c
Fix the error handling in function xilinx_xcvr_prbs_err_cnt_get().
The return value of a previous call was checked.
Signed-off-by: George Mois <george.mois@analog.com>
> iio: jesd204: xilinx_transceiver.c: Fix error handling

- drivers/iio/adc/ad9081/adi_ad9081_jesd.c
- drivers/iio/adc/ad9081/adi_ad9081_sync.c
Not available but not used either.
Fixes:
fatal error: adi_utils.h: No such file or directory
> iio: adc: ad9081: Remove "adi_utils.h" include

- drivers/iio/adc/ad9081.c
This patch adds support for printing the error counters on the second
link. In JRX dual link mode the results for the second link
will be separated by an additional ':'.
> iio: adc :ad9081: Dual link support for bist_prbs_error_counters_jrx

- arch/arm64/boot/dts/xilinx/zynqmp-adrv9009-zu11eg-revb-adrv2crr-fmc-revb-sync-fmcomms8-jesd204-fsm-using-clockdist.dts
- arch/arm64/boot/dts/xilinx/zynqmp-adrv9009-zu11eg-revb-adrv2crr-fmc-revb-sync-fmcomms8-jesd204-fsm.dts
Added coarse delays on the carrier in order to compensate for trace mismatch.
Signed-off-by: Mihai Bancisor <bancisor.mihai@gmail.com>
> arm64: dts: adrv9009-zu11eg-fmcomms8: Added coarse delays

- arch/arm/boot/dts/socfpga_arria10_socdk_ad9081.dts
Add "link_clk" too, so, jesd_status will be able to provide a
proper report.
> arm: dts: arria10_ad9081: Fix device_clk linking

- arch/arm64/boot/dts/xilinx/zynqmp-zcu102-rev10-ad9082-m4-l8.dts
Lane rate for this mode is 15Gbps,  the link clock (375MHz) is set
to ref clock by 2.  So the ref clock must be 750MHz.
> arm64: dts: zynqmp-zcu102-rev10-ad9082-m4-l8.dts: Fix ref clock

- drivers/iio/adc/navassa/adrv9002.c
The TDD core rate is calculated by dds_rate * rx_rate. In commit
3fc394629138 ("iio: adc: adrv9002: fix tdd clock export") the logic was
changed to fix another bug so that the current channel when dealing with
TDD rate is a TX port. Hence 'chann->rate' cannot be used as we want the
RX rate which is not guaranteed to be the same as TX.
Fixes: 3fc394629138 ("iio: adc: adrv9002: fix tdd clock export")
> iio: adc: adrv9002: fix tdd rate calculation

- arch/arm/boot/dts/socfpga_cyclone5_de10_nano.dtsi
- arch/arm/boot/dts/socfpga_cyclone5_de10_nano_hps.dts
- arch/arm/boot/dts/socfpga_cyclone5_de10_nano_hps.dtsi
Move processor peripherals to new de10-nano hps dtsi
Add new dts for socfpga_cyclone5_de10_nano_hps, no fpga content 
Signed-off-by: Michael Bradley <michael.bradley@analog.com>
> arm: dts: add socfpga_cyclone5_de10_nano_hps

- drivers/spi/spi-zynqmp-gqspi.c
Cherry pick from Xilinx 2021.2 to fix zynqmp_runtime_resume clk_enable issue
> Fix zynqmp qspi

- arch/arm/boot/dts/zynq-zc706-adv7511-ad9081-np12.dts
Gearbox modes require a device_clk and a link_clk.
Provide both.
> dts: zynq-zc706-adv7511-ad9081-np12.dts: Fix axi_jesd204_[rx|tx] clocks

- drivers/iio/adc/ad9467.c
For the ad9250 the jesd lane clock must not be prepared prior to
the device configuration. Add chip idcheck for the ad9250.
With the current state of the driver the jesd rx clock is prepared
inside the ad9250_setup function after the device is configured.
This patch aims to fix capture issues on the fmcjesdadc1 and the
double call of the clk prepare/enable for the jesd lane clk.
Fixes: 52cc37b ("iio: adc: ad9467: rework clock init; use devm_ helpers")
**This is a partial fix for the fmcjesdadc1 capture issues.**
> iio: adc: ad9467: don't prepare clk for ad9250

- arch/arm64/boot/dts/xilinx/zynqmp-zcu102-rev10-adrv9002-rx2tx2.dts
- arch/arm64/boot/dts/xilinx/zynqmp-zcu102-rev10-adrv9002.dts
Update TX DMA interrupt number according to HDL update.
> arch: arm64: dts: adrv9002: Fix/Update TX DMA interrupt

- arch/arm64/boot/dts/xilinx/zynqmp-zcu102-rev10-ad9695.dts
zynqmp-zcu102-rev10-ad9695.dts: update hdl tag
> zcu102_ad9695.dts: update hdl tag

- Documentation/devicetree/bindings/mfd/adi,ad242x-master.yaml
- Documentation/devicetree/bindings/mfd/adi,ad242x-slave.yaml
- drivers/a2b/a2b-core.c
- drivers/a2b/a2b-mailbox.c
- drivers/a2b/a2b-of.c
- include/linux/a2b/a2b.h
This PR adds the following commits
1. Fix kernel panic in mailbox driver
2. Enable I2S configration in devicetree
3. Enable PDM configration in devicetree
> a2b: patches for configs and kernel panic fix

- arch/arm/boot/dts/overlays/Makefile
- arch/arm/boot/dts/overlays/rpi-adxl313-i2c-overlay.dts
- arch/arm/boot/dts/overlays/rpi-adxl313-spi-overlay.dts
Add SPI and I2C dt overlays for the ADXL313 driver.
Signed-off-by: George Mois <george.mois@analog.com>
> Add rpi-adxl313 spi & i2c overlay

- drivers/dma/dma-axi-dmac.c
Marking the DMA as cache coherent (dma-coherent in devicetree) is only
safe with versions of axi_dmac that have this feature enabled.
Related to https://github.com/analogdevicesinc/hdl/pull/925.
Example devicetree using the dma-coherent property:
```
mydma: dma@82510000 {
compatible = "adi,axi-dmac-1.00.a";
reg = <0x0 0x0082510000 0x0 0x1000>;
interrupt-parent = <&gic>;
interrupts = <0 111 4>;
clock-names = "s_axi_aclk";
clocks = <&zynqmp_clk 71>;
#dma-cells = <1>;
dma-coherent;
adi,channels {
#size-cells = <0>;
#address-cells = <1>;
dma-channel@0 {
reg = <0>;
adi,source-bus-width = <64>;
adi,source-bus-type = <AXI_DMAC_TYPE_AXI_STREAM>;
adi,destination-bus-width = <128>;
adi,destination-bus-type = <AXI_DMAC_TYPE_AXI_MM>;
};
};
};
```
Data can be corrupt if used with a version of axi-dmac …
> dmaengine: axi-dmac: check cache coherency register

- drivers/spi/spi-xilinx.c
The bits-per-word property can be specified in the devicetree
but the bits_per_word_mask is always set to support only 8-bit
word transfers.
Fixes: ad7897e45022 ("spi: spi-xilinx: Updated axi-qspi controller driver")
Reviewed-by: Shubhrajyoti Datta <Shubhrajyoti.datta@xilinx.com>
> spi: spi-xilinx: Fix bits_per_word_mask

- drivers/iio/adc/ad400x.c
- drivers/iio/adc/ad7768-1.c
- drivers/iio/adc/ad_adc.c
- drivers/iio/adc/admc_adc.c
- drivers/iio/adc/admc_speed.c
- drivers/iio/adc/cf_axi_adc_core.c
- drivers/iio/buffer/industrialio-buffer-dmaengine.c
- drivers/iio/frequency/cf_axi_dds.c
- drivers/iio/frequency/cf_axi_dds_buffer_stream.c
- drivers/iio/frequency/m2k-dac.c
- drivers/iio/logic/m2k-logic-analyzer.c
- drivers/misc/mathworks/mw_stream_iio_channel.c
- include/linux/iio/buffer-dmaengine.h
The goal of this PR is to turn `iio_dmaengine_buffer_alloc()` private and only use the devm variant. This will make us a little bit closer with what we have upstream. Along the way, I fixed some things and just moved all the probes() to be completely resource managed.
Regarding the last change where the move to static is done, I could have waited until we move to a newer kernel to do it, but I just want to sop any possible use of `iio_dmaengine_buffer_alloc()` in the meantime.
> turn `iio_dmaengine_buffer_alloc()` static

- Documentation/devicetree/bindings/iio/accel/adi,adxl313.yaml
- drivers/iio/accel/adxl313.h
- drivers/iio/accel/adxl313_core.c
- drivers/iio/accel/adxl313_i2c.c
- drivers/iio/accel/adxl313_spi.c
ADXL312 and ADXL314 are small, thin, low power, 3-axis accelerometers with high resolution (13-bit) measurement up to +/-12 g and +/- 200 g, respectively. They are based on the same ASIC as ADXL313 and support for their operation is added to the already existing ADXL313 driver.
> Addition of support for ADLX312 and ADXL314 for the ADXL313 driver.

- drivers/iio/dac/ad5593r.c
For reliable operation across the full range of supported
interface rates. The AD5593R needs a STOP condition between
address write, and data read (like show in the datasheet Figure 40)
so in turn i2c_smbus_read_word_swapped cannot be used.
See here:
https://ez.analog.com/linux-software-drivers/f/q-a/560845/ad5593r-missing-i2c-stop-bit-in-linux-driver/466631
> iio: dac: ad5593r: Fix i2c read protocol requirements

- arch/arm64/boot/dts/xilinx/adi-ad9083-4p-vna.dtsi
- drivers/iio/dac/ad5752.c
Add support for 2s complement mode on AD5752. Set the clamp mode to avoid the output being reset to 0 (caused by overcurrent).
In case the 2s complement mode is selected, the raw attribute's value range will be -8192...8191.
> drivers: iio: dac: AD5752 2s complement

- drivers/iio/adc/ad7923.c
Some of the supported devices have 4 or 2 LSB trailing bits that should not be taken into account. Hence we need to shift these bits out which fits perfectly on the scan type shift property. This change fixes both raw and buffered reads.
Fixes: f2f7a449707e ("iio:adc:ad7923: Add support for the ad7904/ad7914/ad7924")
Fixes: 851644a60d20 ("iio: adc: ad7923: Add support for the ad7908/ad7918/ad7928")
Link: https://lore.kernel.org/r/20220912081223.173584-2-nuno.sa@analog.com
Cc: <Stable@vger.kernel.org>
> ad7923 fixes 2021 r1

- Documentation/devicetree/bindings/iio/adc/lltc,ltc2497.yaml
- MAINTAINERS
- drivers/iio/adc/ltc2496.c
- drivers/iio/adc/ltc2497-core.c
- drivers/iio/adc/ltc2497.c
- drivers/iio/adc/ltc2497.h
Fix the current driver for the LTC2497, and extend it to support the LTC2499 ADC. These patches have been accepted upstream. The only difference is the `____cacheline_aligned` usage instead of `__aligned(IIO_DMA_MINALIGN)`
> LTC2499 driver

- drivers/iio/adc/navassa/adrv9002.c
Having the "<table>", "</table>" markers should not really be mandatory for loading a table (as long as the entries are valid). However, with this change they can still be used which means applications using them should still work.
Moreover, if the pattern was not found we where still returning as everything went good although no table was loaded. This could be confusing for userspace.
> iio: adc: adrv9002: remove check for "</table" in frequency hopping

- drivers/iio/filter/admv8818.c
ADMV8818_SW_IN_WR0_MSK and ADMV8818_SW_OUT_WR0_MSK have 3 bits,
which means a length of 8, but freq_range_hpf and freq_range_lpf array size is 4,
may end up reading 4 elements beyond the end of those arrays.
Fix to check value first before access freq_range_hpf and freq_range_lpf.
Fixes: bd10500 ("iio:filter:admv8818: add support for ADMV8818")
> iio: filter: admv8818: fix out-of-bounds read

- ci/travis/run-build.sh
Without GitPython installed, the checkpatch script prints an error when trying to run the spdxcheck.py script.
Traceback (most recent call last):
File "scripts/spdxcheck.py", line 10, in <module>
import git
ModuleNotFoundError: No module named 'git'
Although it is not fatal, just install the python package to get rid of it.
> CI: install GitPython for checkpatch

- arch/arm64/boot/dts/xilinx/zynqmp-adrv9009-zu11eg-revb-adrv2crr-fmc-revb-jesd204-fsm-xmicrowave.dts
Update the hdl tag to match the actual hdl project.
> arch: arm64: dts: xmicrowave: fix hdl tag

- arch/arm/boot/dts/socfpga_arria10_socdk_ad9136_fmc_ebz.dts
Add HDL project tag and Copyright lines in
arch/arm/boot/dts/socfpga_arria10_socdk_ad9136_fmc_ebz.dts
> arch/arm/boot/dts: a10soc_ad9136 dts: add hdl tag

- arch/arm/boot/dts/overlays/Makefile
- arch/arm/boot/dts/overlays/rpi-max14830-i2c-overlay.dts
- arch/arm/boot/dts/overlays/rpi-max14830-spi-overlay.dts
The MAX14830 is an advanced quad universal asynchronous receiver-transmitter (UART), each UART having 128 words of receive and transmit first-in/first-out (FIFO) and a high-speed serial peripheral interface (SPI) or I2C controller interface. A PLL and fractional baud-rate generators allow a high degree of flexibility in baud-rate programming and reference clock selection.
Each of the four UARTs is selected by in-band SPI/I2C addressing. The 128-word FIFOs have advanced FIFO control reducing host processor data flow management.
> arch: arm: dts: overlays: add rpi-max14830

- include/linux/a2b/a2b-regs.h
Fix typo in `A2B_DNMASK` definition.
Signed-off-by: Jay Mistry <jay.mistry@getcruise.com>
> a2b: fix typo in A2B_DNMASK definition

- arch/arm/boot/dts/adi-adrv9002.dtsi
- arch/arm64/boot/dts/xilinx/adi-adrv9002.dtsi
- drivers/iio/adc/navassa/adrv9002.c
- drivers/iio/adc/navassa/adrv9002.h
Add support for having external LOS connected to the device. This has to be enabled in the loaded profile. While doing, one bugs in the devicetree was found, so the first 2 patches are fixing it (for different platforms)
> adrv9002 ext lo support

- Documentation/ABI/testing/sysfs-bus-iio-adc-max11410
- Documentation/devicetree/bindings/iio/adc/adi,max11410.yaml
- drivers/iio/Kconfig.adi
- drivers/iio/adc/Kconfig
- drivers/iio/adc/Makefile
- drivers/iio/adc/max11410.c
Add driver support for Analog Devices max11410 adc.
> iio: adc: add max11410 adc driver

- arch/arm/boot/dts/socfpga_cyclone5_de10_nano.dtsi
Commit originally added to release branch 2021_R1. Adding this commit to master, for issue:
[Master] No sysid in kernel message
https://jira.analog.com/projects/SDGREL/issues/SDGREL-589?filter=allopenissues
Previous commit on 2021_R1:
[arch: arm: dts: de10nano: add sysid support]
https://github.com/analogdevicesinc/linux/commit/5d3532c4c5740473b7b1d413d67ba2a7fa47f70b
> arch/arm/dts/de10nano: Add sysid support to master

- arch/microblaze/boot/dts/vcu118.dtsi
Device tree was missing sysid node.
PR created for issue _[vcu118-ad9208] No sysid_:
`https://jira.analog.com/browse/SDGREL-591`
No sysid message, but axi_sysid present in HDL base design for carrier:
_ad_cpu_interconnect 0x45000000 axi_sysid_0_
`https://github.com/analogdevicesinc/hdl/blob/master/projects/common/vcu118/vcu118_system_bd.tcl`
> arch/microblaze/boot/dts: Add sysid support vcu118

- drivers/net/ethernet/adi/adin1110.c
aaf06339859e - net: ethernet: adi: adin1110: Fix SPI transfers
5bf007e549a3 - net: ethernet: adi: adin1110: Add check in netdev_event
Two patches for ADIN1110 that have been accepted upstream and are needed on ADI linux repo too.
> Adi adin1110 sync upstream

- arch/arm/boot/dts/adi-ad9083-fmc-ebz.dtsi
- arch/arm/boot/dts/socfpga_arria10_socdk_ad9083_fmc_ebz.dts
Tested on hardware.
Works, but jesd_status reports "measured link clock" as being double the value of "reported link clock".
> arm: dts: Add AD9083-FMC-EBZ + Arria 10 SoC Development Kit support

- Documentation/devicetree/bindings/net/adi,adin1110.yaml
- drivers/net/ethernet/adi/adin1110.c
36f616882b33 - dt-bindings: net: adin1110: Document reset
f7f0b029487a - net: ethernet: adi: adin1110: add reset GPIO
Both are accepted upstream. Need them backported.
> Adin1110 add reset gpio

- arch/arm/boot/dts/overlays/Makefile
- arch/arm/boot/dts/overlays/rpi-ad4130-overlay.dts
AD4130-8 is an ultra-low power, high precision, measurement solution for low bandwidth battery operated applications.
The fully integrated AFE (Analog Front-End) includes a multiplexer for up to 16 single-ended or 8 differential inputs, PGA (Programmable Gain Amplifier), 24-bit Sigma-Delta ADC, on-chip reference and oscillator, selectable filter options, smart sequencer, sensor biasing and excitation options, diagnostics, and a FIFO buffer.
> arch: arm: dts: overlays: add rpi-ad4130

- drivers/net/ethernet/adi/adin1110.c
ADIN1110 was registering netdev_notifiers on each device probe. This leads to warnings/probe failures because of double registration of the same notifier when to adin1110/2111 devices are connected to the same system.
Move the registration of netdev_notifiers in module init call, in this way multiple driver instances can use the same notifiers.
Fixes: bc93e19d088b ("net: ethernet: adi: Add ADIN1110 support")
Link: https://lore.kernel.org/r/20221027095655.89890-2-alexandru.tachici@analog.com
Signed-off-by: Jakub Kicinski <kuba@kernel.org>
> net: ethernet: adi: adin1110: Fix notifiers

- arch/arm64/boot/dts/xilinx/zynqmp-zcu102-rev10-stingray-direct-clk.dts
- arch/arm64/boot/dts/xilinx/zynqmp-zcu102-rev10-stingray-vcxo100-direct-clk.dts
- arch/arm64/boot/dts/xilinx/zynqmp-zcu102-rev10-stingray-vcxo100.dts
- arch/arm64/boot/dts/xilinx/zynqmp-zcu102-rev10-stingray.dts
Update HDL tags in next device tree files:
zynqmp-zcu102-rev10-stingray.dts
zynqmp-zcu102-rev10-stingray-vcxo100.dts
zynqmp-zcu102-rev10-stingray-direct-clk.dts
zynqmp-zcu102-rev10-stingray-vcxo100-direct-clk.dts
to match new HDL project name.
> arch: arm64: boot: dts: update stingray HDL tags

- drivers/net/usb/smsc95xx.c
An external PHY needs settling time after power up or reset. In the bind() function an mdio bus is registered. If at this point the external PHY is still initialising, no valid PHY ID will be read and on phy_find_first() the bind() function will fail.
If an external PHY is present, wait the maximum time specified in 802.3 45.2.7.1.1.
Fixes: 05b35e7eb9a1 ("smsc95xx: add phylib support")
Reviewed-by: Andrew Lunn <andrew@lunn.ch>
Link: https://lore.kernel.org/r/20221115114434.9991-2-alexandru.tachici@analog.com
Signed-off-by: Paolo Abeni <pabeni@redhat.com>
> net: usb: smsc95xx: fix external PHY reset

- ci/travis/run-build.sh
The dt_binding_check rule won't exit with an error for schema errors, but will exit with an error for dts example errors. All schema files must be validated before exiting, so the script should not exit on error.
Disable exit-on-error flag, check the exit code manually, and set err if the exit-code is non-zero, before enabling exit-on-error back.
> CI: do not exit on dt_binding_check error

- drivers/iio/imu/adis.c
- include/linux/iio/imu/adis.h
Add '__adis_enable_irq()' implementation which is the unlocked version of 'adis_enable_irq()'.
Call '__adis_enable_irq()' instead of 'adis_enable_irq()' from '__adis_intial_startup()' to keep the expected unlocked functionality.
This fix is needed to remove a deadlock for all devices which are using 'adis_initial_startup()'. The deadlock occurs because the same mutex is acquired twice, without releasing it. The mutex is acquired once inside 'adis_initial_startup()', before calling '__adis_initial_startup()', and once inside 'adis_enable_irq()', which is called by '__adis_initial_startup()'. The deadlock is removed by calling '__adis_enable_irq()', instead of 'adis_enable_irq()' from within '__adis_initial_startup()'.
Fixes: b600bd7eb3335 ("iio: adis: do not disabe IRQs in 'adis_init()'") …
> iio: adis: add '__adis_enable_irq()' implementation

- drivers/jesd204/jesd204-core.c
The correct selection of the source fir copying SYSREF settings.
> drivers: jesd204 :jesd204-core: copy_link_params() sysref param fix

- drivers/jesd204/jesd204-core.c
jesd204_copy_link_params() copy the SYSREF settings form source to destination.
Fixes: 16e9ede (drivers: jesd204 :jesd204-core: copy_link_params() handle sysref param)
Signed-off-by: George Mois <george.mois@analog.com>
> drivers: jesd204 :jesd204-core: copy_link_params() sysref param fix 2021_R1

- arch/arm/boot/dts/overlays/Makefile
- arch/arm/boot/dts/overlays/rpi-ad74115-overlay.dts
The AD74115H is a single-channel, software-configurable, input and output device for industrial control applications. The AD74115H provides a wide range of use cases, integrated on a single chip.
These use cases include analog output, analog input, digital output, digital input, resistance temperature detector (RTD), and thermocouple measurement capability. The AD74115H also has an integrated HART modem.
A serial peripheral interface (SPI) is used to handle all communications to the device, including communications with the HART modem. The digital input and digital outputs can be accessed via the SPI or the general-purpose input and output (GPIO) pins to support higher speed data rates.
The device features a 16-bit, sigma-delta analog-to-digital converter (ADC) and a 14-bit …
> arch: arm: dts: overlays: add rpi-ad74115

- drivers/iio/frequency/ad9172.c
jesd204-fsm callbacks must return JESD204_STATE_CHANGE_DONE on success. Returning 0 is equal to JESD204_STATE_CHANGE_DEFER, which will stop/stall the FSM until it is resumed.
This fixes this erroneous behavior.
fixes: 7a4e388df955 ("iio: frequency: ad9172: Add support for jesd204-fsm")
> iio: frequency: ad9172: Fix jesd204-fsm final state transition

- arch/arm/boot/dts/socfpga_arria10_socdk_adrv9002.dts
Use the same naming as on ZCU102-ADRV9002 and ZED-ADRV9002:
adrv9002-phy
axi-adrv9002-rx-lpc
axi-adrv9002-rx2-lpc
axi-core-tdd
axi-core-tdd
axi-adrv9002-tx-lpc
axi-adrv9002-tx2-lpc
> arch: arm: dts: arria10_adrv9002: Devices names inconsistency

- arch/arm64/boot/dts/xilinx/zynqmp-adrv9009-zu11eg-tx-l2-rx-l2-orx-l2.dts
- arch/arm64/boot/dts/xilinx/zynqmp-adrv9009-zu11eg-tx-l4-rx-l2-orx-l2.dts
TX_L=2 RX_L=2 ORX_L=2
TX_L=4 RX_L=2 ORX_L=2
The corresponding HDL projects were built using the following parameters.
make TX_JESD_M=4 TX_JESD_L=2 RX_JESD_M=8 RX_JESD_L=2 RX_OS_JESD_M=4 RX_OS_JESD_L=2 
make TX_JESD_M=8 TX_JESD_L=4 RX_JESD_M=8 RX_JESD_L=2 RX_OS_JESD_M=4 RX_OS_JESD_L=2
> arch: arm64: boot: dts: Add devicetree for adrv9009zu11eg

- arch/arm/boot/dts/zynq-zc706-adv7511-adrv9009-tx-l1-rx-l1-orx-l1.dts
- arch/arm/boot/dts/zynq-zc706-adv7511-adrv9009-tx-l2-rx-l1-orx-l1.dts
TX_L=1 RX_L=1 ORX_L=1
TX_L=2 RX_L=1 ORX_L=1
The corresponding HDL project was built using the following parameters.
make TX_JESD_M=2 TX_JESD_L=1 RX_JESD_M=4 RX_JESD_L=1 RX_OS_JESD_M=2 RX_OS_JESD_L=1 make TX_JESD_M=4 TX_JESD_L=2 RX_JESD_M=4 RX_JESD_L=1 RX_OS_JESD_M=2 RX_OS_JESD_L=1
> arch: arm: boot: dts: Add devicetree for adrv9009 new JESD mode

- Documentation/devicetree/bindings/net/adi,adin.yaml
- arch/arm/boot/dts/adi-cn0506-socfpga-mii.dtsi
- drivers/net/ethernet/stmicro/stmmac/stmmac_main.c
- drivers/net/phy/adin.c
ea5b2f2a2779 - arch: arm: boot: dts: Fix cn0506 socfpga DT
Tested with CN0506 connected to the arria 10 FMC port A.
99c3b00687cc - net: ethernet: stmicro: stmmac_main: Fix mode mask
This one is fixed in 5.18 but could not port it neatly. "Fixes" were made over multiple patches.
a2c2d569d041 - net: phy: adin: add support for clock output
cherry-picked from upstream, needed it backported.
8295ba3c59e9 - dt-bindings: net: adin: document phy clock output properties
cherry-picked from upstream, needed it backported.
> Arria10 cn0506 fix

- arch/arm64/boot/dts/xilinx/zynqmp-zcu102-rev10-adrv9009-fmcomms8-tx-l2-rx-l2-orx-l2.dts
- arch/arm64/boot/dts/xilinx/zynqmp-zcu102-rev10-adrv9009-fmcomms8-tx-l4-rx-l2-orx-l2.dts
TX_L=2 RX_L=2 ORX_L=2
TX_L=4 RX_L=2 ORX_L=2
The corresponding HDL project was built using the following parameters.
make TX_JESD_M=4 TX_JESD_L=2 RX_JESD_M=8 RX_JESD_L=2 RX_OS_JESD_M=4 RX_OS_JESD_L=2 make TX_JESD_M=8 TX_JESD_L=4 RX_JESD_M=8 RX_JESD_L=2 RX_OS_JESD_M=4 RX_OS_JESD_L=2
> arch: arm64: boot: dts: Add devicetree for fmcomms8

- drivers/iio/adc/ad4630.c
This PR adds the test pattern channel to the missing device modes and fixes a bug when the output mode is set to averaging and the user wants to do a "test pattern" capture.
> ad4630 fixes

- drivers/iio/adc/ad7124.c
There was a divergence between the upstream and ADI version of the driver regarding the maximum number of active slots. As it turns out the upstream version is the correct one and we can't have more than 8 channels sampled without a stop. Thus, we need to fix it in our end...
Fixes: 541a8ff397e4f ("iio: adc: ad7124: allow multiple-channels enabled")
> iio: adc: ad7124: fix sequencer support

- drivers/iio/adc/ad7124.c
There was a divergence between the upstream and ADI version of the driver regarding the maximum number of active slots. As it turns out the upstream version is the correct one and we can't have more than 8 channels sampled without a stop. Thus, we need to fix it in our end...
Fixes: 541a8ff397e4f ("iio: adc: ad7124: allow multiple-channels enabled")
(cherry picked from commit cbdcc4022a5e9ff947533f0dc3542ff06cb5817d)
> ad7124 fix for 2021.2

- drivers/iio/adc/ad7124.c
There was a divergence between the upstream and ADI version of the driver regarding the maximum number of active slots. As it turns out the upstream version is the correct one and we can't have more than 8 channels sampled without a stop. Thus, we need to fix it in our end...
Fixes: 541a8ff397e4f ("iio: adc: ad7124: allow multiple-channels enabled")
(cherry picked from commit cbdcc4022a5e9ff947533f0dc3542ff06cb5817d)
> ad7124 fix for 2021.1

- drivers/net/ethernet/adi/adin1110.c
Driver marked broadcast/multicast frames as offloaded incorrectly. Mark them as offloaded only when HW offloading has been enabled. This should happen only for ADIN2111 when both ports are bridged by the software.
Fixes: bc93e19d088b ("net: ethernet: adi: Add ADIN1110 support")
Already accepted upstream.
> net: ethernet: adi: adin1110: Fix multicast offloading

- drivers/iio/adc/cf_axi_adc_core.c
Don't explicitly set the masklength (wrong), the IIO core will set it for us, based on the max scan_index. In this particular case we copy all channels and assume all are buffer channels (scan_index > 0) This is not always the case, so we end up with a larger than necessary scan_mask. So far this didn't cause issues. However on 5.15 master-next branch this causes a NULL pointer dereference:
[  110.301120] Call trace:
[  110.303551]  iio_compute_scan_bytes+0x90/0x138
[  110.307986]  __iio_update_buffers+0x818/0x8b8
[  110.312334]  iio_buffer_store_enable+0x13c/0x170 [  110.316943]  dev_attr_store+0x18/0x30
[  110.320597]  sysfs_kf_write+0x44/0x60
> iio: adc: cf_axi_adc_core: Fix masklenght initialization

- drivers/iio/dac/ad5592r-base.c
Add array of explicit gpio names for the `gpiochip` structure of ad5592r, mainly for debug purposes.
Since the gpios are configurable via the dts, generic names are used.
Link: https://lore.kernel.org/all/20221117090130.51702-1-antoniu.miclaus@analog.com
> drivers: iio: dac: ad5592r: add gpio_chip names

- arch/arm64/boot/dts/xilinx/zynqmp-zcu102-rev10-ad9694.dts
- drivers/iio/adc/ad9208.c
Added custom config for the AD9694 board inside iio: adc: ad9208.
Created a devicetree for the ZCU102 carrier: arch: arm64: dts: add zynqmp-zcu102-rev10-ad9694 dts
> AD9694 initial support

- arch/arm64/boot/dts/xilinx/zynqmp-adrv9009-zu11eg-reva-adrv2crr-fmc-reva.dts
To match default AD-SYNCHRONA14-EBZ configuration:
CH8 - HMC7044 CLKOUT4 - CMOS
CH10 - HMC7044 CLKOUT5 - LVPECL AC-COUPLED
CH6 - HMC7044 CLKOUT6 - CMOS
CH9 - HMC7044 CLKOUT12 - LVPECL AC-COUPLED
> arch: arm64: adrv9009-zu11eg: Update hmc7044_ext

- arch/microblaze/boot/dts/kc705.dtsi
- arch/microblaze/boot/dts/kcu105.dtsi
- arch/microblaze/boot/dts/vc707.dtsi
- arch/microblaze/boot/dts/vcu118.dtsi
Update [kc705|kcu105|vc707|vcu118].dtsi to use compatible xlnx,axi-iic-2.1 This removes some quirk necessary for 2.0, which in return causes issues with 2.1.
> microblaze: dts: Update compatible xlnx,axi-iic-2.1

- drivers/iio/adc/navassa/adrv9002.c
- drivers/iio/adc/navassa/adrv9002.h
Improve the reported available interface gain values. These values can change when loading a new profile as they depend on the RX interface rate and Gain Table type. The values are reported like this:
Compensated Gain && rate >= 1MHz
0dB -6dB -12dB -18dB -24dB -30dB -36dB
Compensated Gain && rate < 1MHz
18dB 12dB 6dB 0dB -6dB -12dB -18dB -24dB -30dB -36dB
Correction Gain && rate >= 1MHz
0dB
Correction Gain && rate < 1MHz
18dB 12dB 6dB 0dB
> iio: adc: adrv9002: dynamically export valid interface gain values

- Documentation/ABI/testing/sysfs-bus-iio-temperature-max31865
- drivers/iio/Kconfig.adi
- drivers/iio/temperature/Kconfig
- drivers/iio/temperature/Makefile
- drivers/iio/temperature/max31865.c
This backports the max31865 temperature sensor as we need it for a project (and ideally, our tree should contain all ADI drivers).
Note that this only backports the patches that cleanly build in our tree so that there's no need to change the driver...
> max31865 backport

- drivers/iio/adc/navassa/adrv9002.h
The linker error was triggered when CONFIG_DEBUG_FS is not set as the function was not being statically inlined.
(cherry picked from commit 0b220f4242d11ac18e4ba311238d1ca6d892c23c)
Yeps, old branch but it looks like someone needs this fix:
https://ez.analog.com/linux-software-drivers/f/q-a/567809/petalinux-2019-1-use-adi-linux-kernel-build-error-board-is-zc7020-ad9363
> iio: adrv9002: fix multiple definition of 'adrv9002_debugfs_create()'

- drivers/iio/industrialio-buffer.c
Due to the fact that the rpi upstream branch is linux 5.15.92 and our master branch is linux 5.15.0 some mismatches might pop up when rebasing the new rpi branch.
That was what happened in here resulting in
iio_buffer_unregister_legacy_sysfs_groups() never being called.
Align the code with what exists upstream.
> iio: buffer: fix rebase to rpi-5.15.y

- drivers/iio/adc/ad9361.c
Charge Pump Current value is 6 bits wide, therefore the VCO Bias Tcf value for profile6 needs to be shifted with 6 bits instead of 3.
Fixes: c44c35b ("drivers/iio/adc/ad9361: Add Fastlock Profile Support")
> drivers: ad9361: fix fast lock addressing

- README.md
Reflect links and versions of the new supported xilinx tag.
> README.md: Update to xilinx v2022.2 tag

- drivers/iio/frequency/cf_axi_dds.c
Make sure that the conv->read(), conv->write(), conv->read_raw() or conv->write_raw() are implemented before calling them.
This fixes kernel oopses when used alongside the AD9783 driver, which does not provide these implementations.
> iio: dac: cf_axi_dds: Protect against unimplemented callbacks

- arch/arm64/boot/dts/xilinx/versal-vck190-reva-ad9081.dts
* The hdl design has some problems at higher speeds
* Limit the lane rate until we find a proper fix
> dts: versal-vck190-reva-ad9081: Lower the lane rate to half

- arch/arm/boot/dts/overlays/rpi-adxl355-overlay.dts
Updated rpi-adxl355 device tree overlay to include overrides for CS and INT lines. Defaulted CS and INT lines to match P1 on PMD-RPI-INTZ adapter
> rpi-adxl355-overlay updates

- ci/travis/prepare_artifacts.sh
Add git sha to text file that is uploaded to SwDownloads in order to help people to correlate from which sources were created the binaries from archives.
> CI: add git sha to SwDownloads files

- drivers/iio/adc/navassa/adrv9002_conv.c
The warning was introduced by
commit cf397097e5848 ("iio: adc: adrv9002: constify where possible") and only triggers when DEBUG is defined...
> iio: adc: adrv9002: fix -Wdiscarded-qualifiers warning

- arch/arm64/boot/dts/xilinx/zynqmp-pluto-ng.dts
- drivers/iio/adc/navassa/adrv9002.c
- drivers/iio/adc/navassa/adrv9002.h
- drivers/iio/adc/navassa/adrv9002_of.c
The main goal of this PR is to support adrv9002 port muxes (when available) so that we can make sure all the ports are duly terminated during init calls. It's now possible to select between TX_A and TX_B for transmission. Some devices might re-route TX (through eg: an amplifier) so we can select between those two options.
While doing the above:
* Some cleanups were done;
* Supported GPIOs hogs for fanctl;
* Cherry-picked a missing dts patch.
> pluto adrv9002 rx muxes

- arch/arm/boot/dts/adi-common-dac-fmc-ebz.dtsi
- arch/arm/boot/dts/adi-xilinx-dac-fmc-ebz.dtsi
- arch/arm/boot/dts/zynq-zc706-adv7511-ad9136-fmc-ebz.dts
- ci/travis/dtb_build_test_exceptions
- drivers/iio/jesd204/axi_jesd204_rx.c
- drivers/iio/jesd204/axi_jesd204_tx.c
The ad9136 devicetree was completely outdated and that was brought to our attention in:
https://ez.analog.com/linux-software-drivers/f/q-a/569459/kernel-boot-failure-when-adding-a-new-custom-devicetree-with-petalinux/492733
This PULL should fix those issues...
> ad9136 fixes

- drivers/iio/adc/ad4630.c
Same as #2187 . As stated in there, we need to backport this one...
> ad4630 test pattern debugfs 2021 r2

- arch/arm64/boot/dts/xilinx/versal-vck190-reva-ad9081-204c-txmode23-rxmode25.dts
- arch/arm64/boot/dts/xilinx/versal-vck190-reva-ad9081.dts
- arch/arm64/boot/dts/xilinx/versal-vck190-reva-ad9082.dts
- Updates the default modes for the AD9081 for the VCK190 carrier now that the HDL supports more than 4 lanes and the high lane rates issues have been fixed
- The old AD9081 modes have been added to a different devicetree
- Adds the default modes for AD9082 for the VCK190 carrier
> Change ad9081 default modes for vck190, add default mode for ad9082 for vck190

- arch/arm/boot/dts/adi-ad9136-fmc-ebz.dtsi
- arch/arm/boot/dts/zynq-zc706-adv7511-ad9136-fmc-ebz.dts
DAC control GPIO base must be 54 + 21.
While the EVAL board uses LA07P and LA07N and those map to an offset of 0 and 3.
Fixes: 310ac9d ("dts: Add devicetree for AD9136-FMC-EBZ + ZC706")
> dts: zynq-zc706-adv7511-ad9136-fmc-ebz.dts: Fix TXEN GPIO assignments

- arch/arm/boot/dts/zynq-coraz7s-cn0501.dts
The device tree file was updated to match the new version of the CN0501 HDL project.
[HDL address and interrupt values.](https://github.com/analogdevicesinc/hdl/blob/3f0a487b2e8f7425206bed310c45f2f313dee2b8/projects/cn0501/common/cn0501_bd.tcl#L53-L63)
> arch: arm: dts: Updates for the CN0501 on Coraz7s device tree

- arch/arm/boot/dts/zynq-zc706-adv7511-ad9082.dts
* JESD_MODE    8B10B
* RX_LANE_RATE 10
* TX_LANE_RATE 10
* RX_JESD_M    8
* RX_JESD_L    4
* RX_JESD_S    1
* RX_JESD_NP   16
* RX_NUM_LINKS 1
* TX_JESD_M    8
* TX_JESD_L    4
* TX_JESD_S    1
* TX_JESD_NP   16
* TX_NUM_LINKS 1
(cherry picked from commit dd289167670c13fa5fd49d25f6b9aa07ba0c54b0)
> arch: arm: dts: Add ZC706 + AD9082-FMCA-EBZ support

- arch/arm/boot/dts/zynq-zc706-adv7511-ad9739a-fmc.dts
* The AD9739A-FMC-EBZ board is placed on the LPC FMC port of ZC706
* See also [AD9739A Native FMC Card / Xilinx Reference Designs](https://wiki.analog.com/resources/fpga/xilinx/fmc/ad9739a#:~:text=Legacy%20(limited%20support)-,ZC706%20LPC%20Slot,-Quick%20Start%20Guide) wiki page and the [HDL constraints](https://github.com/analogdevicesinc/hdl/blob/master/projects/ad9739a_fmc/zc706/system_constr.xdc#L4) mentioning LPC
> zc706-ad9739a-fmc.dts: Change node name to LPC

- arch/arm/boot/dts/overlays/max31827-overlay.dts
MAX31827 is a low-power temperature switch with I2C interface.
The device is a ±1°C accuracy from -40°C to +125°C (12 bits) local temperature switch and sensor with I2C/SM- Bus interface. The combination of small 6-bump wafer-lev- el package (WLP) and high accuracy makes this temper- ature sensor/switch ideal for a wide range of applications.
For now only the overlay is ready. The driver is still being reviewed by the linux-hwmon community.
> dts: overlays: add RPi 4 overlay for MAX31827

- drivers/jesd204/jesd204-core.c
- drivers/jesd204/jesd204-fsm.c
There's no point in checking for a null pointer in 'struct jesd204_dev_data::state_ops' since state_ops is an array and will never be NULL.
On more recent compilers, this fixes the following warning:
"warning: the comparison will always evaluate as ‘true’ for the address of ‘state_ops’ will never be NULL [-Waddress]"
> jesd204: remove useless 'state_ops' check

- drivers/iio/adc/navassa/adrv9002.c
The ORx port does not have it's own struct 'adrv9002_chann' instance since it's a very simple one and we can handle it with a couple of specific 'struct adrv9002_rx' members. That means, that we need to explicitly use the encoded port in 'struct iio_chan_spec::address' to identify an ORx port when dealing with it's IIO attributes so we can actually read and write them (instead of changing RX attributes)
Of course that not having it's own instance can lead to subtle errors like this but I still think it's not really worth it...
While at it, made all the port handling coeherent by always using 'adi_common_Port_e'.
Fixes: 2c490432b857c ("iio: adc: adrv9002: improve IIO read/write() callbacks code flow")
---
Same as #2214
> [2021_R2] iio: adc: adrv9002: fix ORx port detection

- drivers/hwmon/max31827.c
Add "adi," to the front of the device name.
> hwmon: max31827: Match of_match_table.compatible with binding

- drivers/iio/adc/ad4630.c
pm_runtime_get_sync() will increment the refcount but it will not release it if it fails to resume the device. Hence, use pm_runtime_resume_and_get() which properly handles the this.
Fixes: 04ff9ea893f9 ("drivers: iio: adc: add support for ad4630")
> iio: adc: ad4630: fix pm runtime unbalanced refcounts

- drivers/iio/adc/ad4630.c
pm_runtime_get_sync() will increment the refcount but it will not release it if it fails to resume the device. Hence, use pm_runtime_resume_and_get() which properly handles the this.
Fixes: 04ff9ea893f9 ("drivers: iio: adc: add support for ad4630")
> [2021_R2] iio: adc: ad4630: fix pm runtime unbalanced refcounts

- drivers/clk/clk.c
- drivers/iio/adc/adrv9009.c
- drivers/iio/adc/adrv9009.h
In some cases transmit/receive chains can be disabled even if the chip supports it. Make the clocks optional so that we get a NULL reference instead of ENOENT.
This PR is related to https://github.com/analogdevicesinc/linux/pull/2219.
> ADRV9009: make jesd clocks optional

- drivers/iio/frequency/ad9783.c
Add channel specifications for ad9780 and ad9781.
device_id points to the enumerated index in ad9783_channels based on the compatible string,
but since the index was empty the channel initialisation failed.
> iio: frequency: ad9783: fix ad9780 and ad9781 channel ref

- drivers/iio/amplifiers/Kconfig
- drivers/iio/amplifiers/ad8366.c
This patch add support for HMC792A. 
HMC792A is a 0.25 dB LSB GaAs MMIC 6-bit digital attenuator, DC - 6 GHz.
> iio: amplifiers: ad8366: Add support for HMC792A DSA

- Documentation/devicetree/bindings/iio/adc/adi,ltc2358.yaml
- arch/arm/boot/dts/socfpga_cyclone5_sockit_dc2677a.dts
- drivers/iio/Kconfig.adi
- drivers/iio/adc/Kconfig
- drivers/iio/adc/Makefile
- drivers/iio/adc/cf_axi_adc.h
- drivers/iio/adc/ltc2358.c
This PR enables the integration of the DC2677A board with the SoC FPGA Cyclone 5 FPGA. 
The setup involves utilizing the [axi-dc2677a-hdl-project](https://github.com/analogdevicesinc/hdl/pull/1130) repository for the required HDL project.
> add ltc2358 support

- drivers/iio/frequency/ad9783.c
DAC1/DAC2 full scale adjustment is possible in range of 8.66-31.66mA. Fix setting and reading of channel full scale value. Note that scaling documented in datasheet is not fully linear, as value of 0x200 will set slightly different value than 20mA.
According to [datasheet](https://www.analog.com/media/en/technical-documentation/data-sheets/AD9780_9781_9783.pdf) DAC1 FSC and DAC2 FSC take values from 0-0x3FF which corresponds to full scale output between 8.66-31.66mA. The current driver sysfs interface for controlling the values did work as expected. This PR provides a fix for setting and getting DAC1/DAC2 gain through the iio sysfs interface.
**Testing details:**
Before applying fix:
~~~~
/sys/kernel/debug/iio/iio:device1 # echo 0xc > direct_reg_access 
/sys/kernel/debug/iio/iio:device1 # …
> iio: frequency: ad9783: fix DAC channel gain get/set

- drivers/iio/frequency/ad9783.c
Add channel specifications for ad9780 and ad9781.
device_id points to the enumerated index
in ad9783_channels based on the compatible string, but since the index was empty the channel initialisation failed.
Fixes: abdceca3a01972 ("drivers: iio: adc: Add support for AD978")
(cherry picked from commit 11c42ec4c03b9a2891b85ca9dcc1a7d1aa559686)
> [2021_R2] iio: frequency: ad9783: fix ad9780 and ad9781 channel ref

- drivers/iio/frequency/ad9783.c
DAC1/DAC2 full scale adjustment is possible in range of 8.66-31.66mA. Fix setting and reading of channel full scale value. Note that scaling documented in datasheet is not fully linear, as value of 0x200 will set slightly different value than 20mA.
Define new constants related to DAC_FSC for better code readability.
Fixes: abdceca3a01972 ("drivers: iio: adc: Add support for AD978")
(cherry picked from commit 8deea8b8a2357c104ca7b545045ba385c9d6bf02)
> [2021_R2] iio: frequency: ad9783: fix DAC channel gain get/set

- drivers/iio/adc/navassa/adrv9002.c
- drivers/iio/adc/navassa/adrv9002.h
The first two patches are fixes and the last patch is an improvement (forcing the hopping table to be written in one go; might be a controversial change, I know, but I'm still willing to take the risk - more on the commit message)
> [adrv9002] frequency hopping fixes

- drivers/iio/adc/adrv9009.c
Update cached ORX enable and framerB M/F vales after restart. This allows the debugfs dts emulation to update those values.
> iio: adc: adrv9009: Update cached ORX enable and framerB M/F vales

- arch/arm/boot/dts/adi-adrv9009.dtsi
- arch/arm64/boot/dts/xilinx/adi-adrv9009.dtsi
M=2, F=2 are the default HDL synthesis parameters.
> dts: adi-adrv9009.dtsi: Set ORX JESD204 Par M=2, F=2 and chanORXen=ORX1

- azure-pipelines-rpi.yml
- ci/travis/prepare_artifacts.sh
- ci/travis/upload_to_artifactory.py
Changing the agent for artifactory upload and eliminating the task regarding restructure of the artifacts, from pipeline due to possible double generating of timestamp folder.
Also changing from quit() to exit(1) so that the exit code in case of error to be different from 0.
> Change agent and fix timestamp folder issue

- ci/travis/upload_to_artifactory.py
To avoid exposing the link of artifactory server the logs regarding uploading of files to artifactory were moved to a local file.
> Move upload logs to a file on server

- arch/arm/boot/dts/overlays/Makefile
- arch/arm/boot/dts/overlays/rpi-ad7124-8-all-diff-overlay.dts
Update rpi-ad7124-8-all-diff-cso-int25-overlay to include overrides for CS and INT lines.
Defaulted CS and INT lines to match P1 on PMD-RPI-INTZ adapter. 
Renamed to rpi-ad7124-8-all-diff to account the dt change.
> arch: arm: boot: dts: overlays: Rename rpi-ad7124-8-all-diff-cs0-int25-overlay

- ci/travis/prepare_artifacts.sh
- ci/travis/upload_to_artifactory.py
In case we want to save the log on a local file we need to specify the file as input parameter when the script is run otherwise the logs are displayed on terminal.
> Log file as parameter in upload script

- drivers/regulator/core.c
I got the the following report:
OF: ERROR: memory leak, expected refcount 1 instead of 2,
of_node_get()/of_node_put() unbalanced - destroy cset entry:
attach overlay node /i2c/pmic@62/regulators/exten
In of_get_regulator(), the node is returned from of_parse_phandle() with refcount incremented, after using it, of_node_put() need be called.
Fixes: 69511a452e6d ("regulator: map consumer regulator based on device tree")
Link: https://lore.kernel.org/r/20221115091508.900752-1-yangyingliang@huawei.com
---
Backport needed because we have people making use of overlays for runtime modification of the ad4360 device and this is an issue.
> regulator: core: fix unbalanced of node refcount in regulator_dev_lokup()

- drivers/regulator/core.c
I got the the following report:
OF: ERROR: memory leak, expected refcount 1 instead of 2,
of_node_get()/of_node_put() unbalanced - destroy cset entry:
attach overlay node /i2c/pmic@62/regulators/exten
In of_get_regulator(), the node is returned from of_parse_phandle() with refcount incremented, after using it, of_node_put() need be called.
Fixes: 69511a452e6d ("regulator: map consumer regulator based on device tree")
Link: https://lore.kernel.org/r/20221115091508.900752-1-yangyingliang@huawei.com
---
Backport needed because we have people making use of overlays for runtime modification of the ad4360 device and this is an issue.
> regulator: core: fix unbalanced of node refcount in regulator_dev_lookup

- ci/travis/run-build.sh
Make sure xz-utils are installed for the build jobs. This matters for the rpi branch (linux 6.1).
> ci: run-build.sh: install xz-utils

- ci/travis/run-build.sh
Install dtschema package using pip instead of getting latest from GitHub since the master may contain bugs that will fail our CIs.
> Fix Azure CI - dt_binding_check job

- drivers/iio/adc/adrv9009.c
- drivers/iio/adc/adrv9009.h
This patch adds support for Serializer/PHY PRBS generation. This is in addition to the existing Framer PRBS support. The main difference is the injection point.
TAL_FTD_FRAMERINPUT vs. TAL_FTD_SERIALIZER.
> iio: adc: adrv9009: Add support for Serializer/PHY PRBS generation

- Documentation/ABI/testing/sysfs-bus-iio-filter-admv8818
- drivers/iio/filter/admv8818.c
[drivers: iio: filter: admv8818: add bypass mode](https://github.com/analogdevicesinc/linux/commit/5830f301c1c53ec7ec90a3e9dbe8c7bb369346e8)
[Documentation: ABI: testing: admv8818: add bypass](https://github.com/analogdevicesinc/linux/commit/17b0a176021826081d68640f79a0b94ec4fa6a8a)
> drivers: iio: filter: admv8818: add bypass support

- drivers/iio/imu/adis16475.c
The temperature channel has 16-bit storage size. We need to perform the padding to have the buffer elements naturally aligned in case the temperature channel is enabled and there are any 32-bit storage size channels enabled which have a scan index higher than the temperature channel scan index.
Fixes: 8f6bc87d67c0 ("iio: imu: adis16475.c: Add delta angle and delta velocity channels")
Reviewed-by: Nuno Sa <nuno.sa@analog.com>
Link: https://lore.kernel.org/r/20230926085721.645687-2-ramona.gradinariu@analog.com
> iio: imu: adis16475: Add buffer padding after temp channel

- drivers/iio/adc/navassa/adrv9002.c
- drivers/iio/adc/navassa/adrv9002.h
- drivers/iio/adc/navassa/adrv9002_conv.c
This patch series addresses the issue present in [1](https://ez.analog.com/wide-band-rf-transceivers/design-support-adrv9001-adrv9007/f/q-a/571138/adrv9002-tx-image-rejection/498677).
The first patches are just preparing the real "fix" present in [iio: adc: adrv9002: add initial_calibrations attribute](https://github.com/analogdevicesinc/linux/commit/e0b42f16f76a9880b6c380a869fdeea791863280).
The last patch is a minor improvement that I realized when supporting the new attribute.
> [ADRV9002] support re-running init calls

- arch/arm/boot/dts/adi-adrv9002.dtsi
- arch/arm64/boot/dts/xilinx/adi-adrv9002.dtsi
- drivers/iio/adc/navassa/adrv9002.c
- drivers/iio/adc/navassa/adrv9002.h
- drivers/iio/adc/navassa/adrv9002_debugfs.c
- drivers/iio/adc/navassa/adrv9002_of.c
- include/dt-bindings/iio/adc/adi,adrv9002.h
Digital Predistortion (dpd) is way to improve a Power Amplifier operation as it increases it's linearity or compensate for non-linearity.
DPD will only take effect if it's enabled in devicetree (tx1 or tx2) and if a valid profile is loaded with External Loop back (ELB) path enabled. Most of the parameters are configurable through devicetree. There are some new runtime attributes for the TX channels though:
1. 1 bin attr for loading the dpd Frequency hopping regions.
2. 8 new bin attrs to load the coefficients to apply to the wholespectrum or to one region as defined in 1).
Note this is being made a runtime parameters since the hop tables (for frequency hopping) are also runtime configurable. Hence, if we are able to change the hop tables, we should also be able to change the DPD regions …
> adrv9002 dpd support

- drivers/iio/addac/Kconfig
Building ad74413r without selecting IIO_BUFFER and IIO_TRIGGERED_BUFFER generates error with respect to the iio trigger functions that are used within the driver.
Update the Kconfig accordingly.
Fixes: fea251b6a5db ("iio: addac: add AD74413R driver")
Link: https://lore.kernel.org/r/20230912085421.51102-1-antoniu.miclaus@analog.com
> iio: addac: Kconfig: update ad74413r selections

- Documentation/devicetree/bindings/iio/frequency/adi,admv1014.yaml
Make the regulators required in the dt bindings.
Despite the fact that the datasheet is not explicit enough, all the specifications of the part are built around these pins being supplied.
Acked-by: Krzysztof Kozlowski <krzysztof.kozlowski@linaro.org>
Link: https://lore.kernel.org/r/20230731144404.389255-1-antoniu.miclaus@analog.com
> dt-bindings: iio: admv1014: make all regs required

- Documentation/devicetree/bindings/iio/frequency/adi,admv1013.yaml
- drivers/iio/frequency/admv1013.c
[dt-bindings: iio: admv1013: add vcc regulators](https://github.com/analogdevicesinc/linux/commit/88f84238e654c357497bd996ad5aff6bccdc3bf1)
[drivers: iio: admv1013: add vcc regulators](https://github.com/analogdevicesinc/linux/commit/c3327aaa664d81f926261a4cad673077946d89fc)
> drivers: iio: admv1013: add vcc regulators

- drivers/iio/imu/adis16475.c
Some devices do not support delta angle and delta velocity burst readings, which means there should be no buffer support for these types of channels.
A new list of channels is created which contains the delta channels structures with the scan index equal to -1 to allow for raw register readings, without buffer support. This list of channels is assigned to the devices which do not support delta angle and delta velocity burst readings.
Fixes: cd8c11a ("iio: imu: adis16475.c: Add delta angle and delta velocity channels")
Reviewed-by: Nuno Sa <nuno.sa@analog.com>
Link: https://lore.kernel.org/r/20231012122456.765709-2-ramona.gradinariu@analog.com
> drivers: imu: adis16475.c: Remove scan index from delta channels

- drivers/usb/phy/Kconfig
- drivers/usb/phy/phy-ulpi.c
This cherry-picks 636fb6d ("usb: phy: Add platform driver support for ULPI phys")
Not because we need the platform device, but we need the vbus control on the phy device, which is part of this commit.
In the last merge commit we dropped commit https://github.com/analogdevicesinc/linux/commit/5ae8640d0d24a25a90e78e67314f687544e2e110 ("drivers: usb: chipidea: Let the PHY set VBUS").
Since Xilinx has up-streamed code for controlling VBUS which looks very similar, but is actually different from this patch.
Control vbus from the phy device structure instead of the org device structure.
And in fact controlling vbus from the phy device requires the needed callbacks, which only exists in the Xilinx tree.
So let's cherry pick this commit to not diverge to much here and restore a working USB port. …
> usb: phy: Add platform driver support for ULPI phys

- drivers/spi/spi-axi-spi-engine.c
This fixes a use after free that can happen if the watchdog timer times out on an SPI message then another message is attempted.
The following struct spi_engine members point to memory managed by the spi framework
struct spi_message *msg;
struct spi_transfer *tx_xfer;
const uint8_t *tx_buf;
struct spi_transfer *rx_xfer;
uint8_t *rx_buf;
During normal operation, tx_xfer and rx_xfer set to NULL by spi_engine_xfer_next() when the last xfer of a message is completed. However, this code path is not taken when the watchdog timer times out and therefore tx_xfer and rx_xfer are not set to NULL and still point to memory that gets freed by spi_finalize_current_message().
When the next message is attempted, spi_engine_transfer_one() will call spi_engine_xfer_next() with the old pointers and will …
> spi: axi-spi-engine: fix use after free after timeout

- azure-pipelines.yml
- ci/travis/run-build.sh
Having dual licensed files upstream is not as simple as one things. Hence (and since we almost never need it), let's flip the job in CI and not allow it.
> don't allow dual licensed files

- drivers/iio/adc/ad_pulsar.c
This removes the #define IIO_DMA_MINALIGN from the ad_pulsar driver. This was previously needed to support 5.10 kernels, but is no longer needed since we are now based on the 6.1 kernel.
> iio: adc: ad_pulsar: drop 5.10 compatibility

- drivers/net/ethernet/adi/adin1110.c
the variable of "t" is not initialized, the unknown value will result in error in SPI driver.
> net:ethernet:adi:adin1110: Fix uninitialized variable

- drivers/hwmon/axi-fan-control.c
axi_fan_control_irq_handler(), dependent on the private axi_fan_control_data structure, might be called before the hwmon device is registered. That will cause an "Unable to handle kernel NULL pointer dereference" error.
Fixes: 8412b41 ("hwmon: Support ADI Fan Control IP")
> hwmon: (axi-fan-control) Fix possible NULL pointer dereference

- arch/arm64/boot/dts/xilinx/zynqmp-jupiter-sdr.dts
- drivers/usb/dwc3/ep0.c
- drivers/usb/dwc3/gadget.c
- drivers/usb/dwc3/gadget.h
This reverts "usb: dwc3: fixed OTG feature failure for xilinx platform"
Which itself is basically a revert of valid patches, which seem to be all mainline.
This revert fixes the iiod gadget functionfs interface.
The second patch syncs usb pincontrol settings with f04343d ("arm64: zynqmp: Fix usb node drive strength and slew rate")
```
arm64: zynqmp: Fix usb node drive strength and slew rate
As per design, all input/rx pins should have fast slew rate and 12mA
drive strength. Rest all pins should be slow slew rate and 4mA drive
strength. Fix usb nodes as per this and remove setting of slow slew rate
for all the usb gorup pins. 
```
> Fix dwc3 iiod gadget

- drivers/clk/adi/clk-ad9545.c
Commit https://github.com/analogdevicesinc/linux/commit/e8b39147657c79b8bb65099bc20075d507370061 ("clk: ad9545: properly check R-divider") is valid, in
the sense that a divider value of zero should return -EINVAL.
However, the omission in the above commit, is that if a Ref is not used,
it will cause a probe fail, if one of the refs is not defined in the DT.
This breaks the AD9545 on the ADRV9009 Talise SOM.
The fix looks like a simple move into the next loop for the R-divider
config.
Fixes: https://github.com/analogdevicesinc/linux/commit/e8b39147657c79b8bb65099bc20075d507370061 ("clk: ad9545: properly check R-divider")
Cc: Jie Zhang <jie.zhang@analog.com>
Cc: Nuno Sa <nuno.sa@analog.com>
Cc: Michael Hennerich <michael.hennerich@analog.com>
Cc: Dragos Bogdan <dragos.bogdan@analog.com> …
> clk: ad9545: fix driver probe when R-divider is zero

- arch/arm64/boot/dts/xilinx/zynqmp-jupiter-sdr.dts
This adds following 4 partitions:
[ ] spi-nor spi1.0: SPI-NOR-UniqueID 10400030fc0b0012110018000c17a3a87f 
[ ] spi-nor spi1.0: n25q512a (131072 Kbytes)
[ ] 4 fixed-partitions partitions found on MTD device spi1.0 
[ ] Creating 4 MTD partitions on "spi1.0":
[ ] 0x000000000000-0x000000100000 : "qspi-fsbl-uboot" 
[ ] 0x000000100000-0x000000600000 : "qspi-linux"
[ ] 0x000000600000-0x000000620000 : "qspi-device-tree" 
[ ] 0x000000620000-0x000000c00000 : "qspi-rootfs"
> dts: zynqmp-jupiter-sdr: Add QSPI dual MT25QL512 64MB with 4 partitions

- drivers/hwmon/max31827.c
Add missing implementation for the max31827 supply regulator.
This is a hardware required property that is not handled.
Link: https://lore.kernel.org/r/20230925122929.10610-1-antoniu.miclaus@analog.com/
> drivers: hwmon: max31827: handle vref regulator

- arch/arm/boot/dts/overlays/Makefile
- arch/arm/boot/dts/overlays/rpi-ad7091r8-overlay.dts
Pull request with raspberry pi overlay for AD7091R-8.
This is the device tree overlay used during the tests with EVAL-AD7091R-xSDZ and Raspberry Pi 4.
Documentation here: https://wiki.analog.com/resources/tools-software/linux-drivers/iio-adc/ad7091r8
Requested on #2204.
> Add AD7091r-8 rpi overlay

- arch/arm/boot/dts/overlays/Makefile
- arch/arm/boot/dts/overlays/rpi-ad7091r8-overlay.dts
Add example device tree overlay for AD7091R-8.
The AD7091R-8 is a multichannel 12-bit, ultra low power, SAR ADC.
**The driver for this has yet to be tested with a real hardware device so maybe better not to merge these changes now.**
Though, I'm opening this draft pull request in case anyone wants to peek at what is coming.
> arch: arm: dts: overlays: Add AD7091R-8 device tree overlay

- drivers/hwmon/ltc2992.c
Do not allow setting shunt resistor to 0. This results in a division by zero when performing current value computations based on input voltages and connected resistor values.
Link: https://lore.kernel.org/r/20231011135754.13508-1-antoniu.miclaus@analog.com/
> drivers: hwmon: ltc2992: avoid division by zero

- Documentation/devicetree/bindings/iio/adc/adi,pulsar.yaml
- arch/arm/boot/dts/zynq-zed-adv7511-ad7944.dts
- arch/arm/boot/dts/zynq-zed-adv7511-ad7985.dts
- arch/arm/boot/dts/zynq-zed-adv7511-ad7986.dts
- drivers/iio/adc/ad_pulsar.c
This adds device tree bindings compatible strings, ad_pulsar driver support and ZedBoard device trees for the AD7944, AD7985, and AD7986 chips.
- https://www.analog.com/media/en/technical-documentation/data-sheets/AD7944.pdf
- https://www.analog.com/media/en/technical-documentation/data-sheets/AD7985.pdf
- https://www.analog.com/media/en/technical-documentation/data-sheets/AD7986.pdf
This has not been tested yet since we are waiting on HDL for these.
> Add support for AD7944, AD7985, AD7986

- arch/arm/boot/dts/overlays/Makefile
- arch/arm/boot/dts/overlays/rpi-ad242x-overlay.dts
Overlay changes to detect AD242x as Sound card
> RPi 4 DTS overlay changes to use AD242x nodes as sound card

- drivers/iio/adc/ad9361.c
- drivers/iio/adc/ad9361.h
This commit adds a new clock to the clock tree that reflects the actual
receive clock rate. For 1RX1TX configurations this simply mirrors the
sample clock, while for 2RX2TX configs the receive clock is twice as
fast as the sample clock, because two channels are served using the same
data width.
This patch is something that came up in the discussion around Phaser, where we needed a clock tree entry that properly reflects the current ADC clock. I'm also still open to changing the nomenclature here, specifically because it's not just a PL interface clock, that's only the function that was important to me.
Note that this is the first time that i'm messing with the clock framework, so I'd love for somebody with more experience to make sure that i haven't done anything stupid ;)
> iio: adc: ad9361: Export pl_intf_clk reflecing interface PL clock rate

- drivers/iio/adc/ad4630.c
Unswap IDs for ad4030 and ad4630 in open firmware / devicetree match table.
Fixes: <04ff9ea893f9> (drivers: iio: adc: add support for ad4630)
(cherry picked from commit 46a898df00e812073816657c0fb679593f9e1b02)
> iio: adc: adaq4224: Fix AD4030 of_match

- drivers/hwmon/ltc2991.c
Remove device reference from struct ltc2991_state since it is used only inside the init function.
Pass the struct device as parameter to the init function instead.
Link: https://lore.kernel.org/all/20231031095647.48376-1-antoniu.miclaus@analog.com/
> hwmon: ltc2991: remove device reference from state

- drivers/hwmon/max31827.c
Include `linux/regulator/consumer.h` since the driver is using `devm_regulator_get_enable` function.
Link: https://lore.kernel.org/all/20231031091324.23991-1-antoniu.miclaus@analog.com/
> hwmon: max31827: include regulator header

- arch/arm/boot/dts/zynq-zc706-adv7511-ad9081.dts
Add axi_data_offload platfrom devices and enable TX offload fifo by default.
> dts: zynq-zc706-adv7511-ad9081: axi_data_offload devices and enable TX

- drivers/iio/jesd204/Kconfig
While the fakedev driver was originally developed to expose a JESD204 link layer peripheral via IIO. It can be useful elsewhere as well.
> iio: jesd204: Kconfig: IIO fakedev driver does not depend on JESD204

- drivers/pwm/pwm-axi-pwmgen.c
This commit will add support for up to 16 PWM output channels and update to the corresponding [period,width,offset] regs' addresses.
HDL repo [PR](https://github.com/analogdevicesinc/hdl/pull/1213);
> drivers: pwm: pwm-axi-pwmgen: Add support for 16 channels

- drivers/iio/adc/navassa/adrv9002.c
- drivers/iio/adc/navassa/adrv9002.h
- drivers/iio/adc/navassa/adrv9002_debugfs.c
- drivers/iio/adc/navassa/adrv9002_of.c
Add support for multi-chip sync. This was requested by the HW team to be present in the release branch and that is the only reason this is being included because there are still two major failure with the feature:
1) We can only run MCS once. That's why the driver is not allowing multiple runs;
2) We need to force the carrier `loGenOptimization` value since the device returns an invalid value when calling `adi_adrv9001_Radio_Carrier_Inspect()`.
> [adrv9002] Add Multi-chip sync support

- drivers/iio/adc/ltc2387.c
The cnv signal was out of phase by one clock.
I fixed the bug by aligning the clk and cnv signal according to the following formula:
clk_en_state.phase = cnv_state.phase + Tfirstclock, which is deduced from the timing diagram of LTC2387-18 datasheet.
Signed-off-by: Ioan-daniel Pop <Pop.Ioan-daniel@analog.com>
(cherry picked from commit 38aa5b9e8e7c21b97038bc490fdad4edd74622f7)
> iio: adc: ltc2387: Fix the conversion signal phase

- drivers/iio/frequency/m2k-dac.c
Fix spike bug issues from m2k dac when pushing a series of cyclical buffers by using a new HDL attribute that forces raw values on output.
Add support for triggered start and stop of the dac DMA.
> M2k-dac spike bug and trigger support

- ci/travis/prepare_artifacts.sh
The DEST_SERVER variable, which comes from Azure, had hardcoded also the rpi branch name at the end(in this case 'rpi-5.15.y'). So output artifacts from any rpi branch were saved on SWDownloads in the same folder rpi-5.15.y. In have updated variable in Azure and changes from this commit just append the branch name at the end.
This commit will be cherry picked automatically to rpi-6.1.y branch. 
There is one more PR to fix rpi-5.15.y.
> ci/travis/prepare_artifacts.sh: fix rpi boot files upload

- ci/travis/prepare_artifacts.sh
The DEST_SERVER variable, which comes from Azure, had hardcoded also the rpi branch name at the end (in this case 'rpi-5.15.y'). So output artifacts from any rpi branch were saved in "rpi-5.15.y" folder, now being overwritten by the ones from rpi-6.1.y.
The changes from this commit just append the branch name at the end. Afterwards will need to trigger the pipeline to upload correct boot files in "rpi-5.15.y" folder.
Signed-off-by: Stefan Raus <Stefan.Raus@analog.com>
(cherry picked from commit c8e8d46a0a2966ca10939bb6a01e74ac2f45506f)
> ci/travis/prepare_artifacts: fix rpi files upload

- Documentation/devicetree/bindings/iio/dac/adi,ad5791.yaml
- drivers/iio/dac/ad5791.c
Cherry-pick 2 commits from master to 2022_R2 branch:
[dt-bindings: adi,ad5791.yaml: Add support for controlling RBUF](https://github.com/analogdevicesinc/linux/commit/83dcc7967c512fc3ed36b11e91c965488bc2f519)
and 
[iio: dac: ad5791: Add support for controlling RBUF via devicetree](https://github.com/analogdevicesinc/linux/pull/2362/commits/c3a38f31fcebed3b9c01dd70b182d863e5b197cf)
> Cherry-pick to 2022_R2

- ci/travis/prepare_artifacts.sh
The CIs will fail because we cannot build rpi on master, due to the following errors:
```
ERROR: modpost: module uio uses symbol dma_buf_attach from namespace DMA_BUF, but does not import it.
ERROR: modpost: module uio uses symbol dma_buf_map_attachment from namespace DMA_BUF, but does not import it.
ERROR: modpost: module uio uses symbol dma_buf_unmap_attachment from namespace DMA_BUF, but does not import it.
ERROR: modpost: module uio uses symbol dma_buf_get from namespace DMA_BUF, but does not import it.
ERROR: modpost: module uio uses symbol dma_buf_put from namespace DMA_BUF, but does not import it.
ERROR: modpost: module uio uses symbol dma_buf_detach from namespace DMA_BUF, but does not import it.
make[1]: *** [scripts/Makefile.modpost:126: Module.symvers] Error 1
make: *** …
```
> prepare_artifacts.sh: Add current branch to logs

- drivers/iio/imu/adis.c
A delay is needed each time the chip selected becomes inactive, even after burst data readings are performed.
Currently, there is no delay added after a burst reading and in case a new SPI transfer is performed before the needed delay, the adis device becomes unresponsive until reset.
This commit is adding the needed delay directly to the spi driver, using the cs_inactive parameter and is removing the additional chip select change delay present in adis APIs to remove the double delay.
> iio: imu: adis: Use spi cs change delay

- drivers/iio/Kconfig.adi
- drivers/jesd204/jesd204-core.c
jesd204_device_count_get() was being declared with empty arguments. Declare it with 'void'.
(cherry picked from commit ac4017e6bd71d476da4468b5ae54706f8300925b)
---
Otherwise it won'z build with clang
> jesd204: jesd204-core: Declare jesd204_device_count_get() with void

- arch/arm/boot/dts/zynq-zc706-adv7511-ad6676-fmc.dts
- arch/arm/boot/dts/zynq-zc706-adv7511-ad9081-np12.dts
- arch/arm/boot/dts/zynq-zc706-adv7511-ad9081.dts
- arch/arm/boot/dts/zynq-zc706-adv7511-ad9172-fmc-ebz.dts
- arch/arm/boot/dts/zynq-zc706-adv7511-ad9625-fmcadc2.dts
- arch/arm/boot/dts/zynq-zc706-adv7511-adrv9008-1.dts
- arch/arm/boot/dts/zynq-zc706-adv7511-adrv9008-2.dts
- arch/arm/boot/dts/zynq-zc706-adv7511-adrv9009-tx-l1-rx-l1-orx-l1.dts
- arch/arm/boot/dts/zynq-zc706-adv7511-adrv9009-tx-l2-rx-l1-orx-l1.dts
- arch/arm/boot/dts/zynq-zc706-adv7511-adrv9009.dts
- arch/arm/boot/dts/zynq-zc706-adv7511-adrv9371.dts
- arch/arm/boot/dts/zynq-zc706-adv7511-fmcadc4.dts
- arch/arm/boot/dts/zynq-zc706-adv7511-fmcdaq2.dts
- arch/arm/boot/dts/zynq-zc706-adv7511-fmcdaq3.dts
- arch/arm/boot/dts/zynq-zc706-adv7511-fmcjesdadc1.dts
- arch/arm/boot/dts/zynq-zc706-adv7511-fmclidar1.dts
- arch/arm/boot/dts/zynq-zc706-adv7511-fmcomms11-RevA.dts
- arch/arm/boot/dts/zynq-zc706-adv7511-fmcomms11.dts
This fixes incorrectly displayed link/device clock frequencies.
> arm: dts: Use proper 100MHz clock handle for axi-jesd204-[rx|tx] devices

- ci/travis/prepare_artifacts.sh
This PR brings the changes that were automatically cherry-picked onto the `rpi-6.1.y` branch on the `rpi-5.15.y` branch as well. 
The changes that are introduced by this PR are:
- Removal of a redundant line (`"boot_date=${timestamp}`) inside the `rpi_archives_properties.txt` file.
- Adding the source branch to both the `rpi_archives_properties.txt` and `rpi_git_properties.txt` files.
- Fixing a bad indent from the `prepare_artifacts.sh` script
> Staging rpi/bring fix

- drivers/iio/adc/ad_sigma_delta.c
Do not lock the mutex multiple times within the same thread. iio_device_claim_direct_mode() already locks the mutex.
Fixes: bfa02fe ("iio: Add initial ad7173 support")
> iio: adc: ad_sigma_delta: Remove mutex locking

- arch/arm/boot/dts/socfpga_arria10_socdk_ad9081.dts
Add axi-pl-fifo-enable in arch/arm/boot/dts/socfpga_arria10_socdk_ad9081.dts to fix the issue related to DAC buffer.
> dts: arria10: ad9081: add axi-pl-fifo-enable

- drivers/iio/adc/madura/Makefile
Some build systems like yocto might not build the kernel on the kernel top directory. In that case the include paths won't be found and the build fails (petalinux is an example of this). So, we now add the full path making sure things are reachable.
Similar with what was done for example for adrv9002.
> [2022_R2] adrv9025 allow out of tree build

- arch/arm/boot/dts/adi-cn0506-mii.dtsi
- arch/arm/boot/dts/adi-cn0506-rgmii.dtsi
- arch/arm/boot/dts/adi-cn0506-rmii.dtsi
The previous [PR for the 2022_R2 branch](https://github.com/analogdevicesinc/linux/pull/2361) contains only the changes for arm64, this one being related to the code changes for the arch=arm.
> dts: arm: adi-cn0506-*: Update to the corresponding macb_config

- azure-pipelines-rpi.yml
The default timeout for azure jobs is 60 minutes but currently the build for rpi braches is failing because of that, and for now this value will be increased to 75 minutes.
> azure-pipeline-rpi.yml: increase timeout for build jobs

- drivers/iio/adc/ad9361.c
- drivers/iio/adc/ad9361_private.h
Applies to the fast AGC and full gain table.
When clear (default), digital saturation does not cause a gain decrease. When set, digital saturation will cause a gain decrease.
Related to  AD9361 “Enable digital saturation gain decrease” setting missing #2390
> iio: adc: ad9361: Add dts attribute adi,agc-dig-sat-ovrg-enable

- azure-pipelines.yml
- ci/travis/run-build.sh
This series makes sure that bugfixes are not forgotten in the rpi branches. That means that fixes in the release branch should be automatically picked into the rpi branch.
> [2022 r2 ] rpi sync

- ci/travis/run-build.sh
The first patch it's just an improvement (potential fix) for running CI locally. The second change is the real fix on the dual license job. Should fix false positives as triggered in #2393.
> [CI]:  fix dual licence job

- drivers/spi/spi-axi-spi-engine.c
The watchdog timer was being activated after enabling the interrupts and that could actually lead for the message to be transferred before we get to call mod_timer() which would lead to a spurious soft interrupt. In extreme cases (like playing with overlays to load + unload devices) this could lead to a panic splat as the timer callback would be called with the spi engine device gone already.
Fixes: fde5597b0ddd ("spi: axi-spi-engine: Add watchdog timer")
---
Note this is also an issue in the main branch but not an issue in the upstream version of the spi-engine @dlech worked on. As I'm expecting the upstream version to be synced in the ADI tree + offload support, I'm not doing this fix in main.
> spi: spi-axi-spi-engine: setup the timer before IRQ enable

- arch/arm/boot/dts/overlays/Makefile
- arch/arm/boot/dts/overlays/rpi-ltc2664-overlay.dts
The LTC2664 is a family of 4-channel, 12/16-bit +/-10V digital-to-analog converters with integrated precision references. They are guaranteed monotonic and have built-in rail-to-rail output buffers. These SoftSpan DACs offer five output ranges up to +/-10V. The range of each channel is independently programmable, or the part can be hardware-configured for operation in a fixed range.
> overlays: rpi-ltc2664-overlay.dts: Add LTC2664 example overlay

- drivers/spi/spi-axi-spi-engine.c
If the transfer word_length is lower than 8, word_len_bytes would be 0. That together with xfer->len * 8 > word_length would lead to a divide by 0 exception. Fix it by setting word_len_bytes to 1 in case word_length is lower or equal to 8.
Fixes: 30707b090c25 ("spi-axi-engine: Calculate buffer dimension for xfer")
---
Note this is a bit of a bandaid fix (as result of abusing the spi framework and going around it) and it's again not being done in main as I'm expecting the driver to be synced with upstream. But this showed me that after the driver is properly synced we will need to update the offload engine users we have (which are not that many) so that they properly populate the offload transfer `.len` field .
> spi: spi-axi-spi-engine: fix divide by 0 exception

- drivers/iio/adc/ad9081.c
Fixes: d65b7088e1d7 ("iio: adc: ad9081: Support of HR and QR 2D Eye Scan")
> iio: adc: ad9081: Fix JESD204 2D eye scan for dual-link operation

- arch/arm/boot/dts/overlays/rpi-adt7420-overlay.dts
Current DTS only supports 0x4b I2C address.
This PR aims to allow boot time reconfiguration of the I2C address via dt_params
> dts: overlays: rpi-adt7420: Add I2C address override

- drivers/iio/adc/navassa/adrv9002.c
- drivers/iio/adc/navassa/adrv9002.h
When running (on demand or automatically) the initial calibrations the TX port selection would not be respected as we were blindly asserting the TX muxes. Note this would be also an issue in case someone selected TX_B and then reinitialize (or loaded a new profile). This changes makes sure the port selection is respected when re-enabling the ports.
While at it, leave the port 50ohm terminated in case it's not enabled in the profile.
Fixes: ffd7faecf904 ("iio: adc: adrv9002: add initial_calibrations attribute")
> [2022_R2] iio: adc: adrv9002: fix tx port selection

- drivers/iio/adc/navassa/adrv9002.c
- drivers/iio/adc/navassa/adrv9002.h
When running (on demand or automatically) the initial calibrations the TX port selection would not be respected as we were blindly asserting the TX muxes. Note this would be also an issue in case someone selected TX_B and then reinitialize (or loaded a new profile). This changes makes sure the port selection is respected when re-enabling the ports.
While at it, leave the port 50ohm terminated in case it's not enabled in the profile.
Fixes: ffd7faecf904 ("iio: adc: adrv9002: add initial_calibrations attribute")
> iio: adc: adrv9002: fix tx port selection

- drivers/tty/serial/amba-pl011.c
pl011_release_port() and pl011_request_port() were removed in the xilinx 5.15 LTS branch. I suspect the versal changes were somehow squashed together with commit
aee7ef0305b1 ("serial: amba-pl011: do not request memory region twice") so that we never noticed it as we merged directly with the stable tree.
> tty: serial: amba-pl011: fix versal uart support

- drivers/iio/adc/adrv9009.c
- drivers/iio/adc/adrv9009.h
This patch enables RX/TX/ORX pin control. It introduces a new device file called 'radio_pinctrl_en'. Writing '1' enables pin control based on the configuration provided by following devicetree attributes:
* adi,radio-ctl-pin-mode-options-mask and
* adi,radio-ctl-pin-mode-orx-en-pinsel Writing '0' respectively disables pin control.
adi,radio-ctl-pin-mode-options-mask: Mask to configure radio tx, rx, orx pin control options
* (TAL_TXRX_PIN_MODE)      0x01: selects Tx and Rx signaling via pins
* (TAL_ORX_PIN_MODE)       0x02: selects ORx signaling via pins
* (TAL_ORX_USES_RX_PINS)   0x04: selects if Rx pins are used to indicate
ORx mode activation/deactivation
* (TAL_ORX_SEL)            0x10: selects ORx2 (1), when not used defaults
to ORx1 (0)
* (TAL_ORX_SINGLE_CHANNEL) 0x20: selects SPI to …
> iio: adc: adrv9009: Enable radio RX/TX/ORX pin control feature

- drivers/iio/frequency/adf4360.c
This fixes a bug reported here: #2424
Fixes: 0c12de6b3c87 ("iio: frequency: adf4360: Add IIO soft power down support")
> iio: frequency: adf4360.c: Fix incorrect bit masked used for power-down

- arch/arm/boot/dts/zynq-zed-adv7511-ad9265-fmc-125ebz.dts
Add the devicetree for the the ad9265-fmc/zed HDL project (https://github.com/analogdevicesinc/hdl/pull/1253)
> Add AD9265 devicetree

- arch/arm64/boot/dts/xilinx/zynqmp-zcu102-rev10-adrv9025.dts
In order to create boot partition folder for the madura project, the hdl_project needs to be set in the description of the dts, but in hdl repository the project is named advr9026.
No functional changes.
> dts: zynqmp-zcu102-rev10-adrv9025: change hdl_project to advr9026

- drivers/iio/adc/ad7768.c
The scale factor had to be corrected from 488uV to 488nV, according to the following formula: (2*4.096)/(2^24) = 488.28125nV.
> iio:adc:ad7768: Fix the ad7768 scale factor

- drivers/rtc/rtc-max31335.c
Fix the register value comparison in the `max31335_volatile_reg` function for the interrupt status register.
MAX31335_STATUS1 macro definition corresponds to the actual interrupt status register.
Fixes: 706316f5e083 ("rtc: max31335: add driver support")
Link: https://lore.kernel.org/linux-rtc/20240219091616.24480-1-antoniu.miclaus@analog.com/
> rtc: max31335: fix interrupt status reg

- drivers/net/ethernet/adi/adin1110.c
In order to do a clause 22 access to the PHY registers of the ADIN1110,
we have to write the MDIO frame to the ADIN1110_MDIOACC register, and
then poll the MDIO_TRDONE bit (for a 1) in the same register. The
device will set this bit to 1 once the internal MDIO transaction is
done. In practice, this bit takes ~50 - 60 us to be set.
The first attempt to poll the bit is right after the ADIN1110_MDIOACC
register is written, so it will always be read as 0. The next check will
only be done after 10 ms, which will result in the MDIO transactions
taking a long time to complete. Reduce this polling interval to 100 us.
Since this interval is short enough, switch the poll function to
readx_poll_timeout_atomic() instead.
> adin1110: Reduce the MDIO_TRDONE poll interval

- drivers/pwm/pwm-axi-pwmgen.c
Commit 25afd8b31027 ("drivers: pwm: pwm-axi-pwmgen: Add support for 16 channels") modified the driver to use the new AXI PWMGEN v2 HDL and dropped support for v1. However there are still users of the old v1 HDL, so we need to restore support for it.
This adds a runtime check for the HDL version and uses the appropriate register offsets based on the version so that the driver will work for both versions.
cc: @Skallwar, @threexc
> pwm: axi-pwmgen: restore support for v1 HDL

- drivers/iio/adc/cf_axi_adc_core.c
The 'label' attribute gives an error polluting the iio_info output.
> iio:adc:ad7768: Fix the ad7768 label attribute

- .github/CODEOWNERS
- .github/PULL_REQUEST_TEMPLATE.md
Persons specified in **CODEOWNERS** will be automatically added as reviewers, whenever new PRs are opened. 
In addition to Code Owners, other reviewers can be added. CODEOWNERS file can be different from one branch to another.
All new PRs will require the approval of at least one code owner.
**PULL_REQUEST_TEMPLATE.md** will populate all new PR description field. Beside PR description, it contains a list of checkboxes, ensuring all team members follow the same guidelines and enforce best practices. PR Template applies for PRs against all protected branches.
Both files were added in .github
> Add CODEOWNERS and PULL_REQUEST_TEMPLATE

- arch/arm/boot/dts/overlays/Makefile
- arch/arm/boot/dts/overlays/rpi-adl5580-overlay.dts
The ADL5580 is a high performance, single-ended or differential amplifier with 10 dB of voltage gain, optimized for applications spanning from dc to 10.0 GHz. The amplifier offers a low referred to input (RTI) noise spectral density (NSD) and is optimized for distortion performance over a wide frequency range, making the device an ideal driver for high speed 12-bit to 16-bit analog-to-digital converters (ADCs).
The SPI of the ADL5580 allows the user to configure the device for specific functions or operations via a 3-wire SPI port. It includes enable blocks, the bias current level, transfer function peaking, change input and output termination block operation modes, and change input and output V CM termination for certain operation modes.
> dts: overlay: adl5580: Fully Differential, 10 GHz ADC Driver 10 dB Gain

- drivers/iio/adc/navassa/adrv9002.c
For TX ports, if dpd is not set, we will continue the loop and possibly skipping the delays. Fix it with a new dpd helper for better control flow.
Fixes: 7855cc7bbafca ("iio: adrv9002: support mcs delays settings")
> iio: adc: adrv9002: Fix setting MCS delays

- Documentation/devicetree/bindings/iio/amplifiers/adi,hmc425a.yaml
- drivers/iio/amplifiers/hmc425a.c
This pull request syncs the HMC425a driver and bindings with upstream changes:
- Add ADRF5730 support
- Add LTC6373 support
> Sync HMC425a driver with upstream

- drivers/iio/adc/ad9081.c
Temporarily disable ADC data inversion option for AD9082, since this option my have negative side effects.
Needs further investigation.
> iio: adc: ad9081: Disable ADC data inversion option for AD9082

- arch/arm/boot/dts/overlays/adis16475-overlay.dts
Add parameters for sync mode configuration: sync_mode to select the desired sync mode and ext_sync_freq to select the external sync frequency (needed for direct mode and scaled sync mode).
> dts: overlays: adis16475: Add parameters for sync mode configuration

- drivers/iio/imu/adis16475.c
Fix sync mode setting by applying the necessary shift bits.
Fixes: fff7352bf7a3 ("iio: imu: Add support for adis16475")
Reviewed-by: Nuno Sa <nuno.sa@analog.com>
Link: https://lore.kernel.org/r/20240405045309.816328-2-ramona.bolboaca13@gmail.com
Cc: <Stable@vger.kernel.org>
> iio:imu: adis16475: Fix sync mode setting

- arch/arm64/boot/dts/xilinx/zynqmp-jupiter-sdr.dts
The fan_en has been set high from the hdl and
the gpio is no longer used for that. 
https://github.com/analogdevicesinc/hdl/blob/main/projects/jupiter_sdr/system_top.v#L202
> dts: zynqmp-jupiter-sdr: remove fan_en gpio

- arch/arm/boot/dts/zynq-zed-adv7511-ad4630-24.dts
- arch/arm/boot/dts/zynq-zed-adv7511-adaq4224-24.dts
- arch/arm/boot/dts/zynq-zed-adv7511-adaq4224-24_cm0_sdi4_cz2.dts
- drivers/iio/adc/ad4630.c
ADI engineers have reported a hardware bug when using average mode zero (no averaging) with AD4630 devices and requested to disallow using that average mode. 
This PR contains a commit to remove average mode zero from the list of available average modes and make average mode one (average over 2 samples) the default average mode on device startup.
This PR also includes a fix from @nunojsa which testers said to be needed as well.
> Ad4630 remove avg 0

- arch/arm64/boot/dts/xilinx/zynqmp-zcu102-rev10-ad9082-m1-l8.dts
- drivers/iio/adc/ad9081.c
iio: adc: ad9081: Add support for JESD204 M=1 (single ADC/DAC)
iio: adc: ad9081: In full bandwidth/bypass mode use unmodified channels
dts: zynqmp-zcu102-rev10-ad9082-m1-l8: New M=1 full BW use case example
> AD9081/82 Support for M=1 with dts example 

- arch/arm/boot/dts/zynq-zed-adv7511-ad4630-24.dts
- arch/arm/boot/dts/zynq-zed-adv7511-adaq4224-24.dts
Default build of HDL uses NUM_SDI=4 this means 2 lanes per channel, accordingly the adi,lane-mode should be 1
> arch: arm: boot: dts: Align dts lane-mode with default build of HDL

- arch/arm/boot/dts/adi-intel-dac-fmc-ebz.dtsi
- arch/arm/boot/dts/socfpga_arria10_socdk_ad9081.dts
- arch/arm/boot/dts/socfpga_arria10_socdk_ad9083_fmc_ebz.dts
- arch/arm/boot/dts/socfpga_arria10_socdk_adrv9002.dts
- arch/arm/boot/dts/socfpga_arria10_socdk_adrv9002_rx2tx2.dts
- arch/arm/boot/dts/socfpga_arria10_socdk_adrv9009.dts
- arch/arm/boot/dts/socfpga_arria10_socdk_adrv9371.dts
- arch/arm/boot/dts/socfpga_arria10_socdk_daq2.dts
- arch/arm/boot/dts/socfpga_arria10_socdk_fmclidar1.dts
- arch/arm/boot/dts/socfpga_arria10_socdk_fmcomms8.dts
Add sys_id node in Arria10 devicetrees since it is already present in HDL projects.
Most of the touched DTSes got tested, and now the sysid looks as expected in dmesg (until now grep command was not finding anything):
`dmesg | grep sysid`
```
axi_sysid ff218000.axi-sysid-000018000: AXI System ID core version (1.01.a) found
axi_sysid ff218000.axi-sysid-000018000: [ad9081_fmca_ebz] on [a10soc]git branch <next_stable> git <606551b4785c676a3e78dab247641e569cba78f2> clean [2024-04-29 16:32:45] UTC
```
> arch/arm/boot/dts/arria10: Add sysid in DTSes

- drivers/iio/dac/ad3552r.c
Fix ad3552r (and ad3542r) product id.
Fix ad3552r (and ad3542r) product id.
- [ x] I have conducted a self-review of my own code changes
- [ x] I have tested the changes on the relevant hardware
> iio:dac:ad3552r: fix product id

- arch/arm/boot/dts/zynq-zed-adv7511-adaq4224-24.dts
To have the name of temperature sensor as adaq4224-temp and not max31827
added the label attribute in dts.
> arch: arm: boot: dts: Add label attribute for ADAQ4224

- drivers/iio/frequency/adrf6780.c
The driver has no clock provider implementation, therefore remove the include.
Link: https://lore.kernel.org/lkml/20240530092835.36892-1-antoniu.miclaus@analog.com/
Fixes: https://github.com/analogdevicesinc/linux/commit/63aaf6d06d87866dd6b58265711a979ed4968420 ("iio: frequency: adrf6780: add support for ADRF6780")
> iio: frequency: adrf6780: rm clk provider include

- drivers/iio/frequency/adf4371.c
Currently the muxout_en attribute does not set the correct bit in the 0x20 register of adf4371.
This makes the muxout feature not being available for usage.
Use the appropriate mask for the MUXOUT_EN bit which is BIT(3) according to the datasheet.
Fixes: df88660ee30f6 ("iio: frequency: adf4371: Support for RFAUX8 VCO output mux")
> iio: frequency: adf4371: fix muxout enable

- drivers/iio/adc/navassa/adrv9002.c
- drivers/iio/adc/navassa/adrv9002.h
- drivers/iio/adc/navassa/adrv9002_conv.c
Before, we either have the TX SSI clock driven by the RX clock of the same channel (eg: TX1 driven by RX1) or TX driven by it's own clock. Now, with the current HW/HDL changes TX clock is fully configurable. This means, each TX can be driven by:
* Own clock;
* RX1 clock;
* RX2 clock.
The first two patches are just some code cleanup...
> [adrv9002] Fully configurable TX clock 

- drivers/iio/frequency/adf4371.c
Currently the muxout_en attribute does not set the correct bit in the 0x20 register of adf4371.
This makes the muxout feature not being available for usage.
Use the appropriate mask for the MUXOUT_EN bit which is BIT(3) according to the datasheet.
Fixes: df88660ee30f ("iio: frequency: adf4371: Support for RFAUX8 VCO output mux")
> iio: frequency: adf4371: fix muxout enable (2022_r2)

- drivers/char/axi-intr-monitor.c
- drivers/iio/adc/Kconfig
- drivers/iio/adc/Makefile
- drivers/iio/adc/ltc2358.c
- drivers/iio/adc/madura/adrv9025.c
- drivers/iio/beamformer/adar300x.c
- drivers/iio/dac/ad5686.c
- drivers/iio/frequency/Makefile
- drivers/iio/frequency/m2k-dac.c
- drivers/iio/jesd204/Makefile
- drivers/iio/jesd204/axi_jesd204_rx.c
- drivers/iio/jesd204/axi_jesd204_tx.c
- drivers/iio/multiplexer/Kconfig
- drivers/jesd204/jesd204-core.c
- include/linux/jesd204/jesd204.h
This is a first (and hopefully the only one) round of fixes to make sure we can compile our drivers as modules. Two exceptions though:
1. ad9361 makes use of non exported OF function and to change the driver to not using that function is non trivial. Since we lived this far without needing the driver as a module, let's go the easy path and just don't allow that driver to be compiled as a module.
2. Same story for the iio-gen-mux driver which uses a non exported function from CCF.
And also exporting the functions is also far from ideal as the two drivers are likely to never be upstreamed which means that we could not really upstream the patches exporting those functions.
This was just compile tested with:
```
make zynq_xcomm_adv7511_defconfig
make yes2modconfig
```
I need to see for zynqmp …
> Fix module compilation

- drivers/iio/adc/ad9361.c
The author used FORCE_VCO_TUNE instead of FORCE_VCO_TUNE_ENABLE.
FORCE_VCO_TUNE is the 8th (MSB) of the VCO capacitor tune word. FORCE_VCO_TUNE_ENABLE is the bit that forces or not the usage of the VCO capacitor tune word.
> ad9361: fix FORCE_VCO_TUNE_ENABLE typo

- drivers/iio/frequency/ltc6952.c
* On POR all channels are fully enabled. This patch keeps those disabled which are not represented by a node in the device-tree.
* We also clear the POR reset bit, which might not be necessary but looks cleaner.
* We also fix LTC6952_PD(x) mask which wasn't doing anything until now.
> iio: frequency: ltc6952: keep unused channels disabled

- Documentation/devicetree/bindings/iio/adc/adi,ad7173.yaml
- drivers/base/property.c
- drivers/iio/adc/Kconfig
- drivers/iio/adc/Makefile
- drivers/iio/adc/ad7173.c
- drivers/iio/adc/ad_sigma_delta.c
- include/linux/array_size.h
- include/linux/iio/adc/ad_sigma_delta.h
- include/linux/kernel.h
- include/linux/property.h
- include/linux/string.h
This pull request syncs the AD7173 driver and bindings with upstream changes
Included backports:
- kernel.h: Move ARRAY_SIZE() to a separate header
- device property: Introduce device_for_each_child_node_scoped()
- device property: Add cleanup.h based fwnode_handle_put() scope based cleanup.
- device property: Move fwnode_handle_put() into property.h
Jonathan Cameron series that adds scoped fwnode handling support
> Sync AD7173 driver with upstream

- Documentation/devicetree/bindings/iio/frequency/adi,adf4350.yaml
- drivers/iio/frequency/adf4350.c
Add clk provider feature for the adf4350.
Even though the driver was sent as an IIO driver in most cases the
device is actually seen as a clock provider.
This patch aims to cover actual usecases requested by users in order to
completely control the output frequencies from userspace.
> iio: frequency: adf4350: add clk provider

- arch/arm64/boot/dts/xilinx/versal-vck190-reva-ad9081.dts
- drivers/iio/jesd204/axi_jesd204.h
- drivers/iio/jesd204/axi_jesd204_rx.c
- drivers/iio/jesd204/axi_jesd204_tx.c
When using the ADXVR IP, the driver handles the GT resets.
However, for AMD/Versal we currently use the Xilinx PHY IP directly.
In this case the RESETs are provided as GPIOs.
And we issue PLL and Datapath resets at the proper  jesd204-fsm states.
This patch depends on corresponding HDL changes.
> Fix: JESD204 AMD/Versal GT reset handling 

- arch/microblaze/boot/dts/vcu118_ad9081_204c_txmode_24_rxmode_26_lr_24_75Gbps.dts
This PR updates the JESD204C Tx and Rx modes, as well as the reg value for the Tx channelizer nodes 2, 3. The label for all 4 of them is also updated.
**The first issue**, is that the Rx and Tx JESD204C modes in the device tree were wrongly set (to 23 & 25, and not 24 & 26 as the name states). Even though the parameters (L, M, etc.) are correctly set, it would use the values given by the mode, causing it to use half of the lanes.
JESD204C Rx mode 26.00 defined now in dts _(and in italic, values for mode 25.00 which was previously set)_:
L = 8 _(4)_, M = 8 _(4)_, F = 3, S = 2, K = 256, E = 3, N = 12, NP = 12, HD = 0
Total DCM (Coarse x Fine) = 2x1 (extracted from dts)
JESD204C Tx mode 24 defined now in dts _(and in italic, values for mode 23 which was previously set)_:
L = 8 _(4)_, M = 8 …
> vcu118_ad9081_204c_txmode_24_rxmode_26_lr_24_75Gbps.dts: Bug fix

- arch/arm/boot/dts/zynq-zed-adv7511-ad9434-fmc-500ebz.dts
Set the frequency to 463.82MHz because on Zedboard, there is a limitation for BUFG input clock frequency to 464MHz, which is below the maximum sampling rate of the ADC (500MSPS).
> arch: arm: boot: dts: ad9434/zed: Fix clock frequency

- Documentation/devicetree/bindings/iio/adc/adi,pulsar.yaml
- drivers/iio/adc/ad_pulsar.c
I received email reporting people were asking about support for AD7683.
It clearly belongs to the PulSAR series of ADCs so adding to that driver.
Also adding AD7684 and AD7694 which were also not there.
This is one example of stuff that didn't go upstream.
Looking back at it now, I think this ad_pulsar driver can be improved (maybe split into a driver for single channel ADCs and another for multiple channel ADCs) and upstreamed with some work.
For now, I'm just sort of taking note this should also support AD7683, AD7684, and AD7694.
> Add code to probe AD7683, AD7684 and AD7694

- arch/arm/boot/dts/zynq-coraz7s-ad7687-pmdz.dts
- arch/arm/boot/dts/zynq-coraz7s-ad7689-ardz.dts
- arch/arm/boot/dts/zynq-coraz7s-ad7946.dts
- arch/arm/boot/dts/zynq-coraz7s-ad7984.dts
- arch/arm/boot/dts/zynq-coraz7s-adaq4003.dts
- arch/arm/boot/dts/zynq-zed-adv7511-ad4020.dts
- arch/arm/boot/dts/zynq-zed-adv7511-ad7944.dts
- arch/arm/boot/dts/zynq-zed-adv7511-ad7985.dts
- arch/arm/boot/dts/zynq-zed-adv7511-ad7986.dts
The HDL support for the AD4000 series and PulSAR series of ADCs was once provided by the **ad40xx_fmc** and **pulsar_adc_pmdz** HDL projects. Those are now integrated into a single HDL project called **pulsar_adc** [1]. Update device tree references to the new project name and point to the new project location.
[1]: https://github.com/analogdevicesinc/hdl/commit/b2dc91b30dae891b6319d88e083f26e726f43ba0
This is expected to help the team taking care of Kuiper releases get compatible HDLs for dts files.
any space), or simply check them after publishing the …
> arm: dts: Update PulSAR HDL project references

- arch/arm/boot/dts/overlays/Makefile
- arch/arm/boot/dts/overlays/rpi-hmc425a-overlay.dts
Add device tree overlay for hmc425a.
> arch: arm: dts: overlays: Add hmc425a overlay

- Documentation/ABI/testing/sysfs-bus-iio-filter-admv8818
Fix description of the filter_mode_available attribute by pointing to the correct name of the attribute that can be written with valid values.
Link: https://lore.kernel.org/lkml/20240702081851.4663-1-antoniu.miclaus@analog.com/
Fixes: bf92d87 ("iio:filter:admv8818: Add sysfs ABI documentation")
> ABI: testing: fix admv8818 attr description

- drivers/iio/adc/ad400x.c
While looking at the ad400x driver to try to find out why/if sub-nanosecond precision for the pwm subsystem is necessary, I noticed these improvements.
- [?] Bug fix (a change that fixes an issue)
- [-] New feature (a change that adds new functionality)
- [-] Breaking change (a change that affects other repos or cause CIs to fail)
- [-] I have tested the changes on the relevant hardware
- [-] I have updated the documentation outside this repo accordingly (if there is the case)
> Improve precision for ad400x iio driver

- Documentation/driver-api/driver-model/devres.rst
- drivers/spi/spi-axi-spi-engine-ex.c
- drivers/spi/spi-mux.c
- drivers/spi/spi.c
- include/linux/spi/spi.h
This backports upstream AXI SPI Engine-related changes from the 6.10 and 6.11 kernels.
> spi 6.11 backports

- drivers/iio/adc/adm1177.c
This fixes:
In file included from include/linux/device/driver.h:21,
from include/linux/device.h:32,
from drivers/iio/adc/adm1177.c:9:
drivers/iio/adc/adm1177.c:222:25: error: ‘nau7802_dt_ids’ undeclared here (not in a function)
222 | MODULE_DEVICE_TABLE(of, nau7802_dt_ids);
|                         ^~~~~~~~~~~~~~
include/linux/module.h:243:15: note: in definition of macro ‘MODULE_DEVICE_TABLE’
243 | extern typeof(name) __mod_##type##__##name##_device_table               \
|               ^~~~
include/linux/module.h:243:21: error: ‘__mod_of__nau7802_dt_ids_device_table’ aliased to undefined symbol ‘nau7802_dt_ids’
243 | extern typeof(name) __mod_##type##__##name##_device_table               \
|                     ^~~~~~
drivers/iio/adc/adm1177.c:222:1: note: in expansion of macro …
> iio: adc: adm1177: Fix compilation with CONFIG_ADM1177=m

- arch/arm64/boot/dts/xilinx/zynqmp-adrv9009-zu11eg-reva.dtsi
ADM1177 switch to HWMON device
Since the IIO version is no longer build into the kernel.
> dts/xilinx/zynqmp-adrv9009-zu11eg-reva: ADM1177 switch to HWMON device

- arch/arm/boot/dts/zynq-coraz7s-ad7687-pmdz.dts
- arch/arm/boot/dts/zynq-coraz7s-ad7689-ardz.dts
- arch/arm/boot/dts/zynq-coraz7s-ad7946.dts
- arch/arm/boot/dts/zynq-coraz7s-ad7984.dts
- arch/arm/boot/dts/zynq-coraz7s-adaq4003.dts
- arch/arm/boot/dts/zynq-zed-adv7511-ad4020.dts
- arch/arm/boot/dts/zynq-zed-adv7511-ad7944.dts
- arch/arm/boot/dts/zynq-zed-adv7511-ad7985.dts
- arch/arm/boot/dts/zynq-zed-adv7511-ad7986.dts
In CI scripts, the DTS and HDL project pairs are identified by the hdl_project tags and those should point to the exact subproject directory of HDL build.
Update hdl_project tags to point to exact subproject directories.
Fixes: 24b683f0bffa ("arm: dts: Update PulSAR HDL project references")
> Specify PulSAR HDL subproject directories

- arch/arm64/boot/dts/xilinx/zynqmp-adrv9009-zu11eg-revb-adrv2crr-fmc-revb-jesd204-fsm-xmicrowave.dts
The HDL support for adrv9009zu11eg/adrv2crr_xmicrowave has merged with another project, adrv9009zu11eg/adrv2crr_fmcxmwbr1 [1]. Update device tree references to point to the correct HDL project and update HDL synthesis parameters for adrv2crr_xmicrowave.
[1]: https://github.com/analogdevicesinc/hdl/commit/4b8f3f0
> arm64: dts: Update xmicrowave HDL project tag

- Documentation/ABI/testing/sysfs-bus-iio
- Documentation/ABI/testing/sysfs-bus-iio-dac
- Documentation/ABI/testing/sysfs-bus-iio-dac-ltc2688
- Documentation/devicetree/bindings/iio/dac/adi,ltc2664.yaml
- Documentation/devicetree/bindings/iio/dac/adi,ltc2672.yaml
- Documentation/devicetree/bindings/iio/dac/dac.yaml
- MAINTAINERS
- drivers/iio/Kconfig.adi
- drivers/iio/dac/Kconfig
- drivers/iio/dac/Makefile
- drivers/iio/dac/ltc2664.c
LTC2664 4 channel, 16 bit Voltage Output SoftSpan DAC
LTC2672 5 channel, 16 bit Current Output Softspan DAC
since ltc2664 and ltc2672 have the same registers/softspan, thus leveraging the use of this PR https://github.com/analogdevicesinc/linux/pull/2408 and there's plenty of shared codes
i'll plan to utilize also the automatic cleanup for mutex but my current kernel used does not yet support that
> add ltc2672 and ltc2664

- arch/arm/boot/dts/overlays/rpi-ltc2664-overlay.dts
Update overlay to align with mainline kernel changes. Adding configurations for the v-pos and v-neg supply regulators. Modify output-range-microvolt based on generalized property name.
> overlays: rpi-ltc2664-overlay.dts: Update LTC2664 example overlay

- arch/arm/boot/dts/overlays/Makefile
- arch/arm/boot/dts/overlays/rpi-ltc2672-overlay.dts
The LTC2672 is a 5-channel, 12-/16-bit DAC offering high compliance current source outputs up to 300 mA per channel, with programmable current ranges. Channels can be combined for up to 1.5 A output. It operates between 2.1 V to VCC, supports optional negative supply, and includes a precision 1.25 V reference. The device features a low-voltage, high-speed SPI interface.
> overlays: rpi-ltc2672-overlay.dts: Add LTC2672 example overlay

- arch/arm64/boot/dts/xilinx/versal-vck190-reva-ad9209.dts
Adds a default device tree for the AD9209 + VCK190 project.
JESD204C mode 27: L=8, M=4, S=4, F=3, NP=12
Lane Rate: 24.75 GSPS
> arch:arm64:boot:dts:xilinx: Added default AD9209 dts for VCK190

- arch/microblaze/boot/dts/vcu118_ad9082.dts
Adds a devicetree for AD9082 + VCU118 for the default JESD mode. The hdl/driver is the same as AD9081 so the only change needed was the adi,compatible string.
> microblaze: dts: vcu118_ad9082: Added default use case

- drivers/iio/adc/ad7124.c
- include/linux/stddef.h
- include/uapi/linux/stddef.h
- scripts/kernel-doc
This pull request is copied from the one on main to ensure that 2022_R2 and rpi-5.15 also receive the fixes.
This pull request fixes two issues regarding the ad7124 driver:
-properly compare config values
-add a delay after reset to allow chip initialization
Backport "stddef: Introduce struct_group() helper macro" was needed for using struct_group()
--This pull request will be updated to include some backports from main as well, do not close--
> ad7124 fixes for 2022 r2

- drivers/iio/adc/ad7124.c
The DT parsing for ad7124 assigns configurations for a certain channel to the next one.
This PR fixes this issue.
> 2022_R2 (iio: adc: ad7124: fix DT configuration parsing)

- drivers/iio/adc/ad7124.c
The DT parsing for ad7124 assigns configurations for a certain channel to the next one.
This PR fixes this issue.
> main: (iio: adc: ad7124: fix DT configuration parsing)

- drivers/iio/adc/ad7124.c
The DT parsing for ad7124 assigns configurations for a certain channel to the next one.
This PR fixes this issue.
> next_stable: (iio: adc: ad7124: fix DT configuration parsing)

- arch/arm/boot/dts/socfpga_arria10_socdk_adrv9025.dts
When booting the system with sysref in N-Shot mode there are always about 9 to 12 errors on the lanes while Continuous sysref gives 0 errors. Those errors don't seem to affect functionality. Both modes work fine in hardware, but continuous gives a cleaner jesd_status.
> dts/socfpga_arria10_socdk_adrv9025.dts: Change sysref mode to continuous

- arch/arm64/boot/dts/xilinx/versal-vpk180-reva-ad9082-m1-l8.dts
- arch/arm64/boot/dts/xilinx/versal-vpk180-reva-ad9082.dts
Adds a devicetree for the default VPK180 + AD9082 configuration.
Also changes some AD9081 references from the previous devicetrees.
> [next_stable]: VPK180: AD9082 minor fixes and a default devicetree

- arch/arm64/boot/dts/xilinx/versal-vpk180-reva-ad9082-m1-l8.dts
- arch/arm64/boot/dts/xilinx/versal-vpk180-reva-ad9082.dts
Adds a devicetree for the default VPK180 + AD9082 configuration.
Also changes some AD9081 references from the previous devicetrees.
> VPK180: AD9082 minor fixes and a default devicetree

- drivers/iio/adc/ad_sigma_delta.c
Buffered mode using ad_sigma_delta is not functional as the IRQ is not enabled in the postenable callback for devices that are not using spi_engine (INDIO_BUFFER_HARDWARE mode).
Comparing to the 2022_R2 version, it seems that the condition should have been negated.
Fix by checking inequality instead of equality to INDIO_BUFFER_HARDWARE.
Fixes: 27b588fc154f ("Merge tag 'xilinx-v2023.1' of https://github.com/Xilinx/linux-xlnx.git")
> [main] iio: adc: ad_sigma_delta: fix buffered mode irq

- drivers/iio/adc/ad_sigma_delta.c
Buffered mode using ad_sigma_delta is not functional as the IRQ is not enabled in the postenable callback for devices that are not using spi_engine (INDIO_BUFFER_HARDWARE mode).
Comparing to the 2022_R2 version, it seems that the condition should have been negated.
Fix by checking inequality instead of equality to INDIO_BUFFER_HARDWARE.
Fixes: 27b588fc154f ("Merge tag 'xilinx-v2023.1' of https://github.com/Xilinx/linux-xlnx.git")
> [nextstable] iio: adc: ad_sigma_delta: fix buffered mode irq

- arch/arm/boot/dts/adi-zynq-cn0363.dtsi
- drivers/iio/adc/ad7173.c
This PR fixes issues in regards to the ad7173 driver and it's usage for cn0363.
- update dt ad7175 instance to match with the current driver parsing
- backport a fix from upstream
> [main] ad7173 fixes

- arch/arm/boot/dts/adi-zynq-cn0363.dtsi
- drivers/iio/adc/ad7173.c
This PR fixes issues in regards to the ad7173 driver and it's usage for cn0363.
- update dt ad7175 instance to match with the current driver parsing
- backport a fix from upstream
> [nextstable] ad7173 fixes

- arch/arm/boot/dts/zynq-zed-adv7511-ad4630-24.dts
- drivers/iio/adc/ad4630.c
The main goal of the pull is to remove the ad463x compatible as it's not needed anymore. Some other small improvements were done while at it.
> AD4630 remove hacky compatible

- arch/arm/boot/dts/zynq-coraz7s-adaq4003.dts
- arch/arm/boot/dts/zynq-zed-adv7511-ad4003.dts
- arch/arm/boot/dts/zynq-zed-adv7511-ad4020.dts
- arch/arm/boot/dts/zynq-zed-adv7511-adaq4003.dts
- drivers/iio/adc/ad400x.c
Adds code to account for ADAQ devices' hardware gain to provide the correct scale for those devices.
This is a bit old (even compared to upstream ad4000.c) but proposing to merge it because otherwise, the scale attribute will not provide correct values for ADAQ devices. Hopefully, when ad4000 gets accepted upstream and fully supports spi-engine offload we will be able to drop ad400x.c entirely in favor of ad4000.c.
> ad400x: Add support for ADAQ hardware gain

- arch/arm/boot/dts/zynq-zed-adv7511-ad4030-24.dts
- arch/arm/boot/dts/zynq-zed-adv7511-ad4032-24.dts
- arch/arm/boot/dts/zynq-zed-adv7511-ad4630-16.dts
- arch/arm/boot/dts/zynq-zed-adv7511-adaq4216.dts
- arch/arm/boot/dts/zynq-zed-adv7511-adaq4220.dts
- drivers/iio/adc/ad4630.c
This PR contains the changes made during the latest tests done with ADAQ4216, ADAQ4220 and similar devices.
Summary of changes:
- Add dts files for using AD4030-24, AD4032-24, AD4630-16, ADAQ4216, and ADAQ4220 on ZedBoard.
- Fix sample read bug by adjusting the fetch trigger PWM phase.
- Add output mode to properly support ADAQ4216 and ADAQ4220
- Set max sampling frequency set to 2MSPS.
- Add a couple of probe error messages to help diagnose when device probe fails.
> Add dts files and fixes for AD4030-24, AD4032-24, AD4630-16, ADAQ4216 and ADAQ4220

- drivers/iio/adc/ad4630.c
BU reported the sampling frequency shown by AD4630-like devices was 1000 times higher than the actual one.
This was confirmed by @ladace and me and this patch fixes the issue.
The ad4630 driver calculated the inverse of the PWM period in pico seconds to report the sampling frequency provided by the device. However, that lead to a sampling frequency 1000 higher than the actual one since the PWM period is actually in the nano seconds. Use NANO instead of PICO to correctly calculate the sampling frequency in Hz.
> Fix AD4630 sampling frequency display

- arch/arm64/boot/dts/xilinx/zynqmp-jupiter-sdr.dts
In jupiter we have a gpio to toggle between a 38.4 and 30.72MHz reference clock. We had a gpio-hog to default to the 38.4MHz source and then we need to manually change the GPIO value when applying a profile for the other reference. This is far from ideal and more importantly, with commit c2edc6279f31 (" iio: adc: adrv9002: check and allow to change ref_clk"), we now try to change the refclk according with the rate we get from the profile (which makes sense). Therefore, with the current DT, we would fail to load the 30.72MHz reference clock based profile. Hence, let's make use of the clk-gpio driver and define our reference clock to be a clk-gpio mux with two parents for the rates we want. With this, we can change clock sources solely by loading the profile without any other manual step …
> arm64: dts: zynqmp-jupiter-sdr: properly use clk-gpio mux

- drivers/iio/frequency/m2k-dac.c
This PR adds two backports from main for the m2k FW release and adds support for the auto trigger rearm HDL feature.
> [2022_R2]dev/m2k_dac

- drivers/iio/frequency/m2k-dac.c
The IIO_ENUM_AVAILABLE() macro only has three arguments upstream (and in the main branch). As 2022_R2 is still based on 5.15, we still need the IIO_ENUM_AVAILABLE_SHARED() out of tree macro.
Fixes: c74f9d760c2e ("iio: frequency: m2k-dac: Improve trigger attributes")
Also Fixes #2607
> iio: frequency: m2k-dac: fix backport of trigger status

- drivers/iio/frequency/ad9783.c
Run loop in accordance with the method described in section "building the array" of the datasheet[1] rev C. page 26. The loop shall be continued until the seek bit toggles, not until the seek bit goes low.
For the case where a value for SET or HLD is not found that would make the SEEK bit toggle, the value should be set to 15. The loop did not break out until HLD == 16, causing overflowing value to be written to the HLD field[0..3] of register 0x4.
[1] https://www.analog.com/media/en/technical-documentation/data-sheets/AD9780_9781_9783.pdf
> iio: frequency: ad9783: fix calibration array values

- drivers/misc/adi-axi-tdd.c
Fixed the computed values in [ms] for the following TDDN registers: STARTUP_DELAY, FRAME_LENGTH, SYNC_PERIOD (renamed from SYNC_COUNTER in the hdl documentation).
> drivers: misc: adi-axi-tdd: Fix reg values in ms

- arch/arm/boot/dts/zynq-coraz7s-ad7687-pmdz.dts
- arch/arm/boot/dts/zynq-coraz7s-ad7984.dts
- drivers/iio/adc/ad_pulsar.c
Some Pulsar ADCs are not presumed to have a fixed voltage to their negative input (IN-).
When the channel is bipolar and the output code is two's complement, one of the precision bits accounts for the sign and we end up with one less bit to express voltage magnitude. The channel scale attribute has to take that into account to provide a proper conversion factor to mV.
Update ad_pulsar driver to provide proper scale for unipolar and bipolar channels. Update dts to set the bipolar property for ADC channels when IN- is not specified to any restricted voltage level.
`grep -nriI arch/arm/boot/dts/ -e "pulsar,ad"` shows we currently have 4 dts for "pulsar,ad" compatibles.
AD7687 has true differential analog input range and IN- is assumed to float from 0V to VREF. That is better modeled as a …
> Fix scale attribute for PulSAR bipolar channels

- drivers/iio/frequency/adf4371.c
When returning early from a device_for_each_child_node() loop, we need to call fwnode_handle_put() on the child node so it does not leak. For that make use of device_for_each_child_node_scoped() which will automatically drop the node reference as soon as go out of the loop scope.
Fixes: c8e6b341abf7 ("iio: frequency: adf4371: Introduce channel child nodes")
> iio: frequency: adf4371: fix possible leak

- arch/arm/boot/dts/overlays/rpi-ad7124-8-all-diff-overlay.dts
Simplify the syntax for the `rpi-ad7124-8-all-diff` overlay. While the resulting dtbo has a different binary representation, it's semantically equivalent. The source file just has less boilerplate. This also includes a simple commit that uses a symbolic name instead of a hardcoded number.
This is compilable with dtc v1.4.6 (since commit https://github.com/dgibson/dtc/commit/c1e55a5513e9bca41dc78a0f20245cc928596a3a from 2017).
If this PR is liked in general, I can follow up with a similar conversion of the other device trees.
> Use simpler syntax for dt overlays

- drivers/clk/adi/clk-ad9545-i2c.c
- drivers/clk/adi/clk-ad9545-spi.c
IIO is not needed at all for the ad9545 device (it's a clock provider). Remove it.
While at it, added mod_devicetable.h for the id tables and placed clk-ad9545.h in it's proper location.
> clk: adi: clk-ad9545: remove iio from includes

- drivers/iio/adc/ltc2387.c
The normal behaviour for PWM drivers in upstream is to round down the duty cycle value (FTR: also period and duty offset). The pwm-axipwmgen driver implements that behaviour since commit
ea331335bc2b ("pwm: Replace axi-pwmgen driver by a backport of the mainline driver")
That means that if
.duty_cycle = DIV_ROUND_CLOSEST(NSEC_PER_SEC, ltc->ref_clk_rate)
is requested and that division happens to round down, the duty cycle programmed will be zero and the PWM won't toggle at all.
So use up-rounding for the duty_cycle value.
> iio: adc: ltc2387: Fix for PWM driver rounding down duty cycle

- arch/arm64/boot/dts/xilinx/zynqmp-zcu102-rev10-stingray.dts
To achieve synchronized TX signals, configure the TX DO in one-shot mode. 
For capturing a large buffer of data on the RX side, the DO has to be bypassed.
> arch/arm64/boot/dts/xilinx/stingray: Change DO modes

- drivers/iio/industrialio-buffer.c
- include/linux/iio/iio.h
It looks like one of the commits from #2433 wasn't the actual upstream commit. This reverts the wrong patch and cherry-picks the correct one.
Cc: @ahaslam2,  @RaduSabau1
> fix recent backports from #2433

- Documentation/devicetree/bindings/iio/dac/adi,ad8460.yaml
- MAINTAINERS
- arch/arm/boot/dts/zynq-zed-adv7511-ad8460.dts
- drivers/iio/Kconfig.adi
- drivers/iio/dac/Kconfig
- drivers/iio/dac/Makefile
- drivers/iio/dac/ad8460.c
This adds device tree bindings compatible strings, driver support and ZedBoard device trees for AD8460 High Voltage, High Current Arbitrary Waveform Generator DAC.
For more information:
[Arbitrary Waveform Generator with Integrated 14-Bit High Speed DAC](https://www.analog.com/media/en/technical-documentation/data-sheets/ad8460.pdf
)
This has been tested on the ZedBoard which controls the EVAL-AD8460SDZ evaluation board
> Add support for AD8460

- drivers/iio/accel/adxl380.c
The adxl380_read_chn function returns either a negative value in case an error occurs or the actual sample.
Check only for negative values after a channel is read.
Link: https://lore.kernel.org/lkml/20241101095202.20121-1-antoniu.miclaus@analog.com/
Fixes: 2535e0ec3546 ("iio: accel: add ADXL380 driver")
> iio: accel: adxl380: fix raw sample read

- drivers/iio/accel/adxl380.c
The adxl380_read_chn function returns either a negative value in case an error occurs or the actual sample.
Check only for negative values after a channel is read.
Link: https://lore.kernel.org/lkml/20241101095202.20121-1-antoniu.miclaus@analog.com/
Fixes: 2535e0ec3546 ("iio: accel: add ADXL380 driver")
> [next_stable] iio: accel: adxl380: fix raw sample read

- drivers/iio/adc/ad7768.c
ad7768_scale() is dependent on st->vref.
Fixes: 92cc452e8f13 ("iio: adc: ad7768: simplify probe")
> iio: adc: ad7768: Fix scale reading

- arch/arm64/boot/dts/xilinx/adi-ad9164-fmc-ebz.dtsi
- arch/arm64/boot/dts/xilinx/zynqmp-zcu102-rev10-ad9164-fmc-ebz_m2_s2.dts
The device trees were added for the EVAL-AD9164 board on the ZCU102.
JESD Link Mode 8 Example: M2, L8, S2, F1, NP'16, Interpolation: 2 : [zynqmp-zcu102-rev10-ad9164-fmc-ebz_m2_s2.dts](https://github.com/analogdevicesinc/linux/compare/main...ad9164_zcu102_dts#diff-fec5122f173d7b2d224ba67a75a98c04e214875e7fe4114a14a7e604dd9c5247)
> arm64: dts: xilinx: Add dts for AD9164

- drivers/iio/adc/navassa/adrv9002.c
- drivers/iio/adc/navassa/adrv9002.h
- drivers/iio/adc/navassa/adrv9002_conv.c
Similar to
commit 7ebe866977d4 ("iio: adc: adrv9002: fixup tx2 power level")
we need to apply the same fixup even in rx2tx2. The reasoning for not doing it at the time was that if the channels are tuned together and have the same SSI delays, it should not be needed. Well...
While at it (and as advised by HW folks), we're now doing the fixup for all TX channels.
Reported and tested:
https://ez.analog.com/linux-software-drivers/f/q-a/588904/adrv9002-tx-at-full-scale-distortion
> iio: adc: adrv9002: fix tx2 scale for rx2tx2

- drivers/iio/adc/ad9081.c
- drivers/iio/adc/ad9083.c
- drivers/iio/adc/ad9371.c
- drivers/iio/adc/adrv9009.c
- drivers/iio/adc/adrv902x/adrv9025.c
- drivers/iio/adc/cf_axi_adc_core.c
- drivers/iio/frequency/ad9144.c
- drivers/iio/frequency/ad9162.c
- drivers/iio/frequency/ad9172.c
- drivers/iio/frequency/ad9528.c
- drivers/iio/frequency/cf_axi_dds.c
- drivers/iio/frequency/hmc7044.c
- drivers/iio/frequency/ltc6952.c
- drivers/iio/jesd204/altera_adxcvr.c
- drivers/iio/jesd204/axi_jesd204_rx.c
- drivers/iio/jesd204/axi_jesd204_tx.c
- drivers/jesd204/jesd204-core.c
- drivers/jesd204/jesd204-fsm.c
- drivers/jesd204/jesd204_top_device.c
- include/linux/jesd204/jesd204.h
This PR improves devm_jesd204_dev_register() and adds a new devm_jesd204_fsm_start() API so we make sure to stop the FSM on unbind. Then, we update all users jesd204_fsm_start() () to use the new variant. ALong the way some drivers were completely converted to a full devm probe (meaning that we do not need any driver .remove() hook)
> Small improvements on jesd204 and users

- drivers/spi/spi-gpio.c
Fix the host->mode_bits mask. Missed to OR SPI_LSB_FIRST with SPI_MOSI_IDLE_LOW .
Fixes: d31fa3135dbe ("Merge tag 'xilinx-v2024.1' of https://github.com/Xilinx/linux-xlnx.git")
> spi: spi-gpio: fix bug introduced by 6.6 merge

- azure-pipelines-rpi.yml
The latest supported rpi branch is rpi-6.6.y. Add support for it in CI.
> azure-pipelines-rpi: update for new rpi branch

- Documentation/devicetree/bindings/iio/dac/adi,ad5791.yaml
- arch/arm/boot/dts/intel/socfpga/socfpga_arria10_socdk_ad9081.dts
- arch/arm/boot/dts/intel/socfpga/socfpga_arria10_socdk_ad9083_fmc_ebz.dts
- arch/arm/boot/dts/intel/socfpga/socfpga_arria10_socdk_adrv9002.dts
- arch/arm/boot/dts/intel/socfpga/socfpga_arria10_socdk_adrv9002_rx2tx2.dts
- arch/arm/boot/dts/intel/socfpga/socfpga_arria10_socdk_adrv9009.dts
- arch/arm/boot/dts/intel/socfpga/socfpga_arria10_socdk_adrv9025.dts
- arch/arm/boot/dts/intel/socfpga/socfpga_arria10_socdk_adrv9371.dts
- arch/arm/boot/dts/intel/socfpga/socfpga_arria10_socdk_fmcomms8.dts
- arch/arm/boot/dts/intel/socfpga/socfpga_cyclone5_de10_nano_ad57xx.dts
- arch/arm/boot/dts/intel/socfpga/socfpga_cyclone5_de10_nano_hps.dtsi
- arch/arm/boot/dts/intel/socfpga/socfpga_cyclone5_sockit_arradio.dts
- arch/arm/boot/dts/intel/socfpga/socfpga_cyclone5_sockit_dc2677a.dts
- drivers/iio/dac/ad5791.c
- drivers/spi/spi-axi-spi-engine-ex.c
This adds offload support for the ad57xx dac to be able to send samples up to 1MSPS.
> ad5791 offload

- drivers/iio/adc/ad_sigma_delta.c
Enabling append status breaks projects that also use SPI engine offload (cn0363). Append status is only necessary when using CPU for reading samples.
Check if SPI engine offload is used before enabling append status.
Fixes: 27b588fc154f ("Merge tag 'xilinx-v2023.1' of https://github.com/Xilinx/linux-xlnx.git")
> iio: adc: ad_sigma_delta: fix spi engine offload

- drivers/spi/spi-bcm2835.c
- drivers/spi/spi-stm32.c
This fixes a FTBFS in the spi-bcm2835 and spi-stm32 driver. Both were broken by a backport of c0c0293cf7a0 ("spi: drop gpf arg from __spi_split_transfer_maxsize()") which resulted in 98847e6e1b77c7a28738722b997c16bc1ce1a427.
> fix broken backport of c0c0293cf7a0 ("spi: drop gpf arg from __spi_split_transfer_maxsize()")

- drivers/spi/spidev.c
The first commit is a cleanup that reduces the diff of the spi driver to mainline. While this is an annoying change now that might result in conflicts, it is expected to reduce further conflicts in the future. The second patch brings the contents of spidev_spi_ids[] and spidev_dt_ids[] into alignment again fixing a runtime warning.
A bit related see [a patch to align the ordering of the two arrays](https://lore.kernel.org/linux-spi/20241217114226.1223724-2-u.kleine-koenig@baylibre.com/) for mainline.
> spidev cleanup

- drivers/iio/adc/ad7768.c
- drivers/iio/adc/navassa/adrv9002.c
- drivers/iio/adc/navassa/adrv9002.h
- drivers/iio/adc/navassa/adrv9002_conv.c
Two fixes for adrv9002 and ad7768 backported from main.
> 2023_R2 backports

- drivers/iio/adc/cf_axi_adc_core.c
With commit
c5a5970bb457 ("iio: adc: cf_axi_adc_core: use devm_jesd204_fsm_start()"),
we started to use devm_platform_ioremap_resource() which means 'regs_size' will stay unchanged during probe and will be 0. Thus, checking the register to fit the mapped area will fail in the debugfs interface. Hence, relax that check and only check for proper alignment. While checking if the register fits the mapped area would be a nice thing, this is a debug interface and users are expected to know what they are doing. Hence I prefer to have simplicity during probe and not to keep 'regs_size' only to be used in the debugfs interface.
Fixes: c5a5970bb457 ("iio: adc: cf_axi_adc_core: use devm_jesd204_fsm_start()")
> iio: adc: cf_axi_adc_core: relax check in register access

- drivers/iio/beamformer/adar1000.c
The compiler is unhappy when the driver is configured as a module:
In file included from drivers/iio/beamformer/adar1000.c:9:
drivers/iio/beamformer/adar1000.c:2639:26: error: ‘adar1000_id_table’ undeclared here (not in a function); did you mean ‘adar1000_read_enable’?
2639 | MODULE_DEVICE_TABLE(spi, adar1000_id_table);
|                          ^~~~~~~~~~~~~~~~~
include/linux/module.h:244:15: note: in definition of macro ‘MODULE_DEVICE_TABLE’
244 | extern typeof(name) __mod_##type##__##name##_device_table               \
|               ^~~~
include/linux/module.h:244:21: error: ‘__mod_spi__adar1000_id_table_device_table’ aliased to undefined symbol ‘adar1000_id_table’
244 | extern typeof(name) __mod_##type##__##name##_device_table               \
|                     ^~~~~~ …
> iio: beamformer: adar1000: Fix a build failure

- arch/arm/boot/dts/xilinx/zynq-zc706-adv7511-adrv9009.dts
- arch/arm64/boot/dts/xilinx/zynqmp-zcu102-rev10-adrv9009.dts
In the HDL design for adrv9009 with zc706, respectively zcu102, the DAC_FIFO component was replaced by Data Offload.
These devicetree changes were tested together with this PR: https://github.com/analogdevicesinc/hdl/pull/1516
> ADRV9009: Add Data Offload to ZC706 and ZCU102 platforms

- drivers/iio/adc/ad4630.c
Since commit 2e424f14a9e3 ("iio: adc: ad4630: Specify PWM parameters in nanoseconds") the unit of PWM parameters is measured in nano seconds and since commit 4246bc985f5d ("pwm: Drop support for time units other than nanoseconds") only nano seconds are possible. Convert tquiet_con_delay to nano seconds accordingly.
Fixes: a18c50e4f1c6 ("iio: adc: ad4630: Make fetch trigger PWM phase smaller than period")
> iio: adc: ad4630: Specify the PWM phase in nano seconds

- drivers/iio/adc/xilinx-ams.c
- drivers/media/platform/xilinx/xilinx-hdcp2x-rx.c
- drivers/pwm/pwm-cadence.c
- drivers/spi/spi-bcm2835.c
- drivers/spi/spi-stm32.c
- include/uapi/misc/xilinx_puf.h
This patchset has a set of fixes so that an allyesconfig compiles (at least) for ARM and ARM64.
> 2023_R2 compile fixes

- arch/arm64/boot/dts/xilinx/adi-ad9162-fmc-ebz.dtsi
- arch/arm64/boot/dts/xilinx/zynqmp-zcu102-rev10-ad9162-fmc-ebz_m2_s2.dts
The device trees were added for the EVAL-AD9164 board on the ZCU102.
JESD Link Mode 8 Example: M2, L8, S2, F1, NP'16, Interpolation: 2 -> [zynqmp-zcu102-rev10-ad9162-fmc-ebz_m2_s2.dts](https://github.com/analogdevicesinc/linux/blob/f1baa824871998ea6df709d2fc506d3355baa634/arch/arm64/boot/dts/xilinx/zynqmp-zcu102-rev10-ad9162-fmc-ebz_m2_s2.dts)
> arm64: dts: xilinx: Add dts for AD9162

- arch/arm64/boot/dts/xilinx/zynqmp-zcu102-rev10-ad9694.dts
Corrected the GPIO numbers in the AD9694 device tree, because in [HDL](https://github.com/analogdevicesinc/hdl/blob/main/projects/ad9694_fmc/zcu102/system_top.v#L103-L108), the powerdown is GPIO 32, fda is GPIO 33 and fdb is GPIO 34.
Adding the offset of 78 (needed for UltraScale), pwdn is 110, fda is 111 and fdb is 112.
> arch: arm64: boot: dts: xilinx: ad9694: Fix GPIO pins

- Documentation/devicetree/bindings/power/supply/ltc4162-l.yaml
- drivers/power/supply/ltc4162-l-charger.c
Add support for:
LTC4162-F 35V/3.2A Multi-Cell LiFePO4 Step-Down Battery Charger
LTC4162-S 35V/3.2A Lead-Acid Step-Down Battery Charger
LTC4015 35V/3.2A Multichemistry Buck Battery Charger Controller
Bindings:
- Add compatible entries for ltc4162-f/s and ltc4015
- Include datasheets for new devices
- Change vendor prefix from lltc to adi
ltc4162:
- Modify functions for battery voltage/current, input voltage/current,
charge voltage, die temp, and force telemetry to handle different
battery chemistries.
> add support for ltc4162-f/s and ltc4015 battery charger

- Documentation/devicetree/bindings/iio/adc/adi,ad7625.yaml
- Documentation/iio/ad7625.rst
- Documentation/iio/index.rst
- MAINTAINERS
- arch/arm/boot/dts/xilinx/zynq-zed-adv7511-ad7625.dts
- arch/arm/boot/dts/xilinx/zynq-zed-adv7511-ad7960.dts
- drivers/iio/Kconfig.adi
- drivers/iio/adc/Kconfig
- drivers/iio/adc/Makefile
- drivers/iio/adc/ad7625.c
Now that the PWM waveform backport is in, backport the actual AD7625 driver from upstream. This PR currently includes a very minor fix recently submitted by @ukleinek which is currently only on the iio [testing](https://git.kernel.org/pub/scm/linux/kernel/git/jic23/iio.git/log/?h=testing) branch. If that's not desirable to include here, I can just remove it from the patchset.
One of the patches included contains devicetrees for the ad7625 and ad7960 and is not found upstream.
As usual, this has been tested on a Zedboard with an EVAL-AD7626/25FMCZ, similar to how the original patch submission for iio was.
I've ticked the external documentation box below as the Wiki page has been basically ready for review for some time (just need this to be merged before I can give the OK). For reference: …
> AD7625 backport

- drivers/power/supply/ltc4162-l-charger.c
Follow-up patch for ltc4162 driver, already applied upstream.
> power: supply: ltc4162l: Use GENMASK macro in bitmask operation

- Documentation/devicetree/bindings/iio/adc/adi,ad7192.yaml
- drivers/iio/adc/Kconfig
- drivers/iio/adc/ad7192.c
- All commits, except the last one adding the Cora devicetrees, were already accepted upstream.
- Correct AINCOM and VREF supplies setup.
- Add support for AD7194.
- Add correct clock consumer and provider configuration.
- Cleanup driver.
> AD7192 driver new features and devicetrees

- drivers/iio/adc/navassa/adrv9002.c
- drivers/iio/adc/navassa/adrv9002.h
- drivers/iio/adc/navassa/adrv9002_debugfs.c
- drivers/iio/adc/navassa/adrv9002_of.c
RX port switching is a feature where we can either manually switch between RXA and RXB or we can define a set of carrier ranges (one for RXA and another for RXB) and whenever the configured carrier falls in one range, the port configured for that range will be used.
> [ADRV9002]: RX Port Switch support

- drivers/iio/filter/admv8818.c
When a weak pull-up is present on the SDO line, regmap_update_bits fails to write both the SOFTRESET and SDOACTIVE bits because it incorrectly reads them as already set.
Since the soft reset disables the SDO line, performing a read-modify-write operation on ADI_SPI_CONFIG_A to enable the SDO line doesn't make sense. This change directly writes to the register instead of using regmap_update_bits.
> Force ADMV8818 soft reset and SDO initialization

- arch/arm64/boot/dts/xilinx/adi-ad9163-fmc-ebz.dtsi
- arch/arm64/boot/dts/xilinx/zynqmp-zcu102-rev10-ad9163-fmc-ebz_m2_l2_f2_s1.dts
- arch/arm64/boot/dts/xilinx/zynqmp-zcu102-rev10-ad9163-fmc-ebz_m2_l8.dts
Added two .devicetrees for EVAL-AD9163, Mode 8 and Mode 2, working on ZCU102.
> Add dts for AD9163

- arch/microblaze/boot/dts/vcu118_adrv9025.dts
Fix 'hdl_project' tag from header to match HDL project name: adrv9026/vcu118.
> vcu118_adrv9025.dts: fix hdl_project tag

- drivers/iio/adc/ad9081.c
- drivers/iio/adc/ad9081/adi_ad9081_jesd.c
Make sure we enable the link after the PRBS after it is configured and the error counters are cleared. The adi_ad9081_jesd_rx_phy_prbs_test() function assumes the Links to be enabled, log error and return in case no link is enabled.
> iio: adc: ad9081: adi_ad9081_jesd: JRX PHY PRBS toggle LINK_EN

- drivers/iio/adc/navassa/devices/adrv9001/public/include/adi_adrv9001_version.h
The SDK is taken as is which means that compilation will likely fail.
The folloing changes were squashed in the new SDK (need to be sent to the BU):
* 9d9cde6a64b4 ("iio: adc: adrv9002: radio: turn radio functions private")
* 67b6d36a286d ("iio: adc: adrv9002: radio: fix pin mode")
Same as #2730
> iio: adc: adrv9002: Update API to 68.14.13

- drivers/iio/adc/ad4130.c
- drivers/iio/adc/ad7124.c
- drivers/iio/adc/ad7173.c
- drivers/iio/adc/ad_sigma_delta.c
This PR contains a big update for the ad7124 driver. Featurewise it's calibration support (both internal calibration during probe and system calibration on demand). Other than that it contains a bunch of commits from mainline with the eventual goal to have the mainline driver and the variant in the vendor fork as similar as possible.
The topmost 8 commits are taken from https://lore.kernel.org/all/20250303114659.1672695-10-u.kleine-koenig@baylibre.com/, which Jonathan Cameron (the iio maintainer) announced to have applied (it didn't appear in his tree as of now yet though). The other commits are backports from mainline (and next).
I'm a bit unsure about including 7f7bf5703efbe68ead1e5678dee3f27194c3093e in the backport. That's a big change affecting many drivers. It's hard to predict if …
> Ad7124 calibration

- arch/arm64/boot/dts/xilinx/zynqmp-jupiter-sdr.dts
Removing fan_ctl gpio from zynqmp-jupiter-sdr devicetree
because it will be used in userspace and boot scripts.
> arm64: boot: dts: remove fan-ctl gpio from jupiter dts

- ci/travis/run-build.sh
Make use of pix to install dtschema. This is the preferred way of installing apps from python packages (one cannot use pip anymore in distros like ubuntu 24.04 for example). This creates an isolated virtual environment and ensures the command are accessible in $PATH. It also makes sure all dependencies are met and do not interfere with OS's python packages.
(cherry picked from commit daf69ead27dcc115bf19093f647a36b661a459fd)
- If you changes include a …
> [2023_R2] ci: travis: fix dt-bindings job

- arch/microblaze/boot/dts/vcu118_quad_ad9081.dtsi
Add data offload in device trees to support the new HDL changes.
Related to: https://github.com/analogdevicesinc/hdl/pull/1590
> dts: vcu118_quad_ad9081.dtsi: Add Data Offload

- Documentation/devicetree/bindings/iio/adc/adi,ad7191.yaml
- Documentation/iio/ad7191.rst
- Documentation/iio/index.rst
- MAINTAINERS
- drivers/iio/Kconfig.adi
- drivers/iio/adc/Kconfig
- drivers/iio/adc/Makefile
- drivers/iio/adc/ad7191.c
- include/linux/bitmap.h
- include/linux/gpio/consumer.h
- include/linux/iio/adc/ad_sigma_delta.h
Add support to rpi branch for AD7191. The ad7191 driver is already in the linux iio tree. The following commits are cherry picked from there:
- dt-bindings: iio: adc: add AD7191
- iio: adc: ad7191: add AD7191
- docs: iio: add AD7191
Cherry pick 2 other commits from the iio tree to synchronize the driver here with the driver there. The only difference right now is:
MODULE_IMPORT_NS(IIO_AD_SIGMA_DELTA); (here)
vs
MODULE_IMPORT_NS("IIO_AD_SIGMA_DELTA");
One additional commit adding iio.h library. Without this I got errors when building.
P.S. Thank you @nunojsa for the redirection :D !
> Add AD7191 driver (already added to the linux iio tree)

- arch/arm/boot/dts/overlays/Makefile
- arch/arm/boot/dts/overlays/rpi-ad7191-overlay.dts
- include/linux/iio/iio.h
Add support to rpi branch for AD7191. The ad7191 driver is already in the linux iio tree. The following commits are cherry picked from there:
- dt-bindings: iio: adc: add AD7191
- iio: adc: ad7191: add AD7191
- docs: iio: add AD7191
Cherry pick 2 other commits from the iio tree to synchronize the driver here with the driver there. The only difference right now is:
MODULE_IMPORT_NS(IIO_AD_SIGMA_DELTA); (here)
vs
MODULE_IMPORT_NS("IIO_AD_SIGMA_DELTA");
Question: the bitmap.h file of the main branch is behind the upstream one (and also behind the one on rpi-6.6.y branch), in order to add this driver to the main branch too, should I drop the use of bitmap_write there, resulting in difference between the driver on main branch vs rpi-6.6.y branch?
> Add AD7191 overlay

- drivers/iio/adc/ad9361.c
Return error in case TX_QUAD_CAL or RFDC_CAL fail.
> drivers: iio: adc: ad9361.c: Return calib err

- arch/arm/boot/dts/xilinx/zynq-zed-adv7511-ad4630-24.dts
- drivers/iio/adc/ad4630.c
- drivers/spi/spi-offload-trigger-pwm.c
- include/linux/spi/offload/types.h
This makes 4630 dirver use the recently backported upstream spi offload implementation.
Main point is to stop using axi-spi-engine-ex so we can remove it.
> Ad4630 offload update

- Documentation/devicetree/bindings/hwmon/adi,adm1275.yaml
- Documentation/hwmon/adm1275.rst
- drivers/hwmon/pmbus/Kconfig
- drivers/hwmon/pmbus/adm1275.c
The ADM1273 is also a Hot-swap controller similar to the ADM1272, with the
following differences:
* The MFR_MODEL register value is different.
* The ADM1273 includes the STATUS_CML register, which the ADM1272
does not have.
The currently available adm1275 driver supports the adm1272 and this patch
adds support for the adm1273. The ADM1273 is currently unreleased and the
datasheet is not yet publicly available.
> add support for adm1273

- Documentation/devicetree/bindings/iio/adc/adi,ad7380.yaml
- Documentation/iio/ad7380.rst
- Documentation/iio/index.rst
- MAINTAINERS
- arch/arm/boot/dts/xilinx/zynq-zed-adv7511-ad7380.dts
- drivers/iio/adc/Kconfig
- drivers/iio/adc/ad7380.c
Backport more from upstream for ad7380 and then add an ADI-tree only feature to enable using multiple SPI data lines to allow acheiving the max sample rate of 4 MSPS.
This is mostly working, but there are some HDL issues that need to be worked out, so marking this as a draft until we get that sorted.
> AD7380 backport and max sample rate support

- drivers/iio/adc/ad4630.c
2 updates related to HDL:
- use postenable to have dma start before spi engine (recommendation from HDL team)
- use 32bit container for single channel ad4030.
> ad4630:  postenable and 32 bit container 

- drivers/iio/adc/adrv9009.c
- drivers/iio/adc/adrv9009.h
Adds a feature to propagate the PLL-TRX-RF-LO clock rate to the clock system. The scale may be set in the device tree node with trx-lo-clock-scales = <mult div>;
> iio: adc: adrv9009: Propagate PLL-RF-LO clock

- arch/arm/boot/dts/zynq-coraz7s-ad7190.dts
- arch/arm/boot/dts/zynq-coraz7s-ad7192.dts
- arch/arm/boot/dts/zynq-coraz7s-ad7193.dts
- arch/arm/boot/dts/zynq-coraz7s-ad7194.dts
- arch/arm/boot/dts/zynq-coraz7s-ad7195.dts
Add AD7190, AD7192, AD7193, AD7194 and AD7195 devicetrees for Cora z7s board.
> arm: dts: Add AD719x dts for cora

- arch/arm/boot/dts/xilinx/zynq-m2k-reva.dts
- arch/arm/boot/dts/xilinx/zynq-m2k-revb.dts
- arch/arm/boot/dts/xilinx/zynq-m2k-revc.dts
- arch/arm/boot/dts/xilinx/zynq-m2k-revd.dts
- arch/arm/boot/dts/xilinx/zynq-m2k-reve.dts
- arch/arm/boot/dts/xilinx/zynq-m2k-revf.dts
Based on the HDL changes, the path for the m2k project files changed:
https://github.com/analogdevicesinc/hdl/pull/1634
Update the affected dts descriptions.
> m2k: Update hdl project path

- drivers/iio/frequency/hmc7044.c
A bug exists on 0x007D[2] "alarm readback.clock outputs phases status" of HMC7043 and cannot be reliably used.
Resolves false/misleading
```
hmc7044 spi1.4: hmc7044_jesd204_clks_sync3: SYSREF of the HMC7044 is not valid; that is, its phase output is not stable (0x0)
```
> iio: hmc7044: Don't warn CLK_OUT_PHASES for hmc7043

- drivers/iio/frequency/hmc7044.c
A bug exists on 0x007D[2] "alarm readback.clock outputs phases status" of HMC7043 and cannot be reliably used.
Resolves false/misleading
```
hmc7044 spi1.4: hmc7044_jesd204_clks_sync3: SYSREF of the HMC7044 is not valid; that is, its phase output is not stable (0x0)
```
> backport: iio: hmc7044: Don't warn CLK_OUT_PHASES for hmc7043

- drivers/jesd204/jesd204-sysfs.c
Add missing sysfs_attr_init();
Fixes: 1080c2efcfb2 ("jesd204: sysfs: add initial version for sysfs")
> jesd204: jesd204-sysfs: Fix BUG when lock debugging

- Documentation/devicetree/bindings/regulator/adi,adp5055-regulator.yaml
- Kconfig.adi
- MAINTAINERS
- drivers/regulator/Kconfig
- drivers/regulator/Makefile
- drivers/regulator/adp5055-regulator.c
- This adds driver support and device tree bindings for ADP5055 triple buck regulator.
- Datasheet: https://www.analog.com/media/en/technical-documentation/data-sheets/adp5055.pdf
- Tested on RPI4 on the eval board: https://www.analog.com/media/en/technical-documentation/user-guides/adp5055-evalz-ug-1930.pdf
> Add support for ADP5055

- Documentation/devicetree/bindings/iio/jesd204/adi,iio-fakedev.yaml
The axi-jesd204-rx label was duplicated and wording was off.
Add information that the label sets the iio device name.
> dt-bindings: iio: jesd204: adi,iio-fakedev: fix example, misspelling

- drivers/iio/adc/ad9081.c
iio: adc: ad9081: Fix support for JTX_MODE_S_SEL parameter
* JTX_MODE_S_SEL is a required dt parameter for AD9081-4D4AB,
AD9986, and AD9988. 
* For the same variants 1x1 decimation is also not supported.
> iio: adc: ad9081: Fix support for JTX_MODE_S_SEL parameter

- arch/arm/boot/dts/xilinx/zynq-coraz7s-adaq4001.dts
- arch/arm/boot/dts/xilinx/zynq-zed-adv7511-ad4000.dts
- arch/arm/boot/dts/xilinx/zynq-zed-adv7511-ad4000.dtsi
- arch/arm/boot/dts/xilinx/zynq-zed-adv7511-ad4001.dts
- arch/arm/boot/dts/xilinx/zynq-zed-adv7511-ad4002.dts
- arch/arm/boot/dts/xilinx/zynq-zed-adv7511-ad4003.dts
- arch/arm/boot/dts/xilinx/zynq-zed-adv7511-ad4004.dts
- arch/arm/boot/dts/xilinx/zynq-zed-adv7511-ad4005.dts
- arch/arm/boot/dts/xilinx/zynq-zed-adv7511-ad4006.dts
- arch/arm/boot/dts/xilinx/zynq-zed-adv7511-ad4007.dts
- arch/arm/boot/dts/xilinx/zynq-zed-adv7511-ad4008.dts
- arch/arm/boot/dts/xilinx/zynq-zed-adv7511-ad4010.dts
- arch/arm/boot/dts/xilinx/zynq-zed-adv7511-ad4011.dts
- arch/arm/boot/dts/xilinx/zynq-zed-adv7511-ad4020.dts
- arch/arm/boot/dts/xilinx/zynq-zed-adv7511-ad4021.dts
- arch/arm/boot/dts/xilinx/zynq-zed-adv7511-ad4022.dts
- arch/arm/boot/dts/xilinx/zynq-zed-adv7511-adaq4001.dts
- arch/arm/boot/dts/xilinx/zynq-zed-adv7511-adaq4003.dts
This PR updates AD4003, AD4020, and ADAQ4003 device trees to the new SPI offloading support.
It also provides dts for the remaining devices supported by the ad4000 driver.
> Add dts for using AD4000 and similar ADCs on ZedBoard

- azure-pipelines.yml
Pipelines triggered by PRs coming from forks don't have access to the secret variables used by the PushToArtifactory and TestHarness stages. From a security standpoint, it makes sense to limit those pipelines to not have access to our internal servers.
Add condition so that pipelines of PRs coming from forks skip the PushToArtifactory and TestHarness stages.
> ci: Disable hardware tests for PRs from forks

- drivers/iio/adc/ad9361.c
Fix for #2775: Division by zero issue in debugfs initialize handler.
Make sure workqueue has completed before moving on.
Fixes: d95373fb89b2 ("drivers/iio/adc/ad9361: Add BIST - Loopback, PRBS and TONE")
> iio: adc: ad9361: Fix raise condition in debugfs initialize

- .github/workflows/build.yml
- ci/Containerfile
Fixup trying to compile the device tree before setting the deconfig.
Related to run https://github.com/analogdevicesinc/linux/actions/runs/15075543379/job/42386997854
Also set git configs system wide for instances where running the container with the runner user is not possible.
> .github: Run compile devicetrees after make defconfig and set git configs system wide

- arch/arm/boot/dts/xilinx/zynq-zed-adv7511-ad7380.dts
Fix the DMA clock phandle in the ad7380 devicetree. The DMA controller is connected to the same system clock as all of the other IP blocks.
> arm: dts: zynq: fix ad7380 DMA clock

- ci/build.sh
At the compile_step step, we only problem match if it exits with an error code
because we don't want duplicated errors/warnings on sparse,
neither warnings unrelated to the patch, but if the kernel
does not even compile, the checkers don't run and the reason
is at this step.
Also clean-up some unused vars.
Sample run succeed to compile: https://github.com/gastmaier/adi-linux/actions/runs/15118116546/job/42493841013
Sample run fail to compile:  https://github.com/gastmaier/adi-linux/actions/runs/15118118572/job/42493848122
> Ci problem match compile

- drivers/iio/adc/ltc2387.c
For the situation when the maximum sampling is used, 15MHz.
Before: duty_offset_ns = 70, period_length_ns = 67 (rounded from 66.666)
That caused "ltc2387 setup failed", because the PWM framework has a condition
if wf->duty_offset_ns >= wf->period_length_ns, which is true => fail.
In the case of LTC2387 with max sample rate,
tFIRSTCLK >= 65ns and tCONV = 63ns ([data sheet, page 5](https://www.analog.com/media/en/technical-documentation/data-sheets/238718fa.pdf)).
This doesn't go by the PWM framework condition, so the offset needs to be updated, affecting the timing of the cnv and clk_gate signals only at the max sample rate. Just the first time the conversion is affected, being delayed.
Now: duty_offset_ns = 3, period_length_ns = 67.
The first sample is junk anyway.
This doesn't affect the …
> iio: adc: ltc2387: Update calculation of duty_offset_ns value

- ci/build.sh
Infer dts affected by changed dtsi, problem match devitree compile
Use basic '#include "$file"' matching to infer which devicetrees should be compiled when a dtsi gets edited.
The task of ensuring compile once is deferred to Makefile internal timestamp checker.
Add a problem match devicetree compile
Match for single line problems in the format
file:line.col-end_line.end_col: level reason
and
level: file:line.col-end_col reason
Finally, Flush last warning captured
These steps works by printing the last warning when a new is matched, to support muli-line errors. Resolve last warning not being printed.These steps works by printing the last warning when a new is matched, to support muli-line errors. Resolve last warning not being printed.
Sample run: …
> ci: Infeer dts affected by changed dtsi, problem match devitree compile

- drivers/iio/buffer/industrialio-buffer-dmaengine.c
We cannot set the .callback_result() callback for cyclic transfers. If the cyclic transfer is purely done in hardware this would actually bring no issue but in cases cyclic happens in software, we would have the callback called multiple times which would lead to the DMA block to be freed ahead of time (and actually lead to a use after tree).
Fixes: 16dd49b0c5d94 ("iio: buffer-dma: sync upstream and add mmap legacy kconfig")
> iio: buffer-dmaengine: fix cyclic transfers

- ci/build.sh
- ci/symbols_depend.py
Don't run checkers, compilers on files that have been deleted on the range.
Add recursive Kconfig symbol from the .o object searcher.
The following cases are supported:
```
driver-y += devices/driver/public/src/driver_extra.o
driver-objs += some_obj.o
driver-$(CONFIG_OF) += driver_of.o
obj-$(CONFIG_DRIVER) += driver.o
```
Testing is simple:
```
$base_sha=@~500 ; head_sha=@ ; source ci/build.sh ; auto_set_kconfig
Failed to find Makefile targeting drivers/iio/adc/adrv902x/adrv9025.o
Failed to find Makefile targeting arch/arm/mach-ep93xx/core.o
Failed to find Makefile targeting tools/iio/iio_event_monitor.o
```
(`tools/iio/iio_event_monitor.o` should be resolved in a future PR, `drivers/iio/adc/adrv902x/adrv9025.o` is off and I would change the Makefile instead)
Sample run: …
> ci: Filter removed files, recursive Kconfig symbol look-up

- drivers/iio/adc/navassa/adrv9002_of.c
Instead of forcing the 'adi,dpd-config' node to be given in order to add the external path delay boolean property, take it out of that node and allow to add it at the TX node level. This is done because often we want to do the calibration and still have the default DPD settings.
Obviously, the property still depends on 'adi,dpd'.
> iio: adc: adrv9002_of: refactor DPD external path delay property

- arch/arm/boot/dts/xilinx/zynq-coraz7s-ad7689-ardz.dts
- arch/arm/boot/dts/xilinx/zynq-coraz7s-ad7946.dts
- arch/arm/boot/dts/xilinx/zynq-coraz7s-ad7984.dts
- arch/arm/boot/dts/xilinx/zynq-coraz7s-adaq4001.dts
- arch/arm/boot/dts/xilinx/zynq-coraz7s-adaq4003.dts
- arch/arm/boot/dts/xilinx/zynq-coraz7s-axi-sysid.dtsi
- arch/arm/boot/dts/xilinx/zynq-coraz7s-cn0540.dts
- arch/arm/boot/dts/xilinx/zynq-coraz7s-cn0579_i2c.dts
- arch/arm/boot/dts/xilinx/zynq-coraz7s-fpga-eeprom.dts
- arch/arm/boot/dts/xilinx/zynq-coraz7s-pulsar.dtsi
- arch/arm/boot/dts/xilinx/zynq-coraz7s.dts
- arch/arm/boot/dts/xilinx/zynq-coraz7s.dtsi
Remove axi-sysid from base zynq-coraz7s.dtsi so it can be used to
generate a devicetree compatible with BOOT.BIN with not bitstream with:
```
make xilinx/zynq-coraz7z.dtb
```
Since  xilinx/zynq-coraz7z.dts is now xilinx/zynq-coraz7s-fpga-eeprom.dts, somewhere in the pipeline for kuiper should break.
Follow-up to #2657
<details>
<summary>The ci run seems to compiled all dts:</summary>
```
DTC arch/arm/boot/dts/xilinx/zynq-coraz7s.dtb
DTC arch/arm/boot/dts/xilinx/zynq-coraz7s-fpga-eeprom.dtb
DTC arch/arm/boot/dts/xilinx/zynq-coraz7s-cn0579_i2c.dtb
DTC arch/arm/boot/dts/xilinx/zynq-coraz7s-cn0540.dtb
DTC arch/arm/boot/dts/xilinx/zynq-coraz7s-adaq4003.dtb
DTC arch/arm/boot/dts/xilinx/zynq-coraz7s-adaq4001.dtb
DTC arch/arm/boot/dts/xilinx/zynq-coraz7s-ad7984.dtb
DTC …
```
> arm: dts: xilinx: coraz7s no-bitstream compatible

- ci/build.sh
* Sparse errors are piped in sterr, so capture them
* Add a set_arch method to ease local testing
* Consider renamed files, because modified files that were also renamed are Renamed under diff-filter, e.g.:
```
M: zynq-coraz7s.dts (+10,-1)
R: zynq-coraz7s-fpga-eeprom.dts → zynq-coraz7s-no-bitstream.dts (-20)
```
> ci: build: General improvements

- drivers/iio/adc/ad9081.c
- drivers/iio/adc/ad9083.c
- drivers/iio/adc/ad9208.c
- drivers/iio/adc/ad9361.c
- drivers/iio/adc/ad9371.c
- drivers/iio/adc/admc_ctrl.c
- drivers/iio/adc/adrv9009.c
- drivers/iio/adc/adrv902x/adrv9025.c
- drivers/iio/frequency/ad9508.c
- drivers/iio/frequency/ad9528.c
- drivers/iio/frequency/hmc7044.c
- drivers/iio/frequency/m2k-dac.c
- drivers/iio/jesd204/axi_adxcvr.c
- drivers/iio/logic/m2k-fabric.c
- drivers/iio/logic/m2k-logic-analyzer.c
- drivers/jesd204/jesd204_top_device.c
Minor series to move our out of tree drivers to use kstrtobool(). strtobool() is no longer available in 6.12 so better remove it sooner rather than later.
> Move to kstrtobool()

- arch/arm/boot/dts/xilinx/zynq-coraz7s-no-bitstream.dts
- arch/arm/boot/dts/xilinx/zynq-coraz7s.dts
As requested, move zynq-coraz7s-fpga-eeprom to zynq-coraz7s, because this is the usual base devicetree used. For the no-bitstream, add the hdl_project tag, even-though it doesn't relate to an hdl project, it is used for identification during the Kuiper CI.
@SRaus
> arm: dts: xilinx: Move base and no-bitstream coraz7s

- .github/workflows.mirror/self.yml
- .github/workflows/mirror.yml
Use switch to detach head, to avoid failure if current checkout branch
has the same name.
> fix: .github: Same branch checkout

- arch/arm/boot/dts/xilinx/zynq-zed-adv7511-adaq4380-4.dts
Add an example for the EVAL-ADAQ4380-4 (FMCZ) evaluation board. These are similar to AD738x, but have different power supply requirements, so worth a separate example.
Example DTS
> arm: dts: xilinx: add example for ADAQ4380-4 eval board

- drivers/mfd/Kconfig
The driver uses pci_msi methods, only defined when CONFIG_PCI_MSI symbol
is set, and cannot be compiled without. Therefore, it depends on this
symbol.
https://github.com/raspberrypi/linux/pull/6891
cherry-pick https://github.com/raspberrypi/linux/commit/3f1c3474b306509dc901327f140f83680c1df1ab
> cherry-pick: mfd: rp1: depends on PCI_MSI 

- arch/arm/boot/dts/xilinx/zynq-zc706-adv7511-fmcomms11.dts
Add data offload in dts to support the new HDL changes.
Related to: https://github.com/analogdevicesinc/hdl/pull/1603
> arm: dts: xilinx: fmcomms11: Add Data Offload

- .github/workflows.mirror/cron.yml
- .github/workflows/build.yml
- ci/build.sh
on /dev/shm commit, run_id will have a single value for all jobs in the same workflow file, but since there is a single job it doesn't matter.
> ci: add staging-rpi/rpi-6.12.y to cron.yml and use /dev/shm

- drivers/misc/mathworks/mathworks_ip_common.c
- drivers/misc/mathworks/mw_stream_channel.c
Some 32bits architectures (like those in RPIs) support LPAE (Large Physical Address Extension) which means phys_addr_t will be of 'u64' type. Therefore we can have some int-to-pointer-cast warnings if not properly casting (in calls like virt_to_page()). Hence, first cast to uintptr_t before doing (void *).
> misc: mathworks: fix some -Wint-to-pointer-cast

- drivers/iio/adc/ad7380.c
Add max_conversion_rate_hz to the chip info for "adaq4381-4". Without this, the driver fails to probe because it tries to set the initial sample rate to 0 Hz, which is not valid.
Closes: https://github.com/analogdevicesinc/linux/issues/2890
This is backporting a commit that was applied upstream.
(cherry picked from commit b04e4551893fb8a06106a175ed7055d41a9279c4)
> iio: adc: ad7380: fix missing max_conversion_rate_hz on adaq4381-4

- .github/workflows/cron.yml
- .github/workflows/mirror.yml
- .github/workflows/sync_ci.yml
@pamolloy here is the ci to patch the workflow to arbitrary branches.
It is a copy of mirror.yml, but simplified since it is the same remote, so just using `origin` is enough.
It also allows to use the matrix to just pass an array of branches.
Please update 
https://github.com/analogdevicesinc/linux/compare/ci/update?expand=1#diff-69b9772a7fe51bd7c367926862d89ca7d8949cc9832b3645e610a1ec5bfa1ddfR39-R40
with all the branches that are currently relevant to update the ci.
One last note, on sync_ci.yml, the hardcoded main will be replaced by `ci` or similar name when we move the ci to a dedicated branch, and then `xlnx-main` will also be appended to the list of branches called for sync_ci.yml
Final note after last note: the cron.yml runs every 24h or dispatch (e.g. github gui). Now that it …
> Add workflow to patch workflows in the same repository

- ci/travis/deadcode_exceptions
- drivers/iio/adc/adrv902x/Makefile
Complementary PR to  #2909 solely to drop "complex" logic from the Makefile.
Complex from the point of view of statically analyzing the Makefile/Kconfig structure.
This allows symbol_depend to work with adrv902x .
>  iio: adc: adrv902x: Reformat Makefile

- drivers/iio/adc/ad9081.c
- include/dt-bindings/iio/adc/adi,ad9081.h
Add comprehensive device tree support for AD9081 PA (Power Amplifier) protection features including:
- Soft-off/on gain control with configurable ramp rates and triggers
- Long and short averaging power monitoring with thresholds
- Digital Step Attenuator (DSA) configuration
- GPIO PA enable outputs (global setting)
- Rotation mode settings (global setting)
The implementation ensures hardware register defaults are preserved when properties are not specified in the device tree. All numeric properties use standard u32 device tree parsing with proper validation.
Properties are only applied to hardware when explicitly provided, preventing unintended register modifications. Complex features like averaging require all related parameters to be specified.
Global settings (GPIO PA enable and …
> iio: adc: ad9081: add device tree support for PA protection features

- .github/workflows/build.yml
- ci/build.sh
- ci/symbols_depend.py
Consider lines that start with endif, since it may have comments.
Detected by run of #2913
https://github.com/analogdevicesinc/linux/actions/runs/17266053343/job/48998303938?pr=2913
Create deadcode_exceptions file, for API code mostly, to reduce noise from #2909
Demote assert_compiled step, for in case of API code not added yet to the deadcode_exceptions file, still run the next steps, also #2909
> ci: symbol_depend: Fix endif block detection

- .github/workflows/build.yml
- .github/workflows/checks.yml
- .github/workflows/main.yml
- .github/workflows/many_devicetrees.yml
- .github/workflows/top-level.yml
- ci/Containerfile
- ci/build.sh
- ci/symbols_depend.py
- ci/touched_kconfig.awk
Combine git internal treesitter and awk good block syntax to extract symbols of touched (menu)?config blocks.
Captures internal addition/deletions, and whole block addition, for example:
```
@@ -147,6 +147,7 @@ config CONFIG_MOCK
+config CONFIG_MOCK
+ tristate
+ select IIO_BUFFER
+ select IIO_TRIGGERED_BUFFER
@@ -147,6 +147,7 @@ config CONFIG_MOCK
depends on CF_AXI_DDS
+       select REGMAP_SPI
help
Say y
@@ -147,6 +147,7 @@ config CONFIG_MOCK
config CF_AXI_DDS_AD9783
tristate "Analog Devices AD9783 DAC"
depends on CF_AXI_DDS
-       select REGMAP_SPI
help
Say y
```
This is a new method for our CI, previously we would just look at touched files and not individually files, 
and before this, we would just build everything based on kconfig
Commit @~ is better looked with `-w` to ignore the …
> ci: symbols_depend: Extract symbols from kconfig, only touched lines

- drivers/nvmem/Kconfig
Add symbol required to compile without a specific arch symbol.
ARCH_ symbols are useful to filter-out non-relevant code for other archs, for CI we always want to test all code, hence why this symbol exists
> nvmem: Kconfig: Add COMPILE_TEST to NVMEM_AXI_SYSID

- Documentation/devicetree/bindings/clock/clk-ad9545.yaml
- Documentation/devicetree/bindings/iio/adc/adi,ad9083.yaml
- Documentation/devicetree/bindings/iio/adc/adi,adar1000.yaml
- Documentation/devicetree/bindings/iio/adc/lltc,ltc2387.yaml
- Documentation/devicetree/bindings/iio/adc/xlnx,versal-sysmon.yaml
- Documentation/devicetree/bindings/iio/addac/adi,one-bit-adc-dac.yaml
- Documentation/devicetree/bindings/iio/frequency/adf4371.yaml
- Documentation/devicetree/bindings/iio/frequency/adi,adf4360.yaml
- Documentation/devicetree/bindings/media/adi,adi-axi-fb.yaml
I was trying to run `make dtbs_check` on the ADI tree but it was causing the dtschma tool to crash. This lead me to https://github.com/devicetree-org/dt-schema/issues/151 which lead me to running `dt-extract-props -d Documentation/devicetree/bindings/`. This revealed quite a few errors. I fixed some things where it told me the actual file name where the problem was for things that are only in the ADI tree.
The main one though is the last patch which fixes a problem likely from the upstream xilinx tree. I suppose we could submit that patch there, but I think it is important to fix it here ASAP so we can actually use `make dtbs_check` without crashing.
> Fix some invalid DT property types

- azure-pipelines.yml
- ci/travis/prepare_artifacts.sh
Changes introduced in 3b1f15d moved some DTS files to a different location. Update CIs to reflect those changes:
- Update DTBs location in `azure_pipelines.yml`
- Fix pattern matching in `prepare_artifacts.sh` to upload each DTB to the correct destination (based on platform).
> ci: Fix DTBs upload after version upgrade

- drivers/iio/adc/navassa/adrv9002.c
- drivers/iio/adc/navassa/adrv9002_of.c
When using a profile with RX1 on port A and RX2 on port B, RX2 would still receive data on port A. As it turns out, we do have to call adi_adrv9001_Rx_PortSwitch_Configure() even if port switch is disabled. Annoyingly, we also need to put some valid values on the carrier intervals for making the API happy (even if the feature is disabled).
Likely this is a bug in the device FW but for now, let's just workaround it like this. And being this a workaround, I'm not giving a Fixes tag.
> iio: adc: adrv9002: Fix selecting port B on RX2

- .github/workflows/doc.yml
- .github/workflows/main.yml
- .github/workflows/pr-closed.yml
- .github/workflows/top-level.yml
Those workflows do not target a specific tool version.
Less maintenance burden for the actions we maintain.
> .github: use shared-action rolling version, run in any version when possible

- drivers/iio/adc/navassa/adrv9002.c
Fix multiple issues in the frequency hopping bin table write function:
- Correct typo "bellow" to "below" in comment
- Fix off-by-one error in entry bounds check (should be >= not >)
- Use correct rx20_if variable for rx2OffsetFrequencyHz instead of rx10_if
- Use correct rx2_gain variable for rx2GainIndex instead of rx1_gain
These fixes ensure proper configuration of RX2 channel parameters and prevent potential buffer overflow when the entry index equals max_sz.
> iio: adc: adrv9002: fix frequency hopping table configuration

- arch/arm/boot/dts/adi/sc594-som-ezkit.dts
- arch/arm/boot/dts/adi/sc59x.dtsi
Regression between ADSP Linux Yocto releases 3.1.2 -> 5.0.0 
SC594 boards isn't stable when running for more then few minutes, this changes makes its stable.
Max bandwidth benchmark after change stayed at same level >500MBit/s
> devicetree: arm: SC594-EZKIT remove tx dma configs
