drivers/iio/adc/admc_adc.c

When you try to remove the admc_adc module from the kernel, it segfaults.
The reason is that the probe function calls "axiadc_configure_ring_stream" and the remove function currently calls "axiadc_unconfigure_ring". The bug is fixed by modifying the remove function to call "axiadc_unconfigure_ring_stream" instead.

iio: admc_adc: use axiadc_unconfigure_ring_stream() in remove function

---

drivers/iio/accel/st_accel_buffer.c
drivers/iio/adc/ad7923.c
drivers/iio/gyro/itg3200_buffer.c
drivers/iio/gyro/st_gyro_buffer.c
drivers/iio/imu/inv_mpu6050/inv_mpu_core.c
drivers/iio/magnetometer/st_magn_buffer.c
drivers/iio/pressure/st_pressure_buffer.c
include/drm/drm_edid.h

Fix compilation issues with iio_triggered_buffer_setup usage and
st_press_buffer_predisable.

Compile fixes for xcomm_zynq

---

drivers/net/ethernet/xilinx/xilinx_axienet.h
drivers/net/ethernet/xilinx/xilinx_axienet_main.c

The main fix is commit bf25c79be5571a5f231e8629a0847c51bf81463c which moves the init of the internal PHY before the init of the external one.
Also, the external PHY was being initialized inside this else block
```
} else if ((lp->axienet_config->mactype == XAXIENET_1G) ||
(lp->axienet_config->mactype == XAXIENET_2_5G)) {
```
I've removed the fixup routine.
It does not seem to be run.
And finally, added code to cleanup the internal after each [external] PHY cleanup.
Tested successfully on VC707 & KCU105

 net: ethernet: xilinx: fix internal phy initialization

---

drivers/net/ethernet/xilinx/xilinx_axienet.h
drivers/net/ethernet/xilinx/xilinx_axienet_main.c

Same commits from PR #24 but with target-branch set to `xcomm_zynq`

[for xcomm_zynq] net: ethernet: xilinx: fix internal phy initialization

---

Documentation/ABI/testing/sysfs-bus-iio
drivers/iio/industrialio-buffer.c

Add a sysfs attribute that exposes buffer data available to userspace.
This attribute can be checked at runtime to determine the overall buffer
fill level (across all allocated buffers).
Signed-off-by: Matt Fornero <matt.fornero@mathworks.com>

iio: buffer: Expose data available

---

drivers/iio/adc/ad9680.c

iio: ad9680: fix a couple of small inconsistencies

---

drivers/iio/adc/ad6676.c

Fixes commit 8cd9482bf: `drivers/iio/adc/ad6676: Fix compiler warnings`
`do_div` is a macro that passes the result to the
first parameter via reference.
Whereas `div_s64` is function whose return value must be assigned.

iio: ad6676: Assign values from division

---

arch/arm/boot/dts/zynq-mini-itx-adv7511.dtsi

The FPGA should send YUV data to ADV7511 for the Mini-ITX.

arm: dts: zynq-mini-itx-adv7511: Disable axi_hdmi RGB output

---

drivers/staging/iio/impedance-analyzer/ad5933.c

Since commit 152a6a884ae13400bd7c48f011acf81ef5225238 ,
the semantic of the INDIO_BUFFER_HARDWARE flag has changed,
in the sense that buffers are hard/soft hybrid
buffers.
Since commit 2d6ca60f328450ff5c7802d0857d12e3711348ce ,
the INDIO_BUFFER_HARDWARE flag has been re-purposed for
DMA buffers.
This driver has lagged behind these changes, and
in order for buffers to work, the INDIO_BUFFER_SOFTWARE
needs to be used.

staging: iio: ad5933: switch buffer mode to software

---

drivers/iio/dac/Kconfig
drivers/iio/dac/ad5686-spi.c
drivers/iio/dac/ad5686.c
drivers/iio/dac/ad5686.h
drivers/iio/dac/ad5696-i2c.c

This patch adds support for AD5676R (spi) and AD5696R (i2c)
family of DAC devices.

iio: dac: Add support for AD5676R/AD5696R DACs

---

drivers/iio/adc/ad9361.c

ad9361_ensm_force_state() should verify if the part is really in the
desired ENSM state before exit. Otherwise, other operations that are
executed afterwards may fail.

iio: ad9361: Make sure the part is in the desired ENSM state

---

drivers/iio/dac/ad5686.c
drivers/iio/dac/ad5686.h
drivers/iio/dac/ad5696-i2c.c

The AD5691R/AD5692R/AD5693/AD5693R are a family of one channel DACs with 12-bit,
14-bit and 16-bit precision respectively. The devices have either no built-in reference,
or built-in 2.5V reference.
These devices are pretty similar to AD5671R/AD5675R/AD5694/AD5694R/AD5695R/AD5696/AD5696R,
except that they have only one channel. Another difference is that they use a write control
register(addr 0x04) for setting the power down modes and the internal reference instead of
sepparate registers for each function.
Datasheet:
http://www.analog.com/media/en/technical-documentation/data-sheets/AD5693R_5692R_5691R_5693.pdf

iio:dac:ad5686: Add AD5691R/AD5692R/AD5693/AD5693R support

---

drivers/iio/dac/ad5686-spi.c
drivers/iio/dac/ad5686.c
drivers/iio/dac/ad5686.h

The AD5681R/AD5682R/AD5683/AD5683R are a family of one channel DACs with
12-bit, 14-bit and 16-bit precision respectively. The devices have either
no built-in reference, or built-in 2.5V reference.
These devices are simmilar to AD5691R/AD5692R/AD5693/AD5693R except
that they use the spi interface instead of i2c. Another difference is that
in the write control register, DB18 and DB17 are used for setting the power
mode, while DB16 is the REF bit. In order to accommodate this change, a new
regmap type was defined and checked accordingly.
Datasheet:
http://www.analog.com/media/en/technical-documentation/data-sheets/AD5683R_5682R_5681R_5683.pdf

iio:dac:ad5686: Add AD5681R/AD5682R/AD5683/AD5683R support

---

drivers/iio/dac/ad5686.c
drivers/iio/dac/ad5686.h
drivers/iio/dac/ad5696-i2c.c

AD5311R is a single channel DAC with 10-bit precision and i2c interface.
The device includes a 2.5V internal reference which is enabled by default.
This device is similar to AD5691R/AD5692R/AD5693/AD5693R, the only
difference is that it has 10-bit precision.
Datasheet:
http://www.analog.com/media/en/technical-documentation/data-sheets/AD5310R_5311R.pdf

iio:dac:ad5686: Add AD5311R support

---

drivers/iio/dac/ad5686-spi.c
drivers/iio/dac/ad5686.c
drivers/iio/dac/ad5686.h

The AD5310R is a single channel DAC with 10-bit precision, which is
part of the same family as AD5311R, except that it uses the spi interface
instead of i2c. The device has a built-in 2.5V reference which is enabled
by default.
Another important difference is that the SPI write command operation is
16 bits long. The first four bits represent the command, while the
remaining 12 bits are for data. In the control reg, DB9 and DB10 are used
for power-down modes, while DB8 is the REF bit. In order to accommodate
this change, a new regmap type was defined and checked accordingly.
Because AD5310R does not have a readback register, the read_raw operation
was disabled. This is the reason why a new ad5310_info was defined and
initialized as part of ad5686_chip_info struct.
Datasheet: …

iio:dac:ad5686: Add AD5310R support

---

drivers/media/i2c/adv7604.c

Seems this was left-over from a merge commit.
Probably this commit 41d036b3795606 (Merge remote-tracking branch
'xilinx/master' into xcomm_zynq_4_9)
Remove it, since it's a duplicate reset.
The duplicate code is viewable in right above this patch/change.

[media] adv7604: remove duplicate reset code of gpios

---

drivers/dma/dma-axi-dmac.c

The AXI-DMAC supports different types of interface for the data source and
destination ports. Typically one of those ports is a memory-mapped
interface while the other is some kind of streaming interface.
The information about which kind of interface is used for each port is
encoded in the devicetree.
It is also possible in the driver to detect whether a port supports
memory-mapped transfers or not. For streaming interfaces the address
register is read-only and will always return 0. So in order to check if a
port supports memory-mapped transfers write a non-zero value to the
corresponding address register and check that the value read-back is still
non zero.
This allows to detect mismatches between the devicetree description and the
actual hardware configuration.
Unfortunately it is not …

dma: axi-dmac: Sanity check memory mapped interface support

---

drivers/iio/imu/adis_trigger.c

The adis_probe_trigger() creates a new IIO trigger and requests an
interrupt associated with the trigger. The interrupt uses the generic
iio_trigger_generic_data_rdy_poll() function has its interrupt handler.
Currently the driver initializes some fields of the trigger structure after
the interrupt has been requested. But an interrupt can fire as soon as it
has been requested. This opens up a race condition.
iio_trigger_generic_data_rdy_poll() will access the trigger data structure
and dereference the ops field. If the ops field is not yet initialized it
will result in a NULL pointer deref.
It is not expected that the device generates an interrupt at this point, so
typically this issue did not surface unless e.g. due to a hardware
misconfiguration (wrong interrupt number, wrong polarity, …

iio: adis_lib: Initialize trigger before requesting interrupt

---

include/uapi/linux/if_ether.h
include/uapi/linux/kernel.h
include/uapi/linux/libc-compat.h

When trying to build a RPi image with the ADI kernel inside the OpenWrt build-system, netifd fails due to some musl-libc + kernel headers conflicts.
This is because, musl-libc support is not completely upstreamed to the kernel [at least in 4.9].
And OpenWrt prefers musl-libc as a default.
For reference, musl-libc [compares itself against other libc implementations here](http://www.etalabs.net/compare_libcs.html).
Which makes it look interesting for devices with reduced flash storage.
These patches have been sent upstream as well.
Tested successfully that Zynq & ZynqMP still build with this changeset.

uapi: backport patches for musl compatibility from openwrt tree

---

arch/arm/boot/dts/overlays/Makefile
arch/arm/boot/dts/overlays/rpi-adxl372-overlay.dts
drivers/iio/accel/Kconfig
drivers/iio/accel/Makefile
drivers/iio/accel/adxl372.c

This patch adds basic support for Analog Devices ADXL372 SPI-Bus Three-Axis
Digital Accelerometer.
The device is probed and configured the with some initial default values.
With this basic driver, it is possible to read raw acceleration data.
Datasheet:
http://www.analog.com/media/en/technical-documentation/data-sheets/ADXL372.pdf

iio:adxl372: New driver for Analog Devices ADXL372 Accelerometer

---

drivers/iio/industrialio-core.c

Currently two newline characters are appended at the end of
IIO_VAL_FRACTIONAL_LOG2 values when preparing them for displaying in sysfs.
One is added in __iio_format_value() the other in iio_format_value().
This is unintended behavior and can confuse userspace tools. Remove the
newline that is added in __iio_format_value().
Fixes: 4320b0914a5e ("iio:core: add a callback to allow drivers to provide _available attributes")

iio: Fix IIO_VAL_FRACTIONAL_LOG2 newline termination

---

drivers/iio/adc/ad9361.c

Some device configurations require that the GPO be set into a specific
setting before doing init ops.
One example is when a GPO is used to enable a reference clock.
That means that the GPOs should already have a specific configuration
before doing init/calibration ops.

iio: adc: ad9361: move GPO initialization earlier in the setup

---

drivers/iio/adc/ad9361.c

The `ad9361_phy_parse_dt()` is missing a parameter for when no DT support
is enabled.
Add it.

iio: adc: ad9361: fix arguments for ad9361_phy_parse_dt() when not using DT

---

drivers/iio/adc/ad9361.c

The intent is to have this variable readily available when adding the
external band selection call/code.
The focus is not so much on performance here, but more on keeping the code
within the 80 col width [preferred] limit.

iio: adc: ad9361: add short-hand var `new_rate` in clk notifier funcs

---

arch/arm/boot/dts/overlays/rpi-adxl372-overlay.dts
drivers/iio/accel/adxl372.c
drivers/iio/accel/bmc150-accel-core.c
drivers/iio/industrialio-buffer.c
include/linux/iio/buffer.h

This patch adds support for the adxl372 FIFO. In order to accomplish this, triggered buffers were used.
Therefore, adxl372 is configured to trigger the watermark interrupt when 170 sets of concurrent 3-axis data is available in the FIFO. This data along with the timestamp is pushed to the IIO device's buffer. Also, the FIFO is configured in peak detect and stream mode.

Rpi 4.9.y adxl372 fifo

---

.travis.yml
drivers/iio/adc/ad9361.c
drivers/iio/adc/ad9361.h
drivers/iio/adc/ad9361_conv.c

The value of the BIST register via ad9361_get_dig_tune_data() needs to be
stored on the state struct when written back.
Otherwise there could be a discrepancy when between the cached value and
the value in the register.
To do this, the ad9361_write_bist_reg() accessor has been added, which
always caches the last written value.

[2017_R1] iio: adc: ad9361: add ad9361_write_bist_reg() accessor to cache bist reg value

---

.travis.yml

This PR introduced then broken .travis.yml file.
https://github.com/analogdevicesinc/linux/pull/63/commits
The merge button was green when the change was not merged.
Apparently that only meant that the code did not have any conflicts.
The last Travis run was on the commit that ran before the commit the broke
the .travis.yml file.
Travis does not seem to highlight very well on Github if a .travis.yml
file is malformed.

.travis.yml: fix malformed yaml file 

---

arch/microblaze/boot/dts/adi-fmcjesdadc1.dtsi
arch/microblaze/boot/dts/kc705_fmcdaq2.dts
arch/microblaze/boot/dts/kc705_fmcdaq2_pl.dtsi
arch/microblaze/boot/dts/kc705_fmcjesdadc1.dts
arch/microblaze/boot/dts/kc705_fmcjesdadc1_pl.dtsi
arch/microblaze/boot/dts/vc707_fmcdaq2.dts
arch/microblaze/boot/dts/vc707_fmcdaq2_pl.dtsi
arch/microblaze/boot/dts/vc707_fmcjesdadc1.dts
arch/microblaze/boot/dts/vc707_fmcjesdadc1_pl.dtsi

These device trees were not updated to ADI JESD204 link-layer peripherals in the previous release.

Mb dts updates

---

.travis.yml
drivers/iio/jesd204/altera_adxcvr.c

The altera_adxcvr driver currently only supports up to 4 lanes. The number
of lanes of the hardware is read from a configuration register and if it
exceeds 4 the driver will exhibit undefined behavior.
Increase the number of supported lanes to 32, that should be enough for a
while.
Also add a check to prevent undefined behavior if the hardware has more
transceivers than what the driver supports.

iio: altera_adxcvr: Support more than 4 lanes

---

Documentation/devicetree/bindings/iio/jesd204/adi,jesd204-rx.txt
Documentation/devicetree/bindings/iio/jesd204/adi,jesd204-tx.txt
arch/microblaze/boot/dts/adi-fmcjesdadc1.dtsi
arch/microblaze/boot/dts/kc705_fmcdaq2.dts
arch/microblaze/boot/dts/kc705_fmcdaq2_pl.dtsi
arch/microblaze/boot/dts/kc705_fmcjesdadc1.dts
arch/microblaze/boot/dts/kc705_fmcjesdadc1_pl.dtsi
arch/microblaze/boot/dts/vc707_fmcdaq2.dts
arch/microblaze/boot/dts/vc707_fmcdaq2_pl.dtsi
arch/microblaze/boot/dts/vc707_fmcjesdadc1.dts
arch/microblaze/boot/dts/vc707_fmcjesdadc1_pl.dtsi

Follow up to  PR #68.
Changes vs PR #68 :
* added documentation adapted from ADI Wiki ; so that `checkpatch.pl` does not throw any warnings
* minor re-format of commit comments to fit in the 75 col-width limits ;

microblaze: dts: update ADI JESD204 link-layer peripherals

---

drivers/iio/adc/ad9361.c
drivers/iio/adc/ad9361.h

This adds the option to set: [D6:D4]—Fast Attack Only.
Decrement Step Size for: Small LPF Gain Change/Full Table Case
If not set the value defaults to 2.
Similar to PR #20

iio: adc: ad9361: Add option to set Reg Gain Step Config2 0x106 [D6:D4]

---

.travis.yml

This change extends the matrix to also test out the build of the ZynqMP
target, which is an ARM64 machine.
It will increase the test coverage a bit.

.travis.yml: add ZynqMP to the build run

---

Documentation/ABI/testing/sysfs-class-power-adp5061
MAINTAINERS
drivers/power/supply/adp5061.c

This set of patches adds four new features:
1. enable/disable battery charging
2. enable/disable charging voltage limit
3. read the charger status 
4. read the battery status
The first two features are not configurable via the power_supply properties, therefore access via sysfs was provided to examine and modify these attributes on the fly.

Master adp5061 support misc

---

drivers/iio/adc/ad9361.c
drivers/iio/adc/ad9361.h

iio: adc: ad9361: Validate MAX Half Band filter rates
The Half Band decimation and interpolation filters do have some max rate
they can run on. Typically the driver itself or AD9361 filter wizard
takes these into account. However recently we discovered a corner case
where max TX_HB1 rate of 160MSPS could have been exceed by using a
interpolate by 4 FIR filter and a Baseband rate of > 40 MSPS.
This patch adds a check for all max ratings of BBPPL, ADC, DAC, HB3, HB2
and HB1 filters in the system.

Validate hb rates

---

drivers/iio/frequency/cf_axi_dds.c

This fixes the driver unbinding issue reported here:
https://ez.analog.com/thread/105269-fmcomms5-getting-error-9-on-iiobufferrefill

Fix cf axi dds issues

---

drivers/iio/accel/adxl372.c

This set of patches does two things:
* replaces the DMA buffer with integers on stack, because for regmap DMA buffer is not needed.
* replaces `adxl372_spi_write_mask()` with `regmap_update_bits()` which does the same thing.

Rpi 4.9.y adxl372 regmap fixes

---

drivers/iio/adc/ad9361.c
drivers/iio/adc/ad9361.h
drivers/iio/adc/ad9361_private.h

Note PR: split away from PR #81 to reduce the review effort for that PR.
----------------------------------------
The TX/RX port selection can be controlled via sysfs, so it makes sense to
make it a member of the state struct [vs the platform data struct].
Added accessor functions to update the selections, and to validate the
input.
The accessor functions will be used later in the band control.

iio: adc: ad9361: move RX/TX port selection on state struct

---

arch/arm/boot/dts/zynq-sidekiqz2-revb.dts

RevA won't exist; no need to keep references about it.
Fix GPIO reset pin in device-tree.
Previously Pluto's reset pin was being used because there were 2 `reset-gpios` and `reset-gpio` properties in the device-tree.
Both are valid, but `-gpios` suffixes take precedence, and they don't override the `-gpio` properties.

sidekiqz2: renamed dts to Rev B and fix GPIO reset reference in device-tree

---

drivers/iio/adc/ad9361.c

The gpiod_set_value() invocation for the reset pin always happens in a context where sleeping is possible. Use gpiod_set_value_cansleep() to indicate this. This will make sure that GPIO drivers that will sleep can be used to driver the reset GPIO.

iio: adc: ad9361: use gpiod_set_value_cansleep() when resetting chip

---

drivers/gpio/gpiolib-of.c
drivers/gpio/gpiolib.c
include/dt-bindings/gpio/gpio.h
include/linux/of_gpio.h

Note [Alexandru Ardelean]: the SidekiqZ2 reset pin is an open drain, however it doesn't behave like one when the `ad9361_reset()` code runs. Because the GPIO_OPEN_DRAIN OF property has the GPIO_ACTIVE_LOW flag, the value is inverted. So, when doing `gpiod_set_value(0)` the final open-drain code is `_gpio_set_open_drain_value(1)`, which is not what we want.
[ upstream commit 4c0facddb7d8 ("gpio: core: Decouple open drain/source
flag with active low/high") ]
Currently, the GPIO interface is said to Open Drain if it is Single
Ended and active LOW. Similarly, it is said as Open Source if it is
Single Ended and active HIGH.
The active HIGH/LOW is used in the interface for setting the pin
state to HIGH or LOW when enabling/disabling the interface.
In Open Drain interface, pin is set to HIGH by …

[backport] gpio: core: Decouple open drain/source flag with active low/high

---

arch/arm/boot/dts/zynq-sidekiqz2-revb.dts

This GPIO will not be toggled during normal operation, so enable it at
startup and leave it like that.
PR note: this has been split away from PR #81 to reduce number of commits to review in that cycle.

arch: arm: sidekiqz2: add LNA_SW gpio as hog in the U21 expander

---

Documentation/devicetree/bindings/mux/adi,adgs140x.txt
MAINTAINERS
arch/arm/boot/dts/bcm2710-rpi-3-b.dts
drivers/mux/Kconfig
drivers/mux/Makefile
drivers/mux/adgs140x.c

mux:adgs1408/1409: New driver for Analog Devices ADGS1408/1409 mux  …
This patch adds basic support for Analog Device ADGS1408/09 SPI mux
controller.
The device is probed and set to a disabled state. It uses the new mux
controller framework.

Adgs1408 driver

---

arch/arm64/boot/dts/xilinx/adi-daq2.dtsi

AD-FMCDAQ2-EBZ is described as a Dual Channel 1GSPS Data Acquisition Kit.
Increase the ADC sampling rate from 500 MSPS to 1 GSPS.

arm64: dts: adi-daq2: Increase ADC sampling rate

---

arch/arm/boot/dts/zynq-sidekiqz2-revb.dts

The SidekiqZ2 has the AD9364 chip onboard.
The Pluto dtsi defines AD9363A.
Added GPIO line names for GPIO expanders to make debugging easier.

SidekiqZ2: define GPIO line-names [for debugging] and use AD9364 chip

---

Documentation/devicetree/bindings/iio/adc/adi,ad9361.txt

Adapted from this wiki page:
https://wiki.analog.com/resources/tools-software/linux-drivers/iio-transceiver/ad9361-customization

devicetree: add AD9361 dt-bindings documentation

---

drivers/iio/adc/Makefile
drivers/iio/amplifiers/ad8366.c
include/linux/iio/iio.h

The biggest change in this PR is the re-organization of the Makefile in `drivers/iio/adc`.
Something similar will be done in the rebased branches.
Sync-ed 2 more files with upstream.
* iio: amplifiers: ad8366 - remove `linux/of.h` include]
* one left-over end-of-comment was updated with upstream's

Sync master with more bits from upstream and re-organize iio/adc Makefile

---

arch/nios2/boot/dts/a10gx_daq2.dts

The FPGA system features now a PL (Programmable Logic) FIFO, so this attribute
should be set.

Enable DAC PL FIFO for a10gx_daq2

---

drivers/iio/dac/ad7303.c

These patches are not present in the ADI tree.
They are present in the ADI history, but they were probably reverted by accident at some point in time.
This changeset, brings them back.

[backports] iio: adc: ad7303: backport upstream patches

---

drivers/iio/adc/ad6676.c

The reset value of the attenuation is according to the datasheet 12 dB
but pdata->base.attenuation was incorrectly set to 0.

iio: ad6676: Fix default attenuation value

---

Documentation/devicetree/bindings/iio/dac/ad5758.txt
drivers/iio/dac/ad5758.c

The ad5758 has a hardware reset active low input pin. This patch adds a
devicetree entry for a reset GPIO and a new ad5758_reset() function. This
function checks if the reset property is specified and asserts the GPIO
during probe, otherwise, a software reset is performed.

iio: dac: ad5758: Add support for hard reset

---

drivers/iio/Kconfig
drivers/iio/logic/Kconfig
drivers/iio/logic/Makefile

Otherwise the M2k logic analyzer always gets built for all devices, and we
don't need this for RPis and some other targets.

iio: logic: add Kconfig menu for logic analyzers

---

drivers/iio/dac/ad5758.c

The output field which is part of the iio_chan_spec struct should be set
to 1.

iio: ad5758: The DAC channel should be output

---

arch/arm/boot/dts/zynq-zed-adv7511-fmcmotcon2.dts

Revert https://github.com/analogdevicesinc/linux/commit/9476d7e27a7516f96dc0bac6199033a00b4a8549
MACB seems to support only a single PHY per MDIO interface. FMCMOTCON2 has two
PHYs per MDIO.

dts: fmcmotcon2: Switch from Cadence to Xilinx Ethernet driver

---

drivers/iio/frequency/ad9517.c

Thus series starts with a few fixes and cleanups for the ad9517 driver and then goes on to add support for the ad9516 and ad9518 which are similar in design but differ in the number of output channels.

AD9517 updates and AD9516 and AD9518 support

---

drivers/clk/clk-axi-clkgen.c

Since axi-clkgen is now supported on ZYNQMP, make sure the max/min
frequencies of the PFD and VCO are respected.
Numbers pulled from the Zynq UltraScale+ datasheet (DS925) for the lowest speedgrade.
Not sure if ARCH_ZYNQMP is the right def to base this on?

clk: axi-clkgen: Respect ZYNQMP PFD/VCO frequency limits

---

drivers/iio/jesd204/axi_adxcvr.c

Currently the axi_adxcvr driver adjusts the div40 clock rate after the lane
rate has been updated.
But when the div40 clock is equal to the reference clock of the transceiver
PLL, like it is in some designs, it is necessary to adjust the reference
clock rate to the new target rate before computing the PLL.
This enables dynamic reconfiguration of the lane rate on these platforms.

iio: axi_adxcvr: Add support for when the ref clock is equal to the div40 clock

---

drivers/net/ieee802154/adf7242.c

These changes are also present in upstream, but with a different format.
Sync with upstream format.
The reference branch is Jonathan Cameron's `togreg`:
https://git.kernel.org/pub/scm/linux/kernel/git/jic23/iio.git

net: ieee802154: adf7242: sync upstream changes (formatting)

---

arch/arm64/boot/dts/xilinx/adi-adrv9009.dtsi
arch/arm64/boot/dts/xilinx/zynqmp-zcu102-rev10-adrv9009.dts
drivers/iio/adc/ad_adc.c

This adds support for both ORX channels. This patch has a HDL counterpart.
We should merge them to master in sync. 
Should not be merged into 2018_R1.

iio adrv9009 dual observation support

---

drivers/iio/frequency/ad9528.c

When updating the register with the new output clock divider the LSB of
previous value is not properly cleared due to how the mask is computed.
E.g. going from a divider value of 0x1 to 0x2 will result in a value of 0x3
to be written to the register, resulting in the wrong divider settings.
Fix this by explicitly defining the mask rather then trying to use some
macro magic. Do this for all register fields that are updated for
consistency and to avoid future problems.

iio: ad9528: Fix updating clock output rate

---

drivers/iio/frequency/ad9144.c
drivers/iio/frequency/ad9144.h
drivers/iio/frequency/ad9162.c
drivers/iio/frequency/cf_axi_dds.h

This series updates the AD9144 driver to match the latest datasheet recommendation, adds support for configuring all JESD204 modes of the device and also adds support for the AD9135/AD9136.

AD9144 Updates

---

Documentation/devicetree/bindings/iio/adc/adi,ad7768.txt
MAINTAINERS
arch/arm/boot/dts/zynq-zed-adv7511-ad7768.dts
drivers/iio/adc/Kconfig
drivers/iio/adc/Makefile
drivers/iio/adc/ad7768.c

The ad7768 is an 8-channel, 24-bit resolution ADC.
In standard mode, ad7768 operates as the master and streams data to the
DSP or FPGA. The ad7768 supplies the data, the data clock (DCLK) and a
falling edge framing signal (DRDY) to the slave device.
In this version of the driver the default configuration is set:
- eco power mode
- interface configuration of DCLK = MCLK/8, with CRC disabled
- filter configuration is set to sinc5 and decimation = x1024
- continuous conversion mode

Master ad7768 support

---

drivers/dma/dma-axi-dmac.c

Starting with version 4.1.a the AXI-DMAC is capable of reporting the
required length alignment.
The LSBs that are required to be set for alignment will always read back as
set from the transfer length register. It is not possible to clear them by
writing a 0. This means the driver can discover the length alignment
requirement by writing 0 to that register and reading back the value.
Since the DMA will support length alignment requirements that are different
from the address alignment requirement track both of them independently.
For older versions of the peripheral assume that the length alignment
requirement is equal to the address alignment requirement.

dma: axi-dmac: Discover length alignment requirement

---

drivers/iio/buffer/kfifo_buf.c

This patch resolves a bug introduced in c559afbfb08c7eac215ba417251225d3a8e01062 where the element size and length was used to set up the FIFO, instead of just the required number of bytes.
The patch has been tested on a TI OMAP4460, using a custom IIO device whose buffer contains samples made up of two 16-bit signed integers. This patch also resolves issue #143.
Signed-off-by: Michael Allwright <allsey87@gmail.com>

iio: Fix kfifo checks in iio_kfifo_remove_from

---

Documentation/devicetree/bindings/iio/frequency/hmc7044.txt
drivers/iio/frequency/Kconfig
drivers/iio/frequency/Makefile
drivers/iio/frequency/hmc7044.c

HMC7044 is a high performance, dual-loop, integer-N jitter attenuator
capable of performing reference selection and generation of ultralow
phase noise frequencies for high speed data converters with either
parallel or serial (JESD204B type) interfaces.

iio: frequency: New driver for HMC7044

---

Documentation/devicetree/bindings/iio/adc/adi,ad7768.txt
arch/arm/boot/dts/zynq-zed-adv7511-ad7768.dts
drivers/iio/adc/ad7768.c

This patch set adds the option for the user to set the sampling frequency. In
order to accomplish this, the master clock signal (MCLK) must be provided
in the device-tree.
MLCK signal is used to define the digital output clock (DCLK). Divider
settings for MCLK and DCLK in conjunction with the digital filter
decimation rate further determine the sampling frequency.
The user can input the desired sampling frequency and by controling MCLK
and DCLK division, the closest valid rate will be set. The power mode
(fast, median or eco) is also modified with every MCLK_DIV change.

Master ad7768 samp freq support

---

drivers/iio/dac/ad5770r.c

This patch adds the output filter resistor functionality. This is done using IIO_ENUM and IIO_ENUM_AVAILABLE. A new attribute has also been documented.

Ad5770r iio driver

---

drivers/media/i2c/ad9389b.c

These patches were added a long time ago in the kernel (~2013).
Seems they disappeared during some merges.
This PR brings them back.

[media] ad9389b: re-apply ommited patches

---

drivers/bus/Kconfig
drivers/usb/chipidea/host.c

These newlines (white-spaces) have been added during merges.
Upstream doesn't have these, so remove them to make things easier to diff.

treewide: sync white-space with upstream

---

drivers/iio/jesd204/axi_jesd204_rx.c

Starting with version 1.02.a the JESD204 RX core counts the number of
invalid characters that were received over the link for each lane.
Expose this information through the lane status file. It can be helpful
for debugging and also characterizing the lane integrity performance.

iio: jesd204_rx: Add error statistics to lane status info

---

arch/arm/boot/dts/adi-fmcomms2.dtsi
arch/arm/boot/dts/adi-fmcomms4.dtsi
arch/arm/boot/dts/adi-fmcomms5.dtsi
arch/arm/boot/dts/zynq-adrv9361-z7035.dtsi
arch/arm/boot/dts/zynq-adrv9364-z7020.dtsi
arch/arm/boot/dts/zynq-e310.dts
arch/arm/boot/dts/zynq-pluto-sdr.dtsi
arch/arm64/boot/dts/xilinx/adi-fmcomms2.dtsi
arch/arm64/boot/dts/xilinx/adi-fmcomms4.dtsi
arch/arm64/boot/dts/xilinx/adi-fmcomms5.dtsi
arch/microblaze/boot/dts/adi-fmcomms2.dtsi
arch/microblaze/boot/dts/adi-fmcomms4.dtsi
drivers/iio/adc/ad9361.c
drivers/iio/adc/ad9361.h
drivers/iio/adc/ad9361_private.h

This small series fixes the out_volatge_hardwaregain_available readings. And introduces a new TX LO power-down managed mode, which is then made the default for all ad936x based boards and modules.

Misc ad9361 driver and dt fixes

---

Documentation/devicetree/bindings/iio/frequency/hmc7044.txt
drivers/spi/spi.c
include/linux/spi/spi.h

Transmit/receive only is a valid SPI mode. For example, the MOSI line
might be missing from an ADC while for a DAC the MISO line may be
optional. This patch adds these two new modes: SPI_NO_MOSI and
SPI_NO_MISO. This way, the drivers will be able to identify if any of
these two lines is missing and to adjust the transfers accordingly.

devicetree: bindings: hmc7044: Spelling fix & spi: Add NO_MOSI/MISO support

---

drivers/gpu/drm/bridge/adv7511/adv7511_drv.c

adv7511->i2c_main must be initialized prior in calling
adv7511_init_regulators().
This fixes this kernel panic:
i2c i2c-0: Added multiplexed i2c bus 1
Unable to handle kernel NULL pointer dereference at virtual address 00000174
pgd = c0004000
[00000174] *pgd=00000000
Internal error: Oops: 5 [#1] PREEMPT SMP ARM
Modules linked in:
CPU: 1 PID: 1 Comm: swapper/0 Not tainted 4.14.0-11988-g7ede93a #2457
Hardware name: Xilinx Zynq Platform
task: ef03f840 task.stack: ef040000
PC is at _raw_spin_lock_irqsave+0x28/0x64
LR is at devres_add+0x18/0x38
pc : [<c06a99d8>]    lr : [<c03af8d8>]    psr: 40000193
sp : ef041be0  ip : 00000000  fp : 00000000
r10: 00000000  r9 : c073d078  r8 : 00000020
r7 : ef387790  r6 : 00000020  r5 : 00000020  r4 : 00000174
r3 : ef040000  r2 : 00000174  r1 : 00000001  r0 : …

gpu: drm: bridge: adv7511: Fix de-referencing initialized pointer

---

drivers/iio/accel/bmc150-accel-core.c
drivers/iio/accel/kxcjk-1013.c
drivers/iio/accel/kxsd9.c
drivers/iio/accel/stk8312.c
drivers/iio/accel/stk8ba50.c
drivers/iio/adc/ad7766.c
drivers/iio/adc/dln2-adc.c
drivers/iio/adc/mxs-lradc-adc.c
drivers/iio/adc/stm32-adc.c
drivers/iio/adc/ti-adc084s021.c
drivers/iio/adc/ti-ads1015.c
drivers/iio/adc/vf610_adc.c
drivers/iio/chemical/atlas-ph-sensor.c
drivers/iio/gyro/bmg160_core.c
drivers/iio/gyro/mpu3050-core.c
drivers/iio/humidity/hdc100x.c
drivers/iio/humidity/hts221_buffer.c
drivers/iio/light/rpr0521.c
drivers/iio/light/si1145.c
drivers/iio/magnetometer/bmc150_magn.c
drivers/iio/potentiostat/lmp91000.c
drivers/iio/pressure/zpa2326.c
drivers/iio/proximity/sx9500.c

This amends commit eee97d12665fef8c ("iio: Move attach/detach of the poll
func to the core").
A lot of drivers were updated since this patch was added and we need to
update all of them until a consensus is reached upstream about whether to
do this patch (upstream) or not (in which case we will need to revert it).

iio: Move attach/detach of the poll func to the core (part2)

---

drivers/spi/spi.c
include/linux/spi/spi.h

Should prevent dead-locks when SPI-to-SPI bridges are added.
Upstream kernel has a local lock defined via commit e48880e02e7e7 ("spi:
bugfix spi_add_device() with duplicate chipselects").

spi: move registration lock to master SPI device struct

---

drivers/bus/Kconfig

Was removed via a merge commit.
Only helps for diff-ing with branch `adi-4.14.0`.

drivers/bus/Kconfig: add back empty line

---

drivers/iio/frequency/ad9517.c

One small fix and then some re-structuring to allow to use the AD9517 driver without having to provide any firmware files that provide the initial register settings.

Allow AD9517 firmware less operation

---

drivers/gpio/gpio-adp5588.c

This fixes some bugs reported on lkml:
[BUG] gpio: gpio-adp5588: A possible sleep-in-atomic-context bug
in adp5588_gpio_write()
[BUG] gpio: gpio-adp5588: A possible sleep-in-atomic-context bug
in adp5588_gpio_direction_input()
The driver may sleep with holding a spinlock.
The function call paths (from bottom to top) in Linux-4.16 are:
[FUNC] mutex_lock_nested
drivers/gpio/gpio-adp5588.c, 113: mutex_lock_nested in adp5588_gpio_direction_input
drivers/gpio/gpio-adp5588.c, 224: adp5588_gpio_direction_input in adp5588_irq_set_type
kernel/irq/manage.c, 686: [FUNC_PTR]adp5588_irq_set_type in __irq_set_trigger
kernel/irq/manage.c, 1350: __irq_set_trigger in __setup_irq
kernel/irq/manage.c, 1238: _raw_spin_lock_irqsave in __setup_irq 
Reported-by: Jia-Ju Bai <baijiaju1990@gmail.com>

drivers: gpio: gpio-adp5588: Fix sleep-in-atomic-context bug

---

arch/arm/boot/dts/adi-adrv9371.dtsi
arch/arm64/boot/dts/xilinx/adi-adrv9371.dtsi
arch/microblaze/boot/dts/adi-adrv9371.dtsi
drivers/iio/adc/ad9371.c

Add support for loading FIR filters, ADC and loopback ADC profiles via
device tree. And update all device trees.
Note: Negative filter coefficient values must be encapsulated in braces!

iio: adc: ad9371: Add support for FIR, ADC and loopback profiles via dt

---

drivers/iio/adc/ad9371.c
drivers/iio/adc/ad9371.h

This debug attribute configures the monitor output function for the GPIOs
The monitor outputs are grouped in set of nibbles, the user can set
individual nibbles for having the monitor output function across the
available GPIO. In order to enable the GPIO monitor function the
function setupGpio has to be run and the
structure should have the proper setup:
- device->auxIo->gpio->gpioOe = 0xXXXFF the first D7:D0 GPIOs will
have the output enable
- device->auxIo->gpio->gpioSrcCtrl3_0 = GPIO_MONITOR_MODE
- device->auxIo->gpio->gpioSrcCtrl4_7 = GPIO_MONITOR_MODE

iio: adc: ad9371: Add support for set/get GPIO Monitor Out via debugfs

---

drivers/iio/frequency/cf_axi_dds.c
drivers/iio/frequency/cf_axi_dds.h
drivers/iio/frequency/cf_axi_dds_buffer_stream.c

In case the user requests streaming transfers the FIFO must be disabled.

cf-axi-dds: handle fifo bypass

---

arch/arm/boot/dts/zynq-adrv9361-z7035-fmc.dts
arch/arm/boot/dts/zynq-zc702-adv7511.dtsi
arch/arm/boot/dts/zynq-zc706-adv7511.dtsi
arch/arm/boot/dts/zynq-zed-adv7511.dtsi
arch/arm/boot/dts/zynq-zed-imageon.dts
drivers/dma/dma-axi-dmac.c
drivers/gpu/drm/adi_axi_hdmi/axi_hdmi_crtc.c

This should be merged when the corresponding HDL changes will be also merged:
https://github.com/analogdevicesinc/hdl/pull/106

Use the ADI's DMA as VDMA

---

arch/arm64/boot/dts/xilinx/zynqmp-zcu102-rev10-ad9361-fmcomms5.dts

This core must be named cf-ad9361-A otherwise the FMCOMMS5 advanced
plugin refuses to load.

arm64: dts: zynqmp-zcu102-rev10-ad9361-fmcomms5.dts: Fix core name

---

drivers/gpu/drm/adi_axi_hdmi/axi_hdmi_encoder.c

Newer IP versions ignore the AXI_HDMI_CTRL_FULL_RANGE bit and implement
two clip registers. Set the clip registers to 0..0xff in all three channels
when in test or RGB mode, and to YCrCb standard levels otherwise.
This fixes the problem that with the newer IP the monitor was unable to
display full back or white.
Signed-off-by: Mike Looijmans <mike.looijmans@topic.nl>

drm: axi_hdmi_encoder: Expand colorspace range for RGB mode

---

Documentation/devicetree/bindings/iio/accel/adxl372.txt
drivers/base/regmap/internal.h
drivers/base/regmap/regmap.c
drivers/iio/accel/adxl372.c
include/linux/regmap.h

The adxl372 driver deviates from the upstream version which was modified
according to the feedback received during review.
The only difference is that the upstream driver calls directly the
iio_triggered_buffer_postenable() and iio_triggered_buffer_predisable()
functions which is not necessary according to eee97d1 patch.

adxl372: Align with upstream version

---

drivers/misc/mathworks/mathworks_ip_common.c
drivers/misc/mathworks/mw_stream_channel.c

On ARM, this reports as a compiler warning/error:
```
drivers/misc/mathworks/mathworks_ip_common.c:218:14: error: initialization from incompatible pointer type [-Werror=incompatible-pointer-types]
.fault = mathworks_ip_mmap_fault,
drivers/misc/mathworks/mw_stream_channel.c:785:23: error: initialization from incompatible pointer type [-Werror=incompatible-pointer-types]
.fault          = mwadma_mmap_fault,
```
It was omitted during merge.
This patch updates the function type to the new required format.

drivers: mathworks: fix functions type for vm fault

---

drivers/iio/accel/adxl372_i2c.c

Before the 3rd revision of the chip, the I2C communication was not
working properly if there were any other I2C devices present on the bus.
Howerver, if adxl372 is the only device, then it should still work, this
is why it is enough to just print a warning and continue with the device
probe.

iio: adxl372: Fix revid check

---

Documentation/devicetree/bindings/iio/dac/ad5758.txt
MAINTAINERS
drivers/iio/dac/Kconfig
drivers/iio/dac/Makefile
drivers/iio/dac/ad5758.c

The ad5758 driver was developed on the rpi branch and then sent upstream. This PR wants to backport 3 commits that have already been accepted upstream.

Master ad5758 upstream backport

---

drivers/dma/dma-axi-dmac.c

It doesn't look like the 2D transfers were used much, prior to commit
81b810593ebcf1a537042704c8363bbaafbcba0b, so this may have not received
much attention.
There is no requirement for Y_LENGTH to be aligned to the bus-width (or
anything). X_LENGTH is required to be aligned though.
So, we shouldn't check that the number of frames is aligned.

dma: axi-dmac: don't check the number of frames for alignment

---

drivers/iio/adc/ad9361.c
drivers/iio/adc/ad9361.h
drivers/iio/adc/ad9361_conv.c

Using the new AD9361's driver format, this is required to
avoid includind the ad9361_private.h header.

iio: adc: ad9361: Add ad9361_axi_half_dac_rate() accessor

---

sound/soc/codecs/hdmi-codec.c

Commit 943fa0228252 ("ASoC: hdmi-codec: Use different name for playback
streams") broke hdmi-codec's routing between it's output "TX" widget
and the S/PDIF or I2S streams by renaming the streams.
Whether an error occurs or not is dependent on whether there is another
widget called "Playback" registered by some other component - if there
is, that widget will be (incorrectly) bound to the HDMI codec's "TX"
output widget.  If we end up connecting "TX" incorrectly, it can result
in components not being started, causing no audio output.
Since the I2S and S/PDIF streams now have different names, we can't
use a static route at component level to describe the relationship, so
arrange to dynamically create the route when the DAI driver is probed.
Fixes: 943fa0228252 ("ASoC: hdmi-codec: Use …

ASoC: hdmi-codec: fix routing

---

drivers/iio/industrialio-core.c

Commit 9823c72f97ab ("iio: Handle enumerated properties with gaps") added
support for handling enum properties with gaps.
This seems to have been broken during the merge with 4.14, but only on the
`iio_enum_write()` path. The `iio_enum_read()` &
`iio_enum_read_available()` functions were merged properly.
This commit also reverts commit 02e9a0ff0d7a ("iio: core: Use
__sysfs_match_string() helper").

iio: core: fix enums with gaps

---

drivers/iio/adc/adrv9009.c

This fixes a typo which caused in_voltage1_gain_control_pin_mode_en to
return the value for in_voltage0_gain_control_pin_mode_en.

iio: adc: adrv9009: Fix get in_voltage1_gain_control_pin_mode_en for RX2

---

drivers/misc/mathworks/mathworks_generic_pci.c

The `pci_enable_msi_range()` function was removed in commit
f46de3644aef7d328 ("PCI/MSI: Remove pci_enable_msi_{exact,range}()").
The recommended alternative is `pci_irq_alloc_vectors()`.
This change updates this driver to use it.

drivers: mathworks: update PCI code

---

drivers/misc/mathworks/mw_stream_channel.c

On 64 bits, `unsigned long` and `unsigned int` differ in size, causing
compile-time errors:
```
./include/linux/thread_info.h:139:19: error: call to ‘__bad_copy_from’ declared with attribute error: copy source size is too small
__bad_copy_from();
./include/linux/thread_info.h:141:17: error: call to ‘__bad_copy_to’ declared with attribute error: copy destination size is too small
__bad_copy_to();
^
```
We need to fix this by adjusting the types of the data that get copied
to/from the user-space.

drivers: mathworks: fix copy sizes

---

drivers/iio/adc/adrv9009.c

The profile wizard may generate not just 2, 2.5, 3, 4, 5 but also
2.0, 3.0, etc. This patch takes care of that.

iio: adc: adrv9009: Handle <clkPllHsDiv=X.0> cases in parse profile

---

.travis.yml
ci/travis/run-build.sh
drivers/misc/mathworks/mw_stream_iio_channel.c

Fixes #212 
Commit b24d8b04bed3 ("iio: Remove buffer_impl.h include from buffer.h") has
removed a temporary workaround for the `buffer.h` that upstream IIO did.
The MathWorks IIO driver was omitted in that changeset.
This change fixes it.
Also added compile-test builds.
We sometimes miss few silly things, because our builds don't go through
all the source code, because we don't cover them in defconfigs.
The kernel has a `COMPILE_TEST` Kconfig flags, so we enable it to try
to address this.
This should extend code-coverage by compiling more code.
This won't necessarily compile everything, but will extend coverage to
parts we don't have in our main defconfigs (like MathWorks driver), and we
may extend stuff to go under this Kconfig symbol later.
Signed-off-by: Alexandru Ardelean …

 drivers: mathworks: fix iio buffer include + add COMPILE_TEST builds

---

drivers/iio/adc/ad9680.c
drivers/misc/mathworks/mw_stream_channel.c

This fixes 2 compiler warnings that were noticed in the Travis-CI build.
There are still some warnings left to look at, but these are the low-hanging-fruit ones.

fix some compiler warnings

---

drivers/iio/jesd204/axi_adxcvr_eyescan.c

If a signal is received while waiting return -EINTR.

iio: jesd204: axi_adxcvr_eyescan: Allow eyescan cancel

---

arch/nios2/boot/dts/a10gx_adrv9371.dts

Add the option to bypass the PL FIFO and use the regular DMA instead,
since the FPGA reference design already supports this feature.

dts: a10gx_adrv9371: Add bypass support for PL FIFO

---

Documentation/devicetree/bindings/iio/adc/adi,ad7124.txt
MAINTAINERS
drivers/iio/adc/Kconfig
drivers/iio/adc/Makefile
drivers/iio/adc/ad7124.c

The ad7124-4 and ad7124-8 are a family of 4 and 8 channel sigma-delta ADCs
with 24-bit precision and reference.
Three power modes are available which in turn affect the output data rate:
* Full power: 9.38 SPS to 19,200 SPS
* Mid power: 2.34 SPS to 4800 SPS
* Low power: 1.17 SPS to 2400 SPS
The ad7124-4 can be configured to have four differential inputs, while
ad7124-8 can have 8. Moreover, ad7124 also supports per channel
configuration. Each configuration consists of gain, reference source,
output data rate and bipolar/unipolar configuration.
Datasheets:
http://www.analog.com/media/en/technical-documentation/data-sheets/AD7124-4.pdf
http://www.analog.com/media/en/technical-documentation/data-sheets/ad7124-8.pdf

Master ad7124 support

---

drivers/iio/jesd204/axi_adxcvr.c
drivers/iio/jesd204/axi_adxcvr.h

Usage:
echo <axi|drp> [drp_port] <reg> [write-val] > reg_access
* Examples:
* AXI access:
root@analog:/sys/bus/platform/devices/44a60000.axi-adxcvr-rx# echo axi 8 0x1234  > reg_access
root@analog:/sys/bus/platform/devices/44a60000.axi-adxcvr-rx# cat reg_access
0x1234
* DRP Access:
root@analog:/sys/bus/platform/devices/44a60000.axi-adxcvr-rx# echo drp 1 0x88 > reg_access
root@analog:/sys/bus/platform/devices/44a60000.axi-adxcvr-rx# cat reg_access
0x20
root@analog:/sys/bus/platform/devices/44a60000.axi-adxcvr-rx# echo drp 1 0x88 0x21 > reg_access
axi-jesd204-rx 44aa0000.axi-jesd204-rx: Lane 0 desynced (10 errors), restarting link
root@analog:/sys/bus/platform/devices/44a60000.axi-adxcvr-rx# cat reg_access
0x21

iio: jesd204: adi_xcvr: Add direct register access debug interface

---

drivers/iio/jesd204/axi_jesd204_rx.c
drivers/iio/jesd204/axi_jesd204_tx.c

The LMFC rate can be useful information for selecting the SYSREF rate.
The SYSREF rate must be SYSREF = LMFC / N, where N must be positive
integers of 1,2,3, ...

iio: jesd204: axi_jesd204_[rx|tx]: Status add LMFC rate

---

Documentation/ABI/testing/sysfs-bus-iio-dma-buffer
arch/arm/boot/dts/zynq-zc706-adv7511-fmcdaq3.dts
drivers/iio/buffer/industrialio-buffer-dmaengine.c

The dmaengine buffer has some length alignment requirements that can differ
from platform to platform. If the length alignment requirements are not met
unexpected behavior like dropping of samples can occur.
Currently these requirements are not reported and applications need to know
the requirements of the platform by some out-of-band means.
Add a new buffer attribute that reports the length alignment requirements
called `length_align_bytes`. The reported length alignment is in bytes that
means the buffer length alignment in sample sets depends on the number of
enabled channels and the bytes per channel. Applications using this
attribute to determine the buffer size requirements need to consider this.

iio: buffer-dmaengine: Report buffer length requirements

---

drivers/usb/dwc3/core.h
drivers/usb/dwc3/ep0.c
drivers/usb/dwc3/gadget.c
drivers/usb/dwc3/gadget.h
drivers/usb/dwc3/gadget_hibernation.c
drivers/usb/dwc3/otg.c
drivers/usb/gadget/function/f_fs.c

Some backports from upstream kernel that seem to fix the remaining crashes of the DWC3 gadget driver when being used with IIOD.
The last patch is more of a workaround than a fix, but it is in upstream, so lets use it.
With these patches the board survived 1h of starting and stopping transfers every 5 seconds.

Fix dwc3 crashes

---

drivers/clk/zynqmp/clkc.c

The zynqmp clock driver does multiple memory allocations when registering a
clock but only ever frees the last allocation. Make sure that all
allocations are freed.
This is not critical since it is just a one time memory leak at system
initialization time, but it still shows up as noise in kmemleak.

clk: zynqmp: Fix memory leak

---

drivers/iio/buffer/industrialio-buffer-dma.c
drivers/iio/buffer/industrialio-buffer-dmaengine.c

Fix some warnings that occur in the IIO buffer code that only occur on 64-bit systems.

Fix some warnings that occur on 64-bit systems

---

drivers/iio/adc/adrv9009.c

Talise API version: 3.5.0.2 and earlier doesn't handle all documented
AGC modes. In order to avoid confusion remove them for now.
talise_rx.c:534
/* performing AGC type check */
switch (mode)
{
case TAL_MGC:
break;
case TAL_AGCSLOW:
break;
case TAL_AGCFAST: /* Fall through to next case */
case TAL_HYBRID:
return (uint32_t)talApiErrHandler(device, TAL_ERRHDL_INVALID_PARAM,
TAL_ERR_UNSUPPORTED_RX_GAIN_MODE_PARM, retVal, TALACT_ERR_CHECK_PARAM);
default:
return (uint32_t)talApiErrHandler(device, TAL_ERRHDL_INVALID_PARAM,
TAL_ERR_INV_RX_GAIN_MODE_PARM, retVal, TALACT_ERR_CHECK_PARAM);
}

iio: adc: adrv9009: Remove unhandled AGC modes

---

arch/arm/boot/dts/adi-ad9136-fmc-ebz.dtsi
arch/arm/boot/dts/adi-common-dac-fmc-ebz.dtsi
arch/arm/boot/dts/adi-intel-dac-fmc-ebz.dtsi
arch/arm/boot/dts/adi-xilinx-dac-fmc-ebz.dtsi
arch/arm/boot/dts/socfpga_arria10_socdk_ad9136_fmc_ebz.dts
arch/arm/boot/dts/socfpga_arria10_socdk_dac_fmc_ebz.dtsi
arch/arm/boot/dts/zynq-zc706-adv7511-ad9136-fmc-ebz.dts
drivers/iio/frequency/cf_axi_dds.c

Add the devicetrees for supporting the AD9136-FMC-EBZ connected to either the Arria10 SoC or ZC706 carrier.
The devicetrees have been split into multiple sub include devicetree files that can be used to easily add support for other similar DAC FMC boards that use the same HDL reference design.
Note that this will not work as is as long as the framer settings from the HDL are not propagated to the AD9144 driver. (Alternative is to manually change the AD9144 source to a different JESD204 link setting).

Add devicetrees for AD9136-FMC-EBZ

---

drivers/iio/frequency/ad9528.c

This patch adds support for controlling the SYSREF rate.
The 16-bit k-divider is a common between all SYSREF channels. This
means that the frequency of each SYSREF output can't be controlled
individually, so changing one will also set all other SYSREF channels.
However this is typically not an issue since this is how the device
designed, and JESD204 Subclass 1 requires this, too.

iio: frequency: ad9528: Add support for controlling the SYSREF rate

---

drivers/iio/frequency/ad9144.c
drivers/iio/frequency/ad9144.h

Two patches that add support for the internal PLL to the AD9144 driver as well as re-configuring the external SYSREF frequency to meet the requirements of the converter.

AD9144 PLL and SYSREF changes

---

Documentation/devicetree/bindings/clock/adi,adf4360.txt
drivers/clk/clk-adf4360.c

The driver currently only supports the ADF4360-8, add support for all
variants.
Special handling for the ADF4360-8 is still preserved for its usage on the
M2K board. This should eventually be removed.
The devicetree bindings aren't quire upstream yet and need to be reworked at some point.

clk: adf4360: Add support for ADF4360-0 through ADF4360-9

---

.travis.yml
ci/travis/run-build.sh

The checkpatch part generates all builds as red, if at least one format
element is wrong, which really reduces the value of builds.
Isolating the checkpatch and dtb builds into their own container,
highlights compile issues better, and if there are any checkpatch stuff
that's easy to fix, this can be re-spun in less than 10 minutes (which is
what a normal Linux build takes).

build,travis: split builds into smaller parts

---

arch/arm/boot/dts/zynq-zc706-adv7511-ad6676-fmc.dts
arch/arm/boot/dts/zynq-zc706-adv7511-ad9625-fmcadc2.dts
arch/arm/boot/dts/zynq-zc706-adv7511-fmcadc4.dts
arch/arm/boot/dts/zynq-zc706-adv7511-fmcdaq2.dts
arch/arm/boot/dts/zynq-zc706-adv7511-fmcdaq3.dts
arch/arm/boot/dts/zynq-zc706-adv7511-fmcjesdadc1.dts
arch/arm/boot/dts/zynq-zc706-adv7511-fmcomms11.dts
arch/arm64/boot/dts/xilinx/zynqmp-zcu102-rev10-fmcdaq2.dts
arch/arm64/boot/dts/xilinx/zynqmp-zcu102-rev10-fmcdaq3.dts

This update introduces a naming convention allowing the jesd-eye-scan-gtk
application to determine target devices.

dts: arm[64]: Update adi,axi-adxcvr-1.0 device names

---

drivers/iio/adc/ad7768.c

This patch adds iio_dmaengine_buffer_free in case of error or if the device
is removed.

iio: adc: ad7768: Fix iio_buffer removal

---

arch/microblaze/boot/dts/kc705_fmcomms2-3.dts
arch/microblaze/boot/dts/kcu105_fmcomms2-3.dts
arch/microblaze/boot/dts/vc707_fmcomms2-3.dts

Apparently all GPIO numbers are off by 32. Which is causing all kinds of
unexpected behaviour since the AD9361 RESETB is floating.
AD9361 GPIO are mapped via on the upper half of the dual axi-gpio
controller. Fixed by adding an offset of 32.
https://github.com/analogdevicesinc/hdl/blob/master/projects/fmcomms2/vc707/system_top.v#L132

microblaze: dts: [vc707|kc705|kcu105]_fmcomms2-3.dts: Fix GPIO numbers

---

arch/arm64/boot/dts/xilinx/adi-adrv9009.dtsi

commit: 69c3c384bade328eb4412bc9e3ef2ef33eb26ae9
devicetree: Cleanup adi-*.dtsi
Accidentally reverted the reg properties - This patch fixes it.

arm64: dts: adi-adrv9009.dtsi: Fix SPI reg properties

---

drivers/iio/adc/ad9361.c

This fixes external LO mode in TDD with SPI Control or whenever
LO POWER DOWN is forced.
ad9361 spi0.1: Calibration TIMEOUT (0x247, 0x2)

iio: adc: ad9361: Avoid checking LO synthesizer lock in power down mode

---

drivers/dma/dma-axi-dmac.c
drivers/dma/virt-dma.c
drivers/dma/virt-dma.h

This changeset implements residue computation for DMAC partial transfers.
It leverages the `callback_result` mechanism for populating the residue field.
A test has been adapted from other DMA tests to validate these changes and tested on a ZedBoard with a special HDL.
There may still be some things to tweak, but this is a initial set created for starting a review.
Some test runs:
```
root@analog:~# ./dmac_test.sh abcdefjhgdskqwerasjgfkjadgfjdgfjkslkdjfhsdajlk
Writing 52 bytes
adi_axi_dmac_test fpga-axi@0:axi_dmac_dmatest@0: Started 1 thread(s) using dma1chan0
adi_axi_dmac_test fpga-axi@0:axi_dmac_dmatest@0: DMA engine result: code 0, residue 1048556
adi_axi_dmac_test fpga-axi@0:axi_dmac_dmatest@0: Got via DMA: 'dcbahjfeksdgrewq'
adi_axi_dmac_test fpga-axi@0:axi_dmac_dmatest@0: DMA engine …
```

dma: axi-dmac: add support for partial transfers

---

drivers/dma/dmatest.c

Cherry-picked changes that bring the dmatest module closer to the upstream version.
This will serve as a base for our changes that will get added on top to test the AXI DMAC engine.

dmaengine: dmatest: backport upstream changes

---

Documentation/devicetree/bindings/iio/adc/adi,ad7124.txt
drivers/iio/adc/ad7124.c

The ad7124 driver deviates from the upstream version which was modified
according to the feedback received during review.
The most important difference is regarding the properties that were
added in the devicetree. The gain, and odr-hz properties did not belong
in the DT, while bipolar and diff-channels were defined as generic
properties.
Another change is that the scale can be set from the user space.

iio: adc: ad7124: Align with upstream version

---

Documentation/dmaengine/provider.txt
drivers/crypto/ccp/ccp-dmaengine.c
drivers/dma/at_hdmac.c
drivers/dma/dmaengine.c
drivers/dma/dmatest.c
drivers/dma/fsldma.c
drivers/dma/mv_xor.c
drivers/dma/nbpfaxi.c
drivers/dma/ste_dma40.c
drivers/dma/xgene-dma.c
drivers/dma/xilinx/zynqmp_dma.c
include/linux/dmaengine.h

This reverts commit d1797ba7285165859c754c6ff22fd77b7c74c0e6.
We don't use the Xilinx PCIE code, so we can revert their revert,
bringing us a bit closer to the upstream kernel.

[RFC] Revert "Revert "dmaengine: remove DMA_SG as it is dead code in kernel""

---

drivers/staging/iio/adc/ad7192.c
drivers/staging/iio/adc/ad7192.h

By adding this option we are able to remove the sync3 field and dt binding.
When setting the required cutoff frequency we also determine the ADC
configuration for chop and sync filter.
(cherry picked from commit 5f3cbb78cd77e3af5971568746d4fc61eeae84f3)

staging: iio: adc: ad7192: Add low_pass_3db_filter_frequency

---

drivers/iio/buffer/industrialio-buffer-dmaengine.c

A transfer may fall shorter than the bytes in the block.
This information is available in the residue from the DMA engine, so we can
compute actual `bytes_used` with that by subtracting the residue.

iio: buffer-dmaengine: adjust `bytes_used` with residue info

---

drivers/dma/dmatest.c

This change-set cleans up the `dmatest` module in the kernel to make it easier to add code to test DMA slave modes.
Currently, the test can only handle memcpy, memset, xor & pq modes/support.

 dmaengine: dmatest: re-structure the test to make adding things cleaner/easier (part 2)

---

drivers/iio/dac/ad5686.c

This patch solves the register readback issue with the bit shift. When the
dac resolution was lower than the register size (ex. 12 bits out of 16
bits) the readback value was not shifted with the difference in bits and
the value was higher. Also a mask is applied on the read value in order to get
the value relative to the actual bit size.

iio: dac: ad5686: Fix bit shift read register

---

Documentation/devicetree/bindings/iio/accel/adxl345.txt
drivers/iio/accel/Kconfig
drivers/iio/accel/adxl345.h
drivers/iio/accel/adxl345_core.c
drivers/iio/accel/adxl345_i2c.c
drivers/iio/accel/adxl345_spi.c

These patches are backports from upstream.
Patch hashes are from Linus' tree.

[backport] iio: accel: adxl345: add support for ADXL375

---

MAINTAINERS
drivers/iio/dac/Kconfig
drivers/iio/dac/Makefile
drivers/iio/dac/ad5686-spi.c
drivers/iio/dac/ad5686.c
drivers/iio/dac/ad5686.h
drivers/iio/dac/ad5696-i2c.c

We want to stop pushing code to the ADI rpi-4.14.y and only use master and adi-4.14.0 instead.
To do this, we should move the drivers that were pushed into that branch to master.
That way, we can have a central place for all ADI drivers, which is great when starting to upstream them.

[backport] iio:dac:ad5686: cherry-pick all patches from Linus' tree

---

arch/arm/boot/dts/zynq-e310.dts

This fixes a floating RX2 antenna port in FDD mode.

arm: dts: zynq-e310.dts: Fix VCRX_V1,V2 GPIO inversion

---

.travis.yml

The `xcomm_zynq` is the old master branch, which is kept in sync for legacy
reasons.
The `adi-4.14.0` branch is a rebased version of the current master branch;
this will need to be updated when the master branch will have a new kernel
version.

.travis.yml: exclude xcomm_zynq & adi-4.14.0 from Travis-CI build

---

drivers/dma/dmatest.c

The current mechanism for selecting DMA tests is pretty rigid, especially
when needing to add other DMA modes to test.
This allows for multiple combinations of tests to be done (memcpy + xor +
pq, etc), by selecting which tests to run. This should make it easier to
add more test-types (e.g. for DMA_SLAVE ops)
It re-uses the DMA transaction type enums, which makes things neater for
matching tests to transaction types.

dmaengine: dmatest: make DMA test selection dynamic

---

drivers/iio/adc/adrv9009.c

iio: adc: adrv9009: Add missing FHM API to set the next hop frequency

---

drivers/iio/adc/ad9361.c

Only if filt_[rx|tx]_bw_Hz is set in ad9361_parse_fir() use it otherwise
keep current RFBW for chain.

iio: adc: ad9361: Fix to prevent invalid RFBW setting during enable FIR

---

drivers/power/supply/adp5061.c

[ Upstream commit 89b135ba ]
We end up reading one element beyond the end of the adp5061_vmax[] array
here.
Fixes: fe8e81b7e899 ("adp5061: New driver for ADP5061 I2C battery charger")
Signed-off-by: Dan Carpenter <dan.carpenter@oracle.com>
Signed-off-by: Sebastian Reichel <sebastian.reichel@collabora.co.uk>

power: supply: adp5061: Fix a couple off by ones

---

arch/arm64/boot/dts/xilinx/zynqmp-zcu102-rev10-adrv9375.dts

arm64: dts: zynqmp-zcu102-rev10-adrv9375.dts: Add devicetree for AD9375

---

drivers/iio/frequency/ad9528.c

The role of the `clock-output-names` DT parameter (for a clock device) is
to specify the name of the output clock.
Currently the AD9528 would generate the same names as described in our
example DTs, but it would ignore the ones in the DT. This change makes sure
that the `clock-output-names` property can be used to override the names
of the clocks generated by this device/driver.

iio: ad9528: read clock-output-names from dt if available

---

Documentation/devicetree/bindings/iio/adc/adi,ad7768-1.txt
MAINTAINERS
drivers/iio/adc/Kconfig
drivers/iio/adc/Makefile
drivers/iio/adc/ad7768-1.c

This PR adds basic support for AD7768-1 ADC. 
The devices is configured in fast mode, with 32 kSPS and leaves the default sinc5 filter.
Two data conversion modes are made available. When data is retrieved by using the read_raw attribute, one shot single conversion mode is set. The continuous conversion mode is enabled when the triggered buffer mechanism is used. To assure correct data retrieval, the driver waits for the interrupt triggered by the low to high transition of the DRDY pin.
Another PR will add additional features such as the configuration of sampling frequency and bandwidth.

Master add ad7768 1 support

---

drivers/iio/adc/ad7768-1.c

The AD7768-1 core ADC receives a master clock signal (MCLK). The MCLK
frequency combined with the MCLK division and the digital filter
decimation rates, determines the sampling frequency. Along with
MCLK_DIV, the power mode is also configured according to datasheet
recommendations.
From user space, available sampling frequencies can be read. However,
it is not required for an exact value to be entered, since the driver
will look for the closest available match.
When the device configuration changes (for example, if the filter
decimation rate changes), a SYNC_IN pulse is required.

iio: adc: ad7768-1: Add support for setting the sampling frequency

---

Documentation/devicetree/bindings/iio/adc/adi,ad7606.txt
drivers/iio/adc/ad7606.c
drivers/iio/adc/ad7606.h
drivers/iio/adc/ad7606_spi.c

The AD7606B is a 16-bit ADC that supports simultaneous sampling of 8
channels. It is pin compatible to AD7606, but adds extra modes by
writing to the register map.
The AD7606B can be configured to work in software mode by setting all
oversampling pins to high. This mode is selected by default.
The oversampling ratio is configured from the OS_MODE register (address
0x08) with the addition of OS=128 and OS=256 that were not available in
hardware mode.
Moreover, in software mode, the range gpio has no longer its function.
Instead, the scale can be configured individually for each channel from
the RANGE_CH registers (address 0x03 to 0x06). Besides the already
supported ±10 V and ±5 V ranges, software mode can also accommodate the
±2.5 V range.

Master ad7606 b support

---

arch/arm/boot/dts/overlays/Makefile
arch/arm/boot/dts/overlays/rpi-ad9834-overlay.dts
drivers/staging/iio/frequency/ad9834.c
drivers/staging/iio/frequency/ad9834.h

The platform data for ad9833/9834 are retrieved from an overlay file.

staging: iio: frequency: ad9833

---

drivers/staging/iio/frequency/ad9834.c
drivers/staging/iio/frequency/ad9834.h

PR https://github.com/analogdevicesinc/linux/pull/292 added the
non-upstreamed patches.
This change syncs to the patches upstreamed to IIO.

drivers: staging: ad9834: sync to upstreamed versions

---

.travis.yml
ci/travis/lib.sh
ci/travis/run-build.sh

This change implements sync-ing branches with master.
The basic gist of it is that there's a new build in Travis-CI (called
`sync_branches_with_master`) which will sync the branches based on 2
strategies (one is fast-forward, the other is cherry-pick).
Normally a better Github-ish mechanism should be implemented by probably
using Github Apps or something, but that takes too much
effort/time/learning to do properly, and it still may be an idea later.
This build won't do any push-es yet, so as not to break stuff and do more
testing. After all looks good, pushing these sync-branches should be fine.

ci/travis: implement basic branch sync-ing mechanism for master 

---

arch/arm/boot/dts/overlays/Makefile
arch/arm/boot/dts/overlays/rpi-ad7190-overlay.dts

This is an example of a device tree used for ad7192 driver.

staging: iio: adc: ad7192: Add device tree example

---

drivers/iio/industrialio-buffer.c

The trialmask is expected to have all bits set to 0 after allocation.
Currently kmalloc_array() is used which does not zero the memory and so
random bits are set. This results in random channels being enabled when
they shouldn't. Replace kmalloc_array() with kcalloc() which has the same
interface but zeros the memory.
The issue was introduced in commit dc54e5c90fc2 ("Merge remote-tracking
branch 'xilinx/master' into adi-master-4-14") due to a mismerge of commit
81d00795b153 ("iio: Track enabled channels on a per channel basis") which
replaced kmalloc() with kzalloc() and commit 057ac1acdfc4 ("iio: Use
kmalloc_array() in iio_scan_mask_set()") which replaced kmalloc() with
kmalloc_array().

iio: Fix scan mask selection

---

drivers/clk/clk-axi-clkgen.c
drivers/iio/jesd204/axi_adxcvr.c
drivers/iio/jesd204/axi_adxcvr.h
drivers/iio/jesd204/xilinx_transceiver.c
drivers/iio/jesd204/xilinx_transceiver.h
include/linux/fpga/adi-axi-common.h

This modification is need to use the new information supplied by the two new registers in the ip core. This required modifying the ranges for VCO frequency mainly. 
Added FPGA info register to the common section of axi_adxcvr, axi_clkgen, axi_hdmi_tx, ADC and DAC cores.
0x0007 >>>  0x001C
{FPGA_TECHNOLOGY, FPGA_FAMILY, SPEED_GRADE, DEV_PACKAGE}; // [8,8,8,8]
For axi_adxcvr and axi_clkgen added also FPGA_VOLTAGE {16'd0, FPGA_VOLTAGE}; // mV
0x0050 >>> 0x0140
XCVR encoding:
INTEL: set xcvr_type_list { 0 9 } # transceiver speedgrade
New XCVR PHY encodings:
XILINX  { \
{ Unknown             0 } \
{ GTPE2_NOT_SUPPORTED 1 } \
{ GTXE2               2 } \
{ GTHE2_NOT_SUPPORTED 3 } \
{ GTZE2_NOT_SUPPORTED 4 } \
{ GTHE3               5 } \
{ GTYE3_NOT_SUPPORTED 6 } \
{ GTRE4_NOT_SUPPORTED 7 } \
{ …

Add fpga info

---

drivers/iio/logic/m2k-fabric.c

Skip going through the safe state before setting the desired value.

iio: logic: m2k-fabric: Fix EN_AWG1/2 glitches

---

drivers/iio/adc/ad9361.c
drivers/iio/adc/ad9361_regs.h

This should not limit the rates which were previously computed.
It just enforces max rates which could have been selected by a
handcrafted filter file.

iio: adc: ad9361: Fix max filter HB rates and update the available attr.

---

drivers/staging/iio/adc/ad7192.c

This patch fixes the differential channels adresses for the ad7193.

staging: iio: ad7192: Fix ad7193 channel address

---

Documentation/devicetree/bindings/sound/adi,adau1977.txt
sound/soc/codecs/adau1977.c

Cherry-pick of upstream commits which add the possibility to specify a DT property for 
setting the output voltage of MICBIAS.

[backport]ASoC: adau1977: cherry-pick upstreamed commits from ASoC tree

---

drivers/clk/clk.c

58d6e6c
The current commit brings clk.c in sync with the upstream version.

clk: Revert "drivers/clk/clk: fix CLK_GET_RATE_NOCACHE"

---

drivers/iio/jesd204/axi_adxcvr.c
drivers/iio/jesd204/xilinx_transceiver.c

This patch fixed PCORE version major verification. The new PCORE version is
0x110161 so we need to use 0x10 as the major in our comparisons.

iio: jesd204: axi_adxcvr: Fix PCORE version major

---

drivers/iio/adc/talise/talise_cals.c
drivers/iio/adc/talise/talise_gpio.c
drivers/iio/adc/talise/talise_radioctrl.c

warning: unused variable ‘halError’ [-Wunused-variable]
adiHalErr_t halError = ADIHAL_OK;
^~~~~~~~

iio: adc: talise: Fix unused variable warnings

---

drivers/iio/imu/adis16480.c

The adis16480 driver deviates from the upstream version which was
modified according to the feedback received during review.

iio: imu: adis16480: Align with upstream changes

---

Documentation/devicetree/bindings/iio/imu/adi,adis16480.txt
drivers/iio/imu/adis16480.c

Inertial sensor data collection and processing can be controlled by
configuring one of the DIOx lines as an external clock input. This
option is available for all devices supported by this driver. However,
only adis1649x devices support different modes for the external clock.
Sync mode is supported by all devices. In this mode, the output data
rate is equal with the clock frequency divided by DEC_RATE + 1. This
mode of calculation is similar with the case when the internal clock is
used.
Pulse Per Second (PPS) Mode, is only supported by adis1649x devices. In
this mode, the output data rate is equal to the product of the external
clock frequency and the scale factor in the SYNC_SCALE register.
This patch uses the "clock-names" property to enable the external clock
in one of the two …

iio: imu: adis16480: Add support for external clock

---

drivers/dma/dma-axi-dmac.c

Currently cyclic transfer using dma-axi-dmac driver is broken. Was discovered in a setup where
AXI DMA is used together with soc-generic-dmaengine and ALSA. 
The first problem is that currently callback function is called only when the last period was 
transferred but it should be called after every finished period. 
In this way ALSA can update the data that's in the buffer before the ring buffer will wrap around.
The second problem is when descriptors are allocated for periods composing the cyclic transfer.
The number of periods multiplied with number of periods must be equal with ring buffer length.
So each descriptor must have a length equal with one period and not the whole buffer.
The commits included in this pull request correct the before mentioned problems.
The changes were tested …

dmaengine: dma-axi-dmac: Fix cyclic transfers 

---

drivers/spi/spi-axi-spi-engine.c

This patch fixes the issue with transfer lengths being higher than 1. In
this case spi_engine_read_buff and spi_engine_write_buff were called
multiple times with the same buffer address and the spi engine was
sending/receiving always the same value. To solve this issue a buffer
address incrementation was added in the case of a transfer with a length
larger then 1.
Fixes: 30707b090c25 ("spi-axi-engine: Calculate buffer dimension for
xfer")

[2018_R2] spi: spi-axi-engine: Fix buffer address incrementation

---

arch/arm/boot/dts/adi-fmcomms11.dtsi

Move devices under the clock node, instead of the SPI bus.

arm: dts: adi-fmcomms11.dtsi: Fix location of fixed-factor-clock

---

Documentation/dmaengine/provider.txt
drivers/crypto/ccp/ccp-dmaengine.c
drivers/dma/at_hdmac.c
drivers/dma/dmaengine.c
drivers/dma/fsldma.c
drivers/dma/mv_xor.c
drivers/dma/nbpfaxi.c
drivers/dma/ste_dma40.c
drivers/dma/xgene-dma.c
drivers/dma/xilinx/zynqmp_dma.c
include/linux/dmaengine.h

This reverts commit a9401f2674694dd3f1e7c114ca9a8b6c6ad395f6.
We removed the Xilinx DMA, and when that was done, the Xilinx DMA was
brought to the same state as the Xilinx upstream tree. But, we also
reverted their revert, which requires their DMAs to build.
So, this is a triple revert, to get back closer to the state in the Xilinx
tree.
This change does not revert the `drivers/dma/dmatest.c` changes, as we want
to upstream more of our changes to that module, and being in-sync with
DMAEngine upstream helps.

Revert "Revert "Revert "dmaengine: remove DMA_SG as it is dead code in kernel"

---

drivers/iio/dac/ad5758.c

This patch will ensure compatibility with the new revision of the AD5758
dac converter. The modifications consist of removing the fault_prot_switch
function since this option is no longer available, and enabling the
ENABLE_PPC_BUFFERS bit in ADC_CONFIG register before setting the PPC
current mode.

iio: dac: ad5758: Modifications for new revision

---

drivers/staging/iio/adc/ad7192.c
drivers/staging/iio/adc/ad7192.h

This patch series consists of an effort to align our rpi version of ad7192 with the upstream one. 
This will help with future work that is required to be done on the driver to move it out of staging and into the iio framework.

Rpi ad7192 upstream

---

drivers/dma/dma-axi-dmac.c
include/linux/scatterlist.h
lib/scatterlist.c

These changes sync parts of the AXI DMAC driver with the version that is upstreamed.
There are still some parts to upstream about it.

dmaengine: axi-dmac: sync changes with upstream version

---

drivers/iio/imu/adis16480.c
drivers/iio/imu/adis_buffer.c
include/linux/iio/imu/adis.h

The burst read function (BRF) provides a method for reading a batch of
data (status, temperature, gyroscopes, accelerometers, timestamp/data
counter and CRC code), which does not require a stall time between each
16-bit sgment and only requires on command on the DIN line to initiate.
The BRF contains either 19 or 20 different data segments of 16-bits
each. After making the burst request, the response can have one or two
"don't care" 16-bit responses before the BURST_ID. This is why the
received burst sequence needs to be followed until the BURST_ID is
detected, which indicates that the data will be contained in the
following 17 segments of 16-bits each. Temperature is the first data
channel in the sequence.
Currently, the burst function is activated by default for all devices
that support …

iio: imu: adis16480: Add support for burst read function

---

drivers/iio/imu/adis16480.c

Although the burst read function does not require a stall time between
each 16-bit segment, it however requires more processing since the
software needs to look for the BURST_ID and take into account the offset
to the first data channel. Some users might find it useful to be able to
switch between the two modes.

iio: imu: adis16480: Add the option to enable/disable burst mode

---

drivers/iio/imu/adis16480.c
drivers/iio/industrialio-core.c
include/uapi/linux/iio/types.h

This PR implements a new channel type called IIO_FLAGS which is further used to push SYS_E_FLAG data and CRC validation result to buffers.

Master adis16480 err flags

---

drivers/iio/adc/cf_axi_tdd.c

The issue was reported here:
https://github.com/analogdevicesinc/linux/issues/345

iio: cf_axi_tdd: Typo fix

---

arch/arm/boot/dts/zynq-zed-adv7511-imageon-loopback.dts
drivers/media/platform/imageon-bridge.c

This PR address a problem in imageon-bridge media platform driver.
Due changes implementd by commit 9832e155f1ed3030fdfaa19e72c06472dc2ecb1d probing of 
imageon-bridge.c resulted in a NULL pointer dereference. 
Also in DT the ADV7511 HDMI output was configured for RGB and not YCbCr 4:2:2.

 media: imageon-loopback: Fix imageon bridge example

---

drivers/iio/jesd204/xilinx_transceiver.c

This avoids issues due to previous rounding errors. For example the
parent clock rate is reported as 349999999 this would result in 349999
instead of 350000 which would be much more accurate.

iio: jesd204: xilinx_transceiver: refclk use round closest

---

drivers/clk/clk-adjustable-rate.c

clk: clk-adjustable-rate: clamp min and max rate to avoid overflows

---

Documentation/devicetree/bindings/iio/adc/adi,ad7768-1.txt
drivers/iio/adc/ad7768-1.c

The ad7768-1 driver deviates from the upstream version which was modified
according to the feedback received during review.

iio: adc: ad7768-1: Align with upstream version

---

Documentation/devicetree/bindings/iio/adc/adi,ad7606.txt
drivers/iio/adc/ad7606.c
drivers/iio/adc/ad7606.h
drivers/iio/adc/ad7606_spi.c

Synced with upstream version. It's not a 100% match because on upstream version, ad7606B wasn't added yet.

Ad7616 master

---

drivers/mtd/spi-nor/spi-nor.c

This change causes the spi-nor driver to query the hardware for the currently selected bank.

Fix initial bank selection for IS25WP256D

---

drivers/iio/adc/mykonos/mykonos.c

This was reported in issue #368

iio: adc: mykonos: mykonos: Add some sleep to relax this busy loop.

---

drivers/iio/adc/ad7606.c
drivers/iio/adc/ad7606.h

The device dependent options were moved in chip info for a more generic
driver. This patch allows supporting more spi devices by te driver.
Also, it is an intermediate step of adding support for ad7616 in software mode.
I would like to know if my approach is good before adding software mode support for ad7616.

iio: adc: ad7616: Move spi device dependent options to chip info

---

drivers/hwmon/axi_fan_control.c

The driver was writting on the wrong register to set the tacho
parameters. For the core to start monitoring the signal, the driver has
to set the TACH_TOLERANCE register. This has to be done after writting
on TACH_PERIOD.

fix: hwmon: axi_fan_control: Set tacho parameters

---

arch/arm/boot/dts/zynq-pluto-sdr.dtsi

Fix the destination and source bus width for DMA transfers.This is in
accordance with the HDL design here:
https://github.com/analogdevicesinc/hdl/blob/master/projects/pluto/system_bd.tcl#L185
https://github.com/analogdevicesinc/hdl/blob/master/projects/pluto/system_bd.tcl#L198

arch: arm: boot: dts: Fix pluto DMA data width

---

drivers/iio/frequency/ad9523.c

This change seems to present upstream, but not in our tree.
Sync it.

iio: ad9523: check and return on error when configuring channels

---

include/linux/iio/frequency/ad9523.h

This patch simply removes the comments from enums, since they don't explain
more than the enum names. They just show numbers, which is pretty obvious.
The only reason to do this is to align the driver to upstream.

iio: include: ad9523: remove enum comments

---

include/linux/iio/buffer-dma.h

Mainline kernel splitted buffer.h into buffer.h and buffer_impl.h. The
latter is supposed to be used by the iio core. For driver's wanting to
include buffer-dma.h, we need buffer_impl.h in order to compile (since
buffer-dma.h directly references structs defined in buffer_impl).
Including it here, avoids nasty #include dependencies in driver's
wanting to use buffer-dma.
Signed-off-by: Nuno Sa <Nuno.Sa@analog.com>

include: iio: buffer-dma: Include buffer_impl.h

---

drivers/spi/spi-axi-spi-engine.c

While using the spi engine for multiple 8 bit transmits the temporary value
used to write to the registers must be reset to 0. Also the transmission
length must be taken into account while incrementing the buffer. This patch
implements these requirements.
This commit must be ported to 2018_R2 branch too.

spi: spi-axi-engine: Fix buffer increment

---

arch/arm/boot/dts/adi-ad9265-fmc-125ebz.dtsi
arch/arm/boot/dts/adi-ad9434-fmc-500ebz.dtsi
arch/arm/boot/dts/adi-ad9467-fmc-250ebz.dtsi
arch/arm/boot/dts/adi-adrv9009.dtsi
arch/arm/boot/dts/adi-adrv9371.dtsi
arch/arm/boot/dts/adi-daq1.dtsi
arch/arm/boot/dts/adi-daq2.dtsi
arch/arm/boot/dts/adi-daq3.dtsi
arch/arm/boot/dts/adi-fmcadc4.dtsi
arch/arm/boot/dts/adi-fmcjesdadc1.dtsi
arch/arm/boot/dts/adi-fmcomms11-RevA.dtsi
arch/arm/boot/dts/adi-fmcomms6.dtsi
arch/arm64/boot/dts/xilinx/adi-adrv9009.dtsi
arch/arm64/boot/dts/xilinx/adi-adrv9371.dtsi
arch/arm64/boot/dts/xilinx/adi-daq2.dtsi
arch/arm64/boot/dts/xilinx/adi-daq3.dtsi
arch/microblaze/boot/dts/adi-ad9467-fmc-250ebz.dtsi
arch/microblaze/boot/dts/adi-adrv9371.dtsi
arch/microblaze/boot/dts/adi-daq2.dtsi
arch/microblaze/boot/dts/adi-daq3.dtsi
arch/microblaze/boot/dts/adi-fmcjesdadc1.dtsi
drivers/iio/adc/ad6676.c
drivers/iio/frequency/ad9122.c
drivers/iio/frequency/ad9508.c
drivers/iio/frequency/ad9517.c
drivers/iio/frequency/ad9523.c
drivers/iio/frequency/ad9528.c
include/linux/iio/frequency/ad9508.h
include/linux/iio/frequency/ad9523.h
include/linux/iio/frequency/ad9528.h

All drivers support upstream 3wire mode by using the upstream `spi-3wire`
property. All device-trees have been updated to use this property.
This change removes all usage/handling of the old/special
adi,spi-3wire-enable.

treewide: remove `adi,spi-3wire-enable` dt property ; use upstream `spi-3wire`

---

arch/arm/boot/dts/zynq-zc706-adv7511-fmclidar1.dts

A naming convention allows the jesd-eye-scan-gtk application to
determine target devices.

arm: dts: adi-fmclidar1: Make it compatible with jesd-eye-scan-gtk

---

Documentation/devicetree/bindings/media/adi,adi-axi-fb.yaml
drivers/media/platform/Kconfig
drivers/media/platform/Makefile
drivers/media/platform/adi-axi-fb.c

This PR propose a new driver for control of AXI Frame Buffer HDL core.
More details here: https://wiki.analog.com/resources/fpga/docs/axi_dmac in section FrameLock Synchronization.
This is the preliminary, standalone version of driver as required by Mathworks.
Possible future integration with V4L2 framework.

 media: adi-fb: Add ADI FB AXI driver

---

drivers/iio/adc/ad_adc.c
drivers/iio/adc/cf_axi_adc.h

Merged ad-adc driver into master. This driver had some conflicts between m2k and master, so  that, m2k device needs to have some special handling in this driver. Also fixed some coding style warnings.
This PR ends the series of PRs to merge m2k into master.

Dev m2k to master

---

arch/arm/boot/dts/adi-ad9265-fmc-125ebz.dtsi
arch/arm/boot/dts/adi-ad9434-fmc-500ebz.dtsi
arch/arm/boot/dts/adi-ad9467-fmc-250ebz.dtsi
arch/arm/boot/dts/adi-adrv9009.dtsi
arch/arm/boot/dts/adi-adrv9371.dtsi
arch/arm/boot/dts/adi-daq1.dtsi
arch/arm/boot/dts/adi-daq2.dtsi
arch/arm/boot/dts/adi-daq3.dtsi
arch/arm/boot/dts/adi-fmcadc4.dtsi
arch/arm/boot/dts/adi-fmcjesdadc1.dtsi
arch/arm/boot/dts/adi-fmcomms11-RevA.dtsi
arch/arm/boot/dts/adi-fmcomms6.dtsi
arch/arm64/boot/dts/xilinx/adi-adrv9009.dtsi
arch/arm64/boot/dts/xilinx/adi-adrv9371.dtsi
arch/arm64/boot/dts/xilinx/adi-daq2.dtsi
arch/arm64/boot/dts/xilinx/adi-daq3.dtsi
arch/microblaze/boot/dts/adi-ad9467-fmc-250ebz.dtsi
arch/microblaze/boot/dts/adi-adrv9371.dtsi
arch/microblaze/boot/dts/adi-daq2.dtsi
arch/microblaze/boot/dts/adi-daq3.dtsi
arch/microblaze/boot/dts/adi-fmcjesdadc1.dtsi
drivers/iio/adc/ad6676.c
drivers/iio/frequency/ad9122.c
drivers/iio/frequency/ad9508.c
drivers/iio/frequency/ad9517.c
drivers/iio/frequency/ad9523.c
drivers/iio/frequency/ad9528.c
include/linux/iio/frequency/ad9508.h
include/linux/iio/frequency/ad9523.h
include/linux/iio/frequency/ad9528.h

This did not take into consideration the fact that the SPI framework does
some validation and won't allow any modes/bits to be set if the controller
does not support it.
The Cadence SPI controller does not support 3wire, so this fails.
There is a HDL wrapper that takes care of converting 3wire to 4wire. Both
the SPI controller & the driver need to support 3wire, otherwise the SPI
framework won't allow it.

 Revert "drivers: iio: remove adi,spi-3wire-enable & handling" 

---

arch/arm/boot/dts/adi-fmclidar1.dtsi
arch/arm/boot/dts/zynq-zc706-adv7511-fmclidar1.dts
drivers/iio/adc/ad7476.c

This series of patches adds support for:
- AD7091
- internal CONVST generation for AD7091 and AD7091R
- IIO_CHAN_INFO_RAW for AD7091 and AD7091R

ad7091 support

---

arch/arm64/boot/dts/xilinx/zynqmp-adrv9009-zu11eg-adrv2crr-fmc.dts
arch/arm64/boot/dts/xilinx/zynqmp-adrv9009-zu11eg.dts

Since phy1 is only available in the carrier board, it should be only
defined in zynqmp-adrv9009-zu11eg-adrv2crr-fmc.

arm64: dts: xilinx: zynqmp-adrv9009-zu11eg.dts: Split phy1 definition

---

Documentation/ABI/testing/sysfs-bus-iio-frequency-adf4371
Documentation/devicetree/bindings/iio/frequency/adf4371.yaml
drivers/iio/frequency/Kconfig
drivers/iio/frequency/Makefile
drivers/iio/frequency/adf4371.c

The ADF4371 is a frequency synthesizer with an integrated voltage
controlled oscillator (VCO) for phase-locked loops (PLLs). The ADF4371
has an integrated VCO with a fundamental output frequency ranging from
4000 MHz to 8000 MHz. In addition, the VCO frequency is connected to
divide by 1, 2, 4, 8, 16, 32, or 64 circuits that allows the user to
generate radio frequency (RF) output frequencies as low as 62.5 MHz at
RF8x. A frequency multiplier at RF16x generates from 8 GHz to 16 GHz. A
frequency quadrupler generates frequencies from 16 GHz to 32 GHz at RF32x.
RFAUX8x duplicates the frequency range of RF8x or permits direct access to
the VCO output.
The driver takes the reference input frequency from the device tree and
uses it to calculate and maximize the PFD frequency (frequency of the …

Master adf4371 support

---

arch/arm64/boot/dts/xilinx/zynqmp-adrv9009-zu11eg-adrv2crr-fmc.dts
arch/arm64/boot/dts/xilinx/zynqmp-adrv9009-zu11eg.dts
drivers/net/ethernet/cadence/macb.h
drivers/net/ethernet/cadence/macb_main.c
drivers/of/of_mdio.c

This PR allows the sgmii interface to still work even if the the rgmii interface is down. The [of_mdio: avoid MDIO bus removal when a PHY is missing](https://github.com/torvalds/linux/commit/95f566de0269a0c59fd6a737a147731302136429) patch was cherry-picked from upstream. Also, some merge from the upstream macb driver was done here. 
The last patch also adds reset-gpios to the device tree so that, the driver can enable the phy if it boots disabled (for some reason).

Fix sgmii when rgmmii down

---

Documentation/ABI/testing/sysfs-bus-iio-frequency-adf4371
Documentation/devicetree/bindings/iio/frequency/adf4371.yaml
arch/arm/boot/dts/overlays/Makefile
arch/arm/boot/dts/overlays/rpi-adf4371-overlay.dts
drivers/iio/frequency/Kconfig
drivers/iio/frequency/Makefile
drivers/iio/frequency/adf4371.c

This version of the driver is already on the master. Additionally, this PR includes a commit which offers a device tree example.

Rpi 4.14.y adf4371 support

---

Documentation/devicetree/bindings/iio/frequency/adf4371.yaml
drivers/iio/frequency/Kconfig
drivers/iio/frequency/adf4371.c

This PR adds support for ADF4372 and the output stage mute feature.
Common Clock Framework provider will follow in a different PR

Master adf4372 support

---

.travis.yml

Branch `master-xilinx-4.19` is built when updating.
This branch is a mirror of that, so don't run un-necessary builds.

build,travis: don't build adi-4.19.0 branch

---

drivers/dma/dma-axi-dmac.c

When doing cyclic DMA transfers, residue information may also be
needed/useful.
To do this, the information for residue must be computed before the
`vchan_cyclic_callback()` call.

dmaengine: axi-dmac: compute residue before cyclic cb

---

drivers/clk/clk-axi-clkgen.c
drivers/dma/dma-axi-dmac.c
drivers/iio/jesd204/axi_adxcvr.c
drivers/iio/jesd204/xilinx_transceiver.c
drivers/iio/jesd204/xilinx_transceiver.h
include/linux/fpga/adi-axi-common.h

The adi-axi-common.h header was partially upstreamed, via the DMAEngine
subsystem. The definitions were prefixed with ADI_, to avoid any potential
collisions with other FPGA providers/vendors that may use AXI FPGA
elements.
This change updates the header and the places where the definitions are
used.

treewide,include: fpga: adi-axi-common.h: update header/sync upstream

---

drivers/dma/dma-axi-dmac.c

The max reg value is no longer for reg DBG2, it's for register
AXI_DMAC_REG_PARTIAL_XFER_ID.
Also, some regs need to be added for validation.

dmaengine: axi-dmac: update regmap register access

---

drivers/dma/dma-axi-dmac.c

The driver has been completely upstreamed, and matches the current one in the ADI tree.
The only thing that differs (now):
* in the ADI tree there is a SPEED_TEST code, which is hacked-in the driver
* the upstream version uses a different helper for allocating the descriptor https://github.com/torvalds/linux/commit/48b02a85fe2e6a0927acaa754ba3bef4a20a5e37  ; this is available in a newer kernel version

dmaengine: axi-dmac: sync driver with upstream version

---

Documentation/devicetree/bindings/media/adi,adi-axi-fb.yaml
drivers/media/platform/adi-axi-fb.c

This patch adds the possibility to set line and frame stride through DT but as optional property. 
Also add the possibility to specify frame buffer address but not using the Linux reserved memory framework. Is useful when the frame buffer is stored in PL RAM and not accessible to CPU and Linux.

media: adi-axi-fb: Add stride and PL only memory space frame buffer allocation 

---

Documentation/devicetree/bindings/iio/frequency/adf4371.yaml
drivers/iio/frequency/adf4371.c

This patch allows the ADF4371/ADF4372 to be used as clock providers.
Because the frequency generated by adf4371 can go up to 32GHz,
clk_{get,set}_rate_scaled()` had to be used to work around the 4.2GHz
limitation imposed by the unsigned long type used by the CCF.

iio: frequency: adf4371: Add common clock framework support

---

drivers/iio/amplifiers/Kconfig
drivers/iio/amplifiers/ad8366.c

The ad8366 driver has been updated upstream.
This change backports some of the changes that went upstream, but are not in the ADI tree.

 iio: amplifiers: ad8366: sync with upstream version (part 1)

---

Documentation/devicetree/bindings/iio/adc/adi,ad5940.yaml
MAINTAINERS
arch/arm/boot/dts/overlays/Makefile
arch/arm/boot/dts/overlays/rpi-ad5940-overlay.dts
drivers/iio/adc/Kconfig
drivers/iio/adc/Makefile
drivers/iio/adc/ad5940.c

Driver support for AD5940 for GSoC 2019. Basic driver skeleton support without any actual operations.
@stefpopa @commodo

[WIP]Add driver support for AD5940

---

drivers/iio/amplifiers/Kconfig
drivers/iio/amplifiers/ad8366.c

Last batch of changes that sync the driver with the upstream version.
The only thing that has not been upstreamed atm, is support for the HMC271 & HMC1119 attenuators.
The HMC271 chip is obsolete, so we may drop it from our tree (but we'll see).
The HMC1119 will probably be upstreamed later.

iio: amplifiers: ad8366: sync with upstream version (part 2)

---

drivers/iio/logic/m2k-logic-analyzer.c
drivers/iio/logic/m2k-trigger-ad.c

In HDL was added support to cascade two or more M2Ks from trigger point of view.
This patch-set adds support for:
- Configure the Logic Analyzer trigger output multiplexer
- Configure the AXI ADC final trigger multiplexer
- Set direction of trigger I/O pin
- Select trigger out source signal

M2k cascading trigger

---

arch/arm/boot/dts/bcm2710-rpi-3-b.dts
arch/arm/boot/dts/overlays/Makefile
arch/arm/boot/dts/overlays/rpi-adgs1408-overlay.dts

This patch removes the adgs1408 device tree entries from
bcm2710-rpi-3-b.dts and moves them to a new overlay file.

arch: arm: boot: dts: Move adgs1408 dt to its own overlay

---

drivers/iio/accel/adxl372.c

Currently, the driver sets the FIFO_SAMPLES register with the number of
sample sets (maximum of 170 for 3 axis data, 256 for 2-axis and 512 for
single axis). However, the FIFO_SAMPLES register should store the number
of samples, regardless of how the FIFO format is configured.
This issue was reported in this EZ thread: https://ez.analog.com/linux-device-drivers/linux-software-drivers/f/q-a/113234/adxl372-setting-of-water-mark-level-not-clear

iio: accel: adxl372: Fix FIFO number of samples limitation

---

drivers/iio/adc/ad7606.c
drivers/iio/adc/ad7606.h
drivers/iio/adc/ad7606_spi.c

The part of the driver which is used only in software mode were moved in spi file.

Ad7616 spi core

---

drivers/iio/adc/ad9361_conv.c
drivers/iio/adc/ad9371_conv.c
drivers/iio/adc/ad_adc.c
drivers/iio/adc/admc_adc.c
drivers/iio/adc/admc_ctrl.c
drivers/iio/adc/admc_speed.c
drivers/iio/adc/adrv9009_conv.c
drivers/iio/adc/cf_axi_adc.h
drivers/iio/adc/cf_axi_adc_core.c
drivers/iio/adc/cf_axi_tdd.c
drivers/iio/frequency/cf_axi_dds.c
drivers/iio/frequency/cf_axi_dds.h

The ADI AXI common register definitions have been added in `include/linux/fpga/adi-axi-common.h` some time ago. Some small parts have also been upstreamed.
These changes makes use of these definitions for the AXI IIO drivers.

iio: use common FPGA defs

---

drivers/iio/adc/ad_adc.c
drivers/iio/adc/admc_ctrl.c

There is plenty of duplication for accessing the regs on the axiadc_state struct.
These changes reduce that by using the already existing axiadc_{slave}_{write,read}() helpers 

 iio: ad_adc,admc_ctrl: use common axiadc_{slave}_{write,read}() helpers 

---

arch/arm/boot/dts/overlays/rpi-cn0508-overlay.dts

This patch adds support for the pitft 3.2" touchscreen. It is mapped to SPI
CS2 and CS3. These correspond to the original SPI CS0 and CS1 pins (GPIO 8
and 7).
Since pins 24 and 25 are used by pitft the interrupt for ad7124 was moved
to pin 23.

arch: arm: boot: dts: overlays: Add pitft support

---

drivers/iio/jesd204/axi_jesd204_rx.c
drivers/iio/jesd204/axi_jesd204_tx.c

The ADI AXI common register definitions have been added in
`include/linux/fpga/adi-axi-common.h` some time ago. Some small parts have
also been upstreamed.
This change makes use of these definitions for the JESD204 RX/TX
peripherals.

drivers: jesd204: use common FPGA reg defs

---

drivers/iio/frequency/cf_axi_dds.c
drivers/iio/frequency/cf_axi_dds.h
drivers/iio/frequency/cf_axi_dds_buffer_stream.c

The state of the cf_axi_dds does not need to be exposed outside of the
`cf_axi_dds.c` file. This change moves it inside the C file.

 iio: cf_axi_dds: make cf_axi_dds_state struct opaque

---

drivers/iio/jesd204/axi_jesd204_rx.c
drivers/iio/jesd204/axi_jesd204_tx.c

These checks can be done right after the regmaps have been initialized.
Doing this earlier, we can avoid initializing clocks before we are sure
that PCORE versions & magic numbers are in order.

iio: jesd204: axi_jesd204_{rx,tx}: move pcore checks to own function

---

Documentation/devicetree/bindings/media/adi,adi-axi-fb.yaml
drivers/media/platform/adi-axi-fb.c

This patch set add check for reserved memory size. If the reserved memory is not big enough to accommodate frame buffer size times number of frames return with error to avoid memory corruption.
Also split the dts example to avoid confusion between case when FB is stored in PS RAM and FB is stored in PL RAM.

media: adi-axi-fb: Add check for reserved memory size and split dts examples

---

drivers/iio/frequency/cf_axi_dds.c
drivers/iio/frequency/cf_axi_dds.h
drivers/iio/frequency/cf_axi_dds_buffer_stream.c

Currently, the PCORE version of the AXI DDS is at version 10.
This change removes all code that handles earlier versions.

 iio: frequency: cf_axi_dds: remove some old PCORE code

---

drivers/iio/frequency/ad9162.c

ad9162 refactor. This is part of the work on splitting #448 in smaller patches. This is now applied to master since it makes more sense (it needs to be ported to the rpi-4.14.y branch).

Dev ad9162 refactor

---

drivers/iio/jesd204/axi_adxcvr.c
drivers/iio/jesd204/axi_adxcvr.h
drivers/iio/jesd204/xilinx_transceiver.c
drivers/iio/jesd204/xilinx_transceiver.h

This patch adds support for GTH3/4 QPLL1 support. Before this only QPLL0
was supported.
QPLL1 frequency range is from 8.0 to 13.0 GHz.
The queston here do we want to set QPLL0 or QPLL1 dynamical in the driver depending on the frequency that is required ? Right now the sysclk is set inside the device tree and the user has to specify which one he wants to use, this will require him to know about the frequency ranges for QPLL0 and QPLL1.

iio: jesd204: axi_adxcvr: Add support GTH3/4 QPLL1 support

---

drivers/iio/frequency/ad9162.c

This PR adds support for standalone mode in which the driver can work independent of cf_axi_dds. It also adds support for DC_TEST_EN mode. A chip_info structure is defined as a preliminary step to add support for more devices of the ad916x family.

Dev ad9162 standalone mode

---

Documentation/devicetree/bindings/display/bridge/adi,adv7511.txt
drivers/gpu/drm/bridge/adv7511/adv7511.h
drivers/gpu/drm/bridge/adv7511/adv7511_drv.c

This patch set add support for ADV7535 MIPI DSI -> HDMI bridge IC.
ADV7533 accept V1P2 supply to be 1.2V or 1.8V but ADV7535 only accept 1.8V.
Also fix the writing of low refresh rate register in case of ADV7533/5.

drm: adv7511: Add support for ADV7535

---

.github/issue_template

Github allows issues & pull-request templates.
For PRs we don't have stuff to recommend for PR descriptions.
Typically things get addressed in the review process.

[RFC] .github: add issue template recommending EZ

---

drivers/iio/frequency/ad9162.c

The DAC output full scale current was being hardcoded. Have this
configurable by adding a devicetree parameter.

iio: ad9162: Support configurable fsc

---

arch/arm/boot/dts/adi-fmcomms11-RevA.dtsi
arch/arm/boot/dts/adi-fmcomms11.dtsi

Due to 2234963b5cba, the ad9162 full scale current is now configured
through devicetree, defaulting to 40mA if no property is set. Since
fmcomms11 needs a configuration of 20mA, this has to be done in the
devicetree.

arm: dts: Fix fmcomms11 ad9162 fsc settings

---

arch/arm/boot/dts/adi-fmcomms11-RevA.dtsi
arch/arm/boot/dts/adi-fmcomms11.dtsi

Due to 798ddf889813, the 3wire SPI mode is configurable through
devicetree. On fmcomms11, ad9162 is using 3wire spi mode, so that,
the devicetree has to be updated accordingly.

arm: dts: Fix fmcomms11 ad9162 3wire spi

---

drivers/iio/adc/ad9361.c
drivers/iio/adc/ad9361.h

This adds support for dynamic GPO[0..3] control via a new debugfs
attribute gpo_set. adi,gpo-manual-mode-enable must be enabled.
Be aware that GPO manual mode can conflict with external LNA and
automatic ENSM slave mode. GPOs can be addressed individual 0..3 or
altogether using 0xF as address select.
Example:

iio: adc: ad9361: GPO support via debugfs

---

arch/arm/boot/dts/adi-fmcomms11-RevA.dtsi
arch/arm/boot/dts/adi-fmcomms11.dtsi
include/linux/clk/clkscale.h

clk_get_rate_scaled() and clk_set_rate_scaled() were doing the same operation, which is obviously wrong. Also update the devicetrees which were using this property.

Fix clkscale

---

.travis.yml

Change adds sync-ing support via cherry-picking to branches:
* adi-4.19.0
* rpi-4.14.y
* rpi-4.19.y
rpi-4.14.y will be obsoleted soon, but we may still want to keep it for a
while longer also to test the auto-sync-ing.

.travis.yml: extend cherry-pick sync

---

ci/travis/run-build.sh

Without any parameter, `git fetch` pulls the entire branch history, which
can take a while and takes up internet bandwidth needlessly.
Also, if we bump the number of branches to sync, the time for this branch
can increase quite a bit [20-30+ minutes].
This patch limits the git fetch depth to 50.
This can be configurable by providing a `GIT_FETCH_DEPTH` parameter, with
the option of doing `GIT_FETCH_DEPTH=disabled` to disable this.

ci/travis/run-build.sh: limit git fetch depth to 50 

---

drivers/iio/frequency/ad9162.c

The reading/writing of the raw amplitude must be properly protected
with a mutex.

iio: ad9162: Add locks on read/write raw

---

drivers/iio/adc/ad9361_regs.h

Fixes #486
Remove it. If it's there it may encourage customers to use it:
https://ez.analog.com/linux-device-drivers/linux-software-drivers/f/q-a/113808/ad9361-not-transmitting-when-configured-for-low-sampling-rates

iio: adc: ad9361: remove commented MIN_ADC_CLK def

---

drivers/iio/adc/ad9361.c
drivers/iio/adc/ad9361_regs.h

This patch exposes the maximum TX attenuation inside the header file. The
new macro will be used to verify the desired attenuation
(MAX_TX_ATTENUATION_DB). The maximum TX attenuation value can be found
on page 55 in UG-570.

iio: adc: ad9361: Expose max TX attenuation value in header

---

drivers/iio/jesd204/axi_adxcvr.c

There's a fixed `mdelay(100)` call right before calling
`adxcvr_status_error()`.
The `adxcvr_status_error()` does a busy loop checking the status reg, which
is 100 x 1mS. Technically that alone should be sufficient.
This change removes the fixed delay before the busy loop.

iio: jesd204: adxcvr: remove fixed sleep when enabling clock

---

drivers/iio/adc/adrv9009.c
drivers/iio/adc/adrv9009.h

This patch adds support for controlling the 12 GPIO3v3 via debugfs.
In order to use these pins, the adi,gpio3v3-source-control attribute
must be set. Please refer to the Rerefer to the reference manual UG-1295.
In addition, dedicated output pins must be masked via
adi,gpio3v3-output-enable-mask.
adi,gpio3v3-source-control = <0x333>;
adi,gpio3v3-output-enable-mask = <0xFFF>;
adi,gpio3v3-output-level-mask = <0x0>;
For test purposes these attributes can be also set via debugfs.
cd /sys/kernel/debug/iio/iio\:device3
echo 0x333 > adi,gpio3v3-source-control
echo 0xFFF > adi,gpio3v3-output-enable-mask
echo 1 > initialize
The gpio3v3 debugfs control allows setting individual gpios by
number 0…11. Or altogether using the 0xFFF mask.
GPIOs masked as inputs can also be read. …

iio: adc: adrv9009: GPIO3v3 control via debugfs

---

drivers/iio/adc/ad9361_ext_band_ctrl.c

Reported via:
https://ez.analog.com/linux-device-drivers/linux-software-drivers/f/q-a/114085/kernel-panic-with-e310/340287
When looping with of_for_each_phandle(), the only time that is recommended
to use `of_node_put()` is on error-paths (which is already being done).
Otherwise, the of_for_each_phandle() call should handle free-ing the
`it.node` if the loop finishes successfully.
This type of API design (with `of_for_each_phandle()`) is a bit error prone
when being used. And in this case it was causing double-free.
Also, ARM is not the most consistent architecture with regards to Linux
panic-ing on access violations. Sometimes it lets you get away with 1-2-3,
which could be one reason why we didn't catch this in our testing.
Signed-off-by: Alexandru Ardelean …

iio: ad9361: fix double-free when parsing DT for filter-band settings

---

drivers/spi/spi-bcm2835.c

This is a backport of the pacth in
https://patchwork.kernel.org/patch/11029323/. However, this
patch does not apply directly since the driver is still using
struct spi_master *master instead of struct spi_controller *ctlr
as in the original patch.

spi: bcm2835: Fix 3-wire mode if DMA is enabled

---

drivers/nvmem/adi_axi_sysid.c

Build complains with a warning:
```
drivers/nvmem/adi_axi_sysid.c: In function ‘axi_sysid_probe’:
drivers/nvmem/adi_axi_sysid.c:185:6: warning: unused variable ‘ret’ [-Wunused-variable]
int ret;
^
```

nvmem: adi_axi_sysid: remove unused variable

---

ci/travis/run-build.sh

The logic for cherry-picking assumed that the last commit is always
cherry-picked from master. For branches like `adi-4.14.0` & `adi-4.19.0`
this is almost always true.
However for the `rpi-4.x.y` branches we sometimes merge device-tree
overlays. And with the altera branches, we will also merge code that is
only specific to those branches.
For these cases, we will have interleaved commits that are not in master,
so we'd need to go back [automatically] further-back in history to find a
commit (that is also in master) to cherry-pick into these branches.
50 commits (back) should be sufficient. If this number needs to be higher
than 50, then (definitely) someone needs to do a manual investigation and
fix-up/cherry-pick/rebase something.
Signed-off-by: Alexandru Ardelean …

ci/travis/run-build.sh: go back 50 commits when trying to cherry-pick

---

drivers/iio/adc/ad7606.c

This fix is only needed on adi repo, upstream it is fixed.
When device is used in software mode, writing scale wasn't updating the
scale property from iio.

iio: adc: ad7606: Fix software scale selection

---

drivers/iio/adc/ad7606.c
drivers/iio/adc/ad7606.h
drivers/iio/adc/ad7606_spi.c

While testing the driver after last modifications and prepare to send it upstream, i observed that ad7606b is not configured to output on a single spi channel by default. The driver configures it now and also makes the initialization delay custom for every device.
The AD7606B output the data on two spi channels by default and this patch
configures the device to output on only one. Also, the initialization delay
can be configured in chip info for every device.

iio: adc: ad7606: Fix ad7606b reading

---

drivers/iio/frequency/adf4371.c

The fract1 word was not being properly programmed on the device leading
to wrong output frequencies.

iio: frequency: adf4371: Fix output frequency setting

---

Documentation/devicetree/bindings/iio/adc/adi,ad7292.yaml
arch/arm/boot/dts/overlays/rpi-ad7292-overlay.dts
drivers/iio/adc/ad7292.c

This pull request adds IIO channels for the eight multiplexed analog input channels included in the AD7292 part. It also adds a voltage regulator to handle its internal voltage reference.

iio: adc: ad7292: Add analog input channels and suport for voltage regulator

---

Documentation/devicetree/bindings/iio/temperature/adi,ltc2983.yaml
drivers/iio/temperature/ltc2983.c

On top of the vast variety of sensors supported by ltc2983, it is also possible to support custom sensors by providing/programing a custom table on the device memory.
This patch adds support for this feature. This patch series also make it easier to configure some properties by doing the Q number format conversion in the driver.

iio: temperature: ltc2983: Support custom sensors

---

drivers/iio/adc/axi_pulse_capture.c

For the IIO framework, 1 means enable and 0 means disable.
For consistency and for avoiding incompatibilities, use the logic here
as well.

iio: axi_pulse_capture: Fix IIO_CHAN_INFO_ENABLE logic

---

arch/arm/boot/dts/adi-ad9265-fmc-125ebz.dtsi
arch/arm/boot/dts/adi-ad9434-fmc-500ebz.dtsi
arch/arm/boot/dts/adi-ad9467-fmc-250ebz.dtsi
arch/arm/boot/dts/adi-fmcjesdadc1.dtsi
arch/arm/boot/dts/adi-fmcomms6.dtsi
arch/microblaze/boot/dts/adi-ad9467-fmc-250ebz.dtsi
arch/microblaze/boot/dts/adi-fmcjesdadc1.dtsi

Because of https://github.com/analogdevicesinc/linux/commit/3fc41fb8c53f20f7ccbe8e8e0a02e41b4b2b6aa7, the default FIRMWARE file is not automatically
loaded when the "firmware" property is missing, so it should be manually
specified, otherwise, the ad9517_default_regs values are used to configure
the clock chip.

dts: Specify AD9517 firmware file

---

ci/travis/run-build.sh

I forgot that branches are sync-ed up-to GIT_FETCH_DEPTH level (which is
50), so trying to sync via cherry-pick at that level needs to be adjusted
to `GIT_FETCH_DEPTH - 1`.
This change does that.

build,travis: adjust cherry-pick sync depth to GIT_FETCH_DEPTH level

---

arch/arm/boot/dts/overlays/Makefile
arch/arm/boot/dts/overlays/rpi-addi9036-overlay.dts

Add devicetree overlay for ADDI9036 3D Time of Flight Development 
Platform.

dts: arm: overlays: Add ADDI9036 overlay

---

drivers/spi/spi.c

The `spi_transfer_wait()` function was merged by accident, when the
`cs_change` delay was merged/cherry-picked.
Might as well use it now. It only replaces an existing block-code from
`spi_transfer_one_message()`.

spi: use `spi_transfer_wait()` (sync with upstream)

---

.travis.yml
ci/travis/run-build.sh

This change allows branches to be sync-ed also locally via:
```
ORIGIN=adi ./ci/travis/run-build.sh sync_branches_with_master
```
ORIGIN is optional, in case it is not named `origin`

build: move branches to script and allow it to be run locally 

---

MAINTAINERS
drivers/net/phy/Kconfig
drivers/net/phy/Makefile
drivers/net/phy/adin.c

This patchset is the first 5 patches that add support for Analog Devices PHYs.
The patches went through about 4 review sets, and these have been reviewed by Andrew Lunn.
The changes are as sent for upstream, so to get them working here, we'll also need a compatibility layer for 4.14 to get them building & working here.
Reviewed-by: Andrew Lunn <andrew@lunn.ch>

 net: phy: adin: add support for Analog Devices PHYs (part 1)

---

drivers/net/phy/adin.c

Part 2 of the upstreamed driver.
There wasn't any feedback on the MDI/MDIX patch.
Adding the driver here as-is and we'll see if we need to sync with upstream later if there are comments.
Reviewed-by: Andrew Lunn <andrew@lunn.ch> (except for patch `
net: phy: adin: add support MDI/MDIX/Auto-MDI selection`)

net: phy: adin: add support for Analog Devices PHYs (part 2)

---

ci/travis/run-build.sh

Because on Travis-CI, the repo is cloned with 50 commits-depth, and
git-fetch is also done at around 50 commits-depth, and because (when doing
git-fetch) we don't keep a local reference to the fetch, we need to use
FETCH_HEAD.
Otherwise the error is something like:
```
From github.com:analogdevicesinc/linux
* branch                xcomm_zynq -> FETCH_HEAD
error: pathspec 'origin/xcomm_zynq' did not match any file(s) known to git.
The command "./ci/travis/run-build.sh" exited with 1.
```
A reason this fails, is related to commit
c76a5209408fc37753a3d2f21dcf9f35078b7059 ("build: use detached versions of
the remote branches"). We still want detached versions of the git-fetch-ed
stuff, and the only reference there exists when doing a git-fetch is
`FETCH_HEAD`.
Tested locally, with a …

build,travis: use FETCH_HEAD when sync-ing

---

Documentation/devicetree/bindings/net/adi,adin.yaml
MAINTAINERS
drivers/net/phy/adin.c

Part 3 of the driver.
One thing is special here: `net: phy: adin: define `features` flags`
This is required so that the PHY can be configured properly by the framework.

net: phy: adin: add support for Analog Devices PHYs (part 3)

---

drivers/iio/temperature/ltc2983.c

For 64bit builds, printk was throwing a warning related with the
printing of size_t variables, which are 64bit long on 64bit
architecture. This patch set's the appropriate length modifier to %zu.

iio: ltc2983: Fix 64bit compilation warnings

---

Documentation/devicetree/bindings/iio/adc/adi,ad5940.yaml
arch/arm/boot/dts/overlays/rpi-ad5940-overlay.dts
drivers/iio/adc/ad5940.c

This adds spi and interrupt support for the device to make it work.

iio: adc: ad5940: add spi and interrupt support 

---

drivers/iio/frequency/m2k-dac.c

HDL added dma_sync_start flag that can be used to force the two DAC DMAs 
to start only when both have data.
dma_sync_start flag should be set to 0 if only one channel is active

iio: frequency: m2k-dac: Add attribute to control dma_sync_start

---

ci/travis/run-build.sh

When the code was written initially some pre-vacation logic was used.
The initial mechanism for cherry-picking (from mater) when merge commits
was sound, except for the last error check when `was_a_merge` variable was
checked.
If `was_a_merge` is 0, it means that no merge commits were found, but an
error occurred, so it should be checked if `was_a_merge` is 1 (not 0).
The last couple of merges contained some merge commits, and that's how this
issue was identified.

build,travis: fix cherry-pick syncing when merge commits found

---

drivers/net/phy/adin.c

The code was merged in ADI master a bit sooner than what was sent upstream
and this slipped through.
The upstream version does not have this bug (i.e. has the fixed version).

net: phy: adin: fix logical condition in adin_get_downshift()

---

arch/arm/boot/dts/zynq-m2k-reva.dts

On M2K the output freq of ADF4360 PLL should be 100MHz. If out freq is
not set explicitly in DT a default value equal with vco_min will be
used.
Also according to already validated M2K setup the CPI should be 
set to 2.5mA.
​

ARM: dtb: m2k: Set out of ADF4360 to 100MHz and CPI to 2.5mA

---

drivers/net/phy/xilinx_gmii2rgmii.c
include/linux/mdio.h

The gmii2rgmii driver had a bug when the PHY driver would have a private field/data.
This was fixed via `net: gmii2rgmii: do not attach if phy has a priv field `, but that only helped to avoid the memory corruption.
Xilinx fixed the issue by adding a `priv` field to `struct mdio_device`.
Not sure if that's the best fix, but since Xilinx is our upstream, we will get it anyway at some point in time.
We need this to make the ADIN dual-phy board to work with the GMII2RGMII converter.
The `gmii2rgmii` driver overrides the `read_status` hook of the PHY driver, because it also needs to update link status to the gmii2rgmii HDL converter.

net: gmii2rgmii: backport patches/fixes for Xilinx master

---

arch/arm/boot/dts/adi-adin1300-dual.dtsi
arch/arm/boot/dts/zynq-zc706-adv7511-adin1300-dual.dts
arch/arm/boot/dts/zynq-zed-adv7511-adin1300-dual.dts

This change adds the example device-tree for the dual ADIN1300 reference
board.
On the ZC706, the PHYs need to be configured in RGMII-ID to work.
The reference design has a GMII2RGMII converter, which sits in-between the
PHY & MAC. This converter IP/HDL needs the `gmii2rgmii` driver to be
instantiated to do the work.
In order to properly work (with the ADIN PHY), this PR is also required:
https://github.com/analogdevicesinc/linux/pull/556
The PR fixes some memory corruption caused by the `gmii2rgmii` when
operating with the ADIN PHY driver.

arch: arm: add reference zynq-zc706-adv7511-adin1300-dual.dts

---

.travis.yml
ci/travis/run-build.sh

At this point in time, cherry-pick sync-ing has been validated by the
`adi-4.Y.0` and `rpi-4.Y.y` branches.
Time to add `altera_4.Y` and relieve some sync-ing duties to automation.
This brings Intel/Altera reference designs closer to Xilinx level, making
them a first-class citizen.
We will need to change the Linux methodology of merging stuff to altera
branches from now on: i.e. merge drivers in master ALL-THE-TIME, and merge
only DT/board/branch specific-stuff in `altera_x.y` branches.

ci,travis: add altera_4.14 to the cherry-pick sync

---

.travis.yml

The `altera_x.y` branches need to build the kernel for Intel Arria
reference boards.
So, we just need to update the `.travis.yml` file to reflect this.

build,travis: add rules to build kernel Intel ARM ref boards

---

ci/travis/run-build.sh

This only fixes the cases when doing branch-sync with master locally.
`git cherry-pick` fails with:
```
Failed to cherry-pick commits '<commit>..adi/master'
error: empty commit set passed
fatal: cherry-pick failed
```
when trying to cherry-pick something that was already cherry-picked.
In this case, the commit was already cherry-picked, so, doing
`git cherry-pick <commit>..adi/master` will error out.

ci,build: don't cherry-pick commit if already up-to-date

---

arch/arm64/boot/dts/xilinx/zynqmp-zcu102-rev10-ad9208-hmc7044.dts

This patch adds support for AD9208-3000EBZ FMC + EVAL-HMC7044 setup.
Required connections:
- EVAL-HMC7044 J28 -> AD9208-3000EBZ J201
- EVAL-HMC7044 J22 -> AD9208-3000EBZ J3
- EVAL-HMC7044 J38 -> ZCU102 J79
- EVAL-HMC7044 J39 -> ZCU102 J80
- EVAL-HMC7044 J1.20 -> ZCU102 J55.1
- EVAL-HMC7044 J1.18 -> ZCU102 J55.5
- EVAL-HMC7044 J1.16 -> ZCU102 J55.3
- EVAL-HMC7044 J1.14 -> ZCU102 J55.7
- EVAL-HMC7044 J1.12 -> ZCU102 J55.9
Compatible hdl project: https://github.com/analogdevicesinc/hdl/releases/tag/legacy_ad9208_2019_r1

arm64: boot: dts: Add zynqmp-zcu102-rev10-ad9208-hmc7044 support

---

drivers/net/ethernet/stmicro/stmmac/dwmac-socfpga.c
drivers/net/ethernet/stmicro/stmmac/stmmac_main.c
drivers/net/ethernet/stmicro/stmmac/stmmac_platform.c
include/linux/stmmac.h

This was tested on a Arria 10 SoC board.
In-between the MAC & PHY there can be a mode converter, which converts one
mode to another (e.g. GMII-to-RGMII).
The converter, can be passive (i.e. no driver or OS/SW information
required), so the MAC & PHY need to be configured differently.
For the `stmmac` driver, this is implemented via a `mac-mode` property in
the device-tree, which configures the MAC into a certain mode, and for the
PHY a `phy_interface` field will hold the mode of the PHY. The mode of the
PHY will be passed to the `[of_]phy_connect()` function and from there-on
the PHY should work a different mode.

net: stmmac: implement support for passive mode converters via dt

---

Documentation/devicetree/bindings/hwmon/adi,ltc2947.yaml
drivers/hwmon/ltc2947-core.c
drivers/hwmon/ltc2947-i2c.c
drivers/hwmon/ltc2947-spi.c
drivers/hwmon/ltc2947.h

This patch series adds support for:
- Power management;
- Support Accumulator control;
- Support GPIO configuration.
The devicetree bindings are also updated according with the added features.

hwmon: ltc2947: New features

---

drivers/hwmon/ltc2947-core.c

For 64bit builds, printk was throwing a warning related with the
printing of size_t variables, which are 64bit long on 64bit
architecture. This patch set's the appropriate length modifier to %zu.

hwmon: ltc2947: Fix 64bit compilation warnings

---

arch/arm/boot/dts/zynq-adrv9361-z7035-fmc.dts

Not sure if (and why) this worked before, but when attaching the PHY to the
`macb` MAC driver via `phy-handle`, the actual PHY node should be passed,
and not the `gmii2rgmii` node.
The `gmii2rgmii` driver is an MDIO driver, not a PHY driver, so it never
made sense to attach them like this, and it probably worked due to some
fluke.
This change attaches the phy1 node to the gem1 (MAC) node, and the M2 port
works.

arch: arm: zynq-adrv9361-z7035-fmc.dts: fix M2 port not working

---

arch/arm/boot/dts/zynq-adrv9361-z7035-fmc.dts

Backport to 2019_R1 fix from master, merged via PR #571 

[2019_R1] arch: arm: zynq-adrv9361-z7035-fmc.dts: fix M2 port not working

---

drivers/dma/dma-axi-dmac.c

dmaengine_slave_config is called by dmaengine_pcm_hw_params when using axi-i2s with axi-dmac. If device_config is NULL, [-ENOSYS](https://github.com/analogdevicesinc/linux/blob/master/include/linux/dmaengine.h#L818) is returned, which breaks the snd_pcm_hw_params function.
This is a fix for the error:
```
$ aplay -D plughw:ADAU1761 /usr/share/sounds/alsa/Front_Center.wav
Playing WAVE '/usr/share/sounds/alsa/Front_Center.wav' : Signed 16 bit Little Endian, Rate 48000 Hz, Mono
axi-i2s 43c20000.axi-i2s: ASoC: 43c20000.axi-i2s hw params failed: -38
aplay: set_params:1403: Unable to install hw params:
ACCESS:  RW_INTERLEAVED
FORMAT:  S16_LE
SUBFORMAT:  STD
SAMPLE_BITS: 16
FRAME_BITS: 16
CHANNELS: 1
RATE: 48000
PERIOD_TIME: 125000
PERIOD_SIZE: 6000
PERIOD_BYTES: 12000
PERIODS: 4
BUFFER_TIME: …
```

dma: axi-dmac: simple device_config operation implemented

---

drivers/hwmon/ltc2947-core.c

Return proper error code when some operation is not supported. In those
cases, the driver was returning -EOPNOTSUPP which stands for "Operation
not supported on transport endpoint".

hwmon: ltc2947: Return proper error code

---

Documentation/ABI/testing/sysfs-bus-iio-accel-adxl372
drivers/iio/accel/adxl372.c

By default, if all three channels (x, y, z) are enabled, sample sets of
concurrent 3-axis data is stored in the FIFO. This patch adds the option
to configure the FIFO to store peak acceleration (x, y and z) of every
over-threshold event. Since we cannot store 1 or 2 axis peak acceleration
data in the FIFO, then all three axis need to be enabled in order for this
mode to work.

iio: accel: adxl372: Add support for FIFO peak mode

---

drivers/net/phy/adin.c
include/uapi/linux/ethtool.h
net/core/ethtool.c

The discussion for EDPD has reached a conclusion.
Backported patch `ethtool: add PHY Fast Link Down support ` as it is a simple patch and with it the EDPD ethtool patch applies without any fixup.
Reviewed-by: Andrew Lunn <andrew@lunn.ch> (for patch 1 of EDPD)
Reviewed-by: Florian Fainelli <f.fainelli@gmail.com> (for both EDPD patches)

net: phy: adin: implement Energy Detect Powerdown mode via phy-tunable

---

Documentation/devicetree/bindings/net/adi,adin.yaml

The `adi,disable-energy-detect` property was implemented in an initial
version of the `adin` driver series, but after a review it was discarded in
favor of implementing the ETHTOOL_PHY_EDPD phy-tunable option.
With the ETHTOOL_PHY_EDPD control, it's possible to disable/enable
Energy-Detect-Power-Down for the `adin` PHY, so this device-tree is not
needed.
Fixes: 767078132ff9 ("dt-bindings: net: add bindings for ADIN PHY driver")

dt-bindings: net: remove un-implemented property

---

drivers/iio/gyro/adis16130.c
drivers/iio/gyro/adis16260.c

This changeset removes some un-needed mlocks.
There are already some locks protecting the state of the ops, so mlock is un-needed.

iio: gyro: remove some un-needed mlocks

---

drivers/iio/frequency/adf4360.c

iio_chan_spec_ext_info read() and write() functions must return a ssize_t.

iio: frequency: adf4360: Fix 64-bits compilation error

---

arch/arm64/boot/dts/xilinx/adi-adin1300-dual.dtsi

The design for the dual-PHY for ZCU102 has been done for it to be setup on
FMC1. However, the EEPROM was initially setup for FMC0 and the EEPROM was
written when connected to FMC0.
This change moves the EEPROM to FMC1, so that the FMC-swap is not needed.
The final design for ZCU102 will be done on FMC1.

arch: arm64: adi-adin1300-dual.dtsi: move eeprom defintion to FMC1

---

arch/arm/boot/dts/socfpga_arria10_socdk_adrv9008-1.dts
arch/arm/boot/dts/socfpga_arria10_socdk_adrv9008-2.dts
arch/arm/boot/dts/socfpga_arria10_socdk_adrv9009.dts

With the previous value, there were errors on the RX/OBS links
With this change, there are no errors at maximum lane rate
Signed-off-by: Adrian Costina <adrian.costina@analog.com>

arm: dts: Change JESD pre emphasis setting for ADRV9009 on A10SOC

---

.travis.yml
arch/arm/boot/dts/adi-ad9265-fmc-125ebz.dtsi
arch/arm/boot/dts/adi-ad9434-fmc-500ebz.dtsi
arch/arm/boot/dts/adi-fmcomms6.dtsi
arch/arm/boot/dts/zynq-zc706-adv7511-cn0506-rgmii.dts
arch/arm/boot/dts/zynq-zed-adv7511-pmod-ad1-da1.dts
arch/arm64/boot/dts/xilinx/zynqmp-adrv9009-zu11eg-revb-adrv2crr-fmc-sync.dts
arch/arm64/boot/dts/xilinx/zynqmp-adrv9009-zu11eg-revb-adrv2crr-fmc.dts
arch/arm64/boot/dts/xilinx/zynqmp-adrv9009-zu11eg-revb.dtsi
arch/microblaze/boot/dts/adi-ad9467-fmc-250ebz.dtsi
ci/travis/run-build.sh

It seems that the dtb builds were not being run since the split, and we
never noticed this.
The initial commit that did the split was done in order to better identify
compiler errors from dtb errors. What happened, was that dtb's were never
compiled since then.
With this change, the matrix was simplified; the DTS_FILES variables have
been moved to separate builds, so that the `dtb_build_test` rules have
something to actually run.
Also, added a new matrix entry for ARM64; previously DTS_FILES were run for
each ARM target, and we have 4 now.
Fixes: 6827f3d ("build,travis: split builds into smaller parts")

arch: arm{64}: fix broken device-trees & dtb_build

---

drivers/iio/gyro/adis16136.c
drivers/iio/imu/adis.c
drivers/iio/imu/adis16400.c
drivers/iio/imu/adis16480.c
drivers/iio/imu/adis_buffer.c
include/linux/iio/imu/adis.h

This changeset is mostly meant for review, and will be sent upstream.
The ADIS drivers and library use indio_dev's mlock in various parts.
The changeset removes the use of mlock, and tries to revise the consistency of locking and unify the locks into a single one that is handled via the ADIS library.

iio: imu: adis: cleanup the lock usage in the ADIS library

---

drivers/iio/adc/ad9680.c
drivers/iio/adc/cf_axi_tdd.c
drivers/iio/adc/talise/talise.c
drivers/iio/adc/talise/talise_arm.c
drivers/iio/frequency/ad917x/ad917x_nco_api.c
drivers/iio/frequency/ad9517.c

This series is intended to fix compilation warnings related with ADI drivers/code. The config file used was adi_zynqmp_defconfig.

Fix linux warnings

---

ci/travis/run-build.sh

'_' is a way more common separator in filenames and does not work well for
files that have underscores.
The '=' symbol is less common, so it should work.

ci,build: use '=' as split separator instead of '_'

---

.travis.yml

Branch `master-xilinx-4.19` is built when updating.

build,travis: build adi-4.19.0 branch

---

arch/arm/boot/dts/overlays/rpi-addi9036-overlay.dts

In ADI ToF REV.C the EEPROM memory is not on a separate I2C bus but 
share the same I2C bus with ADDI9036 ToF conroller. The selection is 
performed using DT overrides and backward compatibility with REV.B is 
preserved.

dts: arm: overlays: Add support for ADDI9036 REV.C

---

drivers/nvmem/adi_axi_sysid.c

At some point in upstream, the nvmem_unregister() function will have a void
return, which will cause a build error.
So, just ignore the return value now.

nvmem: adi_axi_sysid: ignore return value

---

ci/travis/run-build.sh

Same as for the other branches, whatever we merge to master, will get
cherry-picked to this branch as well.
This should give us a good-enough set of patches on top of Jonathan's IIO
togreg branch, which should help a bit more with upstreaming over time.
i.e. what-we've-upstreamed vs what-we-still-need-to-upstream

build,ci: add `adi-iio` to auto cherry-pick sync

---

arch/arm/boot/dts/socfpga_cyclone5_sockit_arradio.dts

Updated interrupts and channel definition according to dma-axi-dmac.c.
Signed-off-by: Sergiu Cuciurean sergiu.cuciurean@analog.com

arch: arm: socfpga_cyclone5_sockit_arradio.dts: Update for dma driver

---

arch/arm/boot/dts/adi-cn0506-socfpga-mii.dtsi

When the split was done for MII modes, the correct property for the PHY
mode is `phy-mode` not `mac-mode`.
Fixes: 8fb262f1fdb0 ("arch: arm: socfpga: split device-trees for MII mode for CN0506")

arch: arm: socfpga: fix cn0506 mii device-tree

---

drivers/iio/imu/adis.c

This lock was forgotten when things were reworked. It should have been
removed then. Leaving it there will cause a deadlock.

iio: imu: adis: remove forgotten lock in __adis_read_reg()

---

arch/arm/boot/dts/zynq-adrv9361-z7035-userspace.dts
arch/arm/boot/dts/zynq-adrv9361-z7035.dtsi
arch/arm/boot/dts/zynq-adrv9364-z7020.dtsi
arch/arm/boot/dts/zynq-e310.dts
arch/arm/boot/dts/zynq-m2k-reva.dts
arch/arm/boot/dts/zynq-m2k.dtsi
arch/arm/boot/dts/zynq-microzed.dtsi
arch/arm/boot/dts/zynq-pluto-sdr.dtsi
arch/arm/boot/dts/zynq-zc702.dtsi
arch/arm/boot/dts/zynq-zc706.dtsi
arch/arm/boot/dts/zynq-zed.dtsi

Newer DTC compilers have more checks and these fail in our DTB build test.
https://travis-ci.org/analogdevicesinc/linux/jobs/597989404
These properties are fixable now in 4.14.
These changes do that.

arch: arm: polish device-trees

---

arch/arm/boot/dts/zynq-m2k-reva.dts
arch/arm/boot/dts/zynq-zed-adv7511-m2k-revb.dts
arch/arm/boot/dts/zynq-zed-adv7511-m2k-revc.dts

The newer DTC compilers crash when they try to process these nodes.
The AD9963 driver does not seem to implement any code for parsing those
remote endpoint nodes, so remove them.
Error is:
```
DTC     arch/arm/boot/dts/zynq-zed-adv7511-m2k-revb.dtb
dtc: scripts/dtc/livetree.c:438: propval_cell: Assertion `prop->val.len == sizeof(cell_t)' failed.
Aborted (core dumped)
make[1]: *** [scripts/Makefile.lib:293: arch/arm/boot/dts/zynq-zed-adv7511-m2k-revb.dtb] Error 134
```

arch: arm: m2k: remove dead-end end-points

---

ci/travis/run-build.sh
drivers/dma/dmatest.c
drivers/gpu/drm/adi_axi_hdmi/axi_hdmi_crtc.c
drivers/gpu/drm/xlnx/zynqmp_disp.c
drivers/iio/frequency/ad917x/ad917x_nco_api.c
drivers/media/i2c/adv7604.c
drivers/misc/mathworks/mw_stream_channel.c
drivers/staging/iio/adc/ad7192.c

Sometimes we don't catch warnings, and they go upstream.
We should catch warnings as early as possible and fix them. Otherwise they
slip and get caught by Greg, which isn't the best thing.
This change treats all (except `-Werror=frame-larger-than=`) warnings as
errors. Some Talise & Mykonos codes use more than 1024 bytes on the stack
and converting/reworking them is unsafe.

build,ci: treat warnings as errors

---

arch/arm/vfp/vfpmodule.c
net/netfilter/ipvs/ip_vs_ctl.c

Since PR #613 , some warnings popped up here as well.
This changeset fixes them

[rpi-4.14.y] build: fix compiler warnings treated as errors

---

Documentation/devicetree/bindings/iio/imu/adi,adis16475.yaml
MAINTAINERS
drivers/iio/imu/Kconfig
drivers/iio/imu/Makefile
drivers/iio/imu/adis16475.c
drivers/iio/imu/adis_buffer.c
drivers/iio/imu/adis_trigger.c
include/linux/iio/imu/adis.h

This series adds support for the ADIS16475 and similar IMU sensors. The first 2 patches in the series are aimed to the adis library:
- The first adds a managed device version for `adis_setup_buffer_and_trigger`;
- The second let's the user configure the irq mask.

Add support for adis16475

---

drivers/gpu/drm/vc4/vc4_firmware_kms.c

The switch statement needed a `default` case. Not the best fix, but it
silences the warning, and it's the best that can be done here.

drm: vc4: fix uninitialized var

---

drivers/iio/imu/adis16475.c

The wrong table was being passed to MODULE_DEVICE_TABLE. Hence,
compiling as module would fail.
Fixes: 699730d5d930 (iio: imu: Add support for adis16475)

iio: adis16475: Fix of_device_id

---

drivers/iio/imu/adis16480.c

This series adds somes major and minor fixes to the adis16480 driver. The first one is related with wait times, which can be different from device to device. Furthermore, some of those times were not being respected which could lead to issues. The major fix for this series is related with the scales which were wrong and giving bad values. Devices tested:
- adis16480;
- adis16485;
- adis16375.

Fixes adis16480

---

.travis.yml
ci/travis/lib.sh
ci/travis/run-build-docker.sh
ci/travis/run-build.sh

This changeset wraps all builds (except for checkpatch & dtb_build_test) in
the docker scripts that were also added for libiio.
The main reason/advantage for this, is to support newer Ubuntu versions
which come with newer compilers & tools. In this day-n-age, things move
so fast, that even Ubuntu 16.04 (from almost 4 years ago) is super-old.
We send patches upstream, only to get hit back by warnings/errors that
newer compilers catch, but older ones don't.

build: dockerize builds to use newer ubuntu versions

---

arch/arm/boot/dts/overlays/Makefile
arch/arm/boot/dts/overlays/adis16475-overlay.dts

Add devicetree overlay for the ADIS16475 IMU.

dts: arm: overlays: Add ADIS16475 overlay

---

ci/travis/run-build.sh

Some 4.19 kernel builds require libssl-dev to be installed on the host.
This isn't required on current 4.14. The reason this is showing up, is
because we're using vanilla Ubuntu docker images, which have few things
installed and now we're finding what to install.

build,ci: install libssl-dev for 4.19 kernel builds

---

.travis.yml
drivers/net/wireless/realtek/rtl8192cu/core/rtw_ap.c
drivers/net/wireless/realtek/rtl8192cu/core/rtw_br_ext.c
drivers/net/wireless/realtek/rtl8192cu/include/drv_conf.h
drivers/net/wireless/realtek/rtl8192cu/include/osdep_service.h
drivers/net/wireless/realtek/rtl8192cu/os_dep/linux/rtw_android.c
fs/proc/task_mmu.c

The only upstream issue is fs/proc/task_mmu.c.
The other issue is the rtl8192cu driver which looks to be present only in
the RPi branch. Errors on this code are ignored.

[rpi-4.14.y] build: fix/disable GCC-9 warnings

---

.travis.yml
drivers/net/wireless/mediatek/mt76/mt76x2_eeprom.c
drivers/net/wireless/realtek/rtl8192cu/include/drv_conf.h
drivers/usb/host/dwc_otg/dwc_otg_hcd.h
drivers/video/fbdev/bcm2708_fb.c
sound/soc/bcm/hifiberry_dacplusadc.c

Since warnings are treated as errors, and the compiler has been updated to GCC-9, we need to address/fix some of them, which are upstream in the RPi Linux.
This changeset does that.

[rpi-4.19.y] build: fix/disable GCC-9 errors/warnings

---

ci/travis/run-build.sh

Some GCC versions output full versions (e.g. 8.3.0), but we want only the
major version. Ubuntu's GCC seems to output only the major.
Also, some checks are present only in GCC 9 & and not GCC 8.
This change splits the checks which are new in GCC 8 & 9, and also just
strips the major version. The idea is to avoid any weird issues that may
arise when/if changing docker images.

build,ci: fine-tune KCFLAGS versus GCC check

---

drivers/iio/adc/ad7606.c

When a conversion result is being read from ADC, the driver reads the number
of channels + 1 because it thinks that IIO_CHAN_SOFT_TIMESTAMP is also a
physical channel. This patch fixes this issue.
Fixes: 552a21f35477 ("staging: iio: adc: ad7606: Move out of staging")

iio: adc: ad7606: fix reading unnecessary data from device

---

drivers/iio/jesd204/axi_jesd204_rx.c
drivers/iio/jesd204/xilinx_transceiver.c
drivers/input/keyboard/adp5589-keys.c
drivers/media/platform/axi-hdmi-rx.c

This only occurs on the adi-iio branch, which means that the upstream kernel may have likely enabled this warning at some point in time.
This change addresses them.

build: fix implicit fall-through statements

---

drivers/dma/xilinx/xilinx_dpdma.c
drivers/iio/adc/cf_axi_adc_core.c
drivers/iio/frequency/cf_axi_dds.c
drivers/iio/jesd204/axi_jesd204b_v51.c

Continuation from #633 
This should be the last batch of implicit fall-through warnings fixes.

build: fix implicit fall-through statements (part 2)

---

drivers/iio/adc/talise/adi_hal.h

On newer kernels warning/error is:
```
drivers/iio/adc/talise/talise_gpio.c:2032:5: error: ISO C90 forbids array 'gpioStatus' whose size can't be evaluated [-Werror=vla]
2032 |     uint8_t gpioStatus[GPIO_STATUS_CMD_SIZE_BYTES];
```
It's probable that upstream kernel decided to enforce some C90 stuff [vs
C99]. We won't fix this code, but we will ignore it so that it builds on
the adi-iio branch.

iio: adc: talise-api: ignore ISO C90 vla warnings

---

drivers/iio/logic/m2k-fabric.c

The main driver for this change is a compiler warning that occurs on GCC 9
(x86_64) where the `gpio_names` & `num_gpio_names` could be un-initialized.
The warning is correct, because there is no final-else path.
This change also fixes this warning by checking `gpio_names`. This should
also cover `num_gpio_names`.

iio: m2k-fabric: move gpio init into it's own function

---

drivers/power/supply/adp5061.c

The return type of these functions is `ssize_t` not `int`. This is reported
on x86_64 compilers.

power: supply: adp5061: fix incompatible function pointer types

---

drivers/iio/logic/m2k-logic-analyzer.c

Found by x86_64 compiler, and Raspberry Pi's build. The `build_rx` is
attached to the IIO buffer, before initialized. It's re-attached also after
it's initialized, so it seems to work. But from the looks of things, this
could potentially corrupt memory and go un-noticed.

iio: m2k-logic-analyzer: fix uninitialized variable usage

---

drivers/iio/Kconfig
drivers/iio/Makefile
drivers/iio/regmap/Kconfig
drivers/iio/regmap/Makefile
drivers/iio/regmap/iio-regmap-i2c.c
drivers/iio/regmap/iio-regmap-spi.c
drivers/iio/regmap/iio-regmap.c
drivers/iio/regmap/iio-regmap.h

This change adds support for the Generic IIO access driver via
I2C and SPI. The intent for this chip is to provide a base/simple driver
for prototyping new IIO drivers and new boards by allowing regmap
sequences to be loaded at probe & remove to do chip init.
Later this may be extended to optionally configure IIO channels.

iio: iio-regmap: New driver for generic regmap

---

drivers/iio/jesd204/axi_adxcvr.c

This patch adds a sys clock check inside adxcvr_clk_set_rate. Previously
this function did not verify the sys clock source and it was always
writing the configuration to QPLL0 register.
Fixes: 439daa8 ("iio: jesd204: axi_adxcvr: Add support GTH3/4 QPLL1
support")

drivers: iio: jesd204: axi_adxcvr: Fix QPLL1 register write

---

drivers/iio/jesd204/axi_adxcvr.c

This patch adds a sys clock check inside adxcvr_clk_set_rate. Previously
this function did not verify the sys clock source and it was always
writing the configuration to QPLL0 register.
Fixes: 439daa8 ("iio: jesd204: axi_adxcvr: Add support GTH3/4 QPLL1
support")

[Port-from-master]drivers: iio: jesd204: axi_adxcvr: Fix QPLL1 register write

---

Documentation/devicetree/bindings/iio/imu/adi,adis16475.yaml
drivers/iio/imu/adis.c
drivers/iio/imu/adis16475.c
include/linux/iio/imu/adis.h

The core of the series is to support the adis1650x family. Additionally, the series has a patch to add `regmap_update_bits` like API to the adis library and some fixes for issues found when supporting the new devices.

Support adis1650x family

---

Documentation/devicetree/bindings/iio/frequency/adi,adf4360.yaml
arch/arm/boot/dts/zynq-m2k-reva.dts
drivers/iio/frequency/adf4360.c

On ADALM2000 was discovered a problem related to PLL loosing lock if the ADF4360 output level is set to 11mA.
This PR add :
- DT property to allow output power level configuration
- update of M2K devicetree 
- fix of a typo in output power level enumeration.

iio: frequency: adf4360: Fix for ADF4360 default output level on M2K

---

drivers/iio/adc/ad9963.c

For M2K turn on the bandgap DAC reference voltage.
Reported-by: Mihai Bancisor <mihai.bancisor@analog.com>

iio: adc: ad9963: Fix external reference drift

---

drivers/iio/gyro/adis16136.c
drivers/iio/gyro/adis16260.c
drivers/iio/imu/Kconfig
drivers/iio/imu/adis.c
drivers/iio/imu/adis16400.c
drivers/iio/imu/adis16460.c
drivers/iio/imu/adis16475.c
drivers/iio/imu/adis16480.c
drivers/staging/iio/accel/adis16201.c
drivers/staging/iio/accel/adis16203.c
drivers/staging/iio/accel/adis16209.c
drivers/staging/iio/accel/adis16240.c
include/linux/iio/imu/adis.h

This series adds some refactoring to the adis library. There was 2 main motivations for this:
1. The definitions of the timeouts for the various devices supported on the drivers was just a big confusion. The timings defined in the datasheets were just not being respected. Sometimes we were not sleeping enough time while some other times we were sleeping way to much. Furthermore, a unique timeout was being defined for all the devices and for both reset and self_test command. In first place, in some devices this timings are different and this is also true between different devices (even when supported by the same driver);
2. Apparently new devices use the GLOB_CMD register while older devices used the MSG_CTRL for the self_test command. This (I think) made that new drivers stopped calling …

ADIS library refactor

---

drivers/iio/imu/adis16475.c

This patch fixes read/write of the iio
IIO_CHAN_INFO_LOW_PASS_FILTER_3DB_FREQUENCY parameter. The value was
being handled as IIO_VAL_INT_PLUS_MICRO without proper scaling.
However, this value can be handled as just IIO_VAL_INT since the allowed
values are all integers. This led to a minor refactor in
`adis16475_read_raw()`.
Fixes: 699730d5d9302 ("iio: imu: Add support for adis16475")

iio: adis16475: Fix Low Pass Filter handling

---

drivers/iio/dac/ad5755.c

Switched of.h used functions to property.h functions.

iio: ad5755: remove use of of.h

---

drivers/iio/gyro/adis16136.c
drivers/iio/imu/adis16400.c
drivers/iio/imu/adis16475.c
drivers/iio/imu/adis16480.c

This series fixes a NULL ptr dereference introduced by  9020f82.

Fix adis fix null ptr

---

drivers/iio/adc/ad7124.c

When the internal reference was selected by a channel it was not enabled.
This patch fixes that and enables it.

drivers: iio: adc: ad7124: Enable internal reference

---

Documentation/devicetree/bindings/iio/adc/adi,ad7091r5.yaml

Documentation for AD7091R5 ADC was added.
Reviewed-by: Rob Herring <robh@kernel.org>

dt-binding: iio: Add documentation for AD7091R5

---

drivers/iio/adc/ad9680.c
drivers/iio/adc/cf_axi_adc.h

When trying to set an invalid rate to the driver, the clk_set_rate() may
fail, exiting without re-initializing the clocks.
This is fine.
However when trying to write a new (maybe valid rate) syslog would get
spammed with plenty of stack-trace warnings like:
```
[<c010ee74>] (unwind_backtrace) from [<c010b5b0>] (show_stack+0x10/0x14)
[<c010b5b0>] (show_stack) from [<c06d4374>] (dump_stack+0x8c/0xa0)
[<c06d4374>] (dump_stack) from [<c011cb6c>] (__warn+0xe4/0x100)
[<c011cb6c>] (__warn) from [<c011c838>] (warn_slowpath_null+0x20/0x28)
[<c011c838>] (warn_slowpath_null) from [<c03354a8>] (clk_unprepare+0x24/0x2c)
[<c03354a8>] (clk_unprepare) from [<c05b0d80>] (ad9680_write_raw+0x23c/0x408)
[<c05b0d80>] (ad9680_write_raw) from [<c05404e0>] (iio_write_channel_info+0x9c/0xc0)
[<c05404e0>] …
```

iio: adc: ad9680: cleanup clock {un}init paths

---

arch/arm/boot/dts/zynq-zc706-adv7511-adrv9009.dts
arch/arm/boot/dts/zynq-zc706-adv7511-adrv9371.dts
arch/arm64/boot/dts/xilinx/zynqmp-zcu102-rev10-adrv9008-1.dts
arch/arm64/boot/dts/xilinx/zynqmp-zcu102-rev10-adrv9008-2.dts
arch/arm64/boot/dts/xilinx/zynqmp-zcu102-rev10-adrv9009.dts
arch/arm64/boot/dts/xilinx/zynqmp-zcu102-rev10-adrv9371.dts
arch/microblaze/boot/dts/kcu105_adrv9371x.dts

This issue was reported on Jira. The active state for the FIR filter gpios was set to active low and was set by default. Also for zcu102 the gpio address was incorrect. 
This set of patches must be ported to 2019_R1 branch also.

Fix interpolation decim

---

drivers/iio/frequency/adf4350.c
include/linux/iio/frequency/adf4350.h

This patch replaces functions from of.h and of_gpio.h with their counterparts 
from property.h and gpio/consumer.h.

Adf4350 remove of use

---

arch/arm64/boot/dts/xilinx/zynqmp.dtsi

https://www.xilinx.com/support/answers/69995.html
The issue is still present and affects other SD card models too (e.g. SanDisk Ultra microSDHC 16GB).
Until the issue is not confirmed on other branches, I would keep the fix only for 2019_R1.

arm64: zynqmp: Prevent mmcblk0 error -110

---

.travis.yml
ci/travis/run-build.sh

We will update to 4.19 in the near-future.
We can stop auto-syncing these rebased branches now, to prevent
un-necessary builds that may fail.
We also would want to stop supporting them.

ci,travis: remove 4.14 rebased branches from auto-sync

---

arch/arm64/boot/dts/xilinx/zynqmp-adrv9009-zu11eg-reva.dts
arch/arm64/boot/dts/xilinx/zynqmp-zcu102-rev10-ad9172-fmc-ebz.dts
arch/arm64/boot/dts/xilinx/zynqmp-zcu102-rev10-ad9208-hmc7044.dts
arch/arm64/boot/dts/xilinx/zynqmp-zcu102-rev10-ad9208.dts
arch/arm64/boot/dts/xilinx/zynqmp-zcu102-rev10-ad9361-fmcomms2-3.dts
arch/arm64/boot/dts/xilinx/zynqmp-zcu102-rev10-ad9361-fmcomms5.dts
arch/arm64/boot/dts/xilinx/zynqmp-zcu102-rev10-ad9364-fmcomms4.dts
arch/arm64/boot/dts/xilinx/zynqmp-zcu102-rev10-adrv9008-1.dts
arch/arm64/boot/dts/xilinx/zynqmp-zcu102-rev10-adrv9008-2.dts
arch/arm64/boot/dts/xilinx/zynqmp-zcu102-rev10-adrv9009.dts
arch/arm64/boot/dts/xilinx/zynqmp-zcu102-rev10-adrv9371.dts
arch/arm64/boot/dts/xilinx/zynqmp-zcu102-rev10-fmcdaq2.dts
arch/arm64/boot/dts/xilinx/zynqmp-zcu102-rev10-fmcdaq3.dts
arch/arm64/boot/dts/xilinx/zynqmp-zcu102-revB-ad9361-fmcomms2-3.dts
arch/arm64/boot/dts/xilinx/zynqmp-zcu102-revB-ad9364-fmcomms4.dts

The reference got renamed in Xilinx's base device-trees.
This change renames it in ADI's device-trees for 4.19.

arch: arm64: rename clk -> zynqmp_clk

---

arch/arm/boot/dts/zynq-zc706-adv7511-ad6676-fmc.dts
arch/arm/boot/dts/zynq-zc706-adv7511-ad9172-fmc-ebz.dts
arch/arm/boot/dts/zynq-zc706-adv7511-ad9625-fmcadc2.dts
arch/arm/boot/dts/zynq-zc706-adv7511-adrv9008-1.dts
arch/arm/boot/dts/zynq-zc706-adv7511-adrv9008-2.dts
arch/arm/boot/dts/zynq-zc706-adv7511-adrv9009.dts
arch/arm/boot/dts/zynq-zc706-adv7511-adrv9371.dts
arch/arm/boot/dts/zynq-zc706-adv7511-fmcadc4.dts
arch/arm/boot/dts/zynq-zc706-adv7511-fmcdaq2.dts
arch/arm/boot/dts/zynq-zc706-adv7511-fmcdaq3.dts
arch/arm/boot/dts/zynq-zc706-adv7511-fmcjesdadc1.dts
arch/arm/boot/dts/zynq-zc706-adv7511-fmclidar1.dts
arch/arm/boot/dts/zynq-zc706-adv7511-fmcomms11-RevA.dts
arch/arm/boot/dts/zynq-zc706-adv7511-fmcomms11.dts

Part 2 for #677 
This fixes warnings/IRQ flags for AXI JESD204 RX/TX & Lidar IP cores.

arch: arm: update ADI zynq device-trees with proper interrupt definitions/flags (part 2)

---

sound/soc/adi/adrv936x_box.c

This driver may need a bigger revamp.
But for now, this change updates it to build on 4.19.

snd: soc: adr936x_box: update driver to newer kernel

---

arch/arm/boot/dts/zynq-adrv9361-z7035.dtsi
drivers/clk/clk-gpio.c

The clk-gpio driver always sets the parent rate now.
The change for the driver is also upstreamed.
This property can now be removed from the DT.

backport: clk-gpio: remove `clk-set-rate-parent-enable` prop 

---

drivers/iio/accel/adis16201.c
drivers/iio/accel/adis16209.c

These 2 drivers have been omitted by accident during the last merge.
The merge with Xilinx's v2019.1 tag was re-done several times, and the previous merge was used as reference.
In the last merge, these 2 were omitted, because the drivers were in `staging`.
This changeset syncs them by comparing the drivers with the adi-4.19.0 branch.

iio: accel: adis16201,adis16209: sync to latest 4.19 changes

---

drivers/iio/jesd204/axi_adxcvr.c
drivers/iio/jesd204/xilinx_transceiver.c

Related to #672 
These 2 changes have been split from that PR and should be safe to implement now.
The only behavior change should be the warning-print.

iio: jesd204: axi_adxcvr,xilinx_transceivers: print warning & move cpll/qpll ranges in functions

---

drivers/spi/spi-axi-spi-engine.c

The old `setup_timer()` function does not exist anymore. This change
updates the code to use the new `timer_setup()`.

spi: axi-spi-engine: update timer_setup() function

---

drivers/iio/temperature/ltc2983.c

Fix copy/paste error in ltc2983 driver (iio/temperature).

iio: temperature: fix ltc2983 of_match registration

---

drivers/net/ethernet/xilinx/xilinx_emaclite.c

Use ulong instead of u32 to fix compile warning when building
kernel for arm64 (zynqmp):
drivers/net/ethernet/xilinx/xilinx_emaclite.c:98:42: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
98 | #define BUFFER_ALIGN(adr) ((ALIGNMENT - ((u32)adr)) % ALIGNMENT)
|                                          ^
Signed-off-by: Quanyang Wang <quanyang.wang@windriver.com>
Signed-off-by: Michal Simek <michal.simek@xilinx.com>
(cherry picked from commit bb248807fa923178ec6d4d76862e130fb8397bc5)

[backport] net: emaclite: fix compile warning in BUFFER_ALIGN

---

drivers/iio/gyro/adis16136.c
drivers/iio/imu/adis.c
drivers/iio/imu/adis16400.c
drivers/iio/imu/adis16460.c
drivers/iio/imu/adis16480.c

The ADIS library functions return zero on success, and negative values for
error. Positive values aren't returned, but we only care about the success
value (which is zero).
This change is mostly needed so that the compiler won't make any inferences
about some about values being potentially un-initialized. This only
triggers after making some functions inline, because the compiler can
better follow return paths.

adis-backports: check ret val for non-zero vs less-than-zero 

---

drivers/gpu/drm/adi_axi_hdmi/axi_hdmi_drv.c
drivers/gpu/drm/adi_axi_hdmi/axi_hdmi_drv.h

The newer kernel helpers hold a reference for the fbdev instance, and
offer some helpers/hooks to manage it.
This change removes the driver's reference, and hooks the DRM helpers.

drm: adi_axi_hdmi: remove driver's fbdev reference

---

drivers/iio/imu/adis.c
drivers/iio/imu/adis16480.c
include/linux/iio/imu/adis.h

This changeset is the final set of ADIS backports that were upstreamed.
Predominantly cases of checking return code when assigning values.

[backports] iio: imu: adis:  assign values only on success paths (part 3)

---

drivers/clk/clk-gpio.c

This was left-over from cherry-picking from master.

[rpi-4.19.y] clk: clk-gpio: remove unused variable in ``gpio_clk_driver_probe

---

.travis.yml
ci/travis/run-build.sh

We typically don't configure other compiler types for the ARCHs that we
build, so just select the default CROSS_COMPILE prefixes in the script.
Users are still allowed to override them from outside the script.

ci,build: configure default CROSS_COMPILE based on ARCH

---

drivers/iio/imu/adis16475.c

This driver hasn't been upstreamed yet, so it did not get updated to check
`if (ret)` vs `if (ret < 0)`.
Though, from the driver's standpoint, both are correct (adis_read_reg()
returns 0 for success and negative for error), the compiler complains that
this could lead to potentially uninitialized assignments of the variables
pass to adis_read_reg() for reading.
So, to please the compiler, we check for `ret` being non-zero vs `< 0`.
This seems to show up under certain builds, in this case, in our rpi-4.19.y
branch. But this could happen also upstream.

iio: imu: adis16475: check non-zero when checking for error

---

arch/arm64/boot/dts/xilinx/zynqmp-adrv9009-zu11eg-reva.dts
arch/arm64/boot/dts/xilinx/zynqmp-zcu102-rev10-ad9172-fmc-ebz.dts
arch/arm64/boot/dts/xilinx/zynqmp-zcu102-rev10-ad9208-hmc7044.dts
arch/arm64/boot/dts/xilinx/zynqmp-zcu102-rev10-ad9208.dts
arch/arm64/boot/dts/xilinx/zynqmp-zcu102-rev10-ad9361-fmcomms2-3.dts
arch/arm64/boot/dts/xilinx/zynqmp-zcu102-rev10-ad9361-fmcomms5.dts
arch/arm64/boot/dts/xilinx/zynqmp-zcu102-rev10-ad9364-fmcomms4.dts
arch/arm64/boot/dts/xilinx/zynqmp-zcu102-rev10-adrv9008-1.dts
arch/arm64/boot/dts/xilinx/zynqmp-zcu102-rev10-adrv9008-2.dts
arch/arm64/boot/dts/xilinx/zynqmp-zcu102-rev10-adrv9009.dts
arch/arm64/boot/dts/xilinx/zynqmp-zcu102-rev10-adrv9371.dts
arch/arm64/boot/dts/xilinx/zynqmp-zcu102-rev10-fmcdaq2.dts
arch/arm64/boot/dts/xilinx/zynqmp-zcu102-rev10-fmcdaq3.dts
arch/arm64/boot/dts/xilinx/zynqmp-zcu102-revB-ad9361-fmcomms2-3.dts
arch/arm64/boot/dts/xilinx/zynqmp-zcu102-revB-ad9364-fmcomms4.dts

Continuation of #678 for ZynqMP

arch: arm64: define interrupt-types for AXI IP cores

---

drivers/iio/adc/ad9361.c
drivers/iio/adc/ad9361.h
drivers/iio/adc/ad9361_conv.c
drivers/iio/adc/ad9361_private.h

Changing the sampling frequency may cause the digital interface timing to
modify on intel carriers. This change adds a feature that forces the calibration of the
digital interface every time the sampling rate changes.

drivers: iio: adc: ad9361: Added continuous digital tune 

---

arch/arm64/boot/dts/xilinx/zynqmp.dtsi

https://www.xilinx.com/support/answers/69995.html
The issue is still present and affects other SD card models
too (e.g. SanDisk Ultra microSDHC 16GB).
(cherry picked from commit b1b92c9423f7e120003f23bc5b675b09080b8f2f)

[2018_R2] arm64: zynqmp: Prevent mmcblk0 error -110

---

arch/arm/boot/dts/overlays/Makefile
arch/arm/boot/dts/overlays/rpi-adxl345-overlay.dts

This patch adds a device tree example for adxl345.

arch: ar: boot: dts: Add adxl345 overlay

---

ci/travis/run-build.sh

When running the job locally, it's useful to limit/extend the number of
jobs running for a build.

ci,run-build.sh: allow number of jobs to be configured

---

drivers/iio/adc/ad7887.c

The channels specification assignment in chip info was simplified.
This patch makes supporting other devices by this driver easier.

iio: adc: ad7887: Cleanup channel assignment

---

sound/soc/adi/Kconfig

Audio ADI reference designs are used on some non ZYNQ or Microblaze
platforms like ADRV2CRR-FMC Carrier Board so remove this dependency.

ASoc: adi: Kconfig: Remove depends on for ADI reference designs

---

arch/arm64/boot/dts/xilinx/zynqmp-adrv9009-zu11eg-reva-adrv2crr-fmc.dts
arch/arm64/boot/dts/xilinx/zynqmp-adrv9009-zu11eg-reva.dts
drivers/net/ethernet/cadence/macb.h
drivers/net/ethernet/cadence/macb_main.c

The merge to 4.19, dropped a few patches that were done for 4.14 in the ADI tree.
This changeset brings back what's needed from the old patchset, and also fixes the GPIO polarity for the PHY reset pins on the Talise. In 4.19 phylib handles the reset GPIOs [if specified in the PHY's DT].

 arm64: dts: talise: fix ethernet interfaces after migration to 4.19

---

arch/arm64/boot/dts/xilinx/zynqmp-adrv9009-zu11eg-reva-adrv2crr-fmc.dts

ADRV2CRR-FMC Carrier Board has an integrated ADAU1761 CODEC.
This patch add support for CODEC and I2S/DMA HDL cores.

arch: arm64: xilinx: Add audio support for ADRV2CRR-FMC Carrier Board

---

arch/arm64/boot/dts/xilinx/zynqmp-adrv9009-zu11eg-reva-adrv2crr-fmc.dts

The device-tree was based on top of 4.14.
In 4.19, some things need to be changed.
This changeset does that. Tested on 4.19 with Talise SOM.

arch: arm64: talise: fix 4.19 device-tree definitions

---

arch/arm/boot/dts/socfpga_arria10_socdk_adrv9371.dts

Using the old DMA's device tree attributes, the iio devices won't get registered.
This PR updates the description for the tx,rx and rx_obs channels and specifies the interrupt types in order to remove the irqchip warnings in the boot phase.

 dts: arch: arm: adrv9371-arria10: Updated dma channels description

---

arch/arm/boot/dts/socfpga_arria10_socdk_daq2.dts

Using the old DMA's device tree attributes, the iio devices won't get registered.
This PR updates the description for the tx and rx channels and specifies the interrupt types in order to remove the irqchip warnings in the boot phase.

dts: arch: arm: daq2-arria10: Updated DMA channel description

---

drivers/gpu/drm/bridge/adv7511/adv7511.h
drivers/gpu/drm/bridge/adv7511/adv7511_drv.c

Create regmap for EDID memory map.

drm: bridge: adv7511: Implement regmap for EDID memory map

---

arch/arm/boot/dts/zynq-zc706-adv7511-fmcdaq2.dts
arch/arm/boot/dts/zynq-zc706-adv7511-fmcdaq3.dts
drivers/iio/jesd204/axi_adxcvr.c
drivers/iio/jesd204/xilinx_transceiver.c
drivers/iio/jesd204/xilinx_transceiver.h

The ZC706 runs the DAQ2 & DAQ3 boards at a VCO frequency that is out of
range/spec. Configure a setting in the DT, to not allow an even higher
frequency that the one that was tested.

axi-adxcvr,daq2/3: override vco max frequencies for CPLL

---

include/linux/hwmon.h

It takes a fair amount of boiler plate code to add new sensors, add a
macro that can be used to specify simple static sensors.
Signed-off-by: Charles Keepax <ckeepax@opensource.cirrus.com>
Signed-off-by: Guenter Roeck <linux@roeck-us.net>

hwmon: Add convience macro to define simple static sensors

---

drivers/gpu/drm/bridge/adv7511/Makefile
drivers/gpu/drm/bridge/adv7511/adv7511.h
drivers/gpu/drm/bridge/adv7511/adv7511_debugfs.c
drivers/gpu/drm/bridge/adv7511/adv7511_drv.c

Add debugfs interface to control Test Pattern Generator on ADV7535.

drm: adv7511: Add debugfs interface

---

drivers/gpio/gpio-xilinx.c

This fixes two issues with the set_multiple() implementation.
* mask is a bitmask, which on 32-bit systems BITS_PER_LONG = 32 may
evaluate to 0, while bits > 32 still can be set. Remove this check
completely.
* This gpio controller handles up to 64 GPIOs, split across two
registers. When crossing the register banks, the first one is updated.
However a bug in the code writes the value for the first bank to
the second bank register offset. This results in undesired behavior.

gpio: gpio-xilinx: Fix set_multiple() issues

---

drivers/iio/frequency/hmc7044.c

iio: frequency: hmc7044: Fix uninitialized variable warning

---

drivers/iio/frequency/adf4371.c

iio: frequency: adf4371: Fix missing space checkpatch warning

---

drivers/iio/adc/ad7124.c

This patch fixes device tree channel configuration.
Before this patch, the driver assumed that the DT children (adc channels)
are parsed in the order they are written in the DT. Now the driver uses the
reg property of each child to correctly identify to which channel the
parsed configuration belongs to.
Fixes b3af341bbd966: ("iio: adc: Add ad7124 support")

iio: adc: ad7124: Fix DT channel configuration

---

drivers/gpu/drm/bridge/adv7511/adv7511_debugfs.c

In upstream Linux, the DRM subsystem has organized their includes. In
order for this file to build, these includes are required so that the
compiler can evaluate these structs.

drm: adv7511: add includes for struct types

---

drivers/iio/adc/ad9081/adi_ad9081_jesd.c

drivers/iio/adc/ad9081/adi_ad9081_jesd.c: In function ‘adi_ad9081_jesd_rx_bring_up’:
drivers/iio/adc/ad9081/adi_ad9081_jesd.c:950:8: warning: ‘rx_div_rate’ may be used uninitialized in this function [-Wmaybe-uninitialized]
err = adi_ad9081_hal_bf_set(device, REG_PLL_RXDIVRATE_ADDR,
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
BF_RXDIVRATE_LCPLL_RC_INFO,
~~~~~~~~~~~~~~~~~~~~~~~~~~~
rx_div_rate); /* not paged */

iio: adc: ad9081: adi_ad9081_jesd: Fix warning [-Wmaybe-uninitialized]

---

drivers/iio/jesd204/axi_adxcvr.c

The QPLL 0/1 checking must go before the usage of the qpll_conf, in other case
the QPLL parameters will be calculated against the wrong VCO ranges
and the function might not find a solution.
Tested on AD9172 ZCU102

axi_adxcvr: Fix checking of selected QPLL

---

drivers/nvmem/Kconfig

Also consider MICROBLAZE || ARCH_SOCFPGA || NIOS2

drivers: nvmem: Kconfig: NVMEM_AXI_SYSID depends on more

---

drivers/iio/jesd204/axi_adxcvr.c
drivers/iio/jesd204/axi_adxcvr.h
drivers/iio/jesd204/axi_jesd204b_gt.c
drivers/iio/jesd204/xilinx_transceiver.c
drivers/iio/jesd204/xilinx_transceiver.h

This change moves the selection of the QPLL (0 or 1) to be an input of the
xilinx qpll functions. This API change is less error prone when configuring
the QPLL, as it is passed directly from the axi_adxcvr state struct (i.e.
st->sys_clk_sel).
This also means that the `conf` field from `struct xilinx_xcvr_qpll_config`
goes away, simplifying the use of this data-type. Using the `conf` field
was problematic as it would make the `struct xilinx_xcvr_qpll_config` have
a dual-role of both input & output when being used for QPLL functions.
Consideration has been taken for the fact that `st->sys_clk_sel` has value
different than 0 or 1. It looks like non-zero value selects QPLL1 and 0
selects QPLL0. Reworking this should probably be done in a different
rework, as this requires a lot of propagation …

iio: jesd204: axi_adxvcri,xilinx_transceiver: pass QPLL selection directly from the state struct

---

drivers/iio/jesd204/axi_adxcvr.c
drivers/iio/jesd204/axi_adxcvr.h
drivers/iio/jesd204/axi_jesd204b_gt.c
drivers/iio/jesd204/axi_jesd204b_v51.c
drivers/iio/jesd204/xilinx_transceiver.c
drivers/iio/jesd204/xilinx_transceiver.h

These patches sync the XCVR code in 2019_R1 with master.
Not all patches have been backported.
These 2 were skipped:
* 46464976eaf18909fce5dbccf1081c2f57cbab27  - `iio: jesd204: axi_jesd204_rx: Add support for up to 16 lanes`
* 0c7173a1f0530a80483aebb365a8926f0f24b813 - `iio: axi_adxcvr: print warning on set_rate in adxcvr_enforce_settings()`

[2019_R1] iio: jesd204: backport patches from master

---

drivers/iio/buffer/industrialio-buffer-dmaengine.c
drivers/iio/industrialio-buffer.c

While checking the IIO DMA buffer, these 2 came out of the diffs.
The backport is straightforward and we can add it now. The only benefit is that it reduces the diff with upstream.
The NULL check seems to have slipped through merges.

iio: buffer: cleanup & backport

---

arch/arm/boot/dts/zynq-m2k-reva.dts
arch/arm/boot/dts/zynq-pluto-sdr.dtsi

the axi_sysid_0 entry is removed from the devicetree because the AXI Sysid IP is missing from the HDL project

ARM: dts: zynq-m2k-reva & zynq-pluto-sdr: remove axi_sysid_0 node

---

drivers/iio/regmap/iio-regmap-i2c.c
drivers/iio/regmap/iio-regmap-spi.c
drivers/iio/regmap/iio-regmap.c
drivers/iio/regmap/iio-regmap.h

Changes regmap fw:
- moved the allocation of regmap_cfg inside iio_regmap_read_config()
- replaced parsing with sscanf. Now parsing is done with a strtok like function and kstrtoul
- moved all parsing in one function read_register_op
- added an array ,iio_regmap_op_required_fields, which specifies what a command should contain
- commands are now case insensitive and may have extra spaces

Iio regmap fw

---

drivers/gpu/drm/xlnx/zynqmp_disp.c

The setup in which we are seeing is this, is on ZynqMP (also ZCU102) with a
monitor connected via DisplayPort and the following Xorg.conf:
```
cat /etc/X11/xorg.conf
Section "Device"
Identifier "myfb"
Driver "fbdev"
Option "fbdev" "/dev/fb0"
EndSection
```
It seems that checking the `fb` pointer disallows the new mode to be set,
and the screen stays blank when the OS boots into a desktop session.
The symptoms seem to be that, on boot the console is displayed, but when
the desktop server initializes a desktop session, the screen goes blank.
It does look like an old state could point to the same DRM framebuffer
struct/info, so it probably doesn't make sense to do that check.
It's also unsure whether this brings back the old issue that the original
patch tried to fix.
Fixes: c4b7d6c966afe …

drm: xlnx: zynqmp_disp: Remove fb check in atomic update callback

---

arch/arm/boot/dts/zynq-zed-adv7511-fmcmotcon2.dts

This reverts commit aeaf4db9df2454923d391da1868f76a25379cc5e.
Which was done via PR https://github.com/analogdevicesinc/linux/pull/117
For Talise SOM we have a similar situation, where GEM0 has 2 PHYs on the
same MDIO bus. And GEM1 needs to use one of the PHYs which are attached to
GEM0.
The situation was resolved for that board.
We just need to test that the same solution works for this board + setup.

Revert "dts: fmcmotcon2: Switch from Cadence to Xilinx Ethernet driver"

---

drivers/iio/regmap/iio-regmap.c

Before this patch, in iio_regmap_probe, nr_ops was not
initialized when parse_firmware failed, the compiler giving
a warning.
Now nr_ops is initialized in iio_regmap_probe.

iio: iio-regmap: Fix uninitialized variable

---

drivers/net/ethernet/cadence/macb_ptp.c

This seems to cause some division-by-zero warnings in the kernel. It looks
like the upstream version of this code has this initialization, while the
Xilinx one doesn't. It may have been lost during some merge, since the
commit ab91f0a9b5f4b ("net: macb: Add hardware PTP support") is present in
the Xilinx tree.

net: macb: ptp: initialize tsu_rate

---

drivers/iio/frequency/Kconfig
drivers/iio/frequency/Makefile
drivers/iio/frequency/ltc6952.c

LTC6952 is a high performance, ultralow jitter, JESD204B/C clock generation
and distribution IC. It includes a Phase Locked Loop (PLL) core, consisting
of a reference divider, phase-frequency detector (PFD) with a phase-lock
indicator, ultralow noise charge pump and integer feedback divider.
The LTC6952's 11 outputs can be configured as up to 5 JESD204B/C subclass 1
device clock/SYSREF pairs plus one general purpose output, or simply 11
general purpose clock outputs for non-JESD204B/C applications.

iio: frequency: ltc6952: Add support for LTC6952

---

include/linux/spi/spi-engine.h

If SPI AXI engine is not enabled, then a linker error can occur with
multiple re-definitions of these functions.
Adding 'static inline' makes sure this doesn't happen.

spi: spi-axi: prefix with 'static inline' functions in header

---

drivers/iio/jesd204/axi_jesd204_rx.c

This only fails on newer kernels which have this check enabled.
Fix this is in master so that it propagates.

iio: jesd204: axi_jesd204_rx: add explicit fall-through comment

---

drivers/iio/industrialio-core.c

The ADI debugfs register code does a bit more error checking than the
upstream version. After an attempt to upstream this the reply from Greg was
[explicitly] to not do that.
Main point was:
```
No, don't do that, I spent a lot of time removing all of these pointless
checks.
No kernel code shoudl ever care if debugfs is workign or not, just make
the call and move on.   You can always pass the result of a debugfs call
into another one with no problems.
```
Link: https://lore.kernel.org/linux-iio/20191217151940.GB3654493@kroah.com/
This change syncs the ADI debugfs register code to upstream's

iio: sync debugfs register code with upstream

---

drivers/media/platform/adi-axi-fb.c

On ARM64, the print throws a warning. Seems that the 'start' field is
dependent on the ARCH.
To make the print happy (and the compiler), we cast it to 'unsigned int'.
Using 'uintptr_t' is also possible, but it would not print anything, due to
some security-change in the kernel.

media: adi-axi-fb: cast var to uint32 for print message

---

arch/arm/boot/dts/overlays/Makefile
arch/arm/boot/dts/overlays/rpi-adau1761-overlay.dts

Add devicetree overlay for ADAU1761 SigmaDSP Stereo codec.

dts: arm: overlays: Add ADAU1761 overlay

---

arch/arm/boot/dts/overlays/rpi-ltc6952-overlay.dts

This is a devicetree example for Analog Devices LTC6952.

arch: arm: boot: dts: overlays: Add LTC6952 devicetree

---

drivers/iio/adc/axi_pulse_capture.c

indio_dev->name was address dependent. That led to:
root@analog:~# cat /sys/bus/iio/devices/iio:device0/name
7c700000.axi-pulse-capture // on ZC706
9c700000.axi-pulse-capture // on ZCU102
Since most of the user space applications are not carrier dependent,
this needs to be fixed somehow.
Having indio_dev->name set to of_node->name, solves the address
dependency:
root@analog:~# cat /sys/bus/iio/devices/iio:device0/name
axi-pulse-capture

iio: adc: axi_pulse_capture: Use of_node name as indio_dev name

---

arch/arm/boot/dts/zynq-adrv9361-z7035-bob-cmos.dts
arch/arm/boot/dts/zynq-adrv9361-z7035-bob.dts
arch/arm/boot/dts/zynq-adrv9361-z7035-fmc-rfcard-tdd.dts
arch/arm/boot/dts/zynq-adrv9361-z7035-fmc.dts
arch/arm/boot/dts/zynq-adrv9361-z7035-packrf.dts
arch/arm/boot/dts/zynq-adrv9361-z7035-userspace.dts
arch/arm/boot/dts/zynq-adrv9364-z7020-bob-cmos.dts
arch/arm/boot/dts/zynq-adrv9364-z7020-bob.dts
arch/arm/boot/dts/zynq-adrv9364-z7020-packrf.dts

This change adds project tags to the RFSOM device-trees.

arch: arm: rfsom: add project tags

---

arch/arm/boot/dts/zynq-zc702-adv7511-ad9361-4-fmcomms2-3-4-userspace.dts
arch/arm/boot/dts/zynq-zc702-adv7511-ad9361-fmcomms2-3.dts
arch/arm/boot/dts/zynq-zc702-adv7511.dts
arch/arm/boot/dts/zynq-zc706-adv7511-ad9361-4-fmcomms2-3-4-userspace.dts
arch/arm/boot/dts/zynq-zc706-adv7511-ad9361-fmcomms2-3.dts
arch/arm/boot/dts/zynq-zc706-adv7511-fmcdaq2.dts
arch/arm/boot/dts/zynq-zc706-adv7511-fmcdaq3-revC.dts
arch/arm/boot/dts/zynq-zc706-adv7511-fmcdaq3.dts
arch/arm/boot/dts/zynq-zc706-adv7511.dts
arch/arm/boot/dts/zynq-zed-adv7511-ad9361-4-fmcomms2-3-4-userspace.dts
arch/arm/boot/dts/zynq-zed-adv7511-ad9361-fmcomms2-3.dts
arch/arm/boot/dts/zynq-zed-adv7511.dts

This changeset adds add license + project tags to the ADV7511, DAQ2/3 & FMCOMMS2/3 projects.

arch: arm: adv7511,fmcomms2/3, daq2/3: add license + project tags

---

arch/arm/boot/dts/zynq-e310.dts
arch/arm/boot/dts/zynq-m2k-reva.dts
arch/arm/boot/dts/zynq-m2k-revb.dts
arch/arm/boot/dts/zynq-m2k-revc.dts
arch/arm/boot/dts/zynq-m2k-revd.dts
arch/arm/boot/dts/zynq-m2k-reve.dts
arch/arm/boot/dts/zynq-m2k-revf.dts
arch/arm/boot/dts/zynq-pluto-sdr-revb.dts
arch/arm/boot/dts/zynq-pluto-sdr-revc.dts
arch/arm/boot/dts/zynq-pluto-sdr.dts
arch/arm/boot/dts/zynq-sidekiqz2-revb.dts

This change adds project tags to the M2k device-trees, and Pluto dts & derivatives [e310 & sidekiqz2].

arch: arm: pluto,m2k & derivatives: add project tags

---

drivers/iio/adc/ad9081.c

It looks like that switch statement is missing some break statements.
The newer kernel branch caught this via build:
```
CC      drivers/iio/adc/ad9081.o
drivers/iio/adc/ad9081.c: In function 'ad9081_calc_lanerate':
drivers/iio/adc/ad9081.c:214:14: error: this statement may fall through [-Werror=implicit-fallthrough=]
214 |   encoding_d = 64;
|   ~~~~~~~~~~~^~~~
drivers/iio/adc/ad9081.c:215:2: note: here
215 |  default:
|  ^~~~~~~
CC      net/ipv4/metrics.o
```

iio: adc: ad9081: fix implicit fall-throughs

---

drivers/iio/adc/ad_sigma_delta.c
include/linux/iio/adc/ad_sigma_delta.h

The current implementation of the ad_sigma_delta driver assumes that all
it's users have the same interrupt type (IRQF_TRIGGER_LOW).
This isn't true for the AD7124 driver, which needs IRQF_TRIGGER_FALLING.
To accommodate support for such variations, the ad_sigma_delta driver
needs a field to store these interrupt type (as flags), and fallback
to IRQF_TRIGGER_LOW if it isn't set.

iio: ad_sigma_delta: Add custom irq flags

---

arch/arm64/boot/dts/xilinx/zynqmp-zcu102-rev10-fmclidar1.dts

The ZCU102 lidar DT was created on top of Xilinx's 4.14 Linux tree.
In 4.19 the reference for the system clock has changed from `clk` to
`zynqmp_clk`. Update references in the lidar1 DT.
Signed-off-by: Alexandru Ardelean <ardeleanalex@gmail.com>

arch: arm64: lidar1: fix zynqmp_clk reference for 4.19

---

arch/arm/boot/dts/zynq-zc706-adv7511-adrv9008-1.dts
arch/arm/boot/dts/zynq-zc706-adv7511-adrv9008-2.dts
arch/arm/boot/dts/zynq-zc706-adv7511-adrv9009.dts
arch/arm/boot/dts/zynq-zc706-adv7511-adrv9371.dts
arch/arm/boot/dts/zynq-zc706-adv7511-adrv9375.dts

This change adds license + project tags for the ADRV9371 & ADRV9375, ADRV9008-1,ADRV9008-2,
ADRV9009 device-trees for ZC706.

arch: arm: adrv9371/5, adrv9008/9: add license + project tags

---

drivers/dma/virt-dma.c

vchan_vdesc_fini() is freeing up 'vd' so the access to vd->tx_result is
via already freed up memory.
Move the vchan_vdesc_fini() after invoking the callback to avoid this.
Fixes: 09d5b702b0f97 ("dmaengine: virt-dma: store result on dma descriptor")
Signed-off-by: Peter Ujfalusi <peter.ujfalusi@ti.com>

dmaengine: virt-dma: Fix access after free in vchan_complete()

---

drivers/iio/amplifiers/hmc425a.c

There build warnings/errors in the newer kernel is:
```
drivers/iio/amplifiers/hmc425a.c:50:2: error: ISO C90 forbids variable length array 'values' [-Werror=vla]
50 |  int i, values[st->gpios->ndescs];
|  ^~~
```
Seems that it does not allow C99 variable-length-arrays.
This change also enforces a max of 6 GPIOs via DT [which is what the device
supports], and limits only the use of the first 6 [if more are specified]
while printing a warning.

iio: hmc425a: limit GPIOs to 6 (max)

---

drivers/iio/amplifiers/hmc425a.c

Seems I was a bit too soon when I merged the HMC425a updated code.
This fixes error:
```
drivers/iio/amplifiers/hmc425a.c:181:23: error: format '%d' expects a matching 'int' argument [-Werror=format=]
181 |   dev_err(&pdev->dev, "%d GPIOs needed to operate\n");
|                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
./include/linux/device.h:1335:22: note: in definition of macro 'dev_fmt'
1335 | #define dev_fmt(fmt) fmt
|                      ^~~
drivers/iio/amplifiers/hmc425a.c:181:3: note: in expansion of macro 'dev_err'
181 |   dev_err(&pdev->dev, "%d GPIOs needed to operate\n");
|   ^~~~~~~
drivers/iio/amplifiers/hmc425a.c:181:25: note: format string is defined here
181 |   dev_err(&pdev->dev, "%d GPIOs needed to operate\n");
|                        ~^
|                         |
| …
```

iio: hmc425a: fix printf format

---

drivers/iio/adc/ad7124.c

This patch allows the user to enable multiple channels.
ad_sigma_delta will not allow the user to enable multiple
channels unless there are multiple sequencer slots available.
The number of slots available is specified in the num_slots
of the ad_sigma_delta struct.
The ad7124 chip supports up to 16 channels enabled. When all
channels are enabled, an internal sequencer will perform
a conversion on each channel sequentially.

iio: adc: ad7124: allow multiple-channels enabled

---

drivers/iio/amplifiers/hmc425a.c

Mostly to prepare it for upstreaming, and avoid any questions of 'why name
some information hmc425 & not hmc425a?'.
Thing is, some drivers and parts get some more chips to support that have a
letter difference, and are really different, so it's good to be nitpick-y
about this detail.

iio: hmc425a: rename hmc425 -> hmc425a

---

drivers/iio/amplifiers/hmc425a.c

This patch fixes a typo for the HMC425A_CHAN macro.

iio: hmc425a: fix typo

---

drivers/iio/adc/ad7124.c

These patches fix some bugs in ad7124:
- interrupt set for iio buffer should fire only on the falling edge
- the driver should implement the update_scan_mode function from iio_info struct in order to enable
or disable channels as specified in the sysfs files
- in the iio_chan_spec the 8 bits shift is unnecessary as there is no padding int the data received

Ad7124 patches

---

drivers/iio/adc/ad7124.c
drivers/iio/adc/ad7173.c
drivers/iio/adc/ad7791.c
drivers/iio/adc/ad7793.c
drivers/iio/adc/ad_sigma_delta.c
drivers/staging/iio/adc/ad7192.c
drivers/staging/iio/adc/ad7780.c
include/linux/iio/adc/ad_sigma_delta.h

These patches move the irq_flag member from the ad_sigma_delta to ad_sigma_delta_info, as there should be no need to change the interrupt type at runtime. All drivers using the ad_sigma_delta layer have to set the irq_flag member of ad_sigma_delta_info before running ad_sd_init.

Ad sigma delta add irq flags field

---

arch/arm/boot/dts/zynq-zed-adv7511-ad4020.dts

This change adds license and project tags to the AD4020 device-tree.

arch: arm: dts: ad4020: add license + project tags

---

arch/arm/boot/dts/zynq-zc706-adv7511-ad6676-fmc.dts
arch/microblaze/boot/dts/vc707_ad6676evb.dts

This change adds license + project tags for the ad6676 device-trees for
ZC706 and VC707.

arch: arm, microblaze: dts: ad6676: add license + project tags

---

arch/arm/boot/dts/zynq-zed-adv7511-ad7768.dts

This change adds license and project tags to the AD7768 device-tree.

arch: arm: dts: ad7768: add license + project tags

---

arch/arm/boot/dts/zynq-zc706-adv7511-ad9265-fmc-125ebz.dts

This change adds license and project tags to the AD9265 device-tree.
Signed-off-by: Bogdan Togorean bogdan.togorean@analog.com

arch: arm: dts: ad9265: add license + project tags

---

arch/arm/boot/dts/zynq-zc706-adv7511-ad9434-fmc-500ebz.dts

This change adds license and project tags to the AD9434 device-tree.
Signed-off-by: Bogdan Togorean bogdan.togorean@analog.com

arch: arm: dts: ad9434: add license + project tags

---

arch/arm/boot/dts/zynq-zed-adv7511-ad9467-fmc-250ebz.dts
arch/microblaze/boot/dts/kc705_ad9467_fmc.dts

This change adds license and project tags to the AD9467 device-trees on
ZED and KC705 platforms.

arch: arm, microblaze: dts: ad9467: add license + project tags

---

arch/arm/boot/dts/zynq-zc706-adv7511-ad9739a-fmc.dts

This change adds license and project tags to the AD9739A device-tree.

arch: arm: dts: ad9739a: add license + project tags

---

arch/arm/boot/dts/socfpga_arria10_socdk_adrv9009.dts
arch/nios2/boot/dts/a10gx_adrv9009.dts

Add device-tree source files for A10GX and A10SOC + ADRV9009.

arch: arm, nios2: adrv9009: Add arria10gx/soc_adrv9009 DTBs

---

arch/arm/boot/dts/socfpga_arria10_socdk_adrv9009.dts
arch/arm64/boot/dts/xilinx/zynqmp-zcu102-rev10-adrv9008-1.dts
arch/arm64/boot/dts/xilinx/zynqmp-zcu102-rev10-adrv9008-2.dts
arch/arm64/boot/dts/xilinx/zynqmp-zcu102-rev10-adrv9009.dts
arch/nios2/boot/dts/a10gx_adrv9009.dts

This change adds license and project tags to the adrv9009 device-trees
on ZCU102, A10SOC and A10GX platforms.

arch: arm64, arm, nios2: dts: adrv9009: add license + project tags

---

arch/arm64/boot/dts/xilinx/zynqmp-adrv9009-zu11eg-reva-adrv2crr-fmc-reva-sync.dts
arch/arm64/boot/dts/xilinx/zynqmp-adrv9009-zu11eg-reva-adrv2crr-fmc-reva.dts
arch/arm64/boot/dts/xilinx/zynqmp-adrv9009-zu11eg-revb-adrv2crr-fmc-revb-sync.dts
arch/arm64/boot/dts/xilinx/zynqmp-adrv9009-zu11eg-revb-adrv2crr-fmc-revb.dts

This change adds license and project tags to the adrv9009zu11eg
device-trees.

arch: arm64: dts: adrv9009zu11eg: add license + project tags

---

.travis.yml

We want to move to philosophy where we have a
build-MUST-be-green-to-merge-code.
Github is great that it can actually implement this check. But in Travis-CI
the sync-branches & checkpatch builds frequently fail, and they are
sometimes nearly impossible to get green.
Travis-CI allows the specification of builds that are **allowed_failures**.
This is great, as Github can be notified that the build passed, even if
these 2 may have failed.
The sync-branches actually fails only on the master branch [since it
actually runs only for the master branch]. We would get less spam now with
this change.

ci,travis: allow failures for checkpatch & sync-branches

---

arch/arm/boot/dts/socfpga_arria10_socdk_adrv9371.dts
arch/arm64/boot/dts/xilinx/zynqmp-zcu102-rev10-adrv9371.dts
arch/arm64/boot/dts/xilinx/zynqmp-zcu102-rev10-adrv9375.dts
arch/microblaze/boot/dts/kcu105_adrv9371x.dts
arch/nios2/boot/dts/a10gx_adrv9371.dts

This patch set add device-tree source files for A10GX and A10SOC + ADRV9371.
Also adds license and project tags to the adrv9371/5 device-trees on ZCU102, 
A10SOC and A10GX platforms.

arch: arm64, microblaze, nios2: add license + project tags

---

arch/arm/boot/dts/socfpga_cyclone5_sockit_arradio.dts

This change adds license and project tags to the arradio device-tree
on c5soc platform.

arch: arm: arradio: add license + project tags

---

arch/arm/boot/dts/socfpga_arria10_socdk_fmclidar1.dts
arch/arm/boot/dts/zynq-zc706-adv7511-fmclidar1.dts

This patch set add device-tree source files for A10SOC + fmclidar1.
Also adds license and project tags to the fmclidar1 device-trees on ZC706 and A10SOC platforms.

arch: arm: add license + project tags fmclidar1

---

arch/arm64/boot/dts/xilinx/zynqmp-zcu102-rev10-ad9081.dts

arm64: dts: xilinx: zynqmp-zcu102-rev10-ad9081.dts: Add interrupt flags

---

arch/arm/boot/dts/socfpga_arria10_socdk_daq2.dts
arch/arm64/boot/dts/xilinx/zynqmp-zcu102-rev10-fmcdaq2.dts
arch/microblaze/boot/dts/kc705_fmcdaq2.dts
arch/microblaze/boot/dts/kcu105_fmcdaq2.dts
arch/nios2/boot/dts/a10gx_daq2.dts

This patch set add device-tree source files for A10SOC/GX + DAQ2.
Also adds license and project tags to the DAQ2 device-trees on ZCU102, KC705, KCU105
and A10GX platforms.
Signed-off-by: Bogdan Togorean bogdan.togorean@analog.com

arch: arm64, microblaze, nios2: add license + project tags DAQ2

---

Documentation/devicetree/bindings/hwmon/adi,adm1177.yaml
Documentation/hwmon/adm1177.rst
drivers/hwmon/adm1177.c

Sync the driver with the upstream version.

hwmon: adm1177: sync with upstream

---

arch/arm/boot/dts/zynq-zed-adv7511-cn0363.dts

This change adds license and project tags to the CN0363 device-tree
on zed platform.

arch: arm: cn0363: add license + project tags

---

.travis.yml

On master we typically builds Zynq (ARM) & ZynqMP (ARM64) device-trees,
because we traditionally had only Xilinx as our master.
Now that we plan to move some Intel/Altera boards to master, we also need
to make sure that the device-trees are building.
This change extends the test [for the ARM architecture] to include these
device-trees as well.

ci,build: arm: build socfpga device-trees on master

---

arch/arm/boot/dts/adi-cn0506-socfpga-mii.dtsi
arch/arm/boot/dts/adi-cn0506-socfpga-rgmii.dtsi
arch/arm/boot/dts/socfpga_arria10_socdk_cn0506_mii.dts
arch/arm/boot/dts/socfpga_arria10_socdk_cn0506_rgmii.dts
arch/arm/boot/dts/zynq-zc706-adv7511-cn0506-mii.dts
arch/arm/boot/dts/zynq-zc706-adv7511-cn0506-rgmii.dts
arch/arm/boot/dts/zynq-zed-adv7511-cn0506-mii.dts
arch/arm/boot/dts/zynq-zed-adv7511-cn0506-rgmii.dts
arch/arm64/boot/dts/xilinx/zynqmp-zcu102-rev10-cn0506-mii.dts
arch/arm64/boot/dts/xilinx/zynqmp-zcu102-rev10-cn0506-rgmii.dts

This patch set add device-tree source files for A10SOC + cn0506.
Also adds license and project tags to the cn0506 device-trees on ZC706, ZCU102, ZED and A10SOC platforms.

arch: arm64, arm: add license + project tags cn0506

---

ci/travis/run-build-docker.sh
ci/travis/run-build.sh

The situation is a bit complicated.
Travis-CI allows us to enable/disable builds for PRs & and for pushed
branches/tags.
If we disable builds for PRs, we won't get any build-runs from external
forks (external contributions).
If we disable builds for branches, people won't get a chance to have the CI
do a check before opening up a PR.
If we enable both, each re-spin of a PR requires up to 2 hours to do both
builds.
A compromise solution, is to implement a check on our build-script to exit
early if we detect that for a branch/tag we have an open PR. It's not
perfect, but should reduce some time.

ci,build: exit early if branch has an open PR

---

drivers/net/phy/adin.c

Some bits of static data should have been made const from the start.
This change adds the const qualifier where appropriate.

net: phy: adin: const-ify static data

---

drivers/iio/gyro/adis16136.c
drivers/iio/imu/Kconfig
drivers/iio/imu/adis16400.c
drivers/iio/imu/adis16475.c
drivers/iio/imu/adis16480.c
drivers/iio/imu/adis_buffer.c
drivers/iio/imu/adis_trigger.c

This change syncs the ADIS drivers closer with upstream.
The adis16475 is not upstreamed, but has been adapted to a version that has been accepted upstream (for adis16136,16400,16480).

iio: imu: adis: sync with upstream

---

drivers/iio/adc/ad9361.c

The reading of the gain-table would always return 4096 bytes. The trailing
data would be garbage.
This change limits the read to the exact amount of data that is read.
The issue was identified when investigating
https://github.com/analogdevicesinc/libiio/issues/268
When doing:
```
iio_attr -a -d ad9361-phy gain_table_config > out
wc -m out
```
The value of `wc -m out` would be 4096. With the patch, the value is ~1688
bytes [i.e. the amount that is useful].

iio: ad9361: return the exact amount of bytes for gain-table

---

arch/microblaze/boot/dts/adi-adrv9371.dtsi

Probably the result of a bad copy-paste, the trx0_ad9371 clocks had
references to non existent nodes (axi_adrv9009_*).
Fixes: 2b0ee592d662 ("iio: adc: ad9371: Add support for setting the SYSREF
rate")

arch: microblaze: adi-adrv9371.dtsi: Fix non-existent reference

---

drivers/iio/adc/cf_axi_adc_core.c

All AXI ADC info structs use the same version of the core.
So, just define a single one, to reduce duplication.
And add a `adi,axi-adc-10.0.a` compat string that can get used in
device-trees.

iio: axi-adc: define & use a single core-info struct & compat string

---

drivers/iio/imu/adis16480.c

This changeset syncs a change from upstream. It was done differently in the ADI tree for the pin check.
And re-adds the prod_id reg back. Was removed by accident in #827 

 iio: imu: adis16480: sync upstream & re-add prod_id reg

---

drivers/iio/accel/adxl372.c

Adxl372 has multiple register that are initialized with default values that are not suited for all applications. These patches aim to make the adxl372 more configurable from the userspace:
- Set iio_chan BE: set the endianness field to IIO_BE. This helps iio-osciloscope interpret the received data
- add sysfs for time registers: activity time and inactivity time are now configurable from the sysfs
- Add sysfs for g thresholds: activity and inactivity thresholds are now configurable from the sysfs

Adxl372 add extra device attr

---

drivers/iio/frequency/Kconfig

ADF4360 driver goes before ADF4371.

iio: frequency: Kconfig: fix alphabetical order for ADF43XX chips

---

drivers/usb/gadget/function/f_fs.c

During Pluto test we encountered the following scenario when triggering a
device reboot:
PC is at ffs_data_clear+0x7c/0x100
LR is at ffs_data_clear+0x2c/0x100
pc : [<c045aa84>]    lr : [<c045aa34>]    psr: 20000013
sp : df4e7f48  ip : 00000000  fp : beddce80
r10: 00000034  r9 : df4e6000  r8 : c0a89220
r7 : df4b041c  r6 : df55d940  r5 : cbee5580  r4 : cbde6400
r3 : 00018520  r2 : 05000400  r1 : cbde645c  r0 : c0a2c294
Flags: nzCv  IRQs on  FIQs on  Mode SVC_32  ISA ARM  Segment none
Control: 18c5387d  Table: 0b71804a  DAC: 00000051
Process umount (pid: 3191, stack limit = 0xaf223aee)
Stack: (0xdf4e7f48 to 0xdf4e8000)
7f40:                   cbde6400 ffffffff df55d940 c045ab14 cbde6400 c045b604
7f60: cbed3400 c0a2c2c0 df55d940 c01e76c4 df4b0400 df55ddb8 df55d940 c02020e0
7f80: 00000000 …

Revert "usb: gadget: f_fs: Fix use-after-free in ffs_free_inst"

---

drivers/iio/adc/ad7124.c

This patch adds the LOW_PASS_FILTER_3DB_FREQUENCY attribute
in iio_chan_spec for each channel. The used filters are sinc3
or sinc4. The filter type with the highest output data rate
is used when setting a low pass frequency in the channel's sysfs.

iio: adc: ad7124: add 3db filter

---

MAINTAINERS
drivers/Kconfig
drivers/Makefile
drivers/iio/jesd204/Kconfig
drivers/jesd204/Kconfig
drivers/jesd204/Makefile
drivers/jesd204/jesd204-core.c
drivers/jesd204/jesd204-priv.h
include/linux/jesd204/jesd204.h

This changeset adds the first bits of the JESD204 framework.
More to come later.
The DAQ2 will be used as base to integrate it.

jesd204: add initial framework bits (part 1)

---

arch/arm/boot/dts/socfpga_arria10_socdk_ad9172_fmc.dts

According to current version of dma-axi-dmac.c.
adi,type and adi,cyclic were completely removed since they are not used
anymore. The DMA capabilities are automatically discovered by the
driver.

arch: arm: arria10_socdk_ad9172_fmc: Update DMA channel

---

arch/arm/boot/dts/overlays/Makefile
arch/arm/boot/dts/overlays/rpi-ad7124-8-all-diff-cs0-int25-overlay.dts

This is an overlay for the ad7124-8 with all channels in
differential mode and internal reference.

dts: overlays: ad7124 all channels diff overlay

---

scripts/spdxcheck.py

This is backported from upstream. The error was poping up with checkpatch and it is annoying...
"
Without this change the following happens when using Python3 (3.6.6):
$ echo "GPL-2.0" | python3 scripts/spdxcheck.py -
FAIL: 'str' object has no attribute 'decode'
Traceback (most recent call last):
File "scripts/spdxcheck.py", line 253, in <module>
parser.parse_lines(sys.stdin, args.maxlines, '-')
File "scripts/spdxcheck.py", line 171, in parse_lines
line = line.decode(locale.getpreferredencoding(False), errors='ignore')
AttributeError: 'str' object has no attribute 'decode'
So as the line is already a string, there is no need to decode it and
the line can be dropped.
/usr/bin/python on Arch is Python 3.  So this would indeed be worth
going into 4.19.
Link: …

scripts/spdxcheck.py: make python3 compliant

---

arch/arm/boot/dts/overlays/Makefile
arch/arm/boot/dts/overlays/rpi-ad5766-overlay.dts

Add device tree overlay to use AD5766 on Raspberry Pi
Signed-off-by: Denis Gheorghescu <denis.gheorghescu@analog.com>

iio: dac: ad5766: add dtoverlay for AD5766

---

drivers/jesd204/Makefile
drivers/jesd204/jesd204-core.c
drivers/jesd204/jesd204-fsm.c
drivers/jesd204/jesd204-priv.h
include/linux/jesd204/jesd204.h

This changeset integrates a few more bits of the framework.
Essentially here:
* the connections between devices are created from DT; at the time of the initial writing DT was used; conversion to more abstract DT/ACPI compat layer will be done later
* we try not to use the term link == connection; to avoid confusion between JESD204 links
* a `connection` refers to the connection/link between 2 devices in terms of clock/inputs 
* a `link` is a JESD204 link
The FSM should handle most of the logic/work-load of the framework when needing to configure/reconfigure links.

jesd204: add basic finite-state-machine logic + linux bus register (part 2)

---

drivers/iio/adc/ad7124.c

This patch adds the posibility do read and write registers from userspace
using the kernel debug direct register access option.
Signed-off-by: Mircea <mircea.caprioru@analog.com>

iio: adc: ad7124: Add direct reg access

---

drivers/iio/adc/ad7124.c

This patch adds a bounds check when trying to obtain the register size for
direct reg access.

iio: adc: ad7124: Add bounds check for register address

---

drivers/iio/adc/cf_axi_adc.h
drivers/iio/adc/cf_axi_adc_core.c

This change was added via commit dce736008005d "drivers/iio/adc/cf_axi_adc:
add support for ADC_DP_DISABLE".
The problem is that at address ADI_REG_ADC_DP_DISABLE (0x00C0), the reg is
now something else.
It's ADI_REG_CLOCKS_PER_PPS.
This change removes the logic.

iio: axi-adc: remove dp_disable logic

---

drivers/iio/adc/cf_axi_adc_core.c

This change is purely design-wise.
The axiadc_decimation_set() function would use both `decimation_factor` and
`st->decimation_factor` to do some computation.
This also was based on the fact that `st->decimation_factor` right before
the call to `axiadc_decimation_set()`.
This change unifies things a bit. `st->decimation_factor` is now set in
`axiadc_decimation_set()`.

iio: axi-adc: store decimation factor in axiadc_decimation_set()

---

drivers/spi/spi-xilinx.c

This patch adds a check if cs_gpios have been defined in the devicetree and
only then tries to vaidate and set the coresponding gpio.
Fixes: 3d8f30dcee71 (spi: xilinx-spi: Add cs-gpios feature)

spi: spi-xilinx: Fix invalid gpio calls

---

Documentation/devicetree/bindings/hwmon/adi,adm1177.yaml
drivers/hwmon/adm1177.c

This patch sync the adm1177 hwmon driver with the upstream version.

hwmon: adm1177: Sync with upstream version

---

drivers/iio/dac/ad5766.c

remove useless cases (`IIO_CHAN_INFO_CALIBBIAS` and
`IIO_CHAN_INFO_CALIBSCALE`) in function `ad5766_write_raw`
Signed-off-by: Denis Gheorghescu <denis.gheorghescu@analog.com>

iio: dac: ad5766: remove useless cases

---

arch/arm/boot/dts/zynq-coraz7s-ad7768-1ARDZ.dts
arch/arm/boot/dts/zynq-coraz7s.dts
arch/arm/boot/dts/zynq-coraz7s.dtsi

This PR adds two devicetrees: one is a reference devicetree for the Cora z7s board and the other one adds support for the ad7768-1ARDZ, using this carrier.

arch: arm: Add support for ad7768-1ARDZ with Cora z7s

---

arch/arm/boot/dts/zynq-zed-adv7511-ad9467-fmc-250ebz.dts
arch/microblaze/boot/dts/kc705_ad9467_fmc.dts
drivers/iio/adc/cf_axi_adc_core.c

This change replaces all uses of 'xlnx,cf-ad9467-core-1.00.a' with
'adi,axi-adc-10.0.a'.
The aim is to unify usage and cleanup the AXI ADC driver.

axi-adc,arch,ad9467: use 'adi,axi-adc-10.0.a' compat string

---

arch/arm64/boot/dts/xilinx/zynqmp-zcu102-rev10-ad9361-fmcomms5.dts

For the master HDL core with DMA, a different compatible string must be
used to enable all 8 required buffer channels (otherwise, only 4 are
enabled).

arm64: dts: fmcomms5: Specify correct compatible string for dac_core_0

---

drivers/iio/adc/ad_sigma_delta.c

This series of patches fix a couple of issues in ad_sigma_delta layer that have been observed when testing the ad7124.

Ad sgima delta fixes

---

drivers/iio/adc/ad9361_conv.c
drivers/iio/adc/ad9371_conv.c
drivers/iio/adc/adrv9009_conv.c

The code was likely written for ad9361 and duplicated for ad9371 and
adrv9009.
Quite a few version checks are there, but for 9371 and 9009 it's likely
that those cores never had support for these chips. And for 9361 we
shouldn't support this in master, so just drop it.
This cleans up the drivers a bit.

iio: ad9361,ad9371,adrv9009: remove support for old cores

---

drivers/media/platform/axi-hdmi-rx.c

The first 2 AXI regs are defined in 'linux/fpga/adi-axi-common.h' and are
common for all ADI AXI cores.
So, use them for the axi-hdmi-rx driver.

media: axi-hdmi-rx: use common AXI ADI regs

---

drivers/iio/adc/cf_axi_adc.h
drivers/iio/adc/cf_axi_adc_core.c

This change-set:
* removes the empty axiadc_toggle_scale_offset_en() func
* removes left-over support for old cores
* moves inline functions to the driver; the intent is to make `struct axiadc_state` opaque

iio: axi-adc: misc cleanups of the driver

---

drivers/iio/adc/ad_adc.c
drivers/iio/adc/admc_adc.c
drivers/iio/adc/admc_ctrl.c
drivers/iio/adc/admc_speed.c

The old AD Motor Control drivers have been adapted from the more generic AXI ADC driver.
They also share some of the definitions included in 'cf_axi_adc.h'.
The Motor Control project is obsolete, so it's probably a good idea to make these old drivers a bit more self-contained, in order to cleanup the generic AXI ADC.

iio: ad-motor-control: make old drivers more self-contained

---

drivers/iio/jesd204/xilinx_transceiver.c

This patch set fixes the VCO ranges for CPLL and QPLL. 
Before this they where limited based on some errored presumptions related on lane rate rather than VCO range.
For reference I will sources that were consulted for this information:
**GTX transceivers**:
https://www.xilinx.com/support/documentation/data_sheets/ds191-XC7Z030-XC7Z045-data-sheet.pdf - Table 91
https://www.xilinx.com/support/documentation/data_sheets/ds182_Kintex_7_Data_Sheet.pdf - Table 56
https://www.xilinx.com/support/documentation/data_sheets/ds183_Virtex_7_Data_Sheet.pdf - Table 55
**GTH transceivers:**
https://www.xilinx.com/support/documentation/data_sheets/ds892-kintex-ultrascale-data-sheet.pdf - Table 51
https://www.xilinx.com/support/documentation/data_sheets/ds893-virtex-ultrascale-data-sheet.pdf - Table 51 …

Fix vco ranges

---

drivers/iio/jesd204/axi_jesd204.h
drivers/iio/jesd204/axi_jesd204_rx.c
drivers/iio/jesd204/axi_jesd204_tx.c

This patch adds a sysfs attribute to read the encoding scheme being used.

jesd204: Add encoder sysfs attr

---

drivers/iio/accel/Kconfig
drivers/iio/accel/adis16201.c
drivers/iio/accel/adis16209.c
drivers/iio/gyro/adis16080.c
drivers/iio/gyro/adis16130.c
drivers/iio/gyro/adis16136.c
drivers/iio/gyro/adis16260.c
drivers/iio/imu/Kconfig
drivers/iio/imu/adis.c
drivers/iio/imu/adis16400.c
drivers/iio/imu/adis16460.c
drivers/iio/imu/adis16480.c
drivers/iio/imu/adis_buffer.c
drivers/iio/imu/adis_trigger.c
drivers/staging/iio/accel/adis16203.c
drivers/staging/iio/accel/adis16240.c
include/linux/iio/imu/adis.h

This change syncs the ADIS drivers with upstream.
Some of the changes were pushed recently.
A few more (like header-changes, mlock stuff, and minor changes) have been in upstream for a while and are now backported.

iio: adis: sync drivers with upstream changes

---

drivers/iio/adc/ad9361.c

ad9361_dig_tune() shouldn't be called if conv is not available. This
situation occurs when ad9361_setup() is called by ad9361_probe()
(axi_converver is not yet registered using ad9361_register_axi_converter).

iio: adc: ad9361: Fix ad9361_set_trx_clock_chain()

---

arch/arm/boot/dts/overlays/Makefile
arch/arm/boot/dts/overlays/rpi-ad5677r-overlay.dts

This patch adds a device tree example for AD5677R nanoDAC+.

dts: overlays: Add dt overlay for AD5677R

---

drivers/iio/industrialio-core.c
include/linux/iio/iio.h

If a label is defined in the device tree for this device add that
to the device specific attributes. This is useful for userspace to
be able to identify an individual device when multiple identical
chips are present in the system.
Tested-by: Michal Simek <michal.simek@xilinx.com>
Signed-off-by: Phil Reid <preid@electromag.com.au>
(cherry picked from commit 2c3d0c9ffd24d9b4c62c5dfb2104695a614be28c)

[backport] iio: core: Add optional symbolic label to device attributes

---

drivers/iio/adc/ad_adc.c

Number of RX observation channels can be read from REG_USR_CNTRL_1 reg.
This change dynamically fill the iio channel structure for all
observation use-cases of this driver.

iio: ad_adc: add dynamic fill of observation channel structure

---

drivers/iio/amplifiers/ad8366.c
drivers/iio/amplifiers/hmc425a.c
drivers/iio/industrialio-core.c
include/linux/iio/types.h

This changeset syncs the recent changes for the iio amplifiers with upstream.
For HMC425A gpiod_set_array_value_cansleep() call was kept unchanged since it differs from recent upstream where the API changed.
Also, backported `iio: core: add char type for sysfs attributes` to make the `iio: core: Handle 'dB' suffix in core` patch easier to apply on ADI code.

iio: amplifiers: sync with upstream changes

---

drivers/char/axi-intr-monitor.c

This fix was caught by the 'make allmodconfig' build.
The 'xdevcfg_of_match' name looks like a copy-paste error. This change
fixes that.

drivers: char: axi-intr-monitor: fix kmod build

---

ci/travis/run-build.sh

This build rule ('make allmodconfig') is part of the standard kernel build
to try to build everything as a kmod.
Building as kmod yields different results, since some module macros become
active.
This change introduces a small helper script to run inside a Jenkins CI
build. This build time takes quite a lot to run, so Travis-CI provides
insufficient resources to run it.

ci,build: add allmodconfig build rule

---

arch/arm64/boot/dts/xilinx/adi-ad9154-fmc-ebz.dtsi
arch/arm64/boot/dts/xilinx/zynqmp-zcu102-rev10-ad9154-fmc-ebz.dts

DAC set for:
fDAC output data rate of 2 GSPS
Interpolation 2
Single link, Mode 0
L=8,M=4 -> Lane rate = 10Gbps
AD9516 configured for:
External CLK frequency - 2GHz
OUT0 - 2 GHz     (DAC clock)
OUT6 - 31.25 MHz  (DAC SYSREF)
OUT7 - 31.25 MHz  (FPGA SYSREF)
OUT9 - 250 MHz  (FPGA ref clock)

arm64: boot: dts: xilinx: adi-ad9154-fmc-ebz: Add devicetree

---

arch/arm64/boot/dts/xilinx/zynqmp-zcu102-rev10-adrv9009-fmcomms8.dts

More information: https://wiki.analog.com/resources/eval/user-guides/ad-fmcomms8-ebz

arm64: dts: xilinx: Add AD-FMCOMMS8-EBZ + ZCU102 support

---

drivers/iio/industrialio-core.c
include/linux/iio/iio.h

Currently iio_debugfs_read_reg calls debugfs_reg_access
every time it is ran. Reading the same hardware register
multiple times during the same reading of a debugfs file
can cause unintended effects.
For example for each: cat iio:device0/direct_reg_access
the file_operations.read function will be called at least
twice. First will return the full length of the string in
bytes  and the second will return 0.
This patch makes iio_debugfs_read_reg to call debugfs_reg_access
only when the user's buffer position (*ppos) is 0. (meaning
it is the beginning of a new reading of the debugfs file).
Fixes: e553f182d55b ("staging: iio: core: Introduce debugfs support, add support for direct register access")
Signed-off-by: Alexandru …

iio: industrialio-core: Fix debugfs read

---

drivers/iio/adc/adrv9009.c

Read modify write must read the Set Level and not the Pin Level.

iio: adc: adrv9009: Fix Gpio3v3 bit-wise control

---

drivers/iio/Kconfig.adi
drivers/iio/frequency/Makefile

This has probably stayed along via various merges. There is no
CF_AXI_DDS_AD9140 Kconfig symbol present, and no ad9167.c file.

iio: frequency: drop non-existing CF_AXI_DDS_AD9140 Kconfig symbol

---

MAINTAINERS

This changeset polishes the MAINTAINERS file a bit.
2 drivers show up twice as a result of merge commits.
These changes (and a few others) come as a results of compressing the adi-4.19.0 branch; which was reduced from ~1400 commits to ~770 commits. Many of them were squashed, since they're not upstreamed [yet].
Also, since Xilinx has moved their master to kernel 5.4, we need to get ready/prepared for the move/merge to 5.4 which should come along in a few months.

MAINTAINERS: polish file a bit after some merges

---

Documentation/devicetree/bindings/iio/frequency/ad916x.yaml
drivers/iio/frequency/ad9162.c
drivers/iio/frequency/cf_axi_dds.h

This patch adds support for reading the die temperature. The part needs a single point calibration in order to get correct readings. The patch adds to mechanisms for this:
1.  Do it at runtime using in_tempX_single_point_calib. Writing this file with a reference/known temperature will cause the driver to read the raw  value, creating the calibration point.
2.  Add the calibration point as a devicetree parameter.

ad9162: Support temperature sensor readings

---

drivers/uio/uio_dmem_genirq.c

This change got upstreamed as commit 3ec1bd7693ee5bb ("uio: fix irq init
with dt support & irq not defined").
In the ADI tree this also exists as 45ec4148b2903
("drivers/uio/uio_dmem_genirq.c: UIO_IRQ_NONE is a valid option for
uioinfo->irq.").
This change syncs to upstream.

drivers: uio_dmem_genirq: sync with upstream

---

Documentation/devicetree/bindings/iio/frequency/adf4371.yaml
drivers/iio/frequency/adf4371.c

The part supports both single-ended and differential reference clocks. This series makes it configurable through devicetree.

Support differential ref clock

---

drivers/iio/frequency/cf_axi_dds.c

This code lies under an undefined #ifdef.
Remove it.

iio: axi-dds: remove dead code

---

arch/arm/boot/dts/socfpga_arria10_socdk_fmclidar1.dts

According to https://github.com/analogdevicesinc/hdl/blob/hdl_2019_r1/projects/ad_fmclidar1_ebz/a10soc/system_top.v#L187.

arm: dts: adi-fmclidar1: Declare CONVST GPIO for AD7091

---

arch/microblaze/boot/dts/kc705.dts
arch/microblaze/boot/dts/kc705_ad9467_fmc.dts
arch/microblaze/boot/dts/kc705_fmcdaq2.dts
arch/microblaze/boot/dts/kc705_fmcjesdadc1.dts
arch/microblaze/boot/dts/kc705_fmcomms1.dts
arch/microblaze/boot/dts/kc705_fmcomms2-3.dts
arch/microblaze/boot/dts/kc705_fmcomms4.dts
arch/microblaze/boot/dts/kcu105.dts
arch/microblaze/boot/dts/kcu105_adrv9371x.dts
arch/microblaze/boot/dts/kcu105_fmcdaq2.dts
arch/microblaze/boot/dts/kcu105_fmcdaq3.dts
arch/microblaze/boot/dts/kcu105_fmcomms2-3.dts
arch/microblaze/boot/dts/kcu105_fmcomms4.dts
arch/microblaze/boot/dts/vc707.dts
arch/microblaze/boot/dts/vc707_ad6676evb.dts
arch/microblaze/boot/dts/vc707_fmcadc2.dts
arch/microblaze/boot/dts/vc707_fmcadc5.dts
arch/microblaze/boot/dts/vc707_fmcdaq2.dts
arch/microblaze/boot/dts/vc707_fmcjesdadc1.dts
arch/microblaze/boot/dts/vc707_fmcomms1.dts
arch/microblaze/boot/dts/vc707_fmcomms2-3.dts
arch/microblaze/boot/dts/vc707_fmcomms4.dts
arch/microblaze/boot/dts/vcu118.dts
arch/microblaze/boot/dts/vcu118_dual_ad9208.dts
arch/microblaze/boot/dts/vcu118_fmcdaq3.dts

The #include directive is a bit more flexible/permissive when including a
mix of DTs and C header files with dt-binding macros.
We did the same for ARM [Zynq] DTs.

[2019_R1] arch: microblaze: rename '/include/' -> '#include'

---

drivers/gpu/drm/bridge/adv7511/adv7511_drv.c

Previously, 4 x i2c_transfer() calls used to be done, to read the EDID.
This does the same thing using regmap_bulk_read().
The i2c-cadence driver can only do 252 bytes, and some i2c controllers can
do 64-byte transfer-sizes.
The issue that is visible [without this change] is that the resolution
[read-back from the monitor] is reduced to a minimal [640x480].
I tried to see whether we can extend that 252-byte-transfer limit, but that
is a bit too difficult, because it requires too many i2c framework changes
that wouldn't make sense.
The i2c controller is configured to issue an i2c transfer, then an
interrupt shoots to notify that it completed.
Fixes 6a83880: ("drm: bridge: adv7511: Implement regmap for EDID memory map")

drm: adv7511: do 4 regmap_bulk_read() calls for EDID 

---

.travis.yml

This should run on all ARCHs. No idea why it isn't. It could be that I ran
this on a local build and it worked, and on Travis-CI it didn't.
This change fixes that.

ci,build: fix dtb build test to run on all archs

---

arch/arm/boot/dts/zynq-pluto-sdr.dtsi

The initial mode (1), for which the comment was true, was updated by
https://github.com/analogdevicesinc/linux/commit/3b42735e3ef9195fb9070e291b278dcbb93fe395 .

dts: zynq-pluto-sdr: Update digital-interface-tune-skip-mode info

---

drivers/iio/frequency/cf_axi_dds.c
drivers/iio/frequency/cf_axi_dds.h

The register at address 0x00C0 is now the PPS counter. We shouldn't read it
in order to do any datapath disable. For now, setting the 'dp_disable' to
false to prevent any potential issues with it.
Also, removing the definition of the old `ADI_REG_DAC_DP_DISABLE`, which
isn't correct anymore.

iio: axi-dds: temporarily hardcode dp_disable to false

---

drivers/iio/adc/cf_axi_adc.h
drivers/iio/adc/cf_axi_adc_core.c

The register at address 0x00C0 is now the PPS counter. We shouldn't read it
in order to do any datapath disable. For now, setting the 'dp_disable' to
false to prevent any potential issues with it.
Also, removing the definition of the old `ADI_REG_ADC_DP_DISABLE`, which
isn't correct anymore.

iio: axi-adc: re-add dp_disable logic & hard-code it to false

---

drivers/iio/accel/kxsd9.c
drivers/iio/gyro/mpu3050-core.c
drivers/iio/imu/inv_mpu6050/inv_mpu_core.c
drivers/iio/industrialio-core.c
drivers/iio/magnetometer/ak8974.c
drivers/iio/magnetometer/ak8975.c
include/linux/iio/iio.h

These patches apply neatly on our tree.
We will get them eventually after an upgrade.
The only reason to have them in our tree, is to make diff-ing easier with patches that are in IIO core in the ADI tree and not upstreamed yet. [there are a few of these].

iio: core: backport some patches for IIO core

---

drivers/iio/industrialio-buffer.c

These got automatically propagated via the auto-sync mechanism.
The bitmap_alloc() functions are not present in an older version of the
kernel (before 4.19).
This change manually reverts that change to 4.14.

iio: buffer: revert use of bitmap_zalloc()

---

drivers/iio/logic/m2k-logic-analyzer.c

While taking a look at the driver's usage of buffers, I found that the iio_device_unregister() could cause a double-free error.
In the meantime, I cleaned up some more bits in the driver.

iio: m2k-logic-analyzer: cleanup error & remove paths

---

ci/travis/run-build.sh

Mostly we just need 'python-git' now [and that also needs
python-setuptools].
This change also installs the required deps for checking dtbindings
schemas. As documented here:
https://github.com/torvalds/linux/blob/master/Documentation/devicetree/writing-schema.rst

ci,build: update checkpatch dependencies

---

drivers/iio/industrialio-buffer.c
include/linux/iio/buffer_impl.h

1 patch looks like a left-over from older internal/ADI work `iio: core: drop iio_buffer_write() function`
the other 2 were upstreamed

iio: core: cleanups and minor syncs with upstream

---

drivers/iio/industrialio-core.c

This patch fixes the call to iio_str_to_fixpoint when using 'dB' sufix.
Before this the scale_db was not used when parsing the string written to
the attribute and it failed with invalid value.
Fixes: c8d44e142d5f ("iio: core: Handle 'dB' suffix in core")

iio: core: Fix handling of 'dB'

---

arch/arm/boot/dts/overlays/Makefile
arch/arm/boot/dts/overlays/rpi-adar1000-overlay.dts

This patch adds an example device tree overlay for the ADAR1000 beamformer.

arch: arm: boot: dts: Add ADAR1000 overlay

---

drivers/iio/dac/ad5770r.c

Currently there is an off-by-one check on the number of channels that
will cause an arry overrun in array st->output_mode when calling the
function d5770r_store_output_range. Fix this by using >= rather than >
to check for maximum number of channels.
Addresses-Coverity: ("Out-of-bounds access")
Fixes: cbbb819837f6 ("iio: dac: ad5770r: Add AD5770R support")
Signed-off-by: Colin Ian King <colin.king@canonical.com>
Reviewed-by: Alexandru Ardelean <alexandru.ardelean@analog.com>

iio: dac: ad5770r: fix off-by-one check on maximum number of channels

---

drivers/iio/accel/adxl372.c

The adxl372 internal FIFO can now be accessed by reading
the 0x42 data register through debugfs. If a sample is composed
of 3 axis data, the first read of fifo_axis_data will
return X axis data, the second read of fifo_axis_data will
return Y axis data and the third read will return Z axis data.

iio: accel: adxl372: allow fifo read in debugfs

---

drivers/media/platform/axi-hdmi-rx.c

The driver defaults to sample on falling edge, but did not offer an interface
to change this. Implement the "pclk-sample" as specified in the devicetree
bindings (video-interfaces.txt) to work for this device.
This solves the artefacts caused by timing issues we've seen on all our boards.
Signed-off-by: Mike Looijmans <mike.looijmans@topic.nl>

media/axi-hdmi-rx: Honor pclk-sample from devicetree

---

drivers/iio/adc/adar1000.c

This patch fixes the read flag mask. Before this modification the mask wast
set to BIT(15) and the read flag was set on the second transfer byte on bit
7.
Fixes: b2316a2ae75e ("iio: adc: adar1000: Initial driver version")

iio: adc: adar1000: Fix regmap read flag

---

drivers/iio/industrialio-buffer.c
drivers/iio/industrialio-core.c
include/linux/iio/buffer_impl.h

Patch `iio: core: Use scnprintf() for avoiding potential buffer overflow ` is the noisiest one from upstream that shows up when diff-ing upstream & ADI tree.
Patch `iio: move 'indio_dev->info' null check first in __iio_device_register()` got accepted this weekend.
Patch `iio: buffer: minor whitespace sync for buffer attribute` addresses a minor whitespace inconsistency with upstream.

iio: core: minor misc backports & 1 sync

---

Documentation/driver-api/iio/triggers.rst
Documentation/driver-model/devres.txt
drivers/iio/buffer/industrialio-hw-consumer.c
drivers/iio/buffer/industrialio-triggered-buffer.c
drivers/iio/buffer/kfifo_buf.c
drivers/iio/industrialio-core.c
drivers/iio/industrialio-trigger.c
drivers/iio/inkern.c
include/linux/iio/consumer.h
include/linux/iio/hw-consumer.h
include/linux/iio/iio.h
include/linux/iio/kfifo_buf.h
include/linux/iio/trigger.h
include/linux/iio/triggered_buffer.h

This series got upstreamed this weekend.
Drop these so that nobody thinks to use them ever.
They are currently unused.

 iio: core: drop unused devm_ unregister APIs

---

drivers/staging/iio/adc/ad7192.c

When the 'spi_device_id' table was removed, it omitted to cleanup/fix the
assignment:
'indio_dev->name = spi_get_device_id(spi)->name;'
After that patch 'spi_get_device_id(spi)' returns NULL, so this crashes
during probe with null de-ref.
This change fixes this by introducing an ad7192_chip_info struct, and
defines all part-names [that should be assigned to indio_dev->name] in a
'ad7192_chip_info_tbl' table.
With this change, the old 'st->devid' is also moved to be a
'chip_info->chip_id'. And the old 'ID_AD719X' macros have been renamed to
'CHIPID_AD719X'. Tld identifiers have been re-purposed to be enum/index
values in the new 'ad7192_chip_info_tbl'.
This should fix the bug, and maintain the ABI for the 'indio_dev->name'
field.
Fixes: 66614ab2be38 ("staging: iio: adc: ad7192: removed …

iio: adc: ad7192: fix null pointer de-reference crash during probe

---

drivers/staging/iio/adc/ad7192.c

Incidentally, both ID_AD7193 & CHIPID_AD7193 have value 2.
But semantically, CHIPID_AD7193 is correct.
Was noticed upstream.

iio: ad7192: rename ID_AD7193 -> CHIPID_AD7193 in ad7192_channels_config()

---

arch/arm/boot/dts/zynq-zed-adv7511-ad7768-1EVB.dts

Add support for the EV-AD7768-1FMC kit. The EV-AD7768-1FMCZ evaluation kit
features the AD7768-1 24-bit, 256 kSPS analog-to-digital converter (ADC).
The EVAD7768-1FMCZ board connects to the USB port of the PC via the
EVAL-SDP-CH1Z motherboard. By default, power is supplied from the
EVAL-SDP-CH1Z supply, which is regulated to 5 V and 3.3 V to supply the
AD7768-1 and support components.

arch: arm: boot: dts: Add support for ad7768-1EVB with Zedboard

---

drivers/iio/Kconfig.adi

Per some suggestions, changed this to a (ARCH_ZYNQ || ARCH_ZYNQMP || MICROBLAZE) from my original ARCH_SOCFPGA. Tested and works with the Arria 10 dev boards. Separate pull request due to some issues on my end with branches.

FIX: IIO_ALL_ADI_DRIVERS option for Intel FPGAs.

---

drivers/media/platform/axi-hdmi-rx.c
kernel/trace/trace.c
kernel/trace/trace.h
kernel/trace/trace_kdb.c

One is a backport.
The other one is for the AXI HDMI RX driver when CONFIG_VIDEO_ADV_DEBUG is un-defined.

build: fix some code compilation issues

---

drivers/hwmon/pmbus/Kconfig
drivers/hwmon/pmbus/pmbus_core.c

CRC8 should be enforced. Otherwise this breaks places where PMBUS is
defined, and we need to explicitly select CRC8 just to have it.
Also, the CRC table should be initialized per module init.
It's not a problem to do it via probe, but that just initializes it on each driver probe.

 hwmon: pmbus: fix CRC8 dep and move table init in module init

---

drivers/iio/industrialio-buffer.c
drivers/iio/industrialio-core.c

Both patches have been upstreamed.
This PR pulls them in our tree to keep the diff with IIO upstream to a minimal.

iio: core: backports from upstream

---

drivers/iio/adc/ad7124.c
drivers/iio/jesd204/axi_adxcvr.c

These 2 are some small fixes that show up on kernel 5.4, but can be fixed now.

iio: minor build updates that show up only kernel 5.4

---

drivers/iio/frequency/adf4371.c

If regmap_bulk_write() fails, this information should be returned
by adf4371_setup() too. This was most likely a typo.

iio: adf4371: Typo fix

---

arch/arm/boot/dts/overlays/rpi-adau1472-overlay.dts

Add devicetree overlay for ADAU1472 SigmaDSP.
Signed-off-by: Jason Wagar <Jason.Wagar@analog.com>

dts: arm: overlays: Add ADAU1472 overlay

---

drivers/hwmon/pmbus/adm1266.c

Adm1266 will write all input/output status in 64 bytes (blackbox).
This series adds support for reading the states through debugfs and blackbox
through nvmem provider api.

Adm1266 add blackbox support

---

drivers/staging/iio/resolver/ad2s1210.c

When doing a transfer, cs_change is mostly useful in-between transfers.
When applying it to the last transfer, this may have a weird effect of
keeping the CS line up.
Whenever a SPI transfer finishes, the CS line is de-asserted anyway, so no
need to apply 'cs_change' to the last transfer.

staging: ad2s1210: remove 2nd cs_change in transfer

---

arch/arm/boot/dts/overlays/rpi-addi9036-overlay.dts

The Chicony ToF camera module has a different termperature
sensor model compared to ADI ToF module. Add a devicetree
fragment to probe the temp sensor with corresponding driver
at correct I2C address.

dts: arm: overlays: Add support for Chicony ToF camera module

---

drivers/iio/frequency/ad9528.c

The kernel CCF assumes ownership and that clocks are disabled
by default. That's not the case for this driver. This property
makes sure that the clock output starts up disabled.
If you want to disable the channel entirely simply remove it's channel
dt node from the device.
This patch also syncs the implementation with the ad9523 driver,
where we initially introduced this.

iio: frequency: ad9528: Fix usage of adi,output-dis dt channel property

---

arch/arm64/boot/dts/xilinx/zynqmp-adrv9009-zu11eg-reva.dtsi

Adjust lmfc-offset so release point in FPGA moves away of the LMFC edge.
Signed-off-by: Mihai Bancisor <mihai.bancisor@analog.com>

arch: arm64: adrv9009-zu11eg: Update framer-lmfc-offset

---

arch/arm/boot/dts/overlays/Makefile
arch/arm/boot/dts/overlays/rpi-ad5791-overlay.dts

This patch adds an example device tree for the AD5791 DAC.

arm: boot: dts: overlays: Add AD5791 device tree

---

drivers/jesd204/jesd204-core.c

Remove `devm_jesd204_dev_unregister() ` & un-needed `kref_get()`

jesd204: core: minor cleanups

---

drivers/iio/adc/adar1000.c

There was a copy/paste error at ADAR1000_SW_CTRL register write. This patch
removes the extra flag inserted in the write operation.
Fixes: b2316a2ae75e ("iio: adc: adar1000: Initial driver version")

iio: adc: adar1000: Fix SW_CTRL register write

---

drivers/iio/adc/adar1000.c

This patch adds an extended name to RX and TX channels to improve
readability.

iio: adc: adar1000: Set channel extended name

---

arch/arm/boot/dts/overlays/Makefile
arch/arm/boot/dts/overlays/rpi-ad7173-overlay.dts

This patch adds an example device tree for the AD7173 ADC.

arm: boot: dts: overlays: Add AD7173 device tree

---

drivers/iio/gyro/adis16136.c
drivers/iio/imu/adis.c
drivers/iio/imu/adis16400.c
drivers/iio/imu/adis16460.c
drivers/iio/imu/adis16475.c
drivers/iio/imu/adis16480.c
drivers/iio/imu/adis_buffer.c
drivers/iio/imu/adis_trigger.c
include/linux/iio/imu/adis.h

This changeset syncs the recently upstreamed changes for the ADIS lib and the ADIS16475.
Particularly for the ADIS16475 driver, the DIAG & CRC channels were dropped.
Should they be needed, they will be re-implemented.

iio: imu: adis,adis16745: sync with upstream

---

arch/arm/boot/dts/overlays/rpi-ad5791-overlay.dts

AD5791 requires SPI mode 1 or 3 (data latched at falling clock edge.)
Signed-off-by: Mark Thoren <mark.thoren@analog.com>

arch:arm:boot:dts:overlays:rpi-ad5791 fix SPI mode

---

drivers/iio/frequency/cf_axi_dds.h

the jesd_tpl_dac wiki page [1] was updated to fix a naming issue in DAC_DDS_SEL field. Update enum to match that change.
[1] https://wiki.analog.com/resources/fpga/peripherals/jesd204/jesd204_tpl_dac (DAC Channel regmap)

cf_axi_dds fix dds_data_select element names

---

drivers/jesd204/jesd204-core.c
drivers/jesd204/jesd204-priv.h
include/linux/jesd204/jesd204.h

Many kernel frameworks allow a 'get_drvdata()' or 'get_priv()' sort of
mechanism that a driver can use to associate information for a particular
driver state.
This one adds a similar facility for the JESD204 framework.
What's a bit different here, is that this is allocated separately from the
'struct jesd204_dev' struct, because we typically allocate these objects
from the DT when the framework loads.
So there is no simple way to allocate it in another fashion.

jesd204: add facility for keeping private info for a driver

---

drivers/iio/adc/adar1000.c

This patch fixes the condition for end of conversion (EOC).
Fixes: b2316a2ae75e ("iio: adc: adar1000: Initial driver version")

iio: adc: adar1000: Fix adc conversion condition

---

drivers/jesd204/jesd204-core.c
drivers/jesd204/jesd204-fsm.c

Handling the `link_idx` as unsigned everywhere is a little more consistent.
And this also adds the option to specify lane IDs statically from the driver. It does fix a potential bug with some use-case with the framework. But it's still not yet complete; will be done later as things evolve.

jesd204: minor tweaks: convert link_idx to unsigned & handle static lane IDs

---

drivers/jesd204/jesd204-core.c
drivers/jesd204/jesd204-fsm.c
drivers/jesd204/jesd204-priv.h
include/linux/jesd204/jesd204.h

These are useful for multi-link devices, when a user may want to call a
hook for all JESD204 links before or after all links are called
individually to transition.

jesd204: add pre/post transition hooks

---

drivers/jesd204/jesd204-core.c

Don't free up topology when device unregisters. In case a driver needs to
re-probe, the topology is free'd up.
This was a mistake in the initial design.
All the jesd204_dev instances are statically initialized from DT, so they
should be free'd only when entire framework/module unloads.

jesd204: rework cleanup device unregister

---

Documentation/devicetree/bindings/hwmon/adi,adm1266.yaml
drivers/hwmon/pmbus/adm1266.c
drivers/hwmon/pmbus/pmbus.h
drivers/hwmon/pmbus/pmbus_core.c

This series adds the ability to write the firmware through PMBus by writing the Intel Hex file at the start of Nvmem file created by adm1266 driver:
- dt-bindings: hwmon: Add ref node for ADM1266 slaves: slaves now have a phandle to their master
- hwmon: (pmbus/core) Add Block W: used for writing the password as specified in AN-1453
- hwmon: (pmbus/core) Add group command support: send commands to all cascaded devices but execute them only when stop bit is sent
- hwmon: pmbus: adm1266: program firmware: writing to address 0 of nvmem file will now trigger a firmware update of all cascaded devices.

Adm1266 program firmware

---

drivers/iio/frequency/adf4350.c

iio: frequency: adf4350: iio device name use of_node name if available

---

drivers/jesd204/jesd204-core.c
drivers/jesd204/jesd204-fsm.c
drivers/jesd204/jesd204-priv.h
include/linux/jesd204/jesd204.h

With this change a driver should first call jesd204_dev_register() really
early.
If a non-error/non-zero pointer is returned, the driver operates with the
JESD204 framework.
Now, what's needed, is that the jesd204_start_fsm_from_probe() be called to
actually run through the FSM and do some framework... work.

jesd204: separate register from FSM start 

---

drivers/net/ethernet/cadence/macb_main.c

This is a special case: both MAC & PHY support gigabit. But the interface
is MII or RMII.
For those cases we need to disable gigabit in 'phydev->supported'.
This patch is temporary for 4.19 and the ADI kernel.
What happens is that in MII/RMII mode the phy negotiates 1000Mbps. Since
the interface between MAC & PHY can't do more than 100Mbps [in MII/RMII],
this doesn't work.
If you give it a 100 Mbps link-partner, all is fine.
The problem appeared sometime after 4.19, which this commit f22dab12b0dec
("net: macb: Sync macb_config usage with mainline").
Or mainline commit 83a77e9ec4150 ("net: macb: Added PCI wrapper for
Platform Driver.").
It's not clear whether this code is still broken in usptream (yet).
But even if it is, a different commit will be needed there as the context
changed. …

net: macb: disable gigabit for MII & RMII modes

---

drivers/iio/adc/adrv9009.c

If clk_disable_unprepare() is called for an already disabled clock, a warning and the
call trace is printed out.

iio: adc: adrv9009: Fix the clk_disable_unprepare() sequence

---

drivers/mmc/host/sdhci-of-arasan.c

The initial code that was adding delays was doing a cast over undefined
memory. This meant that the delays would be all gibberish.
This change, allocates all delays on the stack, and assigns them from the
ZynqMP & Vesal macros/delay-list. And then finally copies them over the
common itapdly & otapdly variables.
It seems that without this change the UHS SD cards don't work well on ZCU102.
Fixes: c0c8d73 ("sdhci: arasan: Add support for Versal Tap Delays")

mmc: host: sdhci-of-arasan: fix timings allocation code 

---

Documentation/devicetree/bindings/iio/adc/adi,ltc2471.yaml

Add dt binding documentation for ltc2471 driver. This covers all supported
devices.
Signed-off-by: Darius Berghe <darius.berghe@analog.com>

ltc2471 driver yaml

---

drivers/iio/frequency/m2k-dac.c
drivers/iio/logic/m2k-logic-analyzer.c

In HDL was added new functionality for external trigger on PG and DAC.
The external trigger source can be one of : `none`, `trigger_i_0`, `trigger_i_1`, 
`trigger-adc` and `trigger-la`. In case of trigger_i_0 or 1 we can also select the
trigger condition for one of: `none`, `level-low`, `level-high`, `edge-any`, 
`edge-rising` or `edge-falling`
This patch set implement this functionality.

iio: m2k-dac, m2k-logic-analyzer: Add support for external triggering

---

drivers/mtd/spi-nor/spi-nor.c

Commit 3a70b0ddf changed Micron JEDEC manufacturer ID from 0x20 to 0x2C.
Almost all Micron flashes I know use 0x20. Example: MT25QU256ABA
Fixes: 3a70b0ddf ("mtd: spi-nor: add macros related to MICRON flash")

mtd: spi-nor: Fix SPI-NOR-UniqueID prints

---

arch/arm/boot/dts/adi-cn0506-rmii.dtsi
arch/arm/boot/dts/zynq-zc706-adv7511-cn0506-rmii.dts
arch/arm/boot/dts/zynq-zed-adv7511-cn0506-rmii.dts
drivers/net/phy/adin.c

This changeset adds device-trees for RMII mode on ZC706 & Zed.
On the CN0506 board RevB there is a Silabs Si514 clock-chip, which
initially boots-up at 25 Mhz, so for RGMII & MII modes, we don't need to
configure it in SW.
However, for RMII the clock is rev-ed up at 50 Mhz, then the reset-GPIO
pins are used to reset the PHY so that it can reconfigure for the new
frequency.

arch: arm: zc706,zed: cn0506: add RMII device-trees

---

arch/arm/boot/dts/zynq-zc706-adv7511-cn0506-rmii.dts
arch/arm/boot/dts/zynq-zed-adv7511-cn0506-rmii.dts
arch/arm64/boot/dts/xilinx/adi-cn0506-rmii.dtsi
arch/arm64/boot/dts/xilinx/zynqmp-zcu102-rev10-cn0506-rmii.dts

Same as for ZC706 & Zed. This DT supports the CN0506 operating in RMII
mode.
Also, adding hdl_project tags for the ZC706 & Zed projects.

arm64: dts: cn0506: add device-tree for ZCU102 carrier & RMII mode 

---

drivers/iio/dac/ad5592r-base.c
drivers/iio/dac/ad5592r-base.h

Reported by @cstanhope  
I've already sent the patches upstream.
https://patchwork.kernel.org/project/linux-iio/list/?series=313283
We can add a Reported-by tag to the patch if @cstanhope wants to.

iio: dac: ad5592r: fix & cleanup locking

---

drivers/mtd/spi-nor/spi-nor.c

This reverts commit 96f15b80459b451e092d867d8bb02d26c288a514.

Revert "mtd: spi-nor: Fix SPI-NOR-UniqueID prints"

---

drivers/jesd204/jesd204-fsm.c

* `jesd204: fsm: fix busy-flags handling and group init links with start links` - the busy flags were not handled properly
* `jesd204: fsm: handle memory free on each call of jesd204_fsm_table()` - fix potential leak on error path
* `jesd204: fsm: clear error current state is DONT_CARE` - so that we can restart the FSM if something goes wrong

jesd204: fsm: cleanups (1)

---

drivers/jesd204/jesd204-fsm.c

* `jesd204: fsm: don't get/put kref too many times` - no bugs noticed yet for this,but it looks like it could occur
* `jesd204: fsm: don't decrease refcounts on error in __jesd204_fsm()` - hasn't happened yet; but a done_cb could trigger on error [even if it shouldn't]
* `jesd204: fsm: return DEFER in initialize_cb if no link_idx found ` - this would still stop at some other state-transition; but better to stop it early
* `jesd204: fsm: fix validation of connection link_idx ` - this would cause a crash if the topology ID is not correct

jesd204: cleanups/fixes (2)

---

drivers/jesd204/jesd204-core.c
drivers/jesd204/jesd204-fsm.c
drivers/jesd204/jesd204-priv.h

* `jesd204: add connection simple unique IDs` - for debugging
* `jesd204: fsm: set error on the connection and jdev object if cb fails` - this error should be reported
* `jesd204: fsm: rename jdev -> jdev_it in propagation ` - this is cosmetic a bit, but mostly semantic; the name of this variable will be important later;
* `jesd204: fsm: remove inputs field` - just dead code

jesd204: minor cleanups/polishes (3)

---

drivers/iio/adc/ad7124.c

This change does the following:
* removes the SPI device table in favor of the OF device table
* adds 'name' && 'chip_id' fields to chip_info
* implements chip ID & silicon revision checking; the device ID for
AD7124-4 is 0x0, so just checking that value can be useless;
but at least the silicon revision isn't 0, so a non-zero value can be
used to check that "a" device is on the SPI bus; it's probably the best
way to narrow it down to one of the 2 AD7124 chip IDs

iio: adc: ad7124: move chip ID & name on the chip_info table

---

Documentation/devicetree/bindings/iio/gyroscope/adi,adxrs290.yaml
arch/arm/boot/dts/overlays/rpi-adxrs290-overlay.dts
drivers/iio/gyro/adxrs290.c

This patch adds channels support for angular rate data & temperature data and the ability to program the 3db frequencies for both low-pass & high-pass filter all through the SPI protocol. This patch also updates the dt-overlay to configure ADXRS290 to SPI mode 3 and correspondingly updates the binding document.

iio: gyro: Update ADXRS290 driver for channels support

---

drivers/jesd204/jesd204-fsm.c

I assumed this was always true, but turns out it isn't. During probe, a
device will propagate only on it's own direct connections, which may be
only for a certain JESD204 link, and will ignore devices for all other
JESD204 links.
When propagating state changes for all JESD204 links, we should always
start from the top-level device.
That way, the propagations will happen for all JESD204 links (if they need
to), or only for a certain JESD204 link (if it needs to).
Though the latter hasn't been tested yet; it will be tested in future
cases.

jesd204: fsm: always start state transition from top-level device

---

ci/travis/run-build.sh

It seems that backporting to an older kernel version is a bit more
problematic sometimes, as master is on 4.19 and intel/altera on 4.14.
We should focus on moving support for intel/altera boards in master and not
carry extra branches around.
At some point we may also switch rpi-4.19.y to master, but first we should
start with altera branches.
If we need things in this branch, we should backport it manually.
The adi-iio branch is too far ahead of master and takes some effort to keep
it working as things change in the kernel (like GPIO APIs).
In the near future, kernel 5.4.0 will be the next version that will be
used. At that point version 4.14 will be more difficult to backport to.

ci: stop auto-sync-ing altera_4.14 & adi-iio branches

---

arch/arm64/boot/dts/xilinx/zynqmp-adrv9009-zu11eg-reva.dtsi
drivers/iio/adc/adm1177.c

https://github.com/analogdevicesinc/linux/commit/3a901a778f83f4c12106bef6670db85c49f9d5be has started to do it, but the i2c_device_id and of_device_id were not updated, so the change had no effect.

iio: adc: adm1177: Make a distinction between the hwmon and iio versions 

---

drivers/iio/adc/ad9081.c

Compiler complains about a potential fall-through. But in reality this can
also be a bug, where -EINVAL is returned by a potential invalid
fall-through.

iio: ad9081: fix potential invalid error code

---

drivers/hwmon/pmbus/adm1266.c

Writing the configuration Intel hex file to the nvmem,
of an adm1266, with offset 0x30000, will now
trigger the configuration programming.
During this process the adm1266 sequencer will be
stopped and at the end will be issued a seq reset
(see AN-1453 Programming the configuration).

hwmon: pmbus: adm1266: program configuration

---

drivers/jesd204/jesd204-core.c

First switch() would always assign the same encoding values, regardless of
the encoder type.
Second one is fine, but the compiler complains that it's an implicit
fall-through, so we should handle it.

jesd204: fix & handle switch implicit fall-through

---

drivers/spi/spi.c
include/linux/spi/spi.h

Transmit/receive only is a valid SPI mode. For example, the MOSI line
might be missing from an ADC while for a DAC the MISO line may be
optional. This patch adds these two new modes: SPI_NO_MOSI and
SPI_NO_MISO. This way, the drivers will be able to identify if any of
these two lines is missing and to adjust the transfers accordingly.

spi: Add NO_MOSI/MISO support

---

drivers/iio/frequency/ad9528.c

Remove owner assignment to the driver object.
Convert the rest of the probe to device-managed functions.

iio: ad9528: minor cleanups of the driver

---

drivers/jesd204/jesd204-core.c
drivers/jesd204/jesd204-fsm.c
include/linux/jesd204/jesd204.h

These helpers can unpack a `struct jesd204` object in a meaningful way for debugging.

 jesd204: add printk helpers

---

drivers/iio/frequency/hmc7044.c

This change just moves the logic into it's own function to be re-used in
other places.

iio: hmc7044: wrap sync pin logic into hmc7044_sync_pin_set() helper

---

drivers/iio/logic/m2k-logic-analyzer.c
drivers/iio/logic/m2k-trigger-ad.c

HDL support trigger out disabling. This commit add support in SW too.

iio: logic: m2k: la & adc add trigger disable option

---

drivers/iio/logic/m2k-logic-analyzer.c

The number of delay taps in the LA data path can be controlled manually
or automatically according to the axi_adc_decimate's rate. This commit
adds support for this control in driver.

iio: logic: M2K LA add delay taps control

---

drivers/iio/adc/navassa/Makefile

Petalinux generates the object files in another location than the
source-files. Because of this, wildcard rule in the Makefile doesn't seem
to find the files, so it doesn't compile them
This results in linker errors.
The fix is to just do a shell find of all C files and paste them into the
Makefile as they are.
Fixes https://github.com/analogdevicesinc/meta-adi/issues/69

iio: adc: adrv9001: list driver files explicitly in Makefile

---

drivers/iio/adc/adrv9009_conv.c

Since almost 2 years the HDL core uses util_pack which doesn't have
channel combination enable constrains. Remove scan_masks for all
derivatives, since they are no longer needed.

iio: adc: adrv9009_conv: Allow any scan_mask combination

---

drivers/iio/jesd204/axi_adxcvr.c
drivers/iio/jesd204/axi_adxcvr.h
drivers/iio/jesd204/axi_jesd204_rx.c
drivers/iio/jesd204/axi_jesd204_tx.c

This patch adds support for an optional CPLL/QPLL REFCLK from a
difference source, which rate and state must be in sync with the main
conv clk (GT REFCLK). This feature is used on the ADRV9009-ZU11EG SoM
in combination with the external FMCOMMS8 FMC card, where each HMC7044
clock chip provides it's own GT REFCLK connected to different QUADs in
an identical configuration.

iio: jesd204: Support for optional (slaved) GT REFCLK

---

drivers/iio/frequency/hmc7044.c

In case the current CLKIN source is provided via the CCF use it's
frequency instead of returning the values from the
adi,pll1-clkin-frequencies property.

iio: frequency: hmc7044: Fix CLKIN frequency debugfs status reading

---

drivers/jesd204/jesd204-core.c
drivers/jesd204/jesd204-fsm.c
drivers/jesd204/jesd204-priv.h
include/linux/jesd204/jesd204.h

Adapted from Michael's work.
This adds the jesd204_sysref_async(), but with a bit more integration into
the topology of the framework.
There can be only one SYSREF provider in a topology. But more devices in a
topology could issue a SYSREF, but only the device configured in the DT
should be used.
This validates that the device configured as a SYSREF provider actually has
callback for issuing a SYSREF. It also validates that no second device
tries to configure itself as a SYSREF provider during probe.
At the moment the jesd204_sysref_async() takes only a single parameter (as
jdev object). Maybe later some other parameters may make sense.

jesd204: core: add async sysref helper

---

drivers/iio/jesd204/axi_jesd204_rx.c
drivers/jesd204/jesd204-core.c
include/linux/jesd204/jesd204.h

This changeset integrates the `axi_jesd204_rx` driver into the JESD204 framework.
The driver should be able to also operate without the framework.

iio: jesd204: axi_jesd204_rx: register & integrate with the JESD204 framework 

---

arch/arm64/boot/dts/xilinx/zynqmp-zcu102-rev10-adrv9008-1-jesd204-fsm.dts
arch/arm64/boot/dts/xilinx/zynqmp-zcu102-rev10-adrv9009-jesd204-fsm.dts
include/dt-bindings/iio/adc/adi,adrv9009.h
include/dt-bindings/iio/frequency/hmc7044.h

Add first batch of device-trees with the JESD204 framework.
Some framework bits still need to be merged, for this to work.
Particularly the adrv9009 driver integration with the framework.

arm64: dts: add device-tree variants for ADRV9009 & ADRV9008-1 with JESD204 FSM

---

drivers/iio/frequency/cf_axi_dds.c
drivers/iio/frequency/cf_axi_dds.h

iio: axi-dds: register with JESD204 framework and add support for ADRV9009-X4

---

drivers/iio/jesd204/axi_adxcvr.c
drivers/iio/jesd204/axi_adxcvr.h

Currently just register some blank init data. Will be populated later as it
evolves.
Also, squeezed in some cleanups.

iio: jesd204: adxcvr: register with the JESD204 framework 

---

drivers/iio/dac/ad5686.c
drivers/iio/dac/ad5686.h

As part of the general cleanup of indio_dev->mlock, this change replaces
it with a local lock on the device's state structure.

iio: dac: ad5686: Replace indio_dev->mlock with own device lock

---

drivers/iio/dac/ad5686-spi.c
drivers/iio/dac/ad5686.c
drivers/iio/dac/ad5686.h
drivers/iio/dac/ad5696-i2c.c

This set of patches adds output buffer support for the AD5686 family of nano DACs. It uses a PWM source to trigger the interrupt to read samples from the buffer and output on DAC channels.

Add output buffer ad5686 master

---

drivers/iio/jesd204/axi_jesd204_rx.c

This patch adds Interrupt support for HDL Core Version >=1.04a
* 0  Frame Alignment Error (204B only)
- At least one of the lanes frame alignment monitor error counter
met a threshold defined by register 0x248
* 1  Unexpected Lane State Error (204B and 204C)
- At least one of the enabled lanes entered in an unexpected state
while the link is up (in DATA phase).
- For 204B this happens when the lane state machine falls back to
INIT phase while the link is up in response to at least four or
more consecutive invalid characters received from the phy.
From this state the lane state machine can recover only with a
CGS sequence.
- For 204C this happens when one of the lanes loses sync header
alignment or multi-block alignment.

iio: jesd204: axi_jesd204_rx: Frame alignment error interrupt support

---

Documentation/devicetree/bindings/iio/gyroscope/adi,adxrs290.yaml
drivers/iio/gyro/adxrs290.c

Update ADXRS290's driver and dt-bindings in the ADI tree with the upstream version [1] [2].
[1] https://patchwork.kernel.org/patch/11685711/
[2] https://patchwork.kernel.org/patch/11685713/

iio: gyro: adxrs290: sync with upstream version

---

arch/arm/boot/dts/overlays/Makefile
arch/arm/boot/dts/overlays/rpi-ad5679r-overlay.dts

This patch will add a dts example for the AD5679R DAC.

arm: boot: dts: overlays: Add ad5679r overlay example

---

drivers/iio/jesd204/axi_jesd204.h
drivers/iio/jesd204/axi_jesd204_rx.c
drivers/iio/jesd204/axi_jesd204_tx.c
drivers/jesd204/jesd204-core.c
include/linux/jesd204/jesd204.h

This change renames the JESD204 framework's enums from JESD204_ENC_xxx to
JESD204_ENCODER_xxx. This is also to make sure we catch some that collide.
Added a helper jesd204_encoder_str() that replaces the
axi_jesd204_encoder_label table.

jesd204: axi-jesd204-rx/tx: move encoder enums to framework 

---

Documentation/devicetree/bindings/iio/gyroscope/adi,adxrs290.yaml
MAINTAINERS
drivers/iio/Kconfig.adi
drivers/iio/gyro/Kconfig
drivers/iio/gyro/Makefile
drivers/iio/gyro/adxrs290.c

ADXRS290 is a high performance MEMS pitch and roll (dual-axis in-plane) angular rate sensor (gyroscope) designed for use in stabilization applications. It also features an internal temperature sensor and programmable high-pass and low-pass filters.
Add support for ADXRS290 in direct-access mode for now.
Corresponding upstream versions: https://patchwork.kernel.org/patch/11685711/ and https://patchwork.kernel.org/patch/11685713/

iio: gyro: Add driver support for ADXRS290

---

drivers/jesd204/jesd204-fsm.c

jesd204: fsm: print once the SYSREF provider

---

drivers/iio/jesd204/axi_jesd204_rx.c
drivers/iio/jesd204/axi_jesd204_tx.c

For both RX & TX JES204 peripheral drivers, this changeset is cleaning up the probe & remove path.
It's taking a better consideration for the framework -vs- non-framework cases.
For the TX, using the framework would cause a crash [introduced by a recent change].
The probe & remove & exit-on-error paths have been balanced as much as possible.

iio: jesd204: axi_jesd204_tx/rx: rework probe & remove

---

arch/arm64/boot/dts/xilinx/zynqmp-adrv9009-zu11eg-reva-adrv2crr-fmc-reva.dts
arch/arm64/boot/dts/xilinx/zynqmp-adrv9009-zu11eg-revb-adrv2crr-fmc-revb-sync-fmcomms8-jesd204-fsm.dts
arch/arm64/boot/dts/xilinx/zynqmp-adrv9009-zu11eg-revb-adrv2crr-fmc-revb-sync-fmcomms8.dts
arch/arm64/boot/dts/xilinx/zynqmp-adrv9009-zu11eg-revb-adrv2crr-fmc-revb.dts
arch/arm64/boot/dts/xilinx/zynqmp-zcu102-rev10-adrv9009-fmcomms8-jesd204-fsm.dts
drivers/iio/frequency/hmc7044.c
drivers/iio/jesd204/axi_jesd204_tx.c

The DT for Talise SOM + FMCOMMS8 will need a bit of polishing at a later point to re-use the `adi-fmcomms8.dtsi`
Added patches for HMC7044 for FMCOMMS8.
Added support for ZCU102 + FMCOMMS8.
1 bugfix for non-framework setup. restored Subclass 1 to JESD204 TX.

arch: arm64: add support for FMCOMMS8 

---

arch/arm64/boot/dts/xilinx/zynqmp-adrv9009-zu11eg-reva-adrv2crr-fmc-reva-jesd204-fsm.dts
arch/arm64/boot/dts/xilinx/zynqmp-adrv9009-zu11eg-revb-adrv2crr-fmc-revb-jesd204-fsm.dts

dts: zynqmp-adrv9009-zu11eg-rev[a|b]-adrv2crr-fmc-rev[a|b]-jesd204-fsm.dts

---

arch/arm/boot/dts/zynq-zc706-adv7511-adrv9008-1-jesd204-fsm.dts
arch/arm/boot/dts/zynq-zc706-adv7511-adrv9008-2-jesd204-fsm.dts
arch/arm/boot/dts/zynq-zc706-adv7511-adrv9009-jesd204-fsm.dts
arch/arm/boot/dts/zynq-zc706-adv7511-adrv9009.dts

arch: arm: zynq-zc706-adv7511: adrv9009: add jesd204-fsm variants

---

drivers/jesd204/jesd204-core.c

Remove list entry for jdev object on framework unload, otherwise the list has a list of 
free'd elements, causing invalid memory access.
Also, up to a point, we should use dev_err(dev, ...) to print errors to identify
the device easier, because the jdev object isn't initialized yet.

jesd204: bug fixes

---

drivers/iio/jesd204/axi_jesd204_tx.c

iio: jesd204: axi_jesd204_tx: Always reset Link Layer before enable

---

drivers/jesd204/jesd204-core.c
drivers/jesd204/jesd204-fsm.c
drivers/jesd204/jesd204-priv.h
include/linux/jesd204/jesd204.h

This change splits the jesd204_fsm_table() function into a
jesd204_fsm_table_single() function that gets re-called a number of
retries.
This allows for a number of retries to be called to transition to the final
state in the table.
The jesd204_fsm_table_single() also performs a rollback, so on a single
try:
- FSM will try to go to the final state
- on an error it will rollback to IDLE
Currently the num_retries need to be specified by the driver, but later we
may add an option to configure this from DT.
The num_retries field will only be taken into consideration for the
top-level device (in a topology).

jesd204: fsm: implement retry mechanism 

---

Documentation/devicetree/bindings/pwm/pwm-axi-pwmgen.yaml
Kconfig.adi
drivers/pwm/Kconfig
drivers/pwm/Makefile
drivers/pwm/pwm-axi-pwmgen.c

This patch adds support for the AXI PWM Generator. This device is an
FPGA-implemented peripheral used as PWM signal generaor and can be
interfaced with AXI4. The register map of this peripheral makes possible
the configuratoin of the output signal, in terms of period and duty cycle.

pwm: add support for AXI PWM generator

---

drivers/iio/frequency/ad916x/ad916x_nco_api.c
drivers/iio/frequency/ad916x/api_def.h
drivers/iio/frequency/ad916x/utils.c
drivers/iio/frequency/ad916x/utils.h

Incorrect behaviours in NCO frequency setting for the ad916x can be due to:
1. Divisors getting truncated in 32-bit-divisor routines.
2. Truncation in computation of GCD. 
3. Setting NCO frequency=0. This causes the driver to hang.
This patch addresses the above causes to fix the problem.
Signed-off-by: kister-jimenez <kister.jimenez@analog.com>

iio: frequency: ad916x: Fix NCO Frequency setting behavior.

---

drivers/jesd204/Makefile
drivers/jesd204/attr.h
drivers/jesd204/jesd204-core.c
drivers/jesd204/jesd204-priv.h
drivers/jesd204/jesd204-sysfs.c

This is an adaptation from an earlier work. It exposes the sysfs for all
JESD204 devices in a topology.
For the top-level device, the JESD204 link parameters are available for
reading.
This will primarily be used for debugging, but we would need at some point
a tool to converge all this data visually a bit better.

jesd204: sysfs: add initial version for sysfs

---

drivers/media/platform/axi-hdmi-rx.c

Add missing MODULE_LICENSE directive, otherwise you'll get this when
you load the module:
axi_hdmi_rx: module license 'unspecified' taints kernel.
Disabling lock debugging due to kernel taint
axi_hdmi_rx: Unknown symbol vb2_queue_init (err -2)
axi_hdmi_rx: Unknown symbol vb2_streamoff (err -2)
axi_hdmi_rx: Unknown symbol devm_kmalloc (err -2)
...
Signed-off-by: Mike Looijmans <mike.looijmans@topic.nl>

media/platform/axi-hdmi-rx: Announce GPLv2 module license

---

drivers/media/platform/axi-hdmi-rx.c

The capture devices doesn't actually work yet after this change, it probes but hangs after capturing the first (garbled) frame. But at least the driver probes now.
Need to provide this info, otherwise video_register_device will trigger a WARN
and fail.
Fixes this kernel WARN message:
```
adv7611 4-004c: adv7611 found @ 0x98 (i2c-0-mux (chan_id 3))
unsupported bus type 0
------------[ cut here ]------------
WARNING: CPU: 1 PID: 320 at drivers/media/v4l2-core/v4l2-dev.c:863 __video_register_device+0x48/0x118
Modules linked in: axi_hdmi_rx(+) videobuf2_dma_contig videobuf2_v4l2 videobuf2_common videobuf2_mema
CPU: 1 PID: 320 Comm: modprobe Tainted: G        W         5.4.0-xilinx-v2020.1 #1
Hardware name: Xilinx Zynq Platform
[<c010d778>] (unwind_backtrace) from [<c0109aec>] …
```

media: axi-hdmi-rx: Provide device_caps in struct video_device

---

drivers/media/platform/axi-hdmi-rx.c

The v4l2-fwnode expects the bus_type member passed to v4l2_fwnode_endpoint_parse
to have an actual value. Set it to V4L2_MBUS_UNKNOWN (0) to request the bus type
to be obtained from the devicetree.
This fixes the color coding and sync signals were not being read from the devicetree.
Signed-off-by: Mike Looijmans <mike.looijmans@topic.nl>

media: axi-hdmi-rx: Initialize bus_type

---

drivers/dma/dma-axi-dmac.c

Starting with core version 4.3.a the DMA bus attributes can (and should) be
read from the INTERFACE_DESCRIPTION (0x10) register.
For older core versions, this will still need to be provided from the
device-tree.
The bus-type values are identical to the ones stored in the device-trees,
so we just need to read them. Bus-width values are stored in log2 values,
so we just need to use them as shift values to make them equivalent to the
current format.

dmaengine: axi-dmac: add support for reading bus attributes from registers

---

arch/microblaze/boot/dts/adi-ad9467-fmc-250ebz.dtsi
arch/microblaze/boot/dts/adi-fmcjesdadc1.dtsi
arch/microblaze/boot/dts/adi-fmcomms1.dtsi

Since moving to OF probing, the match-string is 'adi,adxxxx'. This change
updates all places with devices related to the ad9467 driver, to have this
prefix, to account for this (and future) OF changes.

arch: arm,microblaze: prefix with adi, all compat strings related to ad9467 driver

---

Documentation/devicetree/bindings/iio/gyroscope/adi,adxrs290.yaml
arch/arm/boot/dts/overlays/rpi-adxrs290-overlay.dts
drivers/iio/gyro/Kconfig
drivers/iio/gyro/adxrs290.c

Provide a way for continuous data capture by setting up buffer support. The
data ready signal exposed at the SYNC pin of the ADXRS290 is exploited as
a hardware interrupt which triggers to fill the buffer.
Triggered buffer setup was tested with both hardware trigger (DATA_RDY) and
software triggers (sysfs-trig & hrtimer).
Also, extend support to read/write byte data from/to the device using
debugfs interface.

iio: gyro: adxrs290: Add triggered buffer support

---

drivers/iio/adc/ad9467.c

Split `ad9467_setup()` function from probe.
Cleanup `ad9467_spi_write()` (sync closer to upstream).

iio: adc: ad9467: misc cleanups (part 3)

---

drivers/iio/adc/ad9467.c
drivers/iio/adc/cf_axi_adc.h

This removes the SPI device ID table. Upstream this isn't present.
And re-uses the current chip_info to be matched via OF.

iio: adc: ad9467: convert to full dt probe support 

---

drivers/jesd204/jesd204-fsm.c

When running during these cases, we should not clear the errors. There's
now an API call that does that (i.e. jesd204_fsm_clear_errors()).
These cases were added, when this API call did not exist.
Drivers that want to retry, usually call this function.
Also, if we won't clear error: rollback will work fine, but now the JESD204 link objects contain errors,
so they need to be explicitly cleared before retrying.

jesd204: fsm: cleanup/improve error handling in the state-machine

---

drivers/iio/adc/adrv9009.c

When ADRV9009_GET_FIR() is used by the ORX and TX profiles, the
number of coefficients is incorrectly displayed.

iio: adc: adrv9009: Fix GET_FIR error message

---

drivers/iio/adc/ad7768-1.c

The ad7768-1 is a fully differential ADC, meaning that the voltage
conversion result is a signed value. Since the value is a 24 bit one,
stored in a 32 bit variable, the sign should be extended in order to get
the correct representation.
Also the channel description has been updated to signed representation,
to match the ADC specifications.
Fixes: 8a15c73a9bcf ("iio: adc: Add AD7768-1 ADC basic support")

iio: adc: ad7768-1: Fixes conversion result sign

---

drivers/jesd204/jesd204-core.c
drivers/jesd204/jesd204-fsm.c
drivers/jesd204/jesd204-priv.h
include/linux/jesd204/jesd204.h

Some bits of cleanups done while adding more stuff to the framework.
The more important one [here] is the move error field on the public jesd204_link type; with this we can pass the error information to the state callbacks/ops and to the completion callback.

jesd204: core: tweaks/cleanups; move error field on the public jesd204_link type

---

drivers/jesd204/jesd204-fsm.c
include/linux/jesd204/jesd204.h

When the FSM finishes transitioning [through all states], it can be useful
for some drivers to get a callback to get notified of this.
This is useful even when an error happened.
This change implements this callback, and provides the error callback. This
is called once per each device, regardless of the number of links it
initialized for.

jesd204: fsm: implement fsm completion/finished callback

---

Documentation/devicetree/bindings/iio/adc/adi,ltc2376.yaml
arch/arm/boot/dts/overlays/rpi-ltc2376-overlay.dts
drivers/iio/adc/ltc2376.c

Adds basic read raw functionality and buffer support. 
The frequency of the PWM can be varied and is used as a conversion signal for the device. The falling edge on the busy signal from the device provides hardware trigger for the buffer.

LTC2376 IIO driver - GSoC 2020

---

drivers/iio/adc/ad7124.c

This patch fixes the device name typo.
Fixes: f0bcebbf50dd ("iio: adc: ad7124: move chip ID & name on the chip_info table")

iio: adc: ad7124: Fix typo in device name

---

drivers/iio/adc/ad7768-1.c

The following PR contains the next changes:
- Add hardware buffer support (SPI engine)
- Fix the data representation (sign)
- Add common voltage attribute
- Add gpio controller support

iio: adc: ad7768-1: SPI engine and gpio update

---

Documentation/devicetree/bindings/clock/axi-clkgen.txt
arch/arm/boot/dts/zynq-adrv9361-z7035-fmc.dts
arch/arm/boot/dts/zynq-zc702-adv7511.dtsi
arch/arm/boot/dts/zynq-zc706-adv7511-adrv9008-1.dts
arch/arm/boot/dts/zynq-zc706-adv7511-adrv9008-2.dts
arch/arm/boot/dts/zynq-zc706-adv7511-adrv9009.dts
arch/arm/boot/dts/zynq-zc706-adv7511-adrv9371.dts
arch/arm/boot/dts/zynq-zc706-adv7511.dtsi
arch/arm/boot/dts/zynq-zed-adv7511-m2k-revb.dts
arch/arm/boot/dts/zynq-zed-adv7511.dtsi
arch/arm/boot/dts/zynq-zed-imageon.dts
arch/arm64/boot/dts/xilinx/zynqmp-zcu102-rev10-adrv9008-1.dts
arch/arm64/boot/dts/xilinx/zynqmp-zcu102-rev10-adrv9008-2.dts
arch/arm64/boot/dts/xilinx/zynqmp-zcu102-rev10-adrv9009.dts
arch/arm64/boot/dts/xilinx/zynqmp-zcu102-rev10-adrv9371.dts
arch/microblaze/boot/dts/kcu105_adrv9371x.dts
drivers/clk/clk-axi-clkgen.c

If an axi read (or write) is performed before the clock is configured,
the driver hangs indefinitely. Make sure the axi clock is ready before
trying to access the bus.
This change forces the s_axi_aclk to be the first clock defined in the
devicetree.
Signed-off-by: Liam Beguin <lvb@xiphos.com>

clk: axi-clkgen: check axi clock before bus access

---

Documentation/devicetree/bindings/iio/addac/one-bit-adc-dac.yaml
drivers/iio/Kconfig
drivers/iio/Kconfig.adi
drivers/iio/Makefile
drivers/iio/addac/Kconfig
drivers/iio/addac/Makefile
drivers/iio/addac/one-bit-adc-dac.c
drivers/iio/industrialio-core.c
include/linux/iio/iio.h
include/linux/iio/types.h

This allows remote GPIO read and write, trough libiio.

one-bit-adc-dac: Add initial version of one bit ADC, DAC

---

drivers/iio/addac/one-bit-adc-dac.c

There are cases where these GPIOs are used to enable some auxiliary things
and setting them to default HIGH would have unintended behavior triggered in
the hardware. This patch changes the default to LOW.
I am not saying this is the best fix to this problem, but i wanted to start a discussion around it. Maybe a device tree default state would be more appropriate and would cover the case of inverse logic for enables.

iio: addac: one-bit-adc-dac: Set output to Low

---

arch/arm64/boot/dts/xilinx/zynqmp-zcu102-rev10-stingray.dts

This patch adds support for the XUD1A board along with the GPIOs used for
enabling the board, PLLs, RX and TX controls.
A GPIO controller has been added for the Stingray board for controlling the
ADAR1000s.

arm64: boot: dts: xilinx: Add support for XUD board

---

drivers/jesd204/jesd204-fsm.c
drivers/jesd204/jesd204-sysfs.c

There's also a commit that removes some obsoleted comments.
Otherwise, this mostly does a sysfs cleanup, add exposes for each JESD204 link the `state` & `error` parameters.
The states are Linux FSM states.

jesd204: sysfs: cleanups & expose 'error', 'state' link parameters (in sysfs)

---

drivers/iio/frequency/hmc7044.c

Using non power of two reference frequencies such as 125.00MHz instead
of 122.88MHz, dividing by 2 can cause a residual.
This case must be avoided. Therefore check and stop before this happens.

iio: frequency: hmc7044: Fix MAX SYSREF frequency computation 

---

drivers/iio/adc/adrv9009.c
drivers/jesd204/jesd204-core.c
drivers/jesd204/jesd204-fsm.c
drivers/jesd204/jesd204-priv.h
drivers/jesd204/jesd204-sysfs.c
include/linux/jesd204/jesd204.h

This adds support for stop-states in the FSM.
For the 9009 we need to hack it a bit to re-use libiio to query when the FSM has paused into a
certain state and to resume from that state.
With this, in a device tree, any JESD204 device can define some states on
which it want to defer.
Example:
jesd204-stop-states = <JESD204_FSM_STATE_LINK_PRE_SETUP
JESD204_FSM_STATE_LINK_ENABLE>;
The information can then be queried:
iio_attr -q -a -d adrv9009-phy jesd204_fsm_state
iio_attr -q -a -d adrv9009-phy jesd204_fsm_error
iio_attr -q -a -d adrv9009-phy jesd204_fsm_paused
And then a resume can be called:
iio_attr -q -a -d adrv9009-phy jesd204_fsm_resume 1

jesd204,adrv9009: add support for stop states and resuming from them 

---

arch/arm/boot/dts/zynq-coraz7s-ad7768-1ARDZ.dts
arch/arm/boot/dts/zynq-coraz7s-cn0540.dts

Changes:
-Fix ad7768-1's mclk frequency
-Update spi parameters to use the spi engine at max frequency
- Add ltc2606 and one-bit-adc-dac

arch: arm: dts: cn0540 devicetree updates and rename

---

drivers/iio/adc/cf_axi_adc.h
drivers/iio/frequency/cf_axi_dds.c
drivers/iio/frequency/cf_axi_dds.h
include/linux/jesd204/adi-common.h

This changeset moves the common TPL regs into a common header file.

iio: axi-adc/axi-dds: common-alize the TPL reg definitions into a single header

---

scripts/dtc/dtc-lexer.l

gcc 10 will default to -fno-common, which causes this error at link
time:
(.text+0x0): multiple definition of `yylloc'; dtc-lexer.lex.o (symbol from plugin):(.text+0x0): first defined here
This is because both dtc-lexer as well as dtc-parser define the same
global symbol yyloc. Before with -fcommon those were merged into one
defintion. The proper solution would be to to mark this as "extern",
however that leads to:
dtc-lexer.l:26:16: error: redundant redeclaration of 'yylloc' [-Werror=redundant-decls]
26 | extern YYLTYPE yylloc;
|                ^~~~~~
In file included from dtc-lexer.l:24:
dtc-parser.tab.h:127:16: note: previous declaration of 'yylloc' was here
127 | extern YYLTYPE yylloc;
|                ^~~~~~
cc1: all warnings being treated as errors
which means the declaration is …

scripts/dtc: Remove redundant YYLOC global declaration

---

arch/arm64/boot/dts/xilinx/adi-ad9081-fmc-ebz.dtsi
arch/arm64/boot/dts/xilinx/zynqmp-zcu102-rev10-ad9081-m8-l4.dts
arch/microblaze/boot/dts/adi-ad9081-fmc-ebz.dtsi
arch/microblaze/boot/dts/vcu118_quad_ad9081_204b_txmode_9_rxmode_10.dts
arch/microblaze/boot/dts/vcu118_quad_ad9081_204c_txmode_10_rxmode_11.dts
arch/microblaze/boot/dts/vcu118_quad_ad9081_204c_txmode_11_rxmode_4.dts
arch/microblaze/boot/dts/vcu118_quad_ad9081_204c_txmode_11_rxmode_4_direct_6g.dts

Therefore we can remove the startup-mode-dynamic-enable attributes.

dts: vcu118_quad_ad9081_204*.dts: Always use continuous SYSREF 

---

drivers/jesd204/jesd204-fsm.c

For now, stop-states are only needed during init for sync-ing SOMs. Later
we may [probably] need some stop-states for rollback, but for now, ignore
the stop-states during rollback.

jesd204: fsm: don't handle stop-states during rollback

---

arch/arm/boot/dts/zynq-zed-adv7511.dtsi

In a recent change, the DMA channels can be read from registers (vs reading
them from the DT).
We are too close to a release to do a full-cleanup.
This has been tested, so remove it.

arch: arm: zynq-zed-adv7511: remove adi,channels for video

---

arch/arm/boot/dts/zynq-zed-adv7511.dtsi

These properties don't seem to be parsed in this current form, so they
aren't really used.
The form has changed, and 'frame-master' & 'bitclock-master' are now
phandles and not boolean properties.

arch: arm: zynq-zed-adv7511: remove bitclock & frame-master props

---

arch/arm/boot/dts/zynq-zed-adv7511.dtsi

This reverts commit 4678fddc9fb6df88767aa1ee0c136e345752030f.
Maybe we should wait 1-2 releases before doing these changes. Even
internally we will use some 2019_R1 HDL files with master, and with this
change, video (on ZedBoad) won't work on those.
So, to avoid any questions about this, this change reverts back the
adi,channels.

Revert "arch: arm: zynq-zed-adv7511: remove adi,channels for video"

---

arch/arm/boot/dts/zynq-zc706-adv7511.dtsi

The reg value is correct (0x51). The rtc@54 value is incorrect; should be
rtc@51.
Newer DT compilers complain about this:
arch/arm/boot/dts/zynq-zc706-adv7511.dts:77.11-80.6: Warning (i2c_bus_reg): /fpga-axi@0/i2c@41600000/i2c-mux@74/i2c@4/rtc@54: I2C bus unit address format error, expected "51"

arch: arm: zynq-zc706-adv7511.dtsi: fix i2c node address

---

arch/arm64/boot/dts/xilinx/zynqmp-adrv9009-zu11eg-revb-adrv2crr-fmc-revb-sync-fmcomms8-jesd204-fsm-multisom-primary.dts
arch/arm64/boot/dts/xilinx/zynqmp-adrv9009-zu11eg-revb-adrv2crr-fmc-revb-sync-fmcomms8-jesd204-fsm-multisom-secondary.dts

This fixes a few style issues and adds some additional documentation.
No functional changes.

arm64: dts: zynqmp-adrv9009-zu11eg: Multi-SoM Sync devicetree cleanup

---

drivers/iio/adc/navassa/adrv9002.c
drivers/iio/adc/navassa/adrv9002.h
drivers/iio/adc/navassa/adrv9002_conv.c

To properly test TX test mode, a proper pattern must be generated in the
hdl side otherwise the debug block on the part could never match the
received pattern and the status counters/flags would always be different
than 0. This will be also useful for TX loopback (when supported) since we
need to generate a pattern in the axi core in order to loop it back through the
part RX path so that we can check if we receive a valid signal.

iio: adrv9002: Fix TX test mode in debugfs

---

drivers/iio/adc/ad9081.c
drivers/iio/adc/adrv9009.c
drivers/jesd204/jesd204-core.c
include/linux/jesd204/jesd204.h

In the initial phase of the JESD204 framework work, it wasn't all that
clear where the number of JESD204 links would be specified, so the init
data passed to the framework contained the exact number of JESD204 links
that a topology should contain.
However, with the latest code, the number of "active" links is specified in
the device-tree. So, for this 'num_links' on the init-data we can
re-purpose it to be 'max_num_links' to make sure the DT doesn't go above
the number of JESD204 links that a device can support.

jesd204: adrv9009,ad9081: change semantic num_links -> max_num_links

---

Documentation/devicetree/bindings/iio/gyroscope/adi,adxrs290.yaml
drivers/iio/gyro/Kconfig
drivers/iio/gyro/adxrs290.c

First and foremost, insert a missing mutex initialization call in ADXRS290's probe.
Introduce devm_add_action_or_reset() hook for gracefully switching off the device
during resource unwinding.
Introduce DATA_RDY trigger for triggered buffer setup; this enables continuous
data capture. Additionally, add support for direct register access using the debugfs 
iio interface. 
The device-tree bindings documentation illustrates an example of using a GPIO irq
line to trigger a data capture.

iio: gyro: adxrs290: Fix mutex init bug, use devm hook, add triggered buffer & debugfs support

---

drivers/iio/adc/navassa/adrv9002_conv.c

The last condition to check for errors in the tuning function is wrong.
As it was, if all points of the last raw were invalid, the function
would return error even though there were valid points in another
rows...
Fixes: 17a27f3675b35 ("iio: Add ADRV9002 support")

iio: adrv9002: Fix digital tuning false negative

---

arch/arm/boot/dts/zynq-zed-adrv9002-rx2tx2.dts
arch/arm/boot/dts/zynq-zed-adrv9002.dts
arch/arm64/boot/dts/xilinx/zynqmp-zcu102-rev10-adrv9002-rx2tx2.dts
arch/arm64/boot/dts/xilinx/zynqmp-zcu102-rev10-adrv9002.dts

This is only needed for the zc706 platform as a prevention measure to VADJ
at 2.5V (needs to programmed to 1.8V). The gpio needs to be high in order
for the outputs in the FPGA to be enabled (alongside with a vadj check).
On both zed, and zcu102 this gpio is not used.

arch: dts: Remove the gpio hog on gpio52

---

drivers/iio/adc/adrv9009.c
drivers/jesd204/jesd204-core.c
include/linux/jesd204/jesd204.h

Changeset adds a helper to retrieve active number of links.
For ADR9009, we need to apply the hooks for the FSM paused stuff, based on the number of active links, not the max number of links.

jesd204,adrv9009: tweak the FSM paused hooks

---

drivers/nvmem/adi_axi_sysid.c

For the HDL projects that support multiple configurations (e.g., dac_fmc_ebz),
the System Custom String will reflect the actual configuration/supported part
(e.g., ad9172). Print this field when it is set.

nvmem: adi_axi_sysid: Print System Custom String

---

drivers/iio/jesd204/xilinx_transceiver.c

This patch changes back to the old formula for calculating the CPLL and
QPLL. On ZynqMP the lane rate was not calculated correctly and the device
would fail with an error.

iio: jesd204: xilinx_transceiver: Shift back the the old formula

---

arch/microblaze/boot/dts/kc705_fmcdaq2.dts

DAQ2 CPLL on microblaze KC705 was used out of spec. In order for the device
to be probed correctly VCO max frequency was defined in the device tree
since it was above the 3.3 GHz limit for GTX2.

arch: microblaze: boot: dts: Add CPLL VCO

---

arch/arm/boot/dts/zynq-zc706-adv7511-fmcdaq3-revC.dts

This is a work-around for the TX QPLL, to bump to limit from 10
giga-samples to 12.3 giga-samples.

arch: arm: zc706,daq3: add overclocked VCO limit for QPLL

---

arch/arm/boot/dts/overlays/Makefile
arch/arm/boot/dts/overlays/rpi-cn0504-overlay.dts

This adds support for the CN0504 ethernet hat board for Raspberry Pi.
For the overlay, this needs to setup the Microchip KSZ9477 switch, and
LTC2945 power monitor drivers to be available.

arch: arm: rpi-cn0504: add dt overlay for the board

---

arch/arm/boot/dts/zynq-coraz7s-cn0540.dts

In order to get a more stable spi clock, an axi_clkgen IP has been
added. This change updates the devicetree according to the hardware
changes.

arch: arm: boot: dts: cn0540: cora: Change spi_clk parent

---

arch/arm/boot/dts/zynq-zc706-adv7511-fmcjesdadc1.dts
arch/arm/boot/dts/zynq-zc706-adv7511-fmcomms11.dts
arch/arm/boot/dts/zynq-zed-adv7511-ad9364-fmcomms4.dts
arch/arm/boot/dts/zynq-zed-imageon.dts

This change adds license and project tags to fmcjesdadc1, fmcomms11, fmcomms4 and imageon device tree files.

arch: arm: dts: add license + project tags

---

arch/arm/boot/dts/zynq-zed-imageon.dts

This commit is changing hdl tag in zynq-zed-imageon.dts, from 'imageon' to 'imageon/zed'.

arch: arm: dts: zynq-zed-imageon.dts: fix a typo in hdl tag

---

arch/arm64/kernel/armv8_deprecated.c

These prints are filling the debug log, and are generated because we use a
rootfs compiled with armv6 from Raspberry Pi repositories. We don't have
control on what compiler is used to generate these binaries so the best
approach for now is to silence these warnings.
These instructions are no longer available for ARMv8 so they have to be
emulated to ensure that the rootfs won't crash.

arm64: kernel: armv8: Remove debug logs for deprecated instructions
