- drivers/staging/iio/impedance-analyzer/ad5933.c
Add ad5933 device tree support
> Add ad5933 device tree support

- drivers/clk/clk-altera-a10-fpll.c
In phase aligned mode the fPLL uses an external feedback path that allows
to better align the PLL output phase to the phase of the external reference
clock signal.
This allows for example to support reliable sampling of source synchronous
interfaces.
But when the PLL is configured for external feedback path mode the PLL
calibration can fail and choose the wrong VCO band. The latest Intel
transceiver datasheet contains the proper sequence to make calibration work
in phase aligned mode.
This involves writing to a otherwise undocumented register to select the
internal feedback path while running the calibration. Once the calibration
is done restore the original feedback path setting.
> clk: altera-a10-fpll: Fix calibration for phase aligned mode

- arch/microblaze/boot/dts/adi-daq3.dtsi
- arch/microblaze/boot/dts/kcu105_fmcdaq3.dts
> microblaze: dts: Add FMCDAQ3 support for KCU105

- Documentation/devicetree/bindings/iio/adc/adi,ad9361.txt
- arch/arm/boot/dts/zynq-sidekiqz2-revb.dts
1 typo and 2 device-tree updates (adjust frequency range + remove unreachable filter setting)
> Minor updates to filter-banks doc & device-tree

- drivers/iio/frequency/adf5355.c
This fixes a few issues reported here:
https://ez.analog.com/message/354172
> iio frequency adf5355 misc fixes

- drivers/iio/frequency/ad9508.c
A few small updates and fixes for the ad9508 driver.
> AD9508 fixes and updates

- Documentation/devicetree/bindings/iio/accel/adxl345.txt
- arch/arm/boot/dts/overlays/Makefile
- arch/arm/boot/dts/overlays/rpi-adxl375-overlay.dts
- drivers/iio/accel/Kconfig
- drivers/iio/accel/adxl345.h
- drivers/iio/accel/adxl345_core.c
- drivers/iio/accel/adxl345_i2c.c
- drivers/iio/accel/adxl345_spi.c
I just tested the ADXL375 with Lars's patch to see everything is in order and added an example dts/overlay for it.
> Iio adxl375 rpi

- drivers/iio/adc/ad9371.c
- drivers/iio/adc/ad9371.h
> iio: adc: ad9371: Mixed bag of compiler warning fixes

- drivers/spi/spi-axi-spi-engine.c
This patch adds the option to modify the word length depending on the
data transfer lengths required by the device. Using this option transfers
can have uncommon lengths (e.g. 12, 18, 20).
> axi_spi_engine: Add word length register command

- Documentation/devicetree/bindings/iio/adc/ad400x.txt
- MAINTAINERS
- arch/arm/boot/dts/zynq-zed-adv7511-ad4020.dts
- drivers/iio/adc/Kconfig
- drivers/iio/adc/Makefile
- drivers/iio/adc/ad400x.c
- drivers/spi/spi-axi-spi-engine.c
This is just a first iteration of the ad400x driver. There is still work to be done on it but I created the pull request a bit earlier to get some feedback on the overall driver and spi-engine pieces.
> Ad400x driver

- drivers/dma/dmatest.c
Patchset contains 3 small cleanups of the dmatest module.
> dmaengine: dmatest: minor cleanups of module

- drivers/staging/iio/adc/ad7192.c
- drivers/staging/iio/adc/ad7192.h
Add clock reference for ad7192.
> Add clock reference

- Documentation/devicetree/bindings/mux/adi,adgs1408.txt
- MAINTAINERS
- drivers/mux/Kconfig
- drivers/mux/Makefile
- drivers/mux/adgs1408.c
Align with upstream version of ADGS1408/1409 Mux.
> Adgs1408 align upstream

- drivers/iio/adc/ad9680.c
After recent ad9528 update to make the sysref rate runtime programmable.
This fixes a bug seen on DAQ3 where the ADC forces a incompatible sysref
rate.
> iio: adc: ad9680: maintain current sysref rate in case it's a fit

- README.md
A semi-popular request from EZ is that we describe our kernel, what our
master contains, how it's linked with Xilinx and other stuff.
> README.md: add our own readme that should be picked up by the Github markdown engine

- drivers/staging/iio/frequency/ad9834.c
- drivers/staging/iio/frequency/ad9834.h
> Ad9834 upstream

- drivers/staging/iio/frequency/ad9834.c
A small intermediate patch to use only standard types from iio framework.
> Ad9833 iio standard

- README.md
> README.md: reference wiki for building the kernel

- drivers/spi/spi-axi-spi-engine.c
This patch fixes the issue with transfer lengths being higher than 1. In
this case spi_engine_read_buff and spi_engine_write_buff were called
multiple times with the same buffer address and the spi engine was
sending/receiving always the same value. To solve this issue a buffer
address incrementation was added in the case of a transfer with a length
larger then 1.
Fixes: 30707b090c25 ("spi-axi-engine: Calculate buffer dimension for
xfer")
> spi: spi-axi-engine: Fix buffer address incrementation

- drivers/staging/iio/adc/ad7192.c
- drivers/staging/iio/adc/ad7192.h
This patch series is an effort to synq our master version of ad7192 with the upstream one. In the future more progress will be done in moving this out of staging and we should ensure we have minimum differences between this two versions. 
Some commits that are reverted here will be applied in a different form in the future. (ex. 58ed620c951da1391284c4e5953960ac3d050ae1)
> Ad7192 synq upstream

- drivers/input/keyboard/adp5589-keys.c
This patch implements the gpio_set_multiple interface for ADP558x chip.
> input: adp5589: Add gpio_set_multiple interface

- drivers/net/ethernet/xilinx/xilinx_axienet.h
- drivers/net/ethernet/xilinx/xilinx_axienet_main.c
The commit is cherry-picked from master.
> net: ethernet: xilinx: Revert ADI's fixes

- drivers/net/ethernet/xilinx/xilinx_emaclite.c
> net: xilinx: emaclite: implement minimal ethtool & ioctl (for phytool) support

- drivers/staging/iio/adc/ad7192.c
This patch removes the in_voltage-voltage_scale_available and
in_voltage_scale_available attributes. These are replaced with available
attributes added in info_mask_shared_by_type_available.
With this modification the iio core will be responsible with naming the
attributes thus removing the checkpatch warning related to
in_voltage-voltage_scale_available naming.
> staging: iio: adc: ad7192: Use read_avail for available attributes

- drivers/dma/dma-axi-dmac.c
The old device-tree binding was changed some time ago (~4 years). One
version of the binding went upstream, and another one was also supported
for a while in the ADI tree.
Commit f36c9b9b99128 ("dma: axi-dmac: Sync to upstream version") makes a
reference that this would be phased out over time.
That time has come.
i.e. it's been long enough since then to phase it out.
> dmaengine: axi-dmac: remove old device-tree bindings support

- arch/arm/boot/dts/zynq-zc706-adv7511-fmcomms11.dts
Signed-off-by: Istvan Csomortani <istvan.csomortani@analog.com>
> fmcomms11: Update AD9162 TPL address

- drivers/iio/adc/axi_pulse_capture.c
The same measure unit should be used for both writing and reading
operations - Hz for frequency and ns for pulse_width.
> iio: axi_pulse_capture: Fix the attributes reading

- arch/arm/boot/dts/zynq-zc706-adv7511-adrv9008-1.dts
- arch/arm/boot/dts/zynq-zc706-adv7511-adrv9008-2.dts
> arm: dts: Add device trees for ADRV9008-1 and ADRV9008-2 on ZC706

- Documentation/devicetree/bindings/iio/adc/adi,ad7124.txt
- drivers/iio/adc/Kconfig
- drivers/iio/adc/Makefile
- drivers/iio/adc/ad7124.c
Align with master branch for ad7124 driver. This is required for CN0508 project.
> Pick ad7124

- Documentation/devicetree/bindings/iio/frequency/adf4371.yaml
- drivers/iio/frequency/Kconfig
- drivers/iio/frequency/adf4371.c
These commits were cherry-picked from the master branch.
> Rpi 4.14.y adf4371 sync with master

- drivers/iio/frequency/adf4360.c
This is a prepatory step prior to migration of driver to Regmap API.
See task list in issue #418
> iio: frequency: adf4360: Minor refactor and clean up

- Documentation/devicetree/bindings/iio/adc/adi,ad7124.yaml
- arch/arm/boot/dts/overlays/Makefile
- arch/arm/boot/dts/overlays/rpi-cn0508-overlay.dts
- drivers/iio/adc/ad7124.c
For starters I would like just a general feedback for this PR. No need to merge this set just yet. 
Some commits refer only to the CN0508 application, while the last 3 commits modify the ad7124 driver and introduce a YAML dt-binding documentation. This part is intended to be upstreamed.
> Rpi cn0508

- Documentation/devicetree/bindings/iio/frequency/adf4360.txt
- drivers/iio/frequency/adf4360.c
> iio: frequency: adf4360: Make some hard coded options configurable via dt

- Documentation/ABI/testing/sysfs-bus-iio-frequency-adf4371
- drivers/iio/frequency/adf4371.c
This PR adds support for 3-wire and MUXOUT modes.
> Master adf4371 muxout

- Documentation/ABI/testing/sysfs-bus-iio-frequency-adf4371
- drivers/iio/frequency/adf4371.c
These two commits were cherry-picked from the master branch.
> Rpi 4.14.y muxout support

- drivers/iio/adc/ad9371.c
Add support for reading temperature of the chip with IIO.
This is related to issue described at https://ez.analog.com/wide-band-rf-transceivers/tes-gui-and-api-software-ad9371-ad9375/f/q-a/111543/ad9371-temperature-reading/
> iio: adc: ad9371: Add temperature support

- drivers/iio/frequency/adf4360.c
> iio: frequency: adf4360: Introduce IIO

- Documentation/devicetree/bindings/iio/frequency/adf4360.txt
- arch/arm/boot/dts/adi-ad9136-fmc-ebz.dtsi
- arch/arm/boot/dts/zynq-m2k-reva.dts
- arch/arm/boot/dts/zynq-zed-adv7511-m2k-revb.dts
- arch/arm/boot/dts/zynq-zed-adv7511-m2k-revc.dts
- drivers/iio/frequency/adf4360.c
> iio: frequency: adf4360: IIO support for PLL and REF frequency

- drivers/iio/adc/ad7606.c
- drivers/iio/adc/ad7606.h
- drivers/iio/adc/ad7606_spi.c
Sync modifications with rpi-4.14 branch.
> Ad7616 spi master

- drivers/iio/frequency/adf4360.c
> iio: frequency: adf4360: Refactor definitions pt 2

- drivers/iio/frequency/adf4360.c
> iio: frequency: adf4360: Complete def refactor and Enum Dev IDs

- drivers/iio/frequency/Kconfig
- drivers/iio/frequency/adf4360.c
> iio: frequency: adf4360: Add sysfs register access

- Documentation/devicetree/bindings/iio/frequency/adf4360.txt
- drivers/iio/frequency/adf4360.c
> iio: frequency: adf4360: Add muxout GPIO support

- drivers/iio/frequency/ad9162.c
> iio: ad9162: Fix coding style

- Documentation/devicetree/bindings/iio/frequency/ad916x.yaml
> dt-bindings: iio: frequency: Add ad916x documentation

- ci/travis/run-build.sh
The cherry-pick sync-ing method doesn't work reliably because it tries to
avoid merge commits by generating a list of commits and then checking which
is a merge commit and skipping that.
However that doesn't seem to work.
The best method is still to do `git cherry-pick` over a commit range.
That method will fail for a merge commit, and then it does a retry via
`git cherry-pick --continue` which should ignore the merge commit, and
apply the rest of the patches.
For most cases the cherry-picking should work on the first try.
> build: fix cherry-pick sync-ing

- drivers/iio/frequency/ad9162.c
The dac_clk is a mandatory clock and ad9162_get_clks() should return
error if this clock is not found. Since the other clocks are
optional, the function was ignoring -ENOENT errors. However, if the
dac_clk is missing, the error should not be ignored even though the
device probing fails in the setup phase. This patch reworks the clks
array so that, one can easily define which clocks are mandatory.
> iio: ad9162: Fix ad9162_get_clks

- drivers/iio/frequency/ad9162.c
This PR adds minor refactoring to the ad9162 driver
> Dev ad9162 refactor

- Documentation/devicetree/bindings/iio/frequency/adf4360.txt
- drivers/iio/frequency/adf4360.c
> iio: frequency: adf4360: Add regulator and IIO attr support

- drivers/iio/frequency/adf4360.c
> iio: frequency: adf4360: Add OF match support and update license info

- Documentation/devicetree/bindings/iio/frequency/adi,adf4360.yaml
- MAINTAINERS
- arch/arm/boot/dts/adi-ad9136-fmc-ebz.dtsi
- arch/arm/boot/dts/zynq-m2k-reva.dts
- arch/arm/boot/dts/zynq-zed-adv7511-m2k-revb.dts
- arch/arm/boot/dts/zynq-zed-adv7511-m2k-revc.dts
- drivers/iio/frequency/adf4360.c
> iio: frequency: adf4360: Convert DT CPI property to micro amps

- arch/arm/boot/dts/adi-ad9467-fmc-250ebz.dtsi
Fixes: ece5ef9fd219b (dts: Specify AD9517 firmware file)
> arm: dts: Fix duplicate firmware property

- drivers/iio/logic/m2k-logic-analyzer.c
- drivers/iio/logic/m2k-trigger-ad.c
Cherry pick of M2K cascading trigger implementation from master.
Signed-off-by: Bogdan Togorean bogdan.togorean@analog.com
> M2k cascading trigger

- drivers/iio/frequency/m2k-dac.c
Cherry pick of dma_sync_start attribute patch from m2k.
> iio: frequency: m2k-dac: Add attribute to control dma_sync_start

- Documentation/devicetree/bindings/iio/frequency/adf4371.yaml
- drivers/iio/frequency/adf4371.c
In response to issue: https://github.com/analogdevicesinc/linux/issues/507
> Master adf4371 missing features

- drivers/iio/frequency/ad9172.c
This patch adds support for logic lanes configurations by specifying the
new physical lane mapping.
Note: taken from `altera_4.14` branch; seems this was forgotten.
> iio: frequency: ad9172: Add support for logic lane configuration

- Documentation/hwmon/ltc2947
- MAINTAINERS
> doc: hwmon: Add ltc2947 driver

- arch/arm/boot/dts/socfpga_arria10_socdk_adrv9371.dts
More details:
- https://www.analog.com/en/design-center/evaluation-hardware-and-software/evaluation-boards-kits/eval-adrv9371.html
- https://www.intel.com/content/www/us/en/programmable/products/boards_and_kits/dev-kits/altera/arria-10-soc-development-kit.html
> a10soc_adrv9371

- drivers/iio/adc/ad7292.c
Add a channel for configuring the ADC sequence register.
Change interal spi buffer to 4 byte size for being able issue 4 byte
write commands.
Add a spi_reg_write function to on AD7292 internal registers.
Add a new case to read_raw to allow reading from ADC sequence register.
Refactor spi_reg_read functions to work properly with the new spi buffer
size.
Signed-off-by: Marcelo Schmitt <marcelo.schmitt1@gmail.com>
> iio: adc: ad7292: add support for reading single conversion results

- .travis.yml
- arch/arm/boot/dts/adi-ad9265-fmc-125ebz.dtsi
- arch/arm/boot/dts/adi-ad9434-fmc-500ebz.dtsi
- arch/arm/boot/dts/adi-fmcomms6.dtsi
- arch/arm/boot/dts/zynq-zed-adv7511-pmod-ad1-da1.dts
- arch/arm64/boot/dts/xilinx/zynqmp-adrv9009-zu11eg-revb-adrv2crr-fmc-sync.dts
- arch/arm64/boot/dts/xilinx/zynqmp-adrv9009-zu11eg-revb-adrv2crr-fmc.dts
- arch/arm64/boot/dts/xilinx/zynqmp-adrv9009-zu11eg-revb.dtsi
- arch/microblaze/boot/dts/adi-ad9467-fmc-250ebz.dtsi
- ci/travis/run-build.sh
> [2019_R1] arch: arm{64}: fix broken device-trees & dtb_build

- arch/arm/boot/dts/zynq-zc706-adv7511-adrv9009.dts
- arch/arm/boot/dts/zynq-zc706-adv7511-adrv9371.dts
- arch/arm64/boot/dts/xilinx/zynqmp-zcu102-rev10-adrv9008-1.dts
- arch/arm64/boot/dts/xilinx/zynqmp-zcu102-rev10-adrv9008-2.dts
- arch/arm64/boot/dts/xilinx/zynqmp-zcu102-rev10-adrv9009.dts
- arch/arm64/boot/dts/xilinx/zynqmp-zcu102-rev10-adrv9371.dts
- arch/microblaze/boot/dts/kcu105_adrv9371x.dts
> Add dt decimation interpolation

- drivers/iio/jesd204/axi_adxcvr.c
This change does some whitespace fixup.
No functionality change.
> iio: jesd204: adxcvr: whitespace fixup

- Documentation/devicetree/bindings/iio/imu/adi,adis16475.yaml
- drivers/iio/imu/adis16475.c
Supported devices:
- adis16470;
- adis16465-1;
- adis16465-2;
- adis16465-3;
- adis16467-1;
- adis16467-1;
- adis16467-1.
> Support new devices

- drivers/input/keyboard/adp5589-keys.c
The driver has diverged a bit [not too much] from upstream.
This change syncs it. However, it also needs a bit of adjustment, as that would break other functionalities. The 2 patches (aside from the sync upstream one) have been sent upstream.
> input: adp5589: sync with upstream & cleanup the driver

- arch/arm/boot/dts/overlays/Makefile
- arch/arm/boot/dts/overlays/rpi-ad7124-overlay.dts
> arch: arm: boot: dts: Add ad7124 dt overlay

- drivers/iio/accel/adis16201.c
- drivers/iio/accel/adis16209.c
> Fix rpi 4.19.y build

- arch/arm/boot/dts/socfpga_arria10_socdk_fmcomms2.dts
> arch: arm: boot: dts: Add support for fmcomms2 on Arria10SoC

- arch/arm/boot/dts/zynq-zc706-adv7511-adrv9009.dts
- arch/arm/boot/dts/zynq-zc706-adv7511-adrv9371.dts
- arch/arm64/boot/dts/xilinx/zynqmp-zcu102-rev10-adrv9008-1.dts
- arch/arm64/boot/dts/xilinx/zynqmp-zcu102-rev10-adrv9008-2.dts
- arch/arm64/boot/dts/xilinx/zynqmp-zcu102-rev10-adrv9009.dts
- arch/arm64/boot/dts/xilinx/zynqmp-zcu102-rev10-adrv9371.dts
- arch/microblaze/boot/dts/kcu105_adrv9371x.dts
> Fix interp decim

- drivers/gpu/drm/adi_axi_hdmi/axi_hdmi_crtc.c
- drivers/gpu/drm/adi_axi_hdmi/axi_hdmi_drv.c
- drivers/gpu/drm/adi_axi_hdmi/axi_hdmi_encoder.c
- drivers/media/platform/axi-hdmi-rx.c
- drivers/media/platform/imageon-bridge.c
This changeset is a grouping of some changes required for our DRM & Media drivers.
> media,drm: update drivers to new DRM & media upstream changes

- drivers/iio/imu/adis16480.c
upstreamed a while ago here:
https://patchwork.kernel.org/project/linux-iio/list/?series=196649
> adis-backports: address some checkpatch complaints

- Documentation/devicetree/bindings/iio/frequency/adf4371.yaml
- drivers/iio/frequency/adf4371.c
Some fixes and enhancements...
> ADF4371 fixes

- drivers/iio/jesd204/axi_jesd204_rx.c
> iio: jesd204: axi_jesd204_rx: Add support for up to 16 lanes

- arch/arm/boot/dts/adi-fmclidar1.dtsi
- arch/arm/boot/dts/zynq-zc706-adv7511-fmclidar1.dts
According to https://github.com/analogdevicesinc/hdl/commit/03bec4b49c1da41d8f49af54f23e9d03d7b318f5.
> arm: dts: adi-fmclidar1: Interchange SYSREF and DEV_CLK

- drivers/net/phy/adin-compat.h
This PHY layer was adjusted to build on 4.19, but wasn't tested until now.
The driver does seem to work, but phylib complains with a
warning-stack-trace that some calls to __mdiobus_{read,write} aren't locked
(and should be).
This happens in the phy_modify_mmd_changed() function, because the compat
layer re-implements it. When the kernel will be upgraded to 5.3+, this will
go away, so we just need to adjust our compat layer until then.
The compat layer was added to minimalize the code between the ADIN upstream
version and the ADI version.
> net: phy: adin: adjust compat layer to 4.19

- Documentation/devicetree/bindings/iio/frequency/adi,ltc6952.yaml
- MAINTAINERS
Add documentation and Maintainers entry.
> Ltc6952 iio

- drivers/iio/buffer/industrialio-buffer-dma.c
- drivers/iio/iio_core.h
- drivers/iio/industrialio-buffer.c
- drivers/iio/industrialio-core.c
These 2 patches sync the IIO core code with upstream's.
Resolved via discussions:
https://patchwork.kernel.org/patch/11284717/
https://patchwork.kernel.org/patch/11285301/
>  iio: sync bits with upstream

- drivers/iio/adc/ad_sigma_delta.c
ADCs from Sigma-Delta family using ad_sigma_delta layer send
samples via the serial line in Big-Endian. When the data register
is only 3 bytes ad_sigma_delta stores the samples on 4 bytes thus
the first byte is the most significant and needs to be clear.
In ad_sd_prepare_transfer_msg we see that the start address of the
receiving buffer rx is incremented by 1. The sigma_delta->buf_data
will look after a reading of 3 bytes (one sample of an 24 bit res ADC)
like this:
MSB [00 XX  XX XX] LSB
This patch fixes a bug in ad_sd_trigger_handler where the same
address incrementation did not happen. The next sample would have
been written at the beginning of the buffer yielding wrong values after
the conversion from BE to LE.
> iio: ad_sigma_delta: Fix continuous mode

- .travis.yml
- ci/travis/run-build.sh
Same PR as #811 but for 2019_R1.
> [2019_R1] ci,travis: allow failures for checkpatch & sync-branches 

- drivers/iio/buffer/Kconfig
- drivers/iio/buffer/Makefile
- drivers/iio/buffer/industrialio-hw-consumer.c
- include/linux/iio/hw-consumer.h
These commits were cherry-picked from master.
> Add hardware consumer buffer support on altera_4.14

- Documentation/devicetree/bindings/iio/amplifiers/ad916x-amp.yaml
- Documentation/devicetree/bindings/iio/frequency/ad916x.yaml
- drivers/iio/amplifiers/Kconfig
- drivers/iio/amplifiers/Makefile
- drivers/iio/amplifiers/ad916x_amp.c
- drivers/iio/frequency/ad9162.c
- drivers/iio/frequency/ad916x/ad916x_nco_api.c
- drivers/iio/frequency/ad916x/ad916x_reg.h
The ad9166 was already released so that, we can bring these patches from bitbucket...
> Add ad9166 support

- arch/arm/boot/dts/zynq-pluto-sdr-revc.dts
- drivers/spi/spi-xilinx.c
- drivers/spi/spidev.c
This PR contains the set of commits intended for Pluto Rev. C.
> Pluto rev c master

- drivers/iio/dac/ad5766.c
add reading and writing for DAC ad5766
Signed-off-by: Denis Gheorghescu denis.gheorghescu@analog.com
> iio: dac: ad5766: add reading and writing

- Documentation/devicetree/bindings/iio/jesd204/adi,jesd204-rx.txt
- Documentation/devicetree/bindings/iio/jesd204/adi,jesd204-tx.txt
- drivers/iio/jesd204/axi_jesd204.h
- drivers/iio/jesd204/axi_jesd204_rx.c
- drivers/iio/jesd204/axi_jesd204_tx.c
This PR adds support for JESD204C.
> jesd204c support

- drivers/iio/adc/axi_pulse_capture.c
IRQs must be cleared through ADI_REG_IRQ_PENDING.
During the board power ON, some false IRQs seem to be detected, so in
case ADI_REG_DRIVER_OTW reports no temperature issue, clear them.
Otherwise, clear only ADI_IRQ_SRC_OTW_EXIT, so ADI_IRQ_SRC_OTW_ENTER
will be correctly treated.
> iio: adc: axi_pulse_capture: Fix IRQs clearing

- sound/soc/codecs/adau7002.c
> asoc: adau7002: Sync with upstream

- drivers/iio/dac/ad5766.c
add support for channels for AD5766/5767
Signed-off-by: Denis Gheorghescu <denis.gheorghescu@analog.com>
> iio: dac: ad5766: add channels support

- drivers/iio/dac/ad5766.c
Add support for scale/offset for AD5766/5767.
Note: `_ad5766_get_span_range()` is more of a dummy, it will be implemented
properly when I will add support for span range selection.
Signed-off-by: Denis Gheorghescu <denis.gheorghescu@analog.com>
> iio: dac: ad5766: add scale/offset support

- drivers/iio/adc/ad_sigma_delta.c
Added an assert which will fail when the calculated
data register size will yield more than 4 bytes.
Setting the size more than that will cause
the triggered handler to write to unallocated memory.
> iio: adc: ad_sgima_delta: add size assert

- drivers/iio/adc/ad_adc.c
Add possibility to store calibration bias value inside the driver.
AD5625 raw is used for both voffset and calibrationbias.
When initializing a client software it is impossible to get calibration
bias because the value in ad5625 raw might contain the added value of
voffset and calibrationbias. The client software will handle writing
the calibbias when calibration takes place.
This value is not propagated to hardware and is used only by client SW.
> iio: ad_adc: Add calibbias storage inside driver

- arch/arm/boot/dts/overlays/Makefile
- arch/arm/boot/dts/overlays/rpi-cn0511-overlay.dts
Somehow this overlay was forgotten in the private repos...
> arm: dts: overlays: Add cn0511 overlay

- arch/arm/boot/dts/socfpga_arria10_socdk_fmclidar1.dts
According to the latest HDL changes:
https://github.com/analogdevicesinc/hdl/commit/62704f53c083660402b76de85a47602792f41b7b
> arm: dts: adi-fmclidar1: Update i2c_afe_dac interface

- drivers/iio/frequency/cf_axi_dds.c
This cleans up the code-paths a bit.
> iio: axi-dds: use devm_iio_device_alloc()

- drivers/iio/adc/adrv9009.c
Enabling the clock twice makes the system thinks that the clock
has two active consumers, any rate change not being possible.
> iio: adc: adrv9009: Unprepare CLK_SET_RATE_GATE clocks before adjusting

- Documentation/devicetree/bindings/iio/adc/adi,adar1000.yaml
- MAINTAINERS
- drivers/iio/Kconfig.adi
- drivers/iio/adc/Kconfig
- drivers/iio/adc/Makefile
- drivers/iio/adc/adar1000.c
This is a first version of the ADAR1000 Linux driver.
It has basic functionality and features like gain and phase configurations.
> Adar1000 iio

- drivers/spi/spi-axi-spi-engine.c
Try to access register only after clocks are initialized. If not defer probing.
> Fix clk initialization order in spi-axi-spi-engine

- drivers/iio/jesd204/xilinx_transceiver.c
Whenever I'm reading the computations for CPLL & QPLL my head hurts.
>  iio: jesd204: xilinx_transceiver: cleanup CPLL & QPLL formulae a bit

- drivers/jesd204/jesd204-core.c
- drivers/jesd204/jesd204-fsm.c
- drivers/jesd204/jesd204-priv.h
- include/linux/jesd204/jesd204.h
> jesd204: rework FSM to keep states per each JESD204 link

- drivers/hwmon/pmbus/adm1266.c
Add unique names to GPIO/PDIO pins of adm1266 devices
based on the i2c address of the providing chip.
> hwmon: pmbus: adm1266: Avoid GPIO name collisions

- drivers/jesd204/jesd204-core.c
- include/linux/jesd204/jesd204.h
Some of these utils will be needed in the framework and re-used in drivers.
> jesd204: add some spec definitions and rate computation utils

- drivers/iio/dac/ad5766.c
- Add software and hardware reset functions
- Add span support
> Ad5766 span pr

- drivers/iio/adc/adar1000.c
There are 2 related issues that are highlighted in these scenarious:
1. a) When a read is performed on an ADAR1000 where the HWADDR used matches
the HWADDR of the ADAR1000, the device responds correctly on the designated
output line.
b) When a read is performed on an ADAR1000 where the HWADDR does not match
the HWADDR of the ADAR1000, but the CSB line is shared, the device will
output all zeros on the designated output line. This is fixed by setting
all non-addressed ADAR1000s to the opposite output style (3-wire vs.
4-wire).
2. a) When an ADAR1000 with HWADDR 0b00 is written to register 0x0000, the
resulting behaviour acts as though a "broadcast all: write was made.
Therefore, any device on the CSB line will now have register 0x0000
overwritten. This is fixed by making the write and then …
> iio: adc: adar1000: Fix multiple device communication

- drivers/iio/adc/ad9081.c
- drivers/iio/adc/ad9081/adi_ad9081.h
- drivers/iio/adc/ad9081/adi_ad9081_adc.c
- drivers/iio/adc/ad9081/adi_ad9081_bf_ad9081.h
- drivers/iio/adc/ad9081/adi_ad9081_bf_impala_tc.h
- drivers/iio/adc/ad9081/adi_ad9081_bf_jrxa_des.h
- drivers/iio/adc/ad9081/adi_ad9081_bf_jtx_dual_link.h
- drivers/iio/adc/ad9081/adi_ad9081_bf_jtx_qbf_ad9081.h
- drivers/iio/adc/ad9081/adi_ad9081_bf_lcpll_28nm.h
- drivers/iio/adc/ad9081/adi_ad9081_bf_main.h
- drivers/iio/adc/ad9081/adi_ad9081_bf_nb_coarse_nco.h
- drivers/iio/adc/ad9081/adi_ad9081_bf_nb_ddc_dformat.h
- drivers/iio/adc/ad9081/adi_ad9081_bf_nb_fine_nco.h
- drivers/iio/adc/ad9081/adi_ad9081_bf_rx_paging.h
- drivers/iio/adc/ad9081/adi_ad9081_bf_ser_phy.h
- drivers/iio/adc/ad9081/adi_ad9081_bf_spi_only_up.h
- drivers/iio/adc/ad9081/adi_ad9081_config.h
- drivers/iio/adc/ad9081/adi_ad9081_dac.c
- drivers/iio/adc/ad9081/adi_ad9081_device.c
- drivers/iio/adc/ad9081/adi_ad9081_hal.c
- drivers/iio/adc/ad9081/adi_ad9081_hal.h
- drivers/iio/adc/ad9081/adi_ad9081_jesd.c
- drivers/iio/adc/ad9081/adi_cms_api_common.h
- drivers/iio/adc/ad9081/adi_cms_api_config.h
> iio: adc: ad9081: Update to API Version 1.0.4

- drivers/jesd204/jesd204-core.c
- drivers/jesd204/jesd204-fsm.c
- drivers/jesd204/jesd204-priv.h
* removing global lock
* removing explicit parent ref
* removing explicit kref
* allocate device ID on topology init
> jesd204: framework updates

- drivers/jesd204/jesd204-fsm.c
The state machine is a bit quirky in itself.
This is another patchset to try to simplify the propagation flow of the callbacks over a topology of devices.
> jesd204: framework cleanups

- drivers/iio/adc/ad9081.c
> iio: adc: ad9081: Add support for AD9082

- drivers/iio/frequency/hmc7044.c
HMC7044 is a dual loop, high performance jitter cleaning clock part with
14 high performance outputs. Second PLL of HMC7044 has two overlapping
internal VCOs to cover 2.4 GHz – 3.2 GHz frequency range with overlapping
32 capacitor banks for each VCO core.
VCO core selection is manual and low core should be selected for
VCO frequencies 2.4 GHz-2.8 GHz, high core should be selected for
2.8 GHz – 3.2 GHz. Once the OSCIN clock is provided and N2, R2 values
are set, device waits for Restart command to start calibration and
selects the correct capacitor bank for related frequency. For most of
the applications, automatic capacitor bank selection works perfect.
However, in some applications which require consistent phase relation
between multiple parallel working parts, selected capacitor bank …
> iio: frequency: hmc7044: Support for manual cap bank selection

- drivers/iio/frequency/ad9523.c
The driver pretty much uses device managed functions. The only left-over is
the iio_device_register() function, which also requires an action-or-reset
hook to disable the regulator on remove or error path.
> iio: frequency: ad9523: convert to device managed functions

- drivers/jesd204/jesd204-core.c
- drivers/jesd204/jesd204-fsm.c
> jesd204: one bugfix & some debugging enhancements

- drivers/jesd204/jesd204-core.c
- drivers/jesd204/jesd204-fsm.c
- include/linux/jesd204/jesd204.h
> jesd204: random bits picked from the work branch that can go into master

- drivers/iio/adc/talise/linux_hal.c
> iio: adc: talise: linux_hal: ADIHAL_resetHw() Reduce verbosity

- drivers/iio/jesd204/axi_jesd204_tx.c
Add base logic to operate within the JESD204 framework.
> iio: axi_jesd204_tx: register with the JESD204 framework

- drivers/iio/adc/adrv9009.c
> iio: adc: adrv9009: Fix N & CS JESD, and profile loading in multi-device setups

- arch/microblaze/boot/dts/vcu118_quad_ad9081_204c_txmode_10_rxmode_11.dts
> dts: vcu118_quad_ad9081_204c_txmode_10_rxmode_11: Fix indentation

- arch/arm64/boot/dts/xilinx/zynqmp-zcu102-rev10-adrv9008-2-jesd204-fsm.dts
> dts: zynqmp-zcu102-rev10-adrv9008-2-jesd204-fsm: Add jesd204-fsm variant

- arch/arm64/boot/dts/xilinx/zynqmp-zcu102-rev10-adrv9009-fmcomms8-jesd204-fsm.dts
- arch/arm64/boot/dts/xilinx/zynqmp-zcu102-rev10-adrv9009-fmcomms8.dts
> dts: zynqmp-zcu102-rev10-adrv9009-fmcomms8: Fix HMC7044 reference sources

- drivers/iio/adc/ad9467.c
Signed-off-by: Alexandru Ardelean <alexandru.ardelean@analog.com
> iio: adc: ad9467: rework clock init & gpio init(part 2)

- drivers/jesd204/jesd204-fsm.c
The per-device (vs per-link) calling of callbacks is useful for other cases
than the table of states.
Bu default, the propagation of callbacks would propagate multiple times for
a device. It would be the number of JESD204 links that the device supports
in the topology.
But for some cases, it will be useful to call a callback only once per
device regardless of the number of links.
> jesd204: fsm: move per-device/per-link logic deeper in FSM

- drivers/iio/adc/ad7768-1.c
Add reset gpio to avoid random reset during probe
Update spi read function to separate the reg value from the return code
Update spi functions to prepare the driver for spi engine
> iio: adc: ad7768-1

- drivers/jesd204/jesd204-fsm.c
This is noticed when running a state callback for the top-level device in
the PER_DEVICE mode. When that happens all callbacks are called in
PER_DEVICE mode, and if they don't have a callback for PER_DEVICE mode,
they won't get called.
The move in commit 2a665801f1cb9 ("jesd204: fsm: move per-device/per-link
logic deeper in FSM") was done to make the core FSM a bit more flexible, to
be able to run a completion/finished callback at the end of the transition.
However for the state-table, we need to make sure that each JESD device can
run PER_DEVICE or PER_LINK, depending how it's configured in each driver.
That also means we should run the table of states in PER_LINK mode, so that
each jdev object can decide (in it's callback) whether to run PER_DEVICE or
PER_LINK.
Fixes: 2a665801f1cb9 …
> jesd204: fsm: fix per-device logic

- Documentation/devicetree/bindings/hwmon/adi,adm1266.yaml
- Documentation/hwmon/adm1266.rst
- drivers/hwmon/pmbus/adm1266.c
> hwmon: pmbus: adm1266: sync with upstream

- drivers/iio/adc/adar1000.c
To write a beam position the chip select has to be held low for all 3
bytes. This patch fixes this with the use or regmap_multi_reg_write.
Fixes: eddfca513c93 ("iio: adc: adar1000: Add beam position RAM feature")
> iio: adc: adar1000: Fix save beam

- drivers/iio/adc/ad9081/adi_ad9081.h
- drivers/iio/adc/ad9081/adi_ad9081_adc.c
- drivers/iio/adc/ad9081/adi_ad9081_config.h
- drivers/iio/adc/ad9081/adi_ad9081_dac.c
- drivers/iio/adc/ad9081/adi_ad9081_device.c
- drivers/iio/adc/ad9081/adi_ad9081_hal.c
- drivers/iio/adc/ad9081/adi_ad9081_hal.h
- drivers/iio/adc/ad9081/adi_ad9081_jesd.c
> iio: adc: ad9081: update API to version 1.0.5

- arch/arm64/boot/dts/xilinx/adi-ad9081-fmc-ebz.dtsi
- arch/arm64/boot/dts/xilinx/zynqmp-zcu102-rev10-ad9081.dts
- arch/microblaze/boot/dts/adi-ad9081-fmc-ebz.dtsi
- arch/microblaze/boot/dts/vcu118_ad9081.dts
- arch/microblaze/boot/dts/vcu118_ad9081_m8_l4.dts
- arch/microblaze/boot/dts/vcu118_quad_ad9081.dtsi
- arch/microblaze/boot/dts/vcu118_quad_ad9081_204b_txmode_9_rxmode_10.dts
- arch/microblaze/boot/dts/vcu118_quad_ad9081_204c_txmode_10_rxmode_11.dts
- arch/microblaze/boot/dts/vcu118_quad_ad9081_204c_txmode_11_rxmode_4.dts
- arch/microblaze/boot/dts/vcu118_quad_ad9081_204c_txmode_11_rxmode_4_direct_6g.dts
- include/dt-bindings/iio/adc/adi,ad9081.h
> arch: dt-bindings: ad9081: update project headers and add JESD204 FSM definitions

- drivers/iio/adc/navassa/devices/adrv9001/public/src/adi_adrv9001_radio.c
Considering the following states:
RX1: rf_enabled
RX2: primed
TX1: primed
TX2: rf_enabled
In the previous state everything works as expected and the data is
captured ai RX1. However moving TX1 to calibrated and then back to primed,
the signal in RX1 is lost as if the RX1 path was powered down. This seems
only to affect ports on the same channel meaning that if TX2 is moved to
calibrated and then back to primed or rf_enabled everything works as
expected.
This is a temporary workaround. The real fix must be done in the ARM
firmware.
> adrv9002: api: Fix bug when changing ensm

- arch/microblaze/boot/dts/vcu118_quad_ad9081_204c_txmode_10_rxmode_11.dts
- arch/microblaze/boot/dts/vcu118_quad_ad9081_204c_txmode_11_rxmode_4.dts
- arch/microblaze/boot/dts/vcu118_quad_ad9081_204c_txmode_11_rxmode_4_direct_6g.dts
> dts: vcu118_quad_ad9081_204c_*.dts: minor fixes

- drivers/iio/adc/cf_axi_adc_core.c
> iio: adc: cf_axi_adc_core: Support for JESD204-FSM link device

- drivers/iio/adc/ad9081.c
> iio: adc: ad9081: convert to the JESD204 framework

- arch/arm64/boot/dts/xilinx/zynqmp-zcu102-rev10-ad9081-m8-l4-jesd204-fsm.dts
- arch/microblaze/boot/dts/vcu118_ad9081_jesd204_fsm.dts
- arch/microblaze/boot/dts/vcu118_ad9081_m8_l4_jesd204_fsm.dts
- arch/microblaze/boot/dts/vcu118_quad_ad9081_204b_txmode_9_rxmode_10_jesd204_fsm.dts
- arch/microblaze/boot/dts/vcu118_quad_ad9081_204c_txmode_10_rxmode_11_jesd204_fsm.dts
- arch/microblaze/boot/dts/vcu118_quad_ad9081_204c_txmode_11_rxmode_4_jesd204_fsm.dts
> dts: vcu118_quad_ad9081_204*.dts: add jesd204-fsm variants

- arch/microblaze/boot/dts/vcu118_quad_ad9081.dtsi
> dts: vcu118_quad_ad9081.dtsi: various updates

- drivers/iio/logic/m2k-trigger-ad.c
Trigger hold off add the possibility to ingnore all the trigger
events during a period specified using the holdoff attribute.
The raw value from attribute times 10ns represent the actual holdoff
period.
> iio: logic: m2k-trigger-ad: Add trigger holdoff support

- arch/arm/boot/dts/overlays/rpi-cn0511-overlay.dts
Most of the changes are from @kister-jimenez linux fork.
>  Fixes needed by the CN0511 revB

- arch/arm/boot/dts/socfpga_arria10_socdk_adrv9009.dts
- arch/arm/boot/dts/socfpga_arria10_socdk_adrv9009_jesd204_fsm.dts
- drivers/iio/jesd204/altera_adxcvr.c
- Update the dts according to the latest HDL master branch changes;
- Add the JESD204 FSM version.
> arria10_adrv9009 updates

- drivers/iio/adc/adar1000.c
The detectors make more sense to be paired with the TX channels. Also we do
not have duplicated input channels for the ADC raw values and detector
enable property.
> iio: adc: adar1000: Move detector logic to TX channels

- drivers/iio/frequency/ad9162.c
When a probe_standalone function was created. This attribute was not added.
> Cn0511: Add Fir85_enable attribute when using standalone probe

- drivers/iio/adc/navassa/adrv9002.c
If there's something that fails during a
`for_each_available_child_of_node`, we need to manual decrement the node
refcount sot it can be, potentially, freed.
> iio: adrv9002: Fix of child node refcount

- arch/arm/boot/dts/zynq-zed-adrv9002.dts
According to the actual compatible carrier.
> arm: dts: zed-adrv9002: Update hdl_project information

- .github/workflows/build.yml
This change adds a yaml file to build all ADI kernel images.
> .github/actions: add initial yaml file to build ADI kernels

- .github/workflows/sync_branches_with_main.yml
- ci/travis/run-build.sh
Running this job on Github actions requires a bit more tweaking.
Testing this job is also a bit difficult, as it only runs on the main branches.
> .github/workflows/sync_branches_with_main.yml: fix & tweak auto-sync job

- drivers/iio/amplifiers/ad916x_amp.c
I'm waiting for feedback to see if it was the right way to do it.
> cn0511 create iio interface for api functions

- drivers/iio/frequency/ad9517.c
Various cleanups to the driver to bring it closer to the form of the upstreamed version.
> iio: ad9517: misc cleanups (part 1)

- drivers/iio/logic/m2k-trigger-ad.c
iio_device_unregister() should not be called in the remove hook, since
devm_iio_device_register() is used.
Also, since remove this, might as well move the clock disable on a
devm_add_action_or_reset() handler.
> iio: adc: m2k-trigger-adc: fix/cleanup probe & remove

- arch/arm64/boot/dts/xilinx/zynqmp-zcu102-rev10-stingray.dts
> arch: arm64: dts: stingray: Add PWR_UP_DOWN gpio control

- drivers/iio/adc/ad9081.c
API Version 1.0.6, disables VIF mode and uses 0Hz IF mode in case the
initial IF shift is zero. This is not desired, add dt attribute to
control the default behavior, and restore after the API setup call.
> iio: adc: ad9081: Restore default variable IF mode (VIF)

- drivers/iio/frequency/ad9517.c
Misc cleanups done to the driver while preparing it for upstream.
> iio: ad9517: misc cleanups

- drivers/iio/frequency/ad9144.c
In JESD204B subclass 0, the sysref clock is optional. This is handled
properly in the rest of the code, but make sure not to fail early in the
probe when the sysref clock isn't defined.
Signed-off-by: Liam Beguin <lvb@xiphos.com>
> iio: ad9144: make the sysref clock optional

- drivers/iio/adc/navassa/adrv9002.c
- drivers/iio/adc/navassa/devices/adrv9001/public/src/adi_adrv9001_auxdac.c
> adrv9002 aux converters

- azure-pipelines-rpi.yml
- azure-pipelines.yml
These would probably be interesting later for some build statistics, if we
ever get interested in these.
> ci,azure-pipelines: name the important build jobs

- drivers/iio/adc/adrv9009.c
- drivers/jesd204/jesd204-fsm.c
> jesd204: fsm: fix inbalance in rollback

- ci/travis/run-build-docker.sh
- drivers/jesd204/jesd204-fsm.c
> [2019_R2] jesd204: backport fixes from master

- drivers/iio/frequency/hmc7044.c
In the previous implementation, by multiplying r1 and n1 by 2
instead of incrementing one and recalculating the other,
many possible pfd1 values were omitted.
> iio: frequency: hmc7044: Improve the pfd1 calculation

- arch/arm/boot/dts/socfpga_arria10_socdk_ad9081.dts
> arm: dts: Add AD9081-FMC-EBZ + Arria 10 SoC Development Kit support

- drivers/iio/adc/navassa/adrv9002.h
- drivers/iio/adc/navassa/adrv9002_conv.c
Remove functions with no users...
> iio: adrv9002: remove unused API's

- Documentation/ABI/testing/sysfs-bus-iio-dac-ad5766
- Documentation/devicetree/bindings/iio/dac/adi,ad5766.yaml
- drivers/iio/dac/ad5766.c
Synchronize with upstream version
> Ad5766 dev

- drivers/iio/adc/navassa/adrv9002.c
With the 0.14 SDK, the API to get the device IRQ status register is fixed.
Hence, we can use that to properly log/handle the incoming interrupts.
> iio: adrv9002: fix irq handling

- drivers/iio/adc/navassa/Makefile
iio: adrv9002: add full path for include directories
iio: adrv9002: remove B0 define
> adrv9002 out of tree builds

- drivers/iio/jesd204/axi_adxcvr.c
> iio: jesd204: axi_adxcvr: Fix log level in probe defer information

- arch/arm/boot/dts/adi-adrv9002.dtsi
- arch/arm64/boot/dts/xilinx/adi-adrv9002.dtsi
- drivers/iio/adc/navassa/adrv9002.c
- drivers/iio/adc/navassa/adrv9002.h
- drivers/iio/adc/navassa/adrv9002_debugfs.c
arch: dts: adrv9002: add orx support
iio: adrv9002: support Orx
> ORx support

- drivers/iio/dac/ad5686.c
When pwm was removed from probe in this commit
https://github.com/analogdevicesinc/linux/commit/083b2fdc9d0bf97b5f61355c2fec1572fde6daec
other references to the pwm where not checked and
when trying to access them a segmentation fault
occurs.
> drivers:iio:dac:ad5686: Fix segmentation fault

- arch/microblaze/boot/dts/adi-ad9081-fmc-ebz.dtsi
- arch/microblaze/boot/dts/vcu118_ad9081.dts
- arch/microblaze/boot/dts/vcu118_ad9081_m8_l4.dts
- drivers/iio/frequency/ad9528.c
- drivers/iio/frequency/hmc7044.c
Miscellaneous bag of fixes and updates related to AD9081
> Ad9081 dev 2019 r2

- arch/microblaze/boot/dts/adi-ad9081-fmc-ebz.dtsi
- arch/microblaze/boot/dts/vcu118_ad9081.dts
- arch/microblaze/boot/dts/vcu118_ad9081_204c_txmode_10_rxmode_11.dts
- arch/microblaze/boot/dts/vcu118_ad9081_204c_txmode_23_rxmode_25.dts
- arch/microblaze/boot/dts/vcu118_ad9081_m8_l4.dts
- drivers/iio/adc/ad9081.c
- drivers/iio/frequency/ad9528.c
- drivers/iio/frequency/hmc7044.c
Miscellaneous bag of fixes and updates related to AD9081
> AD9081 dev

- drivers/clk/adi/clk-ad9545.c
Before this patch driver did not recalculate the
output freq of the PLL block correctly when all
refs were invalidated.
In the case where all the references are invalid
compute the output frequency using the free run
freq. of the DPLL's NCO.
Fixes: e8e9d8c3c872 ("clock: ad9545: Add reference priorities")
> clk: ad9545: Fix recalc_rate

- drivers/iio/adc/navassa/adrv9002.c
- drivers/iio/adc/navassa/adrv9002.h
- drivers/iio/adc/navassa/devices/adrv9001/public/include/adi_adrv9001_rx_types.h
- drivers/iio/adc/navassa/devices/adrv9001/public/src/adi_adrv9001_utilities.c
Mainly, this PR adds support for QEC_W_POLY tracking call for ORx and exports the ORx gain in dBs...
> Orx new features

- drivers/iio/amplifiers/ad8366.c
This patch adds support for following digital step attenuators:
* ADRF5720: 0.5 dB LSB, 6-Bit, Digital Attenuator, 9 kHz to 40 GHz
* ADRF5730: 0.5 dB LSB, 6-Bit, Digital Attenuator, 100 MHz to 40 GHz
* ADRF5731: 2 dB LSB, 4-Bit, Digital Attenuator, 100 MHz to 40 GHz
* HMC1018A: 1.0 dB LSB GaAs MMIC 5-BIT DIGITAL ATTENUATOR, 0.1 - 30 GHz
* HMC1019A: 0.5 dB LSB GaAs MMIC 5-BIT DIGITAL ATTENUATOR, 0.1 - 30 GHz
> iio: amplifiers: ad8366: Update device support

- drivers/iio/frequency/adf5355.c
Updates/fixes addressed for the ADF5355 driver.
> ADF5355 updates

- drivers/iio/logic/m2k-fabric.c
fixes commit
c49024fdb0 ("iio: logic: m2k-fabric: rework GPIO code to new framework")
> iio: logic: m2k-fabric: Fix m2k fabric gpio array handling

- arch/microblaze/boot/dts/vcu118_quad_ad9081_204b_txmode_9_rxmode_10.dts
- arch/microblaze/boot/dts/vcu118_quad_ad9081_204b_txmode_9_rxmode_10_onchip_pll_revc_nz1.dts
- arch/microblaze/boot/dts/vcu118_quad_ad9081_204b_txmode_9_rxmode_10_revc_nz1.dts
- arch/microblaze/boot/dts/vcu118_quad_ad9081_204c_txmode_10_rxmode_11.dts
- arch/microblaze/boot/dts/vcu118_quad_ad9081_204c_txmode_10_rxmode_11_onchip_pll_revc_nz1.dts
- arch/microblaze/boot/dts/vcu118_quad_ad9081_204c_txmode_10_rxmode_11_revc_nz1.dts
- arch/microblaze/boot/dts/vcu118_quad_ad9081_204c_txmode_11_rxmode_4.dts
- arch/microblaze/boot/dts/vcu118_quad_ad9081_204c_txmode_11_rxmode_4_direct_6g.dts
- arch/microblaze/boot/dts/vcu118_quad_ad9081_204c_txmode_11_rxmode_4_onchip_pll_revc_nz1.dts
- arch/microblaze/boot/dts/vcu118_quad_ad9081_204c_txmode_11_rxmode_4_revc_nz1.dts
- arch/microblaze/boot/dts/vcu118_quad_ad9081_204c_txmode_23_rxmode_25_onchip_pll_revc_nz1.dts
- arch/microblaze/boot/dts/vcu118_quad_ad9081_204c_txmode_23_rxmode_25_revc.dts
- arch/microblaze/boot/dts/vcu118_quad_ad9081_204c_txmode_23_rxmode_25_revc_nz1.dts
- arch/microblaze/boot/dts/vcu118_quad_ad9081_204c_txmode_29_rxmode_24_onchip_pll_revc_nz1.dts
- arch/microblaze/boot/dts/vcu118_quad_ad9081_204c_txmode_29_rxmode_24_revc.dts
- arch/microblaze/boot/dts/vcu118_quad_ad9081_204c_txmode_29_rxmode_24_revc_nz1.dts
- arch/microblaze/boot/dts/vcu118_quad_ad9082_204c_txmode_12_rxmode_13.dts
- arch/microblaze/boot/dts/vcu118_quad_ad9082_204c_txmode_12_rxmode_13_onchip_pll.dts
- arch/microblaze/boot/dts/vcu118_quad_ad9082_204c_txmode_23_rxmode_25.dts
- arch/microblaze/boot/dts/vcu118_quad_ad9082_204c_txmode_23_rxmode_25_onchip_pll.dts
- arch/microblaze/boot/dts/vcu118_quad_ad9082_204c_txmode_3_rxmode_2.dts
- arch/microblaze/boot/dts/vcu118_quad_ad9082_204c_txmode_3_rxmode_2_onchip_pll.dts
- drivers/iio/adc/ad9081.c
- drivers/iio/frequency/hmc7044.c
Support for the ADQUADMXFE2EBZ & ADQUADMXFE2EBZ.
Some other fixes and improvements.
> AD9081: Support for the ADQUADMXFE2EBZ & ADQUADMXFE2EBZ

- arch/arm/boot/dts/zynq-adrv9002.dtsi
- arch/arm64/boot/dts/xilinx/zynqmp-zcu102-rev10-adrv9002.dts
- drivers/iio/adc/cf_axi_tdd.c
This series add IIO labels to the TDD cores on the adrv9002 related projects
> axi core tdd misc

- drivers/iio/adc/navassa/adrv9002.c
ORx can only be enabled if RX is not enabled and TX is enabled. On top
of that, after enabling it, we won't allow any operation that can
trigger an ensm transition in RX/TX of the same channel as the enabled
ORx. Because allowing it, has the non explicit side effect of
potentially break the ORx capture...
Also note that with this, we need to enable the ORx tracking cal
(if desired) before enabling the capture.
> iio: adrv9002: add checks for ORx

- drivers/iio/adc/navassa/adrv9002_conv.c
We were wrongly ignoring pn errors during interface tuning. The issue is
visible when RX1=off and RX2=on. We would ignore errors because we where
detecting that RX1 is not enabled and wrongly assuming that they not
matter. The check was useful for rx2tx2 mode where we just enable the test
patterns in all channels (so we run the test at the same time for both
channels) and want to ignore errors in not enabled channels. As seen, this
does not work for independent mode.
This patch fixes the issue by only checking/generating test patterns for
the channels that are in fact enabled. For independent mode, it's trivial
and we just go over all the channels in the axi core. For rx2tx2 mode, we
check if RX2/TX2 is enabled or not and if it isn't we just enable patterns
for the first channel (RX2/TX2 …
> [2019_R2]: Fix adrv9002 tuning

- arch/arm/boot/dts/overlays/Makefile
- arch/arm/boot/dts/overlays/rpi-adf4159-overlay.dts
ADF4159 SPI Wideband Synthesizer example devicetree overlay
> arm: dts: overlays/rpi-adf4159-overlay.dts: Add ADF4159 dtb overlay

- drivers/iio/adc/navassa/adrv9002_conv.c
We were wrongly ignoring pn errors during interface tuning. The issue is
visible when RX1=off and RX2=on. We would ignore errors because we where
detecting that RX1 is not enabled and wrongly assuming that they not matter.
The check was useful for rx2tx2 mode where we just enable the test patterns
in all channels (so we run the test at the same time for both channels) and
want to ignore errors in not enabled channels. As seen, this does not work
for independent mode.
This patch fixes the issue by only checking/generating test patterns for the
channels that are in fact enabled. For independent mode, it's trivial and
we just go over all the channels in the axi core. For rx2tx2 mode, we check
if RX2/TX2 is enabled or not and if it isn't we just enable patterns for the
first channel (RX2/TX2 …
> iio: adrv9002: fix interface tuning for independent mode

- arch/arm64/boot/dts/xilinx/zynqmp-zcu102-rev10-stingray.dts
arch: arm64: dts: stingray: Update system GPIO pinouts
This will integrate ZCU102, Single-Chip MxFE, XUD1A and Stingray.
> Adar1000 dev

- drivers/iio/adc/cf_axi_tdd.c
Previously the `cf_axi_tdd` did not support fractional ms, although
the hardware registers are cycle counters. Thus most of the
available precision was inaccessible. This commit enables the use
of decimal notation down to (in theory) 1 ns (0.000001 ms).
> iio: cf_axi_tdd: Convert timing attributes to decimal values

- drivers/iio/adc/adrv9009.c
In case TALISE_waitInitCals() return action/error make sure that
errorFlag gets printed. In addition it may return the action to
rerun the Cals, do it once before error out.
> iio: adc: adrv9009: Improve InitCals error handling and reporting

- drivers/iio/adc/ad9081.c
AD9988 and AD9986 are similar to AD9081/82 with the exception of some
missing auxiliary features, such as FFH, Loopback and DDS.
> iio: adc: ad9081: Add support for AD9988 and AD9986 derivatives

- drivers/iio/adc/adrv9009.c
- drivers/iio/frequency/hmc7044.c
Backport of some fixes from master.
> Hmc7044 adrv9009 updates 2019 r2

- arch/arm/boot/dts/socfpga_cyclone5_de10_nano_cn0501.dts
Add devicetree for cn0501 and de10nano.
> arch: arm: boot: dts: Add support for cn0501 and de10nano

- drivers/pwm/pwm-axi-pwmgen.c
For values like clk_rate = 100MHz and period = 1ms an
overflow will occure when multiplying.
Use u64 as type for tmp to fix the issue
> drivers: pwm: pwm-axi-pwmgen.c: Fix overflow

- arch/arm/boot/dts/overlays/rpi-cn0511-overlay.dts
- Drive DS2 LED from the LD signal
- Remove the __overrides__ section
> cn0511 updates

- arch/arm/boot/dts/adi-adrv9002.dtsi
- arch/arm/boot/dts/zynq-adrv9002-rx2tx2.dtsi
- arch/arm/boot/dts/zynq-adrv9002.dtsi
- arch/arm64/boot/dts/xilinx/adi-adrv9002.dtsi
- drivers/iio/adc/navassa/adrv9002.c
This PR fixes some important warnings for the frequency hopping interface. It also does some cleaning in the devicetrees (mainly on the arm side)
> adrv9002 misc fixes and improvements

- drivers/net/ethernet/cadence/macb.h
- drivers/net/ethernet/cadence/macb_main.c
- drivers/net/ethernet/cadence/macb_ptp.c
- drivers/net/ethernet/xilinx/Kconfig
- drivers/net/ethernet/xilinx/xilinx_axienet.h
- drivers/net/ethernet/xilinx/xilinx_axienet_main.c
- drivers/net/ethernet/xilinx/xilinx_emaclite.c
- drivers/net/phy/dp83867.c
This PR syncs some drivers that somehow got into a broken state when creating this branch... Looking at CI failures for master configurations (which should not really matter for the pi branch), there's still some failures I'm not fixing:
* pluto and m2k configs somehow conflict with an out of tree pi driver;
* pcie-altera driver is broken (does not compile);
* pcie-xilinx-nwl.c has an unused variable warning.
As all of the above issues are actually present in the upstream pi branch so I'm not really fixing them. We should not need any of the above for the PI projects anyways...
> rpi sync pi tree

- arch/arm/boot/dts/zynq-adrv9361-z7035-fmc.dts
- arch/arm/boot/dts/zynq-zc702-adv7511.dtsi
- arch/arm/boot/dts/zynq-zc706-adv7511.dtsi
- arch/arm/boot/dts/zynq-zed-adv7511.dtsi
- arch/arm/boot/dts/zynq-zed-imageon.dts
- drivers/gpu/drm/adi_axi_hdmi/axi_hdmi_drv.c
This PR adds some fixes related with the adv7511 sound and the axi-hdmi-drv that was introduced after the merge with 5.10.
> misc fixes

- arch/arm64/boot/dts/xilinx/adi-adar3002-longs-peack.dts
- arch/arm64/boot/dts/xilinx/adi-adar3003-longs-peack.dts
- drivers/iio/beamformer/adar300x.c
Enable down-converter control on the Rx backplane
> Adar3000 dev 

- arch/arm/boot/dts/overlays/Makefile
- arch/arm/boot/dts/overlays/rpi-dc1962c-overlay.dts
Add overlay for the DC1962C Power System Management Demo Board.
Overlay tested by @mthoren-adi .
> arch:arm:overlays: rpi-dc1962c overlay

- drivers/iio/adc/ad9361.c
This will only work for those SPI controllers which populate their
effective_speed_hz during the clock setting, but for those that do,
this will print out the SPI clock (in MHz) so it is easier to understand
what's going on in the system.
Will see things like:
ad9361 spi0.0: ad9361_probe : AD936x Rev 2 successfully initialized (SPI @ 5.20 MHz)
or
ad9361 spi0.0: ad9361_probe : AD936x Rev 2 successfully initialized (SPI @ 41.66 MHz)
or (with older SPI controller drivers)
ad9361 spi0.0: ad9361_probe : AD936x Rev 2 successfully initialized
tested on PlutoSDR
Signed-off-by: Robin Getz <robin.getz@analog.com>
> iio:ad9361 print out the SPI CLK during probe

- ci/travis/run-build-docker.sh
- drivers/nvmem/adi_axi_sysid.c
Sync axi_sysid with fixes from master
> Fix axi sysid on 2019_R2

- drivers/iio/adc/navassa/adrv9002.c
- drivers/iio/adc/navassa/adrv9002.h
- drivers/iio/adc/navassa/adrv9002_debugfs.c
This set is simply doing some small coding style fixes and improvements.
> small adrv9002 style improvements

- drivers/net/ethernet/adi/adin1110.c
* It was observed that the ADIN1110 MAC-PHY adds 4-7 bytes to the TX frame
upon sending. Turns out, this is a combination of incorrect alignment method
in the driver adding trailing 0-3 bytes to the frame before passing it on to
the MAC which then adds the additional 4 bytes of FCS CRC32.
This behavior caused incompatibility with the 802.3cg standard and other
T1L MAC-PHY manufacturers, resulting in dropping frames and resetting of the
link.
* Upon receiving a frame, the driver passed on the complete frame to the
netdev subsystem, failing to trim the trailing 4 bytes of FCS.
The extra bytes resulted in frame lengths just below the allowed MTU to
break the limit and get dropped on the receiving end if e.g. the interface
was part of a bridge.
It also caused different kinds of issues …
> Fix ADIN1110 T1L driver, incorrect TX and RX frame sizes

- Documentation/devicetree/bindings/iio/frequency/adi,admv4420.yaml
- drivers/iio/Kconfig.adi
- drivers/iio/frequency/Kconfig
- drivers/iio/frequency/Makefile
- drivers/iio/frequency/admv4420.c
- include/linux/units.h
Add support for K Band Downconverter with Integrated
Fractional-N PLL and VCO.
More info:
https://www.analog.com/en/products/admv4420.html
> Admv4420 dev

- arch/arm64/boot/dts/xilinx/zynqmp-zcu102-rev10-ad9695.dts
- drivers/iio/adc/ad9208.c
Added devicetree and modified ad9208.c to work with ad9695 chip
> AD9695 dev

- arch/arm/boot/dts/zynq-zed-otg.dts
Signed-off-by: MIchael Bradley <michael.bradley@analog.com>
> arch: arm: dts: Add zedboard with otg enabled

- Documentation/ABI/testing/sysfs-bus-iio-frequency-adf4377
- Documentation/devicetree/bindings/iio/frequency/adi,adf4377.yaml
- arch/arm/boot/dts/zynq-zed-adv7511-adf4377.dts
- drivers/iio/Kconfig.adi
- drivers/iio/frequency/Kconfig
- drivers/iio/frequency/Makefile
- drivers/iio/frequency/adf4377.c
Add support for Analog Devices ADF4377 Microwave Wideband Synthesizer.
*NOTE:* Datasheet not public yet, thus not subject for upstream.
> iio: frequency: adf4377

- drivers/iio/frequency/adf4371.c
Lock Detect bit readback can be performed only when MUXOUT
is set to " digital lock detect".
> iio: frequency: adf4371: Fix Lock Detect bit reading

- drivers/iio/frequency/ad9528.c
This feature allows one AD9528 to simultaneous request SYSREF pulses
from potentially other AD9528, which share the SAME sysref-req-gpio.
> iio: frequency: ad9528: Support for GPIO trigger SYSREF requests

- drivers/iio/jesd204/axi_adxcvr.c
Correction of measurement unit for rate from Hz to kHz for the rate parameter.
> axi_adxcvr.c: Rate debug message correction

- drivers/misc/adi-axi-data-offload.c
Updates which reflect register map changes done in PR https://github.com/analogdevicesinc/hdl/pull/910
> Data offload updates

- ci/travis/prepare_artifacts.sh
Change the format of the date inside rpi_git_properties.txt file.
> CI:change date format in rpi_git_properties.txt

- ci/travis/prepare_artifacts.sh
Fix upload to Artifactory job.
> CI:fix push to Artifactory

- arch/arm/boot/dts/socfpga_arria10_socdk_cn0506_mii.dts
- arch/arm/boot/dts/socfpga_arria10_socdk_cn0506_rgmii.dts
- arch/arm/boot/dts/zynq-zc706-adv7511-cn0506-mii.dts
- arch/arm/boot/dts/zynq-zc706-adv7511-cn0506-rgmii.dts
- arch/arm/boot/dts/zynq-zc706-adv7511-cn0506-rmii.dts
- arch/arm/boot/dts/zynq-zed-adv7511-cn0506-mii.dts
- arch/arm/boot/dts/zynq-zed-adv7511-cn0506-rgmii.dts
- arch/arm/boot/dts/zynq-zed-adv7511-cn0506-rmii.dts
- arch/arm64/boot/dts/xilinx/zynqmp-zcu102-rev10-cn0506-mii.dts
- arch/arm64/boot/dts/xilinx/zynqmp-zcu102-rev10-cn0506-rgmii.dts
- arch/arm64/boot/dts/xilinx/zynqmp-zcu102-rev10-cn0506-rmii.dts
Update hdl_project tags in device trees for next projects to match the updated HDL:
a10soc + cn0506 device trees 
zed + cn0506 device trees
zcu102 + cn0506 device trees 
zc706 + cn0506 device trees
> Mii rmii rgmii

- README.md
Update links for the new supported xilinx tag.
> README: update links

- Documentation/devicetree/bindings/iio/adc/adi,ad7923.yaml
- drivers/iio/adc/ad7923.c
Some backports of fixes and full range support. The full range support was requested so that I'm backporting it to our tree. Also note there's no git sha of the cherry-picked commits because the patches are still on the IIO testing branch which means the shas will probably change.
> ad7923 fixes

- drivers/iio/adc/navassa/adrv9002.c
- drivers/iio/adc/navassa/adrv9002.h
- drivers/iio/adc/navassa/adrv9002_conv.c
- drivers/iio/adc/navassa/adrv9002_debugfs.c
Some improvements to the driver and also a fix...
> adrv9002 enhancement

- drivers/net/ethernet/adi/adin1110.c
Main features added during upstreaming are FDB offloading and STP support. The rest of the changes are optimisations and refactoring.
> net: ethernet: adi: adin1110: sync with upstream

- arch/arm64/boot/dts/xilinx/zynqmp-adrv9009-zu11eg-revb-adrv2crr-fmc-revb-jesd204-fsm-fmcbridge.dts
Update the hdl tag to match the actual hdl project.
> arch: arm64: dts: fmcbridge: update hdl tag

- arch/arm/boot/dts/adi-ad9083-fmc-ebz.dtsi
- arch/arm/boot/dts/socfpga_arria10_socdk_ad9083_fmc_ebz.dts
Add devicetree for ad9083_a10soc and generic dtsi for intel ad9083
> arm: dts: Add ad9083_a10soc Development Kit support

- drivers/nvmem/adi_axi_sysid.c
For some projects the string containing the build parameters for the HDL projects don't fit inside the default ROM memory space of the sysid component and are truncated.
I added support for variable ROM sizes and increased the custom_info length to fit all the build parameters for the HDL projects.
I have also corrected some typos found inside the error messages for the header checksum.
Signed-off-by: Bogdan Luncan <bogdan.luncan@analog.com>
> drivers: nvmem: adi_axi_sysid: add support for different memory sizes

- drivers/iio/adc/navassa/adrv9002.c
backport the fixes introduced in #2034 into the release branch
> adrv9002 fixes 2021 r1

- Documentation/a2b/a2b.rst
- Documentation/a2b/index.rst
> a2b: Add MDF document

- ci/travis/run-build.sh
The checkpatch job calls '__update_git_ref()' which does a shallow fetch with depth=50 by default to speed things up. However that could be problematic if the branch in the PR diverged from master such that we cannot find a common ancestor. In that case, the job will timeout after 60min even if the branch is able to merge (even if diverged). We could do '$GIT_FETCH_DEPTH="disable"' before calling '__update_git_ref()' but that would slow things a lot. Instead, let's do a treeless fetch which get's the whole history while being much faster than a typical fetch.
> ci: don't timeout on checkpatch job

- drivers/hwmon/ltc2947-core.c
- drivers/iio/dac/ltc2688.c
> backport fixes

- drivers/hwmon/ltc2947-core.c
- drivers/iio/dac/ltc2688.c
> fixes 2021 r2

- drivers/hwmon/ltc2947-core.c
- drivers/iio/dac/ltc2688.c
> fixes 2021 r1

- Documentation/ABI/testing/sysfs-bus-iio-adc-ad4630
- Documentation/devicetree/bindings/iio/adc/adi,ad4630.yaml
- MAINTAINERS
- arch/arm/boot/dts/zynq-zed-adv7511-ad4630-24.dts
- drivers/iio/Kconfig.adi
- drivers/iio/adc/Kconfig
- drivers/iio/adc/Makefile
- drivers/iio/adc/ad4630.c
> drivers: iio: adc: Add support for ad4630

- Documentation/ABI/testing/sysfs-bus-iio-adc-ad4630
- Documentation/devicetree/bindings/iio/adc/adi,ad4630.yaml
- MAINTAINERS
- arch/arm/boot/dts/zynq-zed-adv7511-ad4630-24.dts
- drivers/iio/Kconfig.adi
- drivers/iio/adc/Kconfig
- drivers/iio/adc/Makefile
- drivers/iio/adc/ad4630.c
Cherry pick ad463x support to release branch.
> Cherry pick ad463x support to release branch

- arch/arm/boot/dts/zynq-zed-adv7511-ad4630-24.dts
> arch: arm: boot: dts: fix ad4630 hdl tag

- drivers/iio/adc/ad4630.c
> ad4630 fixes 2021 r2

- arch/arm/boot/dts/overlays/Makefile
- arch/arm/boot/dts/overlays/rpi-cn0554-overlay.dts
Signed-off-by: Angelo Catapang <Angelo.Catapang@analog.com>
> dt: Adding rpi-cn0554 support

- arch/arm/boot/dts/socfpga_cyclone5_de10_nano_cn0579_i2c.dts
- arch/arm/boot/dts/zynq-zed-adv7511-ad7768-4-axi-adc.dts
- mclk freq fix
- device tree for AD7768-4EVB
> dev/ad7768_release 

- arch/arm/boot/dts/adi-common-dac-fmc-ebz.dtsi
- arch/arm/boot/dts/adi-xilinx-dac-fmc-ebz.dtsi
- arch/arm/boot/dts/zynq-zc706-adv7511-ad9136-fmc-ebz.dts
- ci/travis/dtb_build_test_exceptions
- drivers/iio/jesd204/axi_jesd204_rx.c
- drivers/iio/jesd204/axi_jesd204_tx.c
> ad9136 fixes 2021 r2

- drivers/iio/frequency/ad9122.c
- drivers/iio/frequency/ad9172.c
- drivers/iio/frequency/ad9739a.c
- drivers/iio/frequency/adf5355.c
- drivers/iio/frequency/cf_axi_dds.c
- drivers/iio/frequency/cf_axi_dds.h
Next batch of patches dropping mlock. Now for iio/frequency
> iio frequency drop mlock

- arch/arm/boot/dts/overlays/Makefile
Add latest overlay for max31827 to the Makefile.
Reference #2189
> arm: boot: dts: overlays: add max31827 dtbo

- drivers/iio/adc/navassa/adrv9002.c
The ORx port does not have it's own struct 'adrv9002_chann' instance since it's a very simple one and we can handle it with a couple of specific 'struct adrv9002_rx' members. That means, that we need to explicitly use the encoded port in 'struct iio_chan_spec::address' to identify an ORx port when dealing with it's IIO attributes so we can actually read and write them (instead of changing RX attributes)
Of course that not having it's own instance can lead to subtle errors like this but I still think it's not really worth it...
While at it, made all the port handling coeherent by always using 'adi_common_Port_e'.
Fixes: 2c490432b857c ("iio: adc: adrv9002: improve IIO read/write() callbacks code flow")
> iio: adc: adrv9002: fix ORx port detection

- drivers/clk/adi/clk-ad9545.c
Add support for full resolution of AUX NCO center frequency and offset frequency.
> clk: ad9545: improve support for AUX NCO clocks

- drivers/iio/adc/ad6676.c
clamping the ADC frequency will cause issues so better error out.
> AD6676 dev

- ci/travis/run-build.sh
> [CI] don't build ignored devicetrees

- drivers/iio/frequency/ad9528.c
Use devm_regulator_get_optional() and return on error != ENODEV. This will allow the deferred probe mechanism to re-probe if the regulator is not yet available.
> iio: frequency: ad9528: Fix vcc regulator EPROBE_DEFER handling

- arch/arm/boot/dts/socfpga_cyclone5_de10_nano_cn0579_i2c.dts
- arch/arm/boot/dts/zynq-coraz7s-cn0579_i2c.dts
- drivers/iio/adc/Kconfig
- drivers/iio/adc/ad7768.c
> cn0579: Add AD7768 GPIO controls

- drivers/iio/adc/navassa/adrv9002.c
- drivers/iio/adc/navassa/adrv9002.h
- drivers/iio/adc/navassa/adrv9002_conv.c
- drivers/iio/adc/navassa/common/adi_common_log.c
- drivers/iio/adc/navassa/devices/adrv9001/private/include/adrv9001_arm_macros.h
- drivers/iio/adc/navassa/devices/adrv9001/public/include/adi_adrv9001.h
- drivers/iio/adc/navassa/devices/adrv9001/public/include/adi_adrv9001_arm_types.h
- drivers/iio/adc/navassa/devices/adrv9001/public/include/adi_adrv9001_dpd.h
- drivers/iio/adc/navassa/devices/adrv9001/public/include/adi_adrv9001_dpd_types.h
- drivers/iio/adc/navassa/devices/adrv9001/public/include/adi_adrv9001_gpio_types.h
- drivers/iio/adc/navassa/devices/adrv9001/public/include/adi_adrv9001_mcs.h
- drivers/iio/adc/navassa/devices/adrv9001/public/include/adi_adrv9001_powersavingandmonitormode_types.h
- drivers/iio/adc/navassa/devices/adrv9001/public/include/adi_adrv9001_radio.h
- drivers/iio/adc/navassa/devices/adrv9001/public/include/adi_adrv9001_radio_types.h
- drivers/iio/adc/navassa/devices/adrv9001/public/include/adi_adrv9001_rx.h
- drivers/iio/adc/navassa/devices/adrv9001/public/include/adi_adrv9001_rxSettings_types.h
- drivers/iio/adc/navassa/devices/adrv9001/public/include/adi_adrv9001_tx.h
- drivers/iio/adc/navassa/devices/adrv9001/public/include/adi_adrv9001_utilities.h
- drivers/iio/adc/navassa/devices/adrv9001/public/include/adi_adrv9001_version.h
- drivers/iio/adc/navassa/devices/adrv9001/public/include/adrv9001_Init_t_parser.h
- drivers/iio/adc/navassa/devices/adrv9001/public/src/adi_adrv9001_arm.c
- drivers/iio/adc/navassa/devices/adrv9001/public/src/adi_adrv9001_dpd.c
- drivers/iio/adc/navassa/devices/adrv9001/public/src/adi_adrv9001_radio.c
- drivers/iio/adc/navassa/devices/adrv9001/public/src/adi_adrv9001_rx.c
- drivers/iio/adc/navassa/devices/adrv9001/public/src/adi_adrv9001_tx.c
- drivers/iio/adc/navassa/devices/adrv9001/public/src/adi_adrv9001_utilities.c
- drivers/iio/adc/navassa/third_party/jsmn/jsmn.h
Important things for navassa that should be in the next release... this is a first set of cherry picks.
> next_stable picks [PART 1]

- arch/arm/boot/dts/adi-adrv9002.dtsi
- arch/arm64/boot/dts/xilinx/adi-adrv9002.dtsi
- drivers/clk/adi/clk-ad9545.c
- drivers/iio/adc/navassa/adrv9002.c
- drivers/iio/adc/navassa/adrv9002.h
- drivers/iio/adc/navassa/adrv9002_debugfs.c
- drivers/iio/adc/navassa/adrv9002_of.c
- drivers/net/ethernet/adi/adin1110.c
- drivers/spi/spi-axi-spi-engine.c
- include/dt-bindings/iio/adc/adi,adrv9002.h
> 2022_R2 picks [PART 2]

- drivers/iio/adc/ad9081.c
* Enforce required properties and gracefully error out.
* Properly initialize optional properties.
* Fix unhanded of_node_put.
> iio: adc: ad9081: Fix dts parsing

- azure-pipelines-rpi.yml
Let in this PR on the changes related to azure-pipeline-rpi.yml:
- azure-pipeline-rpi: add rpi-6.1.y branch in list of triggers
And open another PR with changes for 'master' to 'main' rename.
> Add rpi 6 10 branch on ci

- drivers/iio/adc/ad6676.h
- drivers/iio/adc/ad9208.c
- drivers/iio/adc/ad9371.c
- drivers/iio/adc/ad9467.c
- drivers/iio/buffer/industrialio-buffer-dmaengine.c
- drivers/iio/frequency/adf4371.c
- drivers/iio/industrialio-buffer.c
sames as #2339 but only with the meaningful fixes...
> misc fixes [2022 r2]

- drivers/iio/adc/ad_adc.c
Add option to keep HDL scale calibration values unwritten for enabling
the alternative of making the computations in user-space, where floating
point operations are permitted.
This fixes the issue where some ADC values are missing because of the HDL
fixed precision multiplier.
> iio: adc: ad_adc: m2k: Add cached calibration scale attributes

- drivers/iio/adc/navassa/adrv9002.c
- drivers/iio/adc/navassa/adrv9002.h
- drivers/iio/adc/navassa/adrv9002_debugfs.c
- drivers/iio/adc/navassa/adrv9002_of.c
same as #2345 . As stated there, this was explicitly requested for the next release
> [adrv9002] Multi-chip sync - 2022_R2

- arch/arm/boot/dts/zynq-zed-adv7511-ad9434-fmc-500ebz.dts
-Added the devicetree for the ad9434-fmc/zed project
-The setup was tested and works fine
> AD9434/Zed .dts file

- arch/arm/boot/dts/adi-cn0506-mii.dtsi
- arch/arm/boot/dts/adi-cn0506-rgmii.dtsi
- arch/arm/boot/dts/adi-cn0506-rmii.dtsi
- Update the macb_config to the corresponding zynq_config (compatible-xlnx,zynq-gem);
> dts: arm: adi-cn0506-*: Update to the corresponding macb_config

- drivers/iio/jesd204/axi_jesd204_rx.c
- drivers/iio/jesd204/axi_jesd204_tx.c
Need to cast to u64 before muliplication
Fixes: 74518b367c33 ("iio: jesd204: axi_jesd204_[rx|tx]: Fix measured device/link clock")
> iio: jesd204: axi_jesd204_[rx|tx]: Fix measured device/link clock

- azure-pipelines.yml
- ci/travis/lib.sh
- ci/travis/run-build.sh
- ci/travis/upload_to_artifactory.py
Update "master" to "main".
Those commits were initially in [PR 2325](https://github.com/analogdevicesinc/linux/pull/2325), but I have splitt them in 2 separate PRs - this one for "master" to "main" changes and [PR 2325](https://github.com/analogdevicesinc/linux/pull/2325) for adding rpi-6.10.y branch in azure pipeline.
> Update master to main

- Documentation/devicetree/bindings/gpio/adi,ds4520-gpio.yaml
- Kconfig.adi
- drivers/gpio/Kconfig
- drivers/gpio/Makefile
- drivers/gpio/gpio-ds4520.c
> ds4520 backport

- Documentation/devicetree/bindings/rtc/adi,max31335.yaml
- Kconfig.adi
- MAINTAINERS
- drivers/rtc/Kconfig
- drivers/rtc/Makefile
- drivers/rtc/rtc-max31335.c
- include/linux/rtc.h
Early stage of the max31335 rtc driver. Not yet tested with hardware.
Datasheet not published yet (early stage).
Initial review is welcome :)
> drivers: rtc: max31335: add support

- arch/arm/boot/dts/overlays/Makefile
- arch/arm/boot/dts/overlays/rpi-max31335-overlay.dts
Add RPi overlay for the max31335 rtc.
> arch: arm: boot: overlays: add max31335 overlay

- drivers/iio/adc/ad9081.c
This patch adds support of Half Rate and Quarter Rate 2D Eye Scan
> iio: adc: ad9081: Support of HR and QR 2D Eye Scan

- Documentation/devicetree/bindings/regulator/adi,max77503-regulator.yaml
- Kconfig.adi
- drivers/regulator/Kconfig
- drivers/regulator/Makefile
- drivers/regulator/max77503-regulator.c
Backport the max77503 into ADI tree
> max77503 backport

- drivers/iio/adc/ad9081.c
Declaring 'adi,adc-invert-en' in the ADC device tree node will invert its respective channel. This feature can be used to correct a PN swap on hardware.
> iio: adc: ad9081: Add option invert ADC data

- Documentation/devicetree/bindings/iio/frequency/adi,admfm2000.yaml
- MAINTAINERS
- drivers/iio/Kconfig.adi
- drivers/iio/frequency/Kconfig
- drivers/iio/frequency/Makefile
- drivers/iio/frequency/admfm2000.c
create a new PR to resolve merge conflicts
the driver was tested on rpi4
CI dt_binding_check error may be able to be fixed with this PR https://github.com/analogdevicesinc/linux/pull/2271
> admfm2000 driver

- Documentation/devicetree/bindings/regulator/adi,max77857.yaml
- Kconfig.adi
- drivers/regulator/Kconfig
- drivers/regulator/Makefile
- drivers/regulator/max77857-regulator.c
Note we need another backport to make sure things compile in every compiler...
> max77857 backport

- drivers/iio/adc/ad4630.c
Update ad4630 driver with fixes for ADAQ4224 scale.
> Adaq4224 scale fix

- drivers/iio/adc/navassa/adrv9002.c
- drivers/iio/adc/navassa/adrv9002.h
- drivers/iio/adc/navassa/adrv9002_conv.c
Main goal of this PULL is o workaround an issue around TX2 power level (when compared to TX1). See more info in the commit message...
> adrv9002 tx level

- drivers/iio/adc/ad7192.c
- drivers/spi/spi.c
- include/linux/spi/spi.h
The commits were already accepted upstream.
Note that I included 2 commits signed by other people because some of my commits depend on them. One of them is a function addition to the spi framework.
> AD7192 updates and fixes

- drivers/jesd204/jesd204-core.c
- drivers/jesd204/jesd204-fsm.c
This patch adds function documentation for all exported symbols. No functional change.
> drivers: jesd204: Add documentation for the exported symbols

- drivers/iio/adc/ad7768.c
According to the calculations, we get the scale value: (2*4.096)/(2^24) = 488.28125nV. But the scale value displayed in iio_osc is 476nV. The scale value is not precise enough,so this has been fixed.
> Fix ad7768 scale factor

- drivers/iio/adc/ad7768.c
Display the scale factor more precisely.
> Fix ad7768 scale factor 2022 r2

- drivers/iio/adc/navassa/adrv9002.c
- drivers/iio/adc/navassa/adrv9002_debugfs.c
Use the new automatic cleanup in adrv9002
> adrv9002 cleanup magic

- drivers/iio/adc/navassa/adrv9002.c
For TX ports, if dpd is not set, we will continue the loop and possibly skipping the delays. Fix it with a new dpd helper for better control flow.
> [2022_R2] iio: adc: adrv9002: Fix setting MCS delays

- drivers/iio/adc/navassa/adrv9002.c
If the loaded profile has support for external LNAs, we need to configure them by calling adi_adrv9001_Rx_ExternalLna_Configure(). After that point the minimun gain index may have changed and we need to update it (and possible overwriting the one given by DT) otherwise we would later fail when configuring the automatic gain control parameters.
Also make sure to update the Automatic Gain Control LNA settling delay with the delay coming from the profile. Otherwise the profile value would be overwritten.
> iio: adc: adrv9002: support RX external LNA

- drivers/iio/frequency/m2k-dac.c
- M2k does not support enabling both start and stop trigger:
Remove attributes start_trigger and stop_trigger, replace by a single
attribute trigger_status with values: disabled, start, stop.
- Eliminate the option to select the pin To as a trigger source due to
the default configuration of the M2k, which does not support using
this pin as an input.
- Rename trigger source option trigger-i_0 to trigger-Ti.
> iio: frequency: m2k-dac: Improve trigger attributes

- arch/arm/boot/dts/overlays/Makefile
- arch/arm/boot/dts/overlays/rpi-adp1050-overlay.dts
> arch: arm: overlays: Add ADP1050 overlay

- Documentation/devicetree/bindings/hwmon/adi,adm1275.yaml
- Documentation/hwmon/adm1275.rst
- drivers/hwmon/pmbus/Kconfig
- drivers/hwmon/pmbus/adm1275.c
> Add support for adm1281

- arch/arm/boot/dts/socfpga_arria10_socdk_adrv9025.dts
Add a10soc support for adrv9025.
Tested on the ADRV9029 eval board.
> arm: Add adrv9025_a10soc dts

- Documentation/hwmon/max31827.rst
- drivers/hwmon/Kconfig
- drivers/hwmon/hwmon.c
- drivers/hwmon/max31827.c
- include/linux/hwmon.h
Upstream wise, changes to hwmon core code had been made, therefore:
1st commit is a commit that manually applies changes from hwmon-next in order to solve existing conflicts.
2nd commit is the upstream sent commit regarding the actual driver update for PEC support.
**Upstream links for patches**
https://patchwork.kernel.org/project/linux-hwmon/patch/20240531203346.1396055-2-linux@roeck-us.net/
https://patchwork.kernel.org/project/linux-hwmon/patch/20240531084645.12935-2-radu.sabau@analog.com/
- [] I have updated the documentation outside this repo accordingly (if there is the case)
> drivers: hwmon: max31827: Add PEC support

- azure-pipelines.yml
Remove trigger for master branch because we switched to main and also add next_stable branch as a trigger for azure build.
> azure-pipelines.yml: modify branch triggers

- drivers/iio/adc/ad9361.c
- drivers/iio/frequency/ltc6952.c
Cherry-pick some fixes from main to 2022_R2 branch in order to build 2022_R2 Patch2.
> Pick commits to 2022_R2

- include/dt-bindings/iio/adc/adi,ad9081.h
- Add defines used for serialzer and deserialzer configuration.
> dt-bindings: iio: adc: adi,ad9081.h: Add de/serializer config options

- arch/arm/boot/dts/overlays/rpi-ad7173-overlay.dts
Update the devicetree overlay to match the expected structure of the upstream version of the driver.
> arch: arm: dts: overlays: Update ad7173 overlay

- arch/arm/boot/dts/overlays/Makefile
- arch/arm/boot/dts/overlays/rpi-adxl380-overlay.dts
Add overlay example for the adxl380.
> overlays: rpi-adxl380-overlay: add ADXL380 overlay

- Documentation/devicetree/bindings/iio/frequency/adi,adf4377.yaml
- drivers/iio/frequency/adf4377.c
sync driver and bindings with the upstream version.
> adf4377 sync

- Documentation/devicetree/bindings/iio/frequency/adi,adf4377.yaml
- drivers/iio/frequency/adf4377.c
[dt-bindings: iio: adf4377: add adf4378 support](https://github.com/analogdevicesinc/linux/commit/0b4ae5aad4325969a23c5706c00b90bade1e9563)
[iio: frequency: adf4377: add adf4378 support](https://github.com/analogdevicesinc/linux/commit/c6645498059faf798f25a2ee3d10cf4c344b5773)
> iio: frequency: add adf4378 support

- arch/arm64/boot/dts/xilinx/versal-vpk180-reva-ad9081.dts
- arch/arm64/boot/dts/xilinx/versal-vpk180-reva-ad9082-m1-l8.dts
Pick vpk180 support from main to next_stable
> Pick vpk180 support from main to next_stable

- drivers/iio/adc/ad7768.c
Simply probe making use of the following headers:
* spi_get_device_match_data();
* devm_clk_get_enabled();
* devm_regulator_get_enable().
> iio: adc: ad7768: simplify probe

- arch/arm/boot/dts/overlays/Makefile
- arch/arm/boot/dts/overlays/rpi-admfm2000-overlay.dts
> add admfm2000 overlay

- arch/microblaze/boot/dts/vcu118_ad9082.dts
- drivers/iio/adc/ad7768.c
Pick ad9082+vcu118 DTS and a fix for ad7768 to next_stable
> [next_stable] Pick ad9082+vcu118 DTS and a fix for ad7768 to next_stable 

- arch/arm64/boot/dts/adi/sc59x-64.dtsi
- drivers/clocksource/timer-adi-adsp-sc5xx.c
- drivers/tty/serial/adi_uart4.c
Adding UART support to new kernel version
> Adsp main 6.10 uart

- arch/arm64/boot/dts/xilinx/zynqmp-zcu102-rev10-adrv9025.dts
- drivers/iio/adc/madura/adrv9025.c
- drivers/iio/adc/madura/adrv9025.h
AUTOMATIC GAIN CONTROL implementation.
> Madura AGC

- drivers/iio/dac/ltc2664.c
> iio: dac: ltc2664: Fix off by one in ltc2664_channel_config()

- arch/arm/boot/dts/overlays/rpi-adxl380-overlay.dts
Fix title in the header comment of the overlay.
> overlays: rpi-adxl380-overlay: fix title

- arch/arm/boot/dts/zynq-coraz7s-adaq4003.dts
- arch/arm/boot/dts/zynq-zed-adv7511-ad4003.dts
- arch/arm/boot/dts/zynq-zed-adv7511-ad4020.dts
- arch/arm/boot/dts/zynq-zed-adv7511-adaq4003.dts
- drivers/iio/adc/ad400x.c
Cherry-pick relevant commits for ad400x (specifically the dts for adaq4003) to have them in next_stable for the release.
> [next_stable] Cherry-pick support for ad400x

- drivers/iio/frequency/ad9508.c
The AD9508 can function even if register read is not available. The updates first test if the read is available by reading the CHIP_ID. If it is not, the values written into the registers are saved in the regs_hw array and are returned when the register read function is called.
> iio: frequency: ad9508: Fix reg read

- arch/arm/boot/dts/socfpga_cyclone5_de10_nano.dtsi
- arch/arm/boot/dts/socfpga_cyclone5_de10_nano_cn0501.dts
- arch/arm/boot/dts/socfpga_cyclone5_de10_nano_cn0540.dts
- arch/arm/boot/dts/socfpga_cyclone5_de10_nano_cn0579_i2c.dts
- arch/arm/boot/dts/socfpga_cyclone5_de10_nano_hps.dtsi
Here come some more cleanups noticed while working on the device tree for the DE10-nano board.
> DE10-nano dts cleanups

- arch/arm64/boot/dts/xilinx/zynqmp-adrv9009-zu11eg-reva.dtsi
- arch/arm64/boot/dts/xilinx/zynqmp-jupiter-sdr.dts
- arch/arm64/boot/dts/xilinx/zynqmp-jupiter-sdr.dtsi
- arch/arm64/boot/dts/xilinx/zynqmp-zcu102-rev10-ad9081-default.dtsi
- arch/arm64/boot/dts/xilinx/zynqmp-zcu102-rev10-ad9081-m8-l4-overlay.dts
- arch/arm64/boot/dts/xilinx/zynqmp-zcu102-rev10-ad9083-fmc-ebz.dts
- arch/arm64/boot/dts/xilinx/zynqmp-zcu102-rev10-ad9083-vna-15p625msps.dts
- arch/arm64/boot/dts/xilinx/zynqmp-zcu102-rev10-ad9161-fmc-ebz_m2_s2.dts
- arch/arm64/boot/dts/xilinx/zynqmp-zcu102-rev10-ad9162-fmc-ebz_m2_s2.dts
- arch/arm64/boot/dts/xilinx/zynqmp-zcu102-rev10-ad9163-fmc-ebz_m2_l8.dts
- arch/arm64/boot/dts/xilinx/zynqmp-zcu102-rev10-ad9164-fmc-ebz_m2_s2.dts
- arch/arm64/boot/dts/xilinx/zynqmp-zcu102-rev10-ad9172-fmc-ebz.dts
- arch/arm64/boot/dts/xilinx/zynqmp-zcu102-rev10-ad9361-fmcomms2-3.dts
- arch/arm64/boot/dts/xilinx/zynqmp-zcu102-rev10-ad9361-fmcomms5.dts
- arch/arm64/boot/dts/xilinx/zynqmp-zcu102-rev10-ad9364-fmcomms4.dts
- arch/arm64/boot/dts/xilinx/zynqmp-zcu102-rev10-ad9694.dts
- arch/arm64/boot/dts/xilinx/zynqmp-zcu102-rev10-ad9695.dts
- arch/arm64/boot/dts/xilinx/zynqmp-zcu102-rev10-ad9783.dts
- arch/arm64/boot/dts/xilinx/zynqmp-zcu102-rev10-adrv9002-rx2tx2.dts
- arch/arm64/boot/dts/xilinx/zynqmp-zcu102-rev10-adrv9002.dts
- arch/arm64/boot/dts/xilinx/zynqmp-zcu102-rev10-adrv9008-1.dts
- arch/arm64/boot/dts/xilinx/zynqmp-zcu102-rev10-adrv9008-2.dts
- arch/arm64/boot/dts/xilinx/zynqmp-zcu102-rev10-adrv9009-fmcomms8.dts
- arch/arm64/boot/dts/xilinx/zynqmp-zcu102-rev10-adrv9009.dts
- arch/arm64/boot/dts/xilinx/zynqmp-zcu102-rev10-adrv9025.dts
- arch/arm64/boot/dts/xilinx/zynqmp-zcu102-rev10-adrv9371.dts
- arch/arm64/boot/dts/xilinx/zynqmp-zcu102-rev10-fmcdaq2.dts
- arch/arm64/boot/dts/xilinx/zynqmp-zcu102-rev10-fmcdaq3.dts
- Enables Cache Coherency on the currently supported UltraScale+ projects
- Related to: https://github.com/analogdevicesinc/hdl/pull/1527
> Enable Cache Coherency on UltraScale+

- arch/arm/boot/dts/intel/socfpga/socfpga_cyclone5_de10_nano_hps.dtsi
- arch/arm/boot/dts/xilinx/zynq-coraz7s-ad7687-pmdz.dts
- arch/arm/boot/dts/xilinx/zynq-coraz7s-ad7689-ardz.dts
- arch/arm/boot/dts/xilinx/zynq-coraz7s-ad7946.dts
- arch/arm/boot/dts/xilinx/zynq-coraz7s-ad7984.dts
- arch/arm/boot/dts/xilinx/zynq-coraz7s-adaq4003.dts
- arch/arm/boot/dts/xilinx/zynq-coraz7s-cn0540.dts
- arch/arm/boot/dts/xilinx/zynq-zed-adv7511-ad3552r-hs.dts
- arch/arm/boot/dts/xilinx/zynq-zed-adv7511-ad4030-24.dts
- arch/arm/boot/dts/xilinx/zynq-zed-adv7511-ad4032-24.dts
- arch/arm/boot/dts/xilinx/zynq-zed-adv7511-ad4630-16.dts
- arch/arm/boot/dts/xilinx/zynq-zed-adv7511-ad4630-24.dts
- arch/arm/boot/dts/xilinx/zynq-zed-adv7511-ad7625.dts
- arch/arm/boot/dts/xilinx/zynq-zed-adv7511-ad7768-1-evb.dts
- arch/arm/boot/dts/xilinx/zynq-zed-adv7511-ad7960.dts
- arch/arm/boot/dts/xilinx/zynq-zed-adv7511-adaq4216.dts
- arch/arm/boot/dts/xilinx/zynq-zed-adv7511-adaq4220.dts
- arch/arm/boot/dts/xilinx/zynq-zed-adv7511-adaq4224-24.dts
- arch/arm/boot/dts/xilinx/zynq-zed-adv7511-adaq4224-24_cm0_sdi4_cz2.dts
- arch/arm/boot/dts/xilinx/zynq-zed-adv7511-cn0577.dts
- arch/arm/boot/dts/xilinx/zynq-zed-adv7511-ltc2387.dts
- arch/arm64/boot/dts/xilinx/zynqmp-zcu102-rev10-ad9083-fmc-ebz.dts
- arch/arm64/boot/dts/xilinx/zynqmp-zcu102-rev10-ad9083-vna-15p625msps.dts
This is just cleaning up some inconsistencies I noticed in some .dts files.
> DT @address cleanup

- arch/arm64/boot/dts/xilinx/zynqmp-jupiter-sdr.dts
Specify the external shunt resistor value for properly display the current and the power.
> arm64: boot: xilinx: jupiter: specify shunt resistor value

- arch/arm/boot/dts/overlays/Makefile
- arch/arm/boot/dts/overlays/adis16550-overlay.dts
> arch:arm:boot:dts:overlays: add overlay for adis16550

- drivers/iio/dac/ad3552r-common.c
- drivers/iio/dac/ad3552r-hs.c
- drivers/iio/dac/ad3552r.h
Add debugfs register access.
Reviewed-by: Nuno Sá <nuno.sa@analog.com>
Add debugfs register access.
> iio: dac: ad3552r-hs: add debugfs reg access

- azure-pipelines-rpi.yml
Remove old branches from trigger and pr section and update the condition from artifacts push jobs.
> azure-pipelines-rpi.yml: remove old branches from trigger

- azure-pipelines-rpi.yml
- azure-pipelines.yml
- ci/travis/prepare_artifacts.sh
- ci/travis/prepare_artifacts_rpi.sh
- ci/travis/run-build.sh
Updates:
- Add microblaze builds
- Build dtbs using ADI defconfigs
- Upload generated artifacts to Artifactory
- Trigger Hardware Testing job for pull requests and commits made to main, next_stable and release branches
> ci: Refactor ci

- arch/arm/boot/dts/overlays/Makefile
- arch/arm/boot/dts/overlays/rpi-ad3530r-overlay.dts
> overlays: rpi-ad3530r-overlay.dts: Add AD3530R example overlay

- drivers/iio/frequency/hmc7044.c
- include/dt-bindings/iio/frequency/hmc7044.h
Add OSCOUTx logic to the HMC7044 driver.
> HMC7044 OSCOUTx logic

- .github/workflows/build.yml
- .github/workflows/kernel.yml
- ci/build.sh
Reformat json escaped quotes to solve false positives due to wrong quotes conversion; and
Add clang analyzer step, using flags --analyze -Xanalyzer -analyzer-output=text
Sample run: https://github.com/gastmaier/adi-linux/actions/runs/15109661683
> ci: Analyzer fixes and llvm analyzer

- .github/workflows.mirror/cron.yml
- .github/workflows.mirror/self.yml
- .github/workflows/mirror.yml
In some contexts GITHUB_TOKEN permissions are not enough, so add a secret called WORKFLOW_TOKEN with higher precedence.
Also fixes the name of ci_branch.
> GitHub secret

- arch/arm/boot/dts/xilinx/zynq-zed-adv7511.dtsi
- arch/arm/boot/dts/xilinx/zynq-zed.dtsi
Fix up the `zynq-zed-adv7511.dtsi` file. See the commit messages for the details.
Cleanup. And I guess technically one new feature, although not one I expect people to use.
> Zynq zed adv7511 improvements

- drivers/spi/spi-axi-spi-engine.c
This are some changes that were recently upstreamed. They allow us to get up to 4 MSPS on a 16-bit ADC with 80 MHz SPI clock, e.g. for AD738x.
In case anyone else want to try this, there is one HDL issue we are still working through. I have a patch for it. But it doesn't change the Linux code, so we can go ahead and commit this PR now.
> SPI Engine optimizations backport

- azure-pipelines-rpi.yml
- ci/travis/prepare_artifacts_rpi.sh
Modify path for dtb artifacts and check that the copy task was successful.
> Check artifacts for rpi branch

- azure-pipelines-rpi.yml
- ci/travis/prepare_artifacts_rpi.sh
change naming of the artifacts for the 64 bit architecture solving the error from the export step
> azure-pipelines-rpi.yml: add parameters for the arm64 defconfigs

- Documentation/devicetree/bindings/iio/adc/adi,ad7380.yaml
- Documentation/iio/ad7380.rst
This should have been included in #2830 but I missed the non-driver changes, so this is the docs and dt-bindings to go with it.
> AD7380 backports (the rest of it)

- drivers/clk/adi/clk-ad9545.c
- drivers/iio/adc/ad7768.c
- drivers/iio/adc/ad9081.c
- drivers/iio/adc/ad9361.c
- drivers/iio/adc/ad9371.c
- drivers/iio/adc/admc_ctrl.c
- drivers/iio/adc/adrv9009.c
- drivers/iio/adc/navassa/platforms/linux_platform.c
- drivers/iio/frequency/ad9508.c
- drivers/iio/frequency/ad9523.c
- drivers/iio/frequency/ad9528.c
- drivers/media/platform/adi/adi-axi-fb.c
- drivers/media/platform/adi/axi-hdmi-rx.c
- drivers/spi/spi-ad9250fmc.c
Some mixtures of fixes that will be anyways needed when moving to linux 6.12.
> [xlnx/misc stuff]

- ci/maintenance.sh
So next steps are in the correct branch.
> ci: Revert-back to original branch after sync_branches

- .github/workflows/build.yml
- .github/workflows/checks.yml
- .github/workflows/top-level.yml
- ci/build.sh
- ci/travis/dtb_build_test_exceptions
- docs/ci.rst
Only check for hdl tag on devicetree if is a fpga dts.
Fix exception path for 2 intel dts.
> ci: changes

- azure-pipelines-rpi.yml
New rpi branch was created and added in the trigger list for the rpi linux pipeline.
> azure-pipelines-rpi: add rpi-6.12.y branch to trigger list

- azure-pipelines-rpi.yml
Add rpi-6.12.y branch to the condition for the uploading artifacts jobs.
> azure-pipelines-rpi: enable artifacts uploading for rpi-6.12.y branch

- .github/workflows/checks.yml
- ci/build.sh
- ci/runner_env.sh
- docs/ci.rst
Fixes: https://github.com/analogdevicesinc/linux/commit/8eae91a459b82ea7fd1d50e83eaf2c095b33e4eb (".github: checks: checkout target branch include files")
Fixes: https://github.com/analogdevicesinc/linux/commit/9b6cf9fc9e4ec55d63bb284845b20bef9ceec1e6 ("ci: Fix DTS file list missing space")
> ci/update:  Fixes

- Documentation/devicetree/bindings/iio/adc/adi,ad9081.yaml
Add missing dt-bindings YAML file for AD9081 and friends
> bindings: iio: adc: adi,ad9081.yaml: Add bindings for AD9081

- .github/workflows/main.yml
> .github: Fix run main.yml only at org analogdevicesinc
